nix-community/nixvim

- flake.nix
- plugins/colorschemes/tokyonight.nix
- plugins/default.nix
- plugins/statuslines/lualine.nix
I've added `colorschemes/tokyonight` and `statuslines/lualine`.
> Added some plugins

- doc/plugins/colorschemes/tokyonight.md
- plugins/colorschemes/tokyonight.nix
- plugins/statuslines/lualine.nix
I've added documentation for tokyonight and fixed a typo in tokyonight
> added some documentation

- plugins/bufferlines/bufferline.nix
- plugins/default.nix
- plugins/nvim-lsp/default.nix
- plugins/nvim-lsp/pyright.nix
- plugins/utils/comment-nvim.nix
- plugins/utils/easyescape.nix
- plugins/utils/floaterm.nix
I've added the plugin bufferline and nvim-lsp/pyright and the capabilities option for nvim-lsp (will use that later for cmp-nvim)
> add bufferline and nvim-lsp/pyright

- plugins/default.nix
- plugins/plugin-defs.nix
- plugins/utils/mark-radar.nix
- plugins/utils/specs.nix
- specs.nvim: init
- mark-radar: init
> Add mark-radar and specs.nvim plugins

- plugins/nvim-lsp/default.nix
- plugins/nvim-lsp/zls.nix
Recently I found Zig and it is a very interesting programming language and one thing I was missing in nixvim was LSP support for it, so I've added.
> add nvim-lsp/zls support

- plugins/default.nix
- plugins/git/neogit.nix
- plugins/utils/dashboard.nix
- plugins/utils/emmet.nix
Sorry about the lack of description in neogit module, unfortunately the neogit doc isn't clear
Also, sorry about my English
> add dashboard.nvim, neogit and emmet

- nixvim.nix
This PR fixes issue #26
Changes:
Created a luaGlobals variable which holds options and globals.
Made sure luaGlobals is inserted before luaConfigExtra.
> Set globals before plugin setup

- plugins/languages/treesitter.nix
Necessary for me because of https://github.com/claytonrcarter/tree-sitter-phpdoc/issues/15
> treesitter: add ignoreInstall option to treesitter config

- flake.nix
Some useful utility functions in helpers may be helpful to end users, like `mkRaw`. This PR exposes the `helpers` module at `config.nixvim.helpers`.
> Expose helpers to config.nixvim.helpers

- plugins/default.nix
- plugins/helpers.nix
- plugins/telescope/default.nix
- plugins/telescope/project-nvim.nix
- plugins/utils/project-nvim.nix
Init of project.nvim plugin
https://github.com/ahmedkhalf/project.nvim
I have also added two new helpers:
`rawType` and `isRawType`.
> project-nvim: init plugin + added new helpers

- plugins/helpers.nix
- tests/flake.nix
This should resolve #71
I was debating rewriting the function, but I'm going to hold off due to work needing to be done on tests first
> helpers: fix toLuaObject string escapes

- plugins/helpers.nix
- plugins/utils/project-nvim.nix
This PR aims to resolve part of #30.
Initially I have created the `extraOptionsOptions` helper and tested it with project-nvim and seen that it works.
I will work on adding this option to most other plugins if you think this looks fine @pta2002
> Added extra options

- plugins/telescope/default.nix
This PR adds extra options to the telescope module.
It also adds defaultConfig which is used to configure telescope.
> telescope: added extraOptions and defualtConfig

- plugins/completion/lspkind.nix
- plugins/nvim-lsp/trouble.nix
Should resolve #73
To test, run `nix flake check`
> fix: basic flake check should work now

- plugins/default.nix
- plugins/git/gitsigns.nix
This adds the [gitsigns](https://github.com/lewis6991/gitsigns.nvim) plugin. It re-implements the default values for all the setup options.
> plugins/git: Add gitsigns plugin

- README.md
I corrected a few typos in the README.
> readme: typos

- example.nix
- plugins/nvim-lsp/basic-servers.nix
Add the bashls language server.
+ removed a trailing whitespace.
> Lsp add bashls

- modules/autocmd.nix
- tests/flake.nix
This is a basic implementation of an `autocmd` module.
I would be glad to get some feedback on this :)
> modules: add autocmd

- modules/highlights.nix
This PR implements a basic `programs.nixvim.match` module.
> modules/highlights: added a wrapper around vim.fn.matchadd

- flake.nix
- plugins/bufferlines/bufferline.nix
- plugins/null-ls/servers.nix
- plugins/nvim-lsp/basic-servers.nix
- plugins/nvim-lsp/lspsaga.nix
- plugins/snippets/luasnip/default.nix
- plugins/telescope/default.nix
- plugins/telescope/frecency.nix
- plugins/telescope/fzf-native.nix
- plugins/utils/magma-nvim.nix
A few files had trailing white spaces at the end of some lines.
This PR removes them.
> misc: remove trailing whitespaces

- plugins/default.nix
- plugins/utils/nvim-colorizer.nix
Add the support for plugin [nvim-colorizer](https://github.com/NvChad/nvim-colorizer.lua).
> plugins: Add nvim-colorizer

- plugins/default.nix
- plugins/languages/markdown-preview.nix
Add the plugin [markdown-preview](https://github.com/iamcco/markdown-preview.nvim)
> plugins: Add markdown-preview

- plugins/default.nix
- plugins/languages/vimtex.nix
Add the [vimtex](https://github.com/lervag/vimtex) plugin.
> plugins: add vimtex

- plugins/default.nix
- plugins/languages/tagbar.nix
Add [tagbar](https://github.com/preservim/tagbar) plugin.
> plugins: Add tagbar

- plugins/bufferlines/bufferline.nix
- wrappers/_shared.nix
PR #129 broke the helper wrapper and the bufferline plugin support. This PR fixes them.
> Followup fixes for #129

- plugins/default.nix
I think that merging this commit https://github.com/pta2002/nixvim/pull/145/commits/a7f61a17ca1bb16358c3dc3c927ac5bc411adcf6 was a mistake.
Solving it with this PR
> plugins: solve previously merged conflict

- plugins/utils/nvim-tree.nix
The options of the `nvim-tree` plugin were not up-to-date.
This PR ensures they are 1:1 compatible with the upstream plugin.
The documentation has also been ported.
My only concern is that this module is now huge.
Maybe, we may prefer to do something more [RFCS-0042](https://github.com/Infinisil/rfcs/blob/config-option/rfcs/0042-config-option.md)-style.
I would like to get your opinion on this.
Furthermore, a manual implementation of the [`open_on_setup` deprecated options](https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup).
~~NOTE: This PR requires https://github.com/pta2002/nixvim/pull/172 to be merged.~~ now merged.
> plugins/utils/nvim-tree: huge option refactoring + implementation of auto-open deprecated functionality

- lib/helpers.nix
> lib/helpers: syntax change

- plugins/nvim-lsp/language-servers/default.nix
- plugins/nvim-lsp/language-servers/pylsp.nix
Add the pylsp server [settings](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md)
> plugins/nvim-lsp: add pylsp server settings

- plugins/nvim-lsp/trouble.nix
Fixes https://github.com/pta2002/nixvim/issues/190.
> plugins/nvim-lsp/trouble: refactoring + new options

- plugins/statuslines/lualine.nix
Refactoring of the lualine plugin:
- added more options
- cleaned the code
- enhanced documentation
> plugins/statuslines/lualine: refactoring

- plugins/nvim-lsp/language-servers/default.nix
Re-order language server list by alphabetical order.
> plugins/nvim-lsp/language-servers: re-order LS list by alphabetical order

- plugins/default.nix
- plugins/utils/neorg.nix
Add package [neorg](https://github.com/nvim-neorg/neorg).
> plugins/languages/neorg: add package neorg

- plugins/utils/floaterm.nix
New refactor of the `floaterm` module with keymap options.
> plugins/floaterm: refactor + keymap options

- plugins/nvim-lsp/language-servers/pylsp.nix
Add the support for the language server plugin [`pylsp-mypy`](https://github.com/python-lsp/pylsp-mypy).
> plugins/nvim-lsp/pylsp: add support for third-party plugin pylsp-mypy

- lib/helpers.nix
Introduce new helpers function:
```nix
mkIfNonNull' = x: y: (mkIf (!isNull x) y);
mkIfNonNull = x: (mkIfNonNull' x x);
ifNonNull = x: y:
if (isNull x)
then null
else y;
```
Those would help with the refactoring of many plugins.
> lib/helpers: mkIfNonNull', ifNonNull' and ifNonNull

- plugins/utils/todo-comments.nix
- tests/plugins/todo-comments.nix
I went through the [recently added](https://github.com/pta2002/nixvim/pull/232) `todo-comments`.
Fixed some issues, added support for keymaps...
> plugins/todo-comments: refactoring + tests

- plugins/pluginmanagers/packer.nix
- tests/plugins/packer.nix
Several fixes/improvements to the packer module.
Basically, it now supports more stuff and better.
Bonus: tests :)
> plugins/packer: refactoring + fixes + tests

- plugins/nvim-lsp/trouble.nix
- tests/plugins/trouble.nix
https://github.com/pta2002/nixvim/pull/213 introduced a regression in the trouble plugin.
Now fixed.
> plugins/trouble: fix regressions introduced #213

- plugins/default.nix
- plugins/utils/neo-tree.nix
- tests/plugins/neo-tree.nix
Add [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) plugins and the relevant tests.
> plugins/neo-tree: init + tests

- plugins/null-ls/default.nix
- tests/plugins/null-ls.nix
Refactoring of null-ls: added more options.
I also wrote tests.
Fixes https://github.com/pta2002/nixvim/issues/32.
> plugins/null-ls: refactoring + tests

- plugins/languages/rust.nix
- tests/plugins/rust-tools.nix
Refactoring and testing of the `rust-tools` plugin.
> plugins/rust-tools: refactoring + tests

- plugins/completion/lspkind.nix
- tests/plugins/lspkind.nix
Refactoring and testing of the `lspkind` plugin.
> plugins/lspkind: refactoring + tests

- plugins/default.nix
- plugins/languages/sniprun.nix
- tests/plugins/sniprun.nix
Add plugin: [sniprun](https://github.com/michaelb/sniprun)
> plugins/sniprun: init + tests

- plugins/nvim-lsp/helpers.nix
> plugins/nvim-lsp: Correctly take into account extraSettings

- plugins/default.nix
- plugins/utils/presence-nvim.nix
- tests/test-sources/plugins/utils/presence-nvim.nix
Adds plugin for Discord Rich Presence for Neovim: 
https://github.com/andweeb/presence.nvim
Also adds tests for this plugin.
> presence-nvim: init plugin

- plugins/default.nix
- plugins/languages/nvim-jdtls.nix
- tests/test-sources/plugins/languages/nvim-jdtls.nix
Add plugin [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls)
> plugins/nvim-jdtls: init + tests

- plugins/colorschemes/tokyonight.nix
- tests/test-sources/plugins/colorschemes/tokyonight.nix
This is a reviving of https://github.com/pta2002/nixvim/pull/297 which was closed by error.
The author of these changes is @dongcarl.
> tokyonight: Add onColor and onHightlights

- plugins/statuslines/lualine.nix
- tests/test-sources/plugins/statuslines/lualine.nix
Simple PR to expand lualine config to allow winbar and inactive sections and winbar components config.
> lualine: add winbar and inactive sections configs

- plugins/bufferlines/bufferline.nix
Fixes https://github.com/pta2002/nixvim/issues/292
> plugins/bufferline: fix deprecated highlight options

- flake.lock
- plugins/bufferlines/barbar.nix
- tests/test-sources/plugins/bufferlines/barbar.nix
The upstream plugin has changed significantly.
This PR ensures that those changes are applied to the nixvim module.
Relevant deprecation/rename warnings have been made.
Fixes https://github.com/pta2002/nixvim/issues/315.
> plugins/barbar: refactoring + nix flake update

- plugins/nvim-lsp/language-servers/default.nix
- tests/test-sources/plugins/nvim-lsp/nvim-lsp.nix
Add [language server for terraform](https://github.com/hashicorp/terraform-ls).
> plugins/nvim-lsp: add terraform-ls language server

- plugins/colorschemes/poimandres.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/poimandres.nix
Add colorscheme [poimandres](https://github.com/olivercederborg/poimandres.nvim)
> plugins/poimandres: add colorscheme + test

- plugins/default.nix
- plugins/utils/spider.nix
- tests/test-sources/plugins/utils/spider.nix
Add plugin [nvim-spider](https://github.com/chrisgrieser/nvim-spider)
> plugins/spider: add plugin + test

- flake.nix
The flake.nix file was not formatted properly.
> flake: formatting

- wrappers/darwin.nix
[This commit](6ad7575d6f6416f1e7098e4b3cf7572977e90246) broke the module three months ago. Fix it.
> fix nix darwin module

- flake.lock
- plugins/nvim-lsp/language-servers/default.nix
- tests/test-sources/plugins/nvim-lsp/nvim-lsp.nix
Add the [`ruff-lsp`](https://github.com/charliermarsh/ruff-lsp) to nixvim.
> plugins/nvim-lsp: add ruff-lsp for python

- modules/clipboard.nix
Add the `wl-copy` clipboard provider (for wayland).
> modules/clipboard: add wl-copy provider

- plugins/filetrees/nvim-tree.nix
Fixes https://github.com/pta2002/nixvim/issues/362
> plugins/nvim-tree: fix onAttach option

- flake.lock
- plugins/lsp/language-servers/pylsp.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
- tests/test-sources/plugins/lsp/pylsp.nix
- re-enable the `zls` language server test because the package is now working
- Minor refactoring in the pylsp code
- Add new options for third-party plugins of pylsp
> nvim-lsp/pylsp: minor refactoring + test

- plugins/colorschemes/catppuccin.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/catppuccin.nix
Added the catppuccin colorscheme (https://github.com/catppuccin/nvim)
> plugins/catppuccin: add colorscheme + test

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
> nvim-lsp: add clojure-lsp

- plugins/lsp/language-servers/pylsp.nix
Currently, my fancy implementation of auto-installing pylsp plugins does not have any effect.
Indeed, it is needed to change the pylsp derivation itself by adding the different plugins to its `propagatedBuildInputs`.
See https://github.com/NixOS/nixpkgs/issues/229337 for more details
> nvim-lsp/pylsp: fix pylsp plugins

- plugins/default.nix
- plugins/utils/oil.nix
- tests/test-sources/plugins/utils/oil.nix
Add support for the [oil.nvim](https://github.com/stevearc/oil.nvim) plugin.
> plugins/oil: init + tests

- plugins/default.nix
- plugins/languages/typst/typst-vim.nix
- tests/test-sources/plugins/languages/typst/typst-vim.nix
Add support for the [`typst.vim`](https://github.com/kaarmu/typst.vim) plugin.
> plugins/typst-vim: init plugin + test

- plugins/default.nix
- plugins/languages/vim-slime.nix
- tests/test-sources/plugins/languages/vim-slime.nix
Add the [`vim-slime`](https://github.com/jpalardy/vim-slime) plugin.
> plugins/vim-slime: add plugin + test

- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/ltex-settings.nix
- tests/test-sources/plugins/lsp/ltex.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add the [`ltex` language server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#ltex).
> plugins/nvim-lsp: add ltex language server + test

- plugins/utils/indent-blankline.nix
- tests/test-sources/plugins/utils/indent-blankline.nix
Plugin `indent-blankline`:
- Add an `extraOptions` option
- Add a test
> plugins/indent-blankline: add extraOptions option + test

- flake.lock
- flake.nix
This branch is made to be used with Nixpkgs 23.05
> flake: Pin nixpkgs to 23.05

- plugins/default.nix
- plugins/languages/julia/julia-cell.nix
- tests/test-sources/plugins/languages/julia/julia-cell.nix
Add support for the [vim-julia-cell](https://github.com/mroavi/vim-julia-cell) plugin.
> plugins/julia-cell: init + test

- plugins/default.nix
- plugins/utils/mini.nix
- tests/test-sources/plugins/utils/mini.nix
Add support for plugin [`mini.nvim`](https://github.com/echasnovski/mini.nvim).
Fixes #418.
> plugins/mini: init + test

- plugins/default.nix
- plugins/utils/auto-session.nix
- tests/test-sources/plugins/utils/auto-session.nix
Add support for the [`auto-session`](https://github.com/rmagatti/auto-session) plugin.
Fixes #426.
> plugins/auto-session: init + tests

- plugins/colorschemes/rose-pine.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/rose-pine.nix
Added the rose-pine colorscheme: https://github.com/rose-pine/neovim
> plugins/rose-pine: add colorscheme & test

- plugins/default.nix
- plugins/utils/toggleterm.nix
- tests/test-sources/plugins/utils/toggleterm.nix
Added  [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) with tests
> plugins/toggleterm: init + test

- plugins/default.nix
- plugins/utils/nvim-ufo.nix
- tests/test-sources/plugins/utils/nvim-ufo.nix
Added [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo) + test
> plugins/nvim-ufo: init + test

- plugins/filetrees/neo-tree.nix
- plugins/lsp/language-servers/ltex-settings.nix
https://github.com/pta2002/nixvim/pull/445 caused the documentation generation to fail.
This PR addresses the few problematic snippets.
> misc: fix documentation generation

- plugins/default.nix
- plugins/utils/neogen.nix
- tests/test-sources/plugins/utils/neogen.nix
Add a support for [neogen](https://github.com/danymat/neogen) plugin.
> plugins/neogen: init + test

- plugins/default.nix
- plugins/utils/leap.nix
- tests/test-sources/plugins/utils/leap.nix
Add support for the [leap.nvim](https://github.com/ggandor/leap.nvim) plugin.
> plugins/leap: init + test

- plugins/telescope/default.nix
- plugins/telescope/file-browser.nix
Added telescope extension: [telescope-file-browser](https://github.com/nvim-telescope/telescope-file-browser.nvim)
Fixes: #467
> plugins/telescope.file_browser: init

- plugins/default.nix
- plugins/utils/quickmath.nix
- tests/test-sources/plugins/utils/quickmath.nix
Add support for [quickmath.nvim](https://github.com/jbyuki/quickmath.nvim).
Fixes #461.
> plugins/quickmath: init + test

- plugins/default.nix
- plugins/utils/wilder-nvim.nix
- tests/test-sources/plugins/utils/wilder-nvim.nix
Add a support for [wilder.nvim](https://github.com/gelguy/wilder.nvim).
> plugins/wilder-nvim: init + test

- lib/helpers.nix
- plugins/default.nix
- plugins/git/diffview.nix
- tests/test-sources/plugins/git/diffview.nix
Add support for [diffview](https://github.com/sindrets/diffview.nvim) plugin.
> plugins/diffview: init + test

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nixd.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
- tests/test-sources/plugins/lsp/omnisharp.nix
Adds option to enable omnisharp, and options to configure it.
> plugins/lsp: add omnisharp language server

- plugins/default.nix
- plugins/lsp/fidget.nix
- tests/test-sources/plugins/lsp/fidget.nix
Follow up of #491.
The original author of those changes is @ShyProton.
> plugins/fidget: init + test

- CONTRIBUTING.md
Fix some indenting in `CONTRIBUTING.md`
> CONTRIBUTING: fix indenting

- plugins/lsp/language-servers/default.nix
> plugins/lsp: Added volar language server

- plugins/default.nix
- plugins/utils/mkdnflow.nix
- tests/test-sources/plugins/utils/mkdnflow.nix
Add support for plugin [mkdnflow](https://github.com/jakewvincent/mkdnflow.nvim).
~~We have to wait for the [PR](https://github.com/NixOS/nixpkgs/pull/248356) that adds it upstream [to land in `nixos-unstable`](https://nixpk.gs/pr-tracker.html?pr=248356).~~ -> Done !
Fixes #509
> plugins/mkdnflow: init + test

- plugins/default.nix
- plugins/utils/indent-blankline.nix
- plugins/utils/instant.nix
- tests/test-sources/plugins/utils/instant.nix
Add support for the [instant.nvim](https://github.com/jbyuki/instant.nvim) plugin.
Fixes #519
> plugins/instant: init + test

- README.md
Make the branch choice (`main` vs `nixos-23.05`) clearer in the README.
> README: add instructions for branch selection (stable/unstable)

- plugins/completion/nvim-cmp/default.nix
- tests/test-sources/plugins/completion/nvim-cmp.nix
> plugins/nvim-cmp: Correctly handle multi mode mappings

- docs/default.nix
This pull request prevents option aliases from being generated and shown in the book.
It also removes any empty page from the book.
> docs: ignore option aliases

- lib/helpers.nix
- plugins/languages/treesitter/treesitter-context.nix
- tests/test-sources/plugins/languages/treesitter/treesitter-context.nix
Change options and implementation of the plugin regarding upstream changes.
> plugins/treesitter-context: reflect upstream options changes

- plugins/completion/nvim-cmp/default.nix
- tests/test-sources/plugins/completion/nvim-cmp.nix
> plugins/nvim-cmp: allow users to provide a 'listOf listOf sources'

- flake.lock
- plugins/default.nix
- plugins/utils/multicursors.nix
- tests/test-sources/plugins/utils/multicursors.nix
> plugins/multicursors: init + test

- plugins/default.nix
- plugins/git/gitblame.nix
- tests/test-sources/plugins/git/gitblame.nix
PR to add support for the [git-blame.nvim](https://github.com/f-person/git-blame.nvim) plugin
> plugins/gitblame: init + test

- plugins/bufferlines/bufferline.nix
> plugins/bufferline: add missing highlight groups

- plugins/utils/notify.nix
- tests/test-sources/plugins/utils/notify.nix
> plugins/notify: add missing options + test

- plugins/lsp/language-servers/default.nix
Simple add PhpActor as language server for php.
> Add phpactor

- plugins/utils/harpoon.nix
- tests/test-sources/plugins/utils/harpoon.nix
Harpoon has never been tested. Hence, a few bugs were found and fixed.
> plugins/harpoon: fix keymaps + test

- plugins/bufferlines/barbecue.nix
- plugins/default.nix
- tests/test-sources/plugins/bufferlines/barbecue.nix
PR to add support for the [barbecue-nvim](https://github.com/utilyre/barbecue.nvim plugin)
> plugins/barbecue: init + tests

- plugins/default.nix
- plugins/utils/wilder.nix
- tests/test-sources/plugins/utils/wilder.nix
- rename `wilder-nvim` plugin to `wilder`
- Add missing options
Fixes #638
> plugins/wilder: update options and add missing ones

- plugins/default.nix
- plugins/utils/better-escape.nix
- tests/test-sources/plugins/utils/better-escape.nix
PR to add support for the [better-escape-nvim](https://github.com/max397574/better-escape.nvim) plugin
I have a quick questions about the PR to fix before its ready.
> plugins/better-escape: init + tests

- lib/helpers.nix
- plugins/default.nix
- plugins/utils/flash.nix
- tests/test-sources/plugins/utils/flash.nix
> plugins/flash: init + tests

- plugins/default.nix
- plugins/utils/hmts.nix
- tests/test-sources/plugins/utils/hmts.nix
Add the [hmts plugin](https://github.com/calops/hmts.nvim).
> plugin/hmts: init + tests

- lib/helpers.nix
- plugins/default.nix
- plugins/utils/persistence.nix
- tests/test-sources/plugins/utils/persistence.nix
> plugin/persistence: init + tests

- plugins/null-ls/servers.nix
plugins/null-ls: add formatting source: beautysh
> plugins/null-ls: add formatting source: beautysh

- plugins/default.nix
- plugins/utils/nix-develop.nix
- tests/test-sources/plugins/utils/nix-develop.nix
Add [nix-develop](https://github.com/figsoda/nix-develop.nvim/tree/main) plugin.
It seems there are no config options! So this one is pretty simple ?
> plugins/nix-develop: init + tests

- plugins/telescope/default.nix
- plugins/telescope/undo.nix
- tests/test-sources/plugins/telescope/undo.nix
Added telescope extension: [telescope-undo](https://github.com/debugloop/telescope-undo.nvim)
>  plugins/telescope.undo: init

- plugins/snippets/luasnip/default.nix
The title should describe it all.
Since I found a TODO in the code I did not open an issue first.
> [luasnip] adds support for loading lua snippets and setting extra config

- plugins/default.nix
- plugins/utils/refactoring.nix
- tests/test-sources/plugins/utils/refactoring.nix
Add new plugin [refactoring.nvim])https://github.com/ThePrimeagen/refactoring.nvim)
> plugins/refactoring: init + test

- plugins/default.nix
- plugins/git/git-worktree.nix
- tests/test-sources/plugins/git/git-worktree.nix
Adds support for the [git-worktree](https://github.com/ThePrimeagen/git-worktree.nvim) plugin.
> plugins/git-worktree: init + test 

- lib/autocmd-helpers.nix
- lib/helpers.nix
- modules/autocmd.nix
- plugins/default.nix
- plugins/languages/lint.nix
- tests/test-sources/plugins/languages/lint.nix
Add support for [nvim-lint](https://github.com/mfussenegger/nvim-lint).
Fixes #700
> plugins/lint: init + test

- plugins/git/gitsigns.nix
> plugins/gitsigns: onAttach example correction.

- plugins/languages/typst/typst-vim.nix
- tests/test-sources/plugins/languages/typst/typst-vim.nix
I added the plugin options as well as correctly implemented the `extraOptions` option.
> plugins/typst: add options

- plugins/filetrees/neo-tree.nix
Minor cleaning of `neo-tree`.
Mostly removing `mkCompositeOption`.
> plugins/neo-tree: cleaning

- README.md
* Adds punctuation in several places
* Correct small spelling mistakes
> readme: correct grammar and spelling mistakes

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Follow up of #718 which was closed by accident.
> plugins/lsp: add pest_ls, the language server for pest

- plugins/dap/dap-python.nix
You can't debug without this package
> Add debugpy to dap-python

- plugins/none-ls/prettier.nix
- plugins/none-ls/servers.nix
> plugins/none-ls: add disableTsServerFormatter option

- plugins/none-ls/prettier.nix
> plugins/none-ls: fix warning with prettier

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
- plugins/none-ls: add diagnostic source: ansiblelint
- plugins/none-ls: add diagnostic source: markdownlint
- plugins/none-ls: add diagnostic source: write_good
- plugins/none-ls: add diagnostic source: yamllint
- plugins/none-ls: add formatting source: trim_newlines & trim_whitespace
> Add none-ls sources

- modules/filetype.nix
> modules/filetype: code formatting

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for the [pylyzer](https://mtshiba.github.io/pylyzer/) language server.
> plugins/lsp: add pylyzer language server

- lib/keymap-helpers.nix
This slight refactoring has no impact on the codebase.
However it now allows to create a keymap option with certain defaults.
> helpers/keymaps: add mkMapOptionsSubmodule

- plugins/default.nix
- plugins/lsp/wtf.nix
- tests/test-sources/plugins/lsp/wtf.nix
Add support for the [wtf.nvim](https://github.com/piersolenski/wtf.nvim) plugin.
Fixes #771
> plugins/wtf: init

- plugins/default.nix
- plugins/utils/yanky.nix
- tests/test-sources/plugins/utils/yanky.nix
Add support for [yanky.nvim](https://github.com/gbprod/yanky.nvim).
Fixes #803
> plugins/yanky: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
add the [odin language server (ols)](https://github.com/DanielGavin/ols)
Closes #834
> plugins/lsp: add odin language server

- lib/helpers.nix
With this change a user should be able to set raw lua code in more places than before.
The `mkStr` helper was _not_ changed as a large number of places in nixvim are using this helper to directly implement raw lua code.
Also note that types of the form `oneOf [submodule <something else>]` are not well rendered in the documentation, and should be avoided (this includes `listOf [submodule <something else>]`, so the helpers should be avoided in this case)
> helpers: Allow to set raw lua code in more places

- modules/options.nix
- tests/test-sources/modules/options.nix
Wrap `vim.opt_local.*` and `vim.opt_global.*`.
> modules/options: add localOptions and globalOptions

- plugins/default.nix
- plugins/utils/startup.nix
- tests/test-sources/plugins/utils/startup.nix
Add support for [startup.nvim](https://github.com/startup-nvim/startup.nvim).
Fixes #791
> plugins/startup: init

- plugins/utils/illuminate.nix
- tests/test-sources/plugins/utils/illuminate.nix
> plugins/illuminate: fix filetypeOverrides option

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
add [dhall](https://hackage.haskell.org/package/dhall-lsp-server) language server.
> plugins/lsp: add dhall language server

- plugins/TEMPLATE.nix
This will let us (me at least) gain precious time when adding a new plugin.
> plugins: add a sensible template for modern plugins

- plugins/default.nix
- plugins/ui/image.nix
- tests/test-sources/plugins/ui/image.nix
Add support for plugin [image.nvim](https://github.com/3rd/image.nvim).
Fixes #827.
> plugins/image: init

- plugins/completion/nvim-cmp/cmp-helpers.nix
- plugins/completion/nvim-cmp/sources/codeium-nvim.nix
- plugins/completion/nvim-cmp/sources/default.nix
- tests/test-sources/plugins/completion/codeium-nvim.nix
Add support for [codeium.nvim](https://github.com/Exafunction/codeium.nvim).
Fixes #825
> plugins/codeium-nvim: init

- plugins/bufferlines/bufferline.nix
> plugins/bufferline: use nixvimTypes.highlight

- wrappers/modules/output.nix
This seems to be necessary as well...
>  misc/wrapRc: ignore user "after" directory when wrapRc is true 

- flake.nix
- tests/default.nix
- tests/test-sources/plugins/languages/openscad.nix
- tests/test-sources/plugins/lsp/_lsp.nix
- tests/test-sources/plugins/lsp/efmls-configs.nix
- tests/test-sources/plugins/none-ls.nix
- tests/test-sources/plugins/utils/netman.nix
This should dramatically reduce the build time on [buildbot](https://buildbot.nix-community.org).
> tests: disable failing tests + make buildbot CI work

- plugins/utils/comment-nvim.nix
> plugins/comment-nvim: add {pre,post}Hook options

- README.md
- flake-modules/checks.nix
- flake-modules/default.nix
- flake-modules/dev.nix
- flake-modules/legacy-packages.nix
- flake-modules/lib.nix
- flake-modules/modules.nix
- flake-modules/overlays.nix
- flake-modules/packages.nix
- flake-modules/templates.nix
- flake-modules/wrappers.nix
- flake.lock
- flake.nix
- templates/_wrapper/simple/flake.nix
- templates/simple/flake.nix
flake-parts seems to be considered as the "clean" and less "hacky" solution to flake bootstrapping.
> Replace flake-utils with flake-parts

- lib/helpers.nix
- plugins/default.nix
- plugins/utils/ollama.nix
- tests/test-sources/plugins/utils/ollama.nix
Add support for [ollama.nvim](https://github.com/nomnivore/ollama.nvim).
Fixes #778
> plugins/ollama: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for [htmx-lsp](https://github.com/ThePrimeagen/htmx-lsp).
Fixes #933
> plugins/lsp: add htmx lsp

- plugins/default.nix
- plugins/utils/marks.nix
- tests/test-sources/plugins/utils/marks.nix
Add plugin [marks.nvim](https://github.com/chentoast/marks.nvim).
Fixes #939
> plugins/marks: init

- README.md
In Nix a multi line comment is two single quotes.
> Change triple single quotes to two single quotes

- plugins/default.nix
- plugins/snippets/friendly-snippets.nix
- tests/test-sources/plugins/snippets/friendly-snippets.nix
Add support for [friendly-snippets](https://github.com/rafamadriz/friendly-snippets)
Fixes #932
> plugins/friendly-snippets: init

- plugins/default.nix
- plugins/utils/rest.nix
- tests/test-sources/plugins/utils/rest.nix
Add support for [rest.nvim](https://github.com/rest-nvim/rest.nvim).
> plugins/rest: init

- CONTRIBUTING.md
- lib/helpers.nix
- lib/vim-plugin.nix
- plugins/completion/copilot-vim.nix
- plugins/completion/nvim-cmp/cmp-helpers.nix
- plugins/git/fugitive.nix
- plugins/languages/ledger.nix
- plugins/languages/markdown-preview.nix
- plugins/languages/nix.nix
- plugins/languages/tagbar.nix
- plugins/languages/vim-slime.nix
- plugins/languages/zig.nix
- plugins/statuslines/airline.nix
- plugins/utils/emmet.nix
- plugins/utils/endwise.nix
- plugins/utils/goyo.nix
- plugins/utils/instant.nix
- plugins/utils/magma-nvim.nix
- plugins/utils/molten.nix
- plugins/utils/startify.nix
- plugins/utils/surround.nix
- plugins/utils/undotree.nix
This PR is just about two basic renames and their application in the code base:
- `helpers.mkPlugin` -> `helpers.legacy-plugin.mkLegacyPlugin`
- `helpers.mkDefaultOpt` -> `helpers.legacy-plugin.mkDefaultOpt`
> mkPlugin -> mkVimPlugin

- plugins/completion/nvim-cmp/cmp-helpers.nix
- plugins/git/fugitive.nix
- plugins/languages/nix.nix
- plugins/languages/zig.nix
- plugins/lsp/language-servers/default.nix
- plugins/utils/emmet.nix
- plugins/utils/endwise.nix
- plugins/utils/goyo.nix
- plugins/utils/startify.nix
- plugins/utils/surround.nix
Only for the `enable` option though, I haven't fully explored the whole manual yet. Also did some quick corrections on capitalization and whatnot. I just mainly did this to clean up the manual page.
> plugins: clean up module descriptions

- plugins/default.nix
- plugins/languages/haskell-scope-highlighting.nix
- tests/test-sources/plugins/languages/haskell-scope-highlighting.nix
Adds haskell-scope-highlighting, fixes #948
> plugins/haskell-scope-highlighting: init + test

- lib/utils.nix
- plugins/colorschemes/gruvbox.nix
- tests/test-sources/example-configurations/issues.nix
Fixes https://github.com/nix-community/nixvim/discussions/990
>  colorschemes/gruvbox: switch to RFC-42 

- plugins/default.nix
- plugins/languages/helm.nix
- tests/test-sources/plugins/languages/helm.nix
Add support for the [vim-helm](https://github.com/towolf/vim-helm) plugin.
Partially fixes #989
> plugins/helm: init

- plugins/default.nix
- plugins/utils/autoclose.nix
- tests/test-sources/plugins/utils/autoclose-nvim.nix
> plugins/autoclose: init + tests

- docs/default.nix
> docs: Add wrapper specific options

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add LSP support for [vala-language-server](https://github.com/vala-lang/vala-language-server).
> plugins/lsp: add vala-language-server

- flake-modules/modules.nix
- modules/default.nix
Let's get rid of too fancy things.
> misc: import nixvim modules in a simpler way

- plugins/completion/copilot-vim.nix
I'm sure that it has been here for more than 2 months.
> plugins/copilot-vim: remove deprecation warning

- plugins/utils/emmet.nix
Honestly, I don't think that this is too relevant.
> plugins/emmet: remove uselessly strict typing

- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
https://github.com/nix-community/nixvim/pull/1033#discussion_r1484432476
> wrappers: remove shorthandOnlyDefinesConfig

- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
This reverts commit 8549bbeb0c4b2fce7baa64a7e424e1f48eadf6a6.
Fixes #1042 #1043
> Revert "wrappers: remove shorthandOnlyDefinesConfig"

- tests/modules/files.nix
- wrappers/modules/files.nix
Needs to be adapted to the new way we propagate helpers.
> modules/files: fix module

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Add an option to enable checkstyle none-ls source.
> plugins/none-ls: add checkstyle

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Add an option to enable astyle none-ls source.
> plugins/none-ls: add astyle

- docs/man/nixvim-header.5
- lib/neovim-plugin.nix
- modules/commands.nix
- modules/doc.nix
- modules/highlights.nix
- modules/lua-loader.nix
- plugins/none-ls/helpers.nix
- wrappers/modules/files.nix
- wrappers/modules/output.nix
Another random drive-by docs clean up.
> docs: clean up descriptions

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
add prettierd formatter source for none-ls.
>  plugins/none-ls: add prettierd

- plugins/lsp/nvim-lightbulb.nix
- tests/test-sources/plugins/lsp/nvim-lightbulb.nix
Closes #843.
Could someone please double check line 40 (actionKinds)? As I'm not exactly sure how to get to a `nil` value in lua from nix.
> plugin/nvim-lightbulb: update module to match latest breaking changes

- plugins/default.nix
- plugins/utils/neocord.nix
- tests/test-sources/plugins/utils/neocord.nix
Add support for https://github.com/IogaMaster/neocord
> plugins/neocord: init

- plugins/utils/auto-session.nix
https://github.com/rmagatti/auto-session/blob/29a8c77a0579636d5520aebd38bdbc2e6079f2f5/lua/auto-session/session-lens/actions.lua#L14
> auto-session: fix sessionLens.sessionControl config attribute

- docs/user-guide/install.md
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
See #1074 for more details. I just went ahead to make this PR since discussion can also take place here anyways. ;p
> wrappers: add env-specific config as part of NixVim module

- plugins/default.nix
- plugins/utils/bacon.nix
- tests/test-sources/plugins/utils/bacon.nix
Will resolve: https://github.com/nix-community/nixvim/issues/1025
There is not yet a package on Nixpkgs though so need to open a PR for it.
> plugins/nvim-bacon: init

- plugins/default.nix
- plugins/utils/indent-o-matic.nix
- tests/test-sources/plugins/utils/indent-o-matic.nix
Adds indent-o-matic will resolve: https://github.com/nix-community/nixvim/issues/1143
> plugins/indent-o-matic: init

- plugins/default.nix
- plugins/utils/baleia.nix
- tests/test-sources/plugins/utils/baleia.nix
Will resolve: https://github.com/nix-community/nixvim/issues/1024
Still needs PR for Nixpkgs.
> plugins/baleia: init

- flake-modules/dev/devshell.nix
Allows to do `tests --show-trace` for instance.
> flake/devshell: forward cli args to commands

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Added configuration for `slint_lsp`.
> plugins/lsp: add slint_lsp

- plugins/none-ls/servers.nix
> plugins/none-ls: add packages for supported builtin tools

- docs/mdbook/default.nix
> docs: avoid duplicate maintainers

- plugins/default.nix
- plugins/ui/transparent.nix
- tests/test-sources/plugins/ui/transparent.nix
Add support for [transparent.nvim](https://github.com/xiyaowong/transparent.nvim).
Fixes #1026
> plugins/transparent: init

- plugins/lsp/default.nix
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Fixes [rnix deprecation](https://github.com/nix-community/nixvim/issues/1244).
> Removed rnix dependencies, as it has been deprecated

- plugins/utils/molten.nix
> plugins/molten: add python3 dependencies

- lib/neovim-plugin.nix
- lib/vim-plugin.nix
- plugins/colorschemes/ayu.nix
- plugins/colorschemes/gruvbox.nix
- plugins/colorschemes/nord.nix
> helpers: refactor mk[Neo]vimPlugin for colorschemes handling

- plugins/completion/coq-thirdparty.nix
> plugins/coq-thirdparty: Fix example & improve documentation

- plugins/colorschemes/vscode.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/vscode.nix
Add  [`vscode.nvim`](https://github.com/Mofiqul/vscode.nvim) colorscheme.
> plugins/vscode: init

- plugins/lsp/trouble.nix
- tests/test-sources/plugins/lsp/trouble.nix
Switch `trouble` to `mkNeovimPlugin` and `settingsOptions`.
Also add the `win_config` option.
> plugins/trouble: switch to settingsOptions

- plugins/default.nix
- plugins/ui/virt-column.nix
- tests/test-sources/plugins/ui/virt-column.nix
Will resolve: https://github.com/nix-community/nixvim/issues/1126
> plugins/virt-column: init

- plugins/default.nix
- plugins/neotest/adapters-list.nix
- plugins/neotest/adapters.nix
- plugins/neotest/default.nix
- plugins/neotest/options.nix
- tests/test-sources/plugins/neotest/dart.nix
- tests/test-sources/plugins/neotest/default.nix
- tests/test-sources/plugins/neotest/dotnet.nix
- tests/test-sources/plugins/neotest/elixir.nix
- tests/test-sources/plugins/neotest/go.nix
- tests/test-sources/plugins/neotest/haskell.nix
- tests/test-sources/plugins/neotest/jest.nix
- tests/test-sources/plugins/neotest/pest.nix
- tests/test-sources/plugins/neotest/phpunit.nix
- tests/test-sources/plugins/neotest/plenary.nix
- tests/test-sources/plugins/neotest/python.nix
- tests/test-sources/plugins/neotest/rspec.nix
- tests/test-sources/plugins/neotest/rust.nix
- tests/test-sources/plugins/neotest/scala.nix
- tests/test-sources/plugins/neotest/vitest.nix
Add support for [neotest](https://github.com/nvim-neotest/neotest).
Fixes #704
> plugins/neotest: init

- plugins/default.nix
- plugins/ui/twilight.nix
- tests/test-sources/plugins/ui/twilight.nix
Add support for [twilight.nvim](https://github.com/folke/twilight.nvim).
Fixes #1273
> plugins/twilight: init

- docs/user-guide/faq.md
Document one approach to solving #1215
Added as an FAQ for now, but may be better suited to a new "Tips and Tricks" section, [as suggested](https://github.com/nix-community/nixvim/issues/1215#issuecomment-1992737399) by @traxys.
> docs: Add keymap alias FAQ

- plugins/completion/codeium-vim.nix
> plugins/codeium-vim: fix keymaps

- plugins/neotest/adapters-list.nix
- plugins/neotest/adapters.nix
- tests/test-sources/plugins/neotest/default.nix
Add the [hardhat.nvim](https://github.com/TheSnakeWitcher/hardhat.nvim) neotest adapter.
> plugins/neotest: add hardhat.nvim

- docs/user-guide/install.md
Implements a suggestion in #1240
> docs: Add a more verbose example on adding the standalone flake

- plugins/default.nix
- plugins/utils/zellij.nix
- tests/test-sources/plugins/utils/zellij.nix
Add support for [zellij-nvim](https://github.com/Lilja/zellij.nvim).
> plugins/zellij-nvim: init

- plugins/neotest/adapters-list.nix
- tests/test-sources/plugins/neotest/default.nix
- tests/test-sources/plugins/neotest/gtest.nix
Add support for the [neotest-gtest](https://github.com/alfaix/neotest-gtest) adapter.
> plugins/neotest: add neotest-gtest

- plugins/default.nix
- plugins/utils/sandwich.nix
- tests/test-sources/plugins/utils/sandwich.nix
- typos.toml
Add support for [vim-sandwich](https://github.com/machakann/vim-sandwich).
Fixes #1161
> plugins/sandwich: init

- plugins/default.nix
- plugins/languages/python/jupytext.nix
- tests/test-sources/plugins/languages/python/jupytext.nix
Add support for [jupytext.nvim](https://github.com/GCBallesteros/jupytext.nvim).
> plugins/jupytext: init

- plugins/default.nix
- plugins/ui/zen-mode.nix
- tests/test-sources/plugins/ui/zen-mode.nix
Add support for [zen-mode.nvim](https://github.com/folke/zen-mode.nvim).
Fixes #1339
> plugins/zen-mode: init

- plugins/default.nix
- plugins/ui/headlines.nix
- tests/test-sources/plugins/ui/headlines.nix
Add support for [headlines.nvim](https://github.com/lukas-reineke/headlines.nvim).
> plugins/headlines: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
> plugins/lsp: Add tinymist language server

- plugins/default.nix
- plugins/utils/hop.nix
- tests/test-sources/plugins/utils/hop.nix
Add support for [hop.nvim](https://github.com/smoka7/hop.nvim).
Fixes #1394
> plugins/hop: init

- lib/types.nix
- plugins/utils/toggleterm.nix
- tests/test-sources/plugins/utils/toggleterm.nix
Switch our module for the [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) plugin to using the `mkNeovimPlugin` helper.
> plugins/toggleterm: switch to mkNeovimPlugin

- plugins/telescope/extensions/media-files.nix
Fixes https://github.com/nix-community/nixvim/pull/1320#discussion_r1563845492
> plugins/telescope/extensions/media-files: add rename warnings

- plugins/default.nix
- plugins/utils/improved-search.nix
- tests/test-sources/plugins/utils/improved-search.nix
Add support for [improved-search.nvim](https://github.com/backdround/improved-search.nvim).
Fixes #1338
> plugins/improved-search: init

- plugins/default.nix
- plugins/languages/qmk.nix
- tests/test-sources/plugins/languages/qmk.nix
Add support for [qmk.nvim](https://github.com/codethread/qmk.nvim).
Fixes #1318
> plugins/qmk: init

- plugins/default.nix
- plugins/ui/statuscol.nix
- tests/test-sources/plugins/ui/statuscol.nix
Add support for [statuscol.nvim](https://github.com/luukvbaal/statuscol.nvim).
Fixes #1428
> plugins/statuscol: init

- plugins/default.nix
- plugins/git/gitignore.nix
- tests/test-sources/plugins/git/gitignore.nix
Add support for [gitignore.nvim](https://github.com/wintermute-cell/gitignore.nvim).
Fixes #1418
> plugins/gitignore: init

- plugins/default.nix
- plugins/languages/godot.nix
- tests/test-sources/plugins/languages/godot.nix
Add support for [vim-godot](https://github.com/habamax/vim-godot).
Fixes #1359
> plugins/godot: init

- lib/maintainers.nix
- plugins/default.nix
- plugins/utils/dressing.nix
- tests/test-sources/plugins/utils/dressing.nix
This PR adds the dressing.nvim plugin. 
closes #1393
> plugins/dressing: init

- lib/maintainers.nix
- plugins/default.nix
- plugins/utils/competitest.nix
- tests/test-sources/plugins/utils/competitest.nix
Add support for [competitest.nvim](https://github.com/xeluxee/competitest.nvim), a neovim plugin for Competitive Programming.
> plugins/competitest: init

- plugins/default.nix
- plugins/git/lazygit.nix
- tests/test-sources/plugins/git/lazygit.nix
This PR adds the [lazygit.nvim](https://github.com/kdheepak/lazygit.nvim) plugin. 
closes #1468.
> plugins/lazygit: init

- plugins/completion/cmp/sources.nix
- tests/test-sources/plugins/completion/cmp-async-path.nix
Add support for [cmp-async-path](https://codeberg.org/FelipeLema/cmp-async-path).
> plugins/cmp-async-path: init

- plugins/lsp/helpers.nix
This is the first step to a more ambitious internal refactoring.
> plugins/lsp: make plugins.lsp.servers.*.settings RFC-42 compliant 

- .github/workflows/build_documentation.yml
- Updates the workflow actions for building the documentation to the latest.
> ci/cd: build_documentation - update workflow actions

- plugins/languages/rustaceanvim.nix
The old option would never convert a string to raw lua code. As it would always interpret it as an enum value, even if it wasn't one of the accepted values.
Using the already existing helper option types would either always convert it to a string or always convert it to raw lua code.  So I've added new option types that test whether it's an value that's part of the enum values and if not, convert it to raw lua: `mkNullOrEnumOrStrLua(Fn)` and `defaultNullOpts.mkEnumOrStrLua(Fn)` 
I'm pretty new to Nix, Neovim and Lua. So if this isn't very idiomatic/correct, please let me know!
Also I've added the `"neotest"` value to the possible executors.
> plugins/languages/rustaceanvim: fix executor option

- lib/options.nix
I hope that this change will heavily reduce people's legitimate confusion on having to "Default: " In the documentation.
> lib/options: change "default: ..." to "Plugin default: ..."

- plugins/utils/ccc.nix
- tests/test-sources/plugins/utils/ccc.nix
Follow up of #1368 which I closed by accident.
> plugins/ccc: Add more settings

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/jsonls.nix
- tests/test-sources/plugins/lsp/yamlls.nix
Cherry-picked @GaetanLepage's commits from #1477 so that these changes can be merged without waiting for that PR.
> plugins/{yamlls,jsonls}: add settings option

- plugins/default.nix
- plugins/git/git-conflict.nix
- tests/test-sources/plugins/git/git-conflict.nix
Add support for [git-conflict.nvim](https://github.com/akinsho/git-conflict.nvim).
Fixes #1553
> plugins/git-conflict: init

- plugins/colorschemes/nightfox.nix
- tests/test-sources/plugins/colorschemes/nightfox.nix
Let's add an option to enhance discoverability.
> colorschemes/nightfox: add flavor option

- lib/maintainers.nix
- plugins/colorschemes/modus.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/modus.nix
> Add the Modus colorscheme

- lib/maintainers.nix
- plugins/default.nix
- plugins/lsp/lsp-status.nix
- tests/test-sources/plugins/lsp/lsp-status.nix
added plugin options for [lsp-status.nvim](https://github.com/nvim-lua/lsp-status.nvim)
> plugin/lsp-status: init

- README.md
- docs/man/default.nix
- docs/mdbook/SUMMARY.md
- docs/user-guide/config-examples.md
Fixes #1295 #1299 (kickstart.nixvim is still a WIP though).
> docs/user-guide: add configuration examples

- plugins/default.nix
- plugins/git/octo.nix
- tests/test-sources/plugins/git/octo.nix
As #805 seems to have been abandoned, I have updated it.
Closes #805
> plugins/git/octo: init

- docs/user-guide/config-examples.md
https://github.com/MikaelFangel/nixvim-config
> docs/user-guide/config-examples: add MikaelFangel's config

- plugins/default.nix
- plugins/ui/edgy.nix
- tests/test-sources/plugins/ui/edgy.nix
Add support for [edgy.nvim](https://github.com/folke/edgy.nvim).
Fixes #1568
> plugins/edgy: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for [ruby-lsp](https://github.com/Shopify/ruby-lsp).
Fixes #1604
> plugins/lsp: add ruby-lsp

- lib/to-lua.nix
> helpers/toLuaObject: fix rawKey handling

- plugins/ai/copilot-chat.nix
- plugins/default.nix
- tests/test-sources/plugins/ai/copilot-chat.nix
Add support for [CopilotChat.nvim](https://github.com/CopilotC-Nvim/CopilotChat.nvim).
Fixes #992
> plugins/copilot-chat: init

- docs/user-guide/config-examples.md
Adds another great configuration example: https://github.com/elythh/nixvim
CC @elythh
> docs/user-guide/config-examples: add elythh's config

- CONTRIBUTING.md
[Final render](https://github.com/MattSturgeon/nixvim/blob/contr_commit_msg/CONTRIBUTING.md)
> contributing: describe commit title style

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Adds support for [languageserver](https://github.com/REditorSupport/languageserver) for R
> plugins/lsp: Add r_language_server lsp

- plugins/snippets/luasnip/default.nix
This PR adds the `plugins.luasnip.fromSnipmate` option. Because there was lots of code duplication, I decided to separate loader types from the configuration. Hopefully, that is not too much for a single commit.
> plugins/luasnip: add SnipMate loader

- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/jsonnet-ls-settings.nix
- tests/test-sources/plugins/lsp/_lsp.nix
- tests/test-sources/plugins/lsp/language-servers/jsonnet.nix
> plugins/lsp/jsonnet: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
> plugins/lsp/tflint: init

- plugins/completion/cmp/sources.nix
- plugins/completion/cmp/sources/cmp-ai.nix
- plugins/completion/cmp/sources/default.nix
- tests/test-sources/plugins/completion/cmp-ai.nix
- tests/test-sources/plugins/completion/cmp-all-sources.nix
Add support for [cmp-ai](https://github.com/tzachar/cmp-ai).
Fixes #1617
> plugins/cmp: add cmp_ai source

- docs/user-guide/config-examples.md
Added my config in the entry.
This may help newcomers to go through.
> docs/config-examples: add niksingh710's config

- plugins/languages/ltex-extra.nix
Minor cleanup extracted from #1674
> plugins/ltex-extra: minor options cleanup

- plugins/languages/treesitter/ts-autotag.nix
- tests/test-sources/plugins/languages/treesitter/ts-autotag.nix
> plugins/ts-autotag: switch to mkNeovimPlugin

- plugins/languages/sniprun.nix
- tests/test-sources/plugins/languages/sniprun.nix
Prompted by #1674, switch https://github.com/michaelb/sniprun to mkNeovimPlugin and update options.
[Docs here](https://michaelb.github.io/sniprun/sources/README.html#configuration). Init PR #271
> plugins/sniprun: switch to mkNeovimPlugin

- flake-modules/dev/devshell.nix
- flake-modules/dev/list-plugins.py
> flake/dev: add list-plugins script/command

- docs/user-guide/config-examples.md
Added my nixvim config to the list of examples
> Update config-examples.md with my Nixvim Config

- docs/user-guide/config-examples.md
Adding new configuration JMartJonesy/kickstart.nixvim
> Adding new example nixvim configuration

- lib/maintainers.nix
- plugins/colorschemes/everforest.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/everforest.nix
Adding the everforest colorscheme https://github.com/sainnhe/everforest
Fairly new to nix, I would super appreciate any feedback yall have!
I pulled all the settings info strings directly out of `:help everforest`
> colorschemes/everforest: init

- CONTRIBUTING.md
- README.md
- **readme: use markdown warning**
- **contributing: add note clarifying freeform `settings`**
> {readme,contributing}: markdown alerts

- plugins/utils/yanky.nix
- tests/test-sources/plugins/utils/yanky.nix
Only question is whether we want to add
```lua
local utils = require("yanky.utils")
local mapping = require("yanky.telescope.mapping")
```
to the scope to reduce the boilerplate in the config.
The question is more general than just for this case: do we want to do such things or do we stick to a very minimal approach (just calling `setup` with `cfg.settings` ?
I have no hard opinion on this.
> plugins/yanky: switch to mkNeovimPlugin

- flake-modules/updates/default.nix
- flake-modules/updates/efmls-configs.nix
- generated/efmls-configs.nix
- plugins/lsp/language-servers/efmls-configs-pkgs.nix
- plugins/lsp/language-servers/efmls-configs.nix
This allows to remove a source of IFD, and reduces the complexity in building the options
> plugins/efmls-configs: Use a generated file

- plugins/languages/treesitter/injections.scm
- plugins/languages/treesitter/treesitter-refactor.nix
- plugins/languages/treesitter/treesitter-textobjects.nix
- plugins/languages/treesitter/treesitter.nix
- plugins/utils/vim-matchup.nix
- tests/test-sources/plugins/languages/treesitter/treesitter.nix
Had a setting I wanted to take advantage of that wasn't supported in its current iteration... figured instead of changing that specific setting I'd help migrate it to the new schema.
> plugins/treesitter: switch to mkNeovimPlugin

- plugins/languages/treesitter/treesitter.nix
Forgot to update this section after a few of the changes near the end of the previous [PR](https://github.com/nix-community/nixvim/pull/1801).
> plugins/treesitter: fix settingsExample

- plugins/default.nix
- plugins/languages/markdown/glow.nix
- tests/test-sources/plugins/languages/markdown/glow.nix
Adds support for https://github.com/ellisonleao/glow.nvim
> plugins/glow: init

- docs/user-guide/faq.md
Documents the fix for #1282
Closes #1282
> docs: Add a section of *Package options

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
> plugins/lsp: add openscad language server

- plugins/languages/treesitter/treesitter.nix
- tests/test-sources/plugins/languages/treesitter/treesitter.nix
Resolves https://github.com/nix-community/nixvim/issues/1911
> plugins/treesitter: support unsetting keymaps

- docs/user-guide/config-examples.md
Adding personal config now that I've migrated it out of my monolithic nix configuration repo. Also included a quick typo fix
> config-examples: add khanelivim

- plugins/snippets/luasnip/default.nix
Simply fixing the link on this documentation page https://nix-community.github.io/nixvim/plugins/luasnip/fromLua.html
> Fix link in doc

- plugins/snippets/luasnip/default.nix
> plugins/luasnip: add filetypeExtend option

- plugins/default.nix
- plugins/utils/firenvim.nix
- tests/test-sources/plugins/utils/firenvim.nix
Add support for [firenvim](https://github.com/glacambre/firenvim).
Fixes #1713
> plugins/firenvim: init

- plugins/default.nix
- plugins/languages/markdown/markview.nix
- tests/test-sources/plugins/languages/markdown/markview.nix
Adds module for https://github.com/OXY2DEV/markview.nvim
> plugins/markview: init

- plugins/utils/which-key.nix
- tests/test-sources/plugins/utils/which-key.nix
Improve documentation for supported configurations
> plugins/which-key: updated spec examples and tests

- plugins/telescope/default.nix
- plugins/telescope/extensions/_helpers.nix
- plugins/telescope/extensions/file-browser.nix
- plugins/telescope/extensions/frecency.nix
- plugins/telescope/extensions/fzf-native.nix
- plugins/telescope/extensions/fzy-native.nix
- plugins/telescope/extensions/media-files.nix
- plugins/telescope/extensions/ui-select.nix
- plugins/telescope/extensions/undo.nix
Similar to https://github.com/nix-community/nixvim/pull/2052
> plugins/telescope: migrate helpers -> lib.nixvim

- plugins/colorschemes/ayu.nix
- plugins/colorschemes/base16/default.nix
- plugins/colorschemes/catppuccin.nix
- plugins/colorschemes/cyberdream.nix
- plugins/colorschemes/dracula.nix
- plugins/colorschemes/everforest.nix
- plugins/colorschemes/gruvbox.nix
- plugins/colorschemes/kanagawa.nix
- plugins/colorschemes/melange.nix
- plugins/colorschemes/modus.nix
- plugins/colorschemes/nightfox.nix
- plugins/colorschemes/nord.nix
- plugins/colorschemes/one.nix
- plugins/colorschemes/onedark.nix
- plugins/colorschemes/oxocarbon.nix
- plugins/colorschemes/palette.nix
- plugins/colorschemes/poimandres.nix
- plugins/colorschemes/rose-pine.nix
- plugins/colorschemes/tokyonight.nix
- plugins/colorschemes/vscode.nix
I see all the colorschemes are like this, gonna just update them all here
> plugins/colorschemes: migrate helpers -> lib.nixvim

- example.nix
- plugins/colorschemes/base16/default.nix
- plugins/statuslines/lightline.nix
- tests/test-sources/plugins/statuslines/lightline.nix
Resolves https://github.com/nix-community/nixvim/issues/2063
> plugins/lightline: migrate to mkNeovimPlugin

- plugins/telescope/extensions/_helpers.nix
See https://github.com/nix-community/nixvim/pull/2053#issuecomment-2307961673
cc @andrevmatos
> plugins/lsp/extensions: remove `with lib` + fix `mkRaw` reference

- plugins/languages/treesitter/treesitter.nix
Adds a section to tree-sitter's documentation describing how to install your own grammars.
> docs: document how to install custom tree-sitter grammars

- plugins/languages/treesitter/treesitter.nix
This PR is a fix for a markdown issue caused by #2061
cc: @khaneliman
> docs: fix markdown issue with tree-sitter docs

- flake-modules/dev/default.nix
- flake-modules/dev/devshell.nix
- flake-modules/dev/list-plugins.py
I have been using this more and wanted to create some filters to only output the information I cared about. This adds the ability to filter by kind, state, and whether a plugin has deprecation warnings.
> flake-modules/list-plugins: add extra filters

- plugins/lsp/conform-nvim.nix
- tests/test-sources/plugins/lsp/conform-nvim.nix
Resolves https://github.com/nix-community/nixvim/issues/2064
> plugins/conform-nvim: migrate to mkNeovimPlugin

- plugins/statuslines/lightline.nix
- tests/test-sources/plugins/statuslines/lightline.nix
Resolves https://github.com/nix-community/nixvim/issues/1934 which is also blocking https://github.com/nix-community/nixvim/pull/2076
> tests/plugins/lightline: fix test

- lib/maintainers.nix
- plugins/default.nix
- plugins/utils/comment-box.nix
- tests/test-sources/plugins/utils/comment-box.nix
Adds comment-box-nvim as a plugin.
Waiting on https://nixpk.gs/pr-tracker.html?pr=335126
> plugins/comment-box-nvim: init

- README.md
Resolves https://github.com/nix-community/nixvim/issues/1934 There is an incorrect example, that might have worked previously, but is no longer the case.
> readme: fix incorrect demo configuration

- plugins/utils/alpha.nix
- plugins/utils/fzf-lua.nix
@MattSturgeon caught me being dumb https://github.com/nix-community/nixvim/pull/2112#discussion_r1737165765
> plugins: fix iconsPackage

- plugins/filetrees/neo-tree.nix
- plugins/filetrees/nvim-tree.nix
- plugins/git/committia.nix
- plugins/git/fugitive.nix
- plugins/git/git-worktree.nix
- plugins/git/gitgutter.nix
- plugins/git/neogit/default.nix
- plugins/pluginmanagers/lazy.nix
- plugins/pluginmanagers/packer.nix
- plugins/statuslines/lualine.nix
- tests/test-sources/plugins/filetrees/neo-tree.nix
- tests/test-sources/plugins/filetrees/nvim-tree.nix
- tests/test-sources/plugins/git/committia.nix
- tests/test-sources/plugins/git/git-worktree.nix
- tests/test-sources/plugins/git/neogit.nix
- tests/test-sources/plugins/pluginmanagers/lazy.nix
- tests/test-sources/plugins/pluginmanagers/packer.nix
- tests/test-sources/plugins/statuslines/lualine.nix
Follow up to https://github.com/nix-community/nixvim/pull/2112
> treewide: standardize gitPackage

- CONTRIBUTING.md
This PR is a direct follow-up of the comment: https://github.com/nix-community/nixvim/pull/2115#issuecomment-2318884967.
> Update contributing md default nix

- plugins/languages/treesitter/treesitter.nix
- plugins/telescope/default.nix
- tests/test-sources/plugins/languages/treesitter/treesitter.nix
- tests/test-sources/plugins/telescope/default.nix
Revert [treesitter](https://github.com/nix-community/nixvim/pull/2108) add (I dont know what was going on in my head)
> plugins/telescope: add iconsPackage

- plugins/TEMPLATE.nix
> plugins/TEMPLATE: drop helpers and adopt new style

- plugins/statuslines/lualine.nix
- tests/test-sources/plugins/statuslines/lualine.nix
Resolves https://github.com/nix-community/nixvim/issues/2130
Expediting this change to resolve the bug. Refactoring has taken longer than I expected and I don't want to hold this up because of it.
> plugins/lualine: support custom extensions

- README.md
Resolves https://github.com/nix-community/nixvim/issues/2142
> readme: fix installation link

- plugins/colorschemes/dracula-nvim.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/dracula-nvim.nix
This PR adds the dracula.nvim plugin.
Here the link to nixpkgs: https://search.nixos.org/packages?channel=24.05&show=vimPlugins.dracula-nvim&from=0&size=50&sort=relevance&type=packages&query=dracula-nvim.
Thanks in advance for reviewing :-)
> plugins/dracula.nvim: init

- plugins/colorschemes/dracula-nvim.nix
- tests/test-sources/plugins/colorschemes/dracula-nvim.nix
Follow up to https://github.com/nix-community/nixvim/pull/2153
Closes https://github.com/nix-community/nixvim/pull/2155
> colorschemes/dracula-nvim: fixes

- docs/mdbook/default.nix
- lib/autocmd-helpers.nix
- lib/deprecation.nix
- lib/keymap-helpers.nix
- lib/neovim-plugin.nix
- lib/options.nix
- lib/to-lua.nix
- lib/types.nix
- lib/utils.nix
- lib/vim-plugin.nix
- modules/autocmd.nix
- modules/clipboard.nix
- modules/colorscheme.nix
- modules/commands.nix
- modules/diagnostics.nix
- modules/editorconfig.nix
- modules/filetype.nix
- modules/highlights.nix
- modules/keymaps.nix
- modules/misc/nixvim-info.nix
- modules/opts.nix
- modules/output.nix
- wrappers/modules/hm.nix
Went through the internal modules and libraries cleaning up `with lib;` usage. Have another branch going through plugins but wanted to get opinions and extra eyes on this first.  
Tested with my own config and it seems to work fine with no regressions, but would like some extra eyes on this.
> internals: cleanup with lib;

- CONTRIBUTING.md
Updates the plugin-declaration docs in line with the current state of nixvim and our current best practices.
See the ["rich" diff](https://github.com/nix-community/nixvim/pull/2173/files?short_path=eca12c0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055), and [fully rendered file](https://github.com/MattSturgeon/nixvim/blob/contributing-fixes/CONTRIBUTING.md).
> contributing: update plugin declaration docs

- plugins/default.nix
- plugins/utils/web-devicons.nix
- tests/test-sources/plugins/utils/web-devicons.nix
The Nixpkg plugin is here: https://search.nixos.org/packages?channel=24.05&show=vimPlugins.nvim-web-devicons&from=0&size=50&sort=relevance&type=packages&query=++nvim-web-devicons.
https://github.com/nvim-tree/nvim-web-devicons/
Thanks in advance :-)
> plugins/nvim-web-devicons: init

- plugins/default.nix
- plugins/ui/numbertoggle.nix
- tests/test-sources/plugins/ui/numbertoggle.nix
This PR adds this plugin: https://search.nixos.org/packages?channel=24.05&show=vimPlugins.vim-numbertoggle&from=0&size=50&sort=relevance&type=packages&query=numbertoggle.
https://github.com/jeffkreeftmeijer/vim-numbertoggle/
> Add the vim-numbertoggle plugin

- plugins/utils/hardtime.nix
- tests/test-sources/plugins/utils/hardtime.nix
This PR will bring the Hardtime plugin to the "settings" era.
This is in direct continuance of this: https://github.com/nix-community/nixvim/discussions/2192.
Who should I put down as the maintainer of the plugin?
Fixes #2192
> plugins/hardtime: migrate to mkNeovimPlugin

- tests/test-sources/example-configurations/issues.nix
> tests/issues: fix deprecation warning

- plugins/languages/rust/rustaceanvim/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1258
> plugins/rustaceanvim: add lsp assertion

- plugins/by-name/treesitter/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1865
> plugins/treesitter: clarify nixGrammars and ensure_installed

- plugins/by-name/rest/default.nix
- tests/test-sources/plugins/by-name/rest/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1466
> plugins/rest: handle dependencies, ease configuration, and cleanup

- docs/default.nix
- docs/pkgs.nix
- flake-modules/packages.nix
Will conflict with #2221 and #2230, so let's hold off on merging.
> docs: move pkgs overlays to their own file

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Harper is a grammar/spell checker "for developers".
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#harper_ls
https://github.com/elijah-potter/harper
> plugins/lsp/harper-ls: init

- plugins/by-name/todo-comments/default.nix
- tests/test-sources/plugins/by-name/todo-comments/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2181
> plugins/todo-comments: support conditional key mappings

- plugins/by-name/sqlite-lua/default.nix
- tests/test-sources/plugins/by-name/sqlite-lua/default.nix
Creating for https://github.com/kkharji/sqlite.lua to support work being done in https://github.com/nix-community/nixvim/pull/2114#discussion_r1759770838
> plugins/sqlite-lua: init

- plugins/by-name/markdown-preview/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2244
> plugins/markdown-preview: fix browserFunc rename

- plugins/by-name/precognition/default.nix
- tests/test-sources/plugins/by-name/precognition/default.nix
Creating a module for https://github.com/tris203/precognition.nvim
> plugins/precognition: init

- plugins/by-name/overseer/default.nix
- tests/test-sources/plugins/by-name/overseer/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1528
> plugins/overseer: init

- plugins/by-name/ts-comments/default.nix
- tests/test-sources/plugins/by-name/ts-comments/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2103
> plugins/ts-comments: init

- plugins/by-name/compiler/default.nix
- tests/test-sources/plugins/by-name/compiler/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1527
From what I could tell, there's not much to setup with this?
> plugins/compiler: init

- plugins/by-name/smartcolumn/default.nix
- tests/test-sources/plugins/by-name/smartcolumn/default.nix
Create module for https://github.com/m4xshen/smartcolumn.nvim
> plugins/smartcolumn: init

- plugins/by-name/overseer/default.nix
- tests/test-sources/plugins/by-name/overseer/default.nix
Actually supports a table to customize the strategy.
> plugins/overseer: fix strategy option

- plugins/by-name/helpview/default.nix
- tests/test-sources/plugins/by-name/helpview/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2085
> plugins/helpview: init

- plugins/by-name/nvim-jdtls/default.nix
Needs to be rewritten, but for now I wanted to pass a lua entry for the field.
> plugins/nvim-jdtls: configuration allow raw lua

- plugins/by-name/telescope/extensions/default.nix
- plugins/by-name/telescope/extensions/manix.nix
- tests/test-sources/plugins/by-name/telescope/manix.nix
Resolves https://github.com/nix-community/nixvim/issues/1232
> plugins/telescope-manix: init

- plugins/by-name/package-info/default.nix
- tests/test-sources/plugins/by-name/package-info/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1380
> plugins/package-info: init

- plugins/by-name/telescope/extensions/manix.nix
> plugins/telescope-manix: fix manixPackage usage

- plugins/by-name/telescope/extensions/default.nix
- plugins/by-name/telescope/extensions/live-greps-args.nix
- tests/test-sources/plugins/by-name/telescope/live-grep-args.nix
Resolves: https://github.com/nix-community/nixvim/issues/1902
> plugins/telescope-live-grep-args: init

- plugins/lsp/language-servers/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2260
> plugins/lsp/gopls: add goPackage

- plugins/by-name/otter/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2111
> plugins/otter: add autoActivate

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Resolves https://github.com/nix-community/nixvim/issues/1937
> plugins/lsp/volar: add ts-ls integration

- plugins/by-name/markview/default.nix
- tests/test-sources/plugins/by-name/markview/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2295
> plugins/markview: mode -> modes

- lib/maintainers.nix
- plugins/by-name/wrapping/default.nix
- tests/test-sources/plugins/by-name/wrapping/default.nix
Add new plugin: wrapping 
This is my first time really trying to contribute to a tool I daily drive. Please let me know what I am doing wrong. I think the contributing docs are a little confusing for a newcomer. 
Thanks!
> plugins/wrapping: init

- plugins/deprecation.nix
Resolves https://github.com/nix-community/nixvim/issues/2330
> plugins/deprecation: update icons warning

- lib/maintainers.nix
- plugins/by-name/lsp-signature/default.nix
- tests/test-sources/plugins/by-name/lsp-signature/default.nix
> plugins/lsp-signature: init

- docs/user-guide/config-examples.md
Adding my own repo to the config examples. Please let me know if anything is wrong. 
Thanks!
> config-examples: add zainkergaye

- plugins/by-name/wrapping/default.nix
- tests/test-sources/plugins/by-name/wrapping/default.nix
Adding more options to wrapping.nvim. Please let me know if anything is amiss. Thank you!
> plugins/wrapping: Add more options

- plugins/lsp/language-servers/default.nix
see https://github.com/NixOS/nixpkgs/pull/340314
> Resolve aliases

- docs/user-guide/config-examples.md
Added my personal configuration, focused on automatic formatting, LSP and debugging of several popular languages.
> config-examples: add fred-drake

- plugins/by-name/lsp-status/default.nix
Follow up to https://github.com/nix-community/nixvim/pull/2366#discussion_r1790571271
> plugins/lsp-status: fix update_interval type

- plugins/by-name/nvim-ufo/default.nix
- tests/test-sources/plugins/by-name/nvim-ufo/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2362
> plugins/nvim-ufo: migrate to mkNeovimPlugin

- plugins/by-name/rustaceanvim/default.nix
Follow up to https://github.com/nix-community/nixvim/pull/2365
> plugins/rustaceanvim: fix deprecation

- docs/default.nix
I've just added a parameter to the search that allows configuring the title. I hope the suggested one is what you like.
>  options-search: configure title 

- plugins/by-name/rest/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2383
> plugins/rest: update v3 options

- plugins/lsp/language-servers/default.nix
- tests/generated.nix
> tests/generated: validate declared lsp packages

- plugins/lsp/language-servers/_mk-lsp.nix
- plugins/lsp/language-servers/default.nix
As per https://github.com/nix-community/nixvim/pull/2365#discussion_r1793846911
> plugins/lsp: use a no-default option when there is no default provided

- plugins/by-name/trouble/default.nix
- tests/test-sources/plugins/by-name/trouble/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2398
Looks like there was a rewrite of the plugin recently that we didn't update the module to properly account for in documentation. Cleaning up the documented options and updating test cases.
> plugins/trouble: v3 cleanup

- plugins/by-name/nabla/default.nix
- tests/test-sources/plugins/by-name/nabla/default.nix
Add [nabla.nvim](https://github.com/jbyuki/nabla.nvim), an helper to take scientific notes in Neovim.
Fixes #2423
> plugins/nabla: init

- plugins/by-name/telekasten/default.nix
- tests/test-sources/plugins/by-name/telekasten/default.nix
Add [telekasten](https://github.com/nvim-telekasten/telekasten.nvim), a
Zettelkasten implementation using telescope.
> plugins/telekasten: init

- plugins/by-name/noice/default.nix
- tests/test-sources/plugins/by-name/noice/default.nix
~Got the main migration done. But, there are tons of options without descriptions or not appropriately formatted descriptions, atm.~
> noice: migrate to mkNeovimPlugin

- plugins/by-name/fastaction/default.nix
- tests/test-sources/plugins/by-name/fastaction/default.nix
Add [fastaction.nvim](https://github.com/Chaitanyabsprip/fastaction.nvim/), an _efficiency plugin designed to optimize code actions in Neovim_.
Fixes #2471
> plugins/fastaction: init

- plugins/by-name/jupytext/default.nix
Add jupytext python3 Dependency for the juptext plugin
#2367
> Add jupytext python3Dependency to jupytext plugin

- plugins/by-name/helm/default.nix
Add the suggestion from https://github.com/nix-community/nixvim/issues/989#issuecomment-2333864377.
> plugins/helm: add recommended autocmd for proper LSP behavior

- plugins/lsp/lsp-packages.nix
This is already in the nixpkgs version locked.
> plugins/lsp: enable angularls

- modules/top-level/output.nix
- tests/test-sources/modules/output.nix
* Added `withPerl` option to enable Perl provider.
* Added `withPython3` option to enable Python 3 provider.
> modules/output: expose other providers

- plugins/by-name/vim-dadbod-completion/default.nix
- plugins/by-name/vim-dadbod-ui/default.nix
- plugins/by-name/vim-dadbod/default.nix
- tests/test-sources/plugins/by-name/vim-dadbod-completion/default.nix
- tests/test-sources/plugins/by-name/vim-dadbod-ui/default.nix
- tests/test-sources/plugins/by-name/vim-dadbod/default.nix
Add vim-dadbod, vim-dadbod-ui, and vim-dadbod-completion
#2389
> plugins/vim-dadbod: init, plugins/vim-dadbod-ui: init, plugins/vim-dadbod-completion: init

- plugins/by-name/snacks/default.nix
- tests/test-sources/plugins/by-name/snacks/default.nix
Closes #2513
- Introduces `snacks.nvim` plugin by folke
> plugins/snacks: init

- CONTRIBUTING.md
I tried to add a little bit of documentation regarding the `mkPlugin` functions.
> docs/contributing: improve mk(Neovim/Vim)Plugin function documentation

- plugins/by-name/kulala/default.nix
- tests/test-sources/plugins/by-name/kulala/default.nix
> plugins/kulala: init

- plugins/by-name/tmux-navigator/default.nix
- **plugins/tmux-navigator: use markdown admonition**
- **plugins/tmux-navigator: re-word usage instructions**
> plugins/tmux-navigator: update usage docs

- plugins/by-name/quarto/default.nix
- tests/test-sources/plugins/by-name/quarto/default.nix
> plugins/quarto: init

- .github/workflows/build_documentation.yml
- docs/mdbook/SUMMARY.md
- docs/mdbook/default.nix
- docs/mdbook/index.md
- docs/user-guide/install.md
Backports:
- re-sync build-docs workflow with main
- #2442
- #2554
> [backport-24.05] docs: link to all "available" versions of the docs

- .github/workflows/build_documentation.yml
- .github/workflows/update.yml
> ci: fix nix-install-action versions

- lib/maintainers.nix
- plugins/by-name/vim-be-good/default.nix
- tests/test-sources/plugins/by-name/vim-be-good/default.nix
Integrate the [vim-be-good](https://github.com/ThePrimeagen/vim-be-good) plugin
> plugins/vim-be-good: init

- plugins/by-name/vim-suda/default.nix
- tests/test-sources/plugins/by-name/vim-suda/default.nix
Read/Write already opened files using sudo.
https://github.com/lambdalisue/vim-suda/
> plugins/vim-suda: init

- README.md
> readme: fix `stable` -> `24.05` in docs URL

- flake.lock
- flake.nix
- tests/lsp-servers.nix
- tests/test-sources/plugins/by-name/none-ls/default.nix
- tests/test-sources/plugins/lsp/efmls-configs.nix
**RELEASE: branch-off for nixos-24.11**
> [RELEASE] nixos 24.11

- plugins/lsp/default.nix
Add keymaps default descriptions for lsp buf and diagnostics
> plugin/lsp: automatic keymap description

- plugins/by-name/trouble/default.nix
Discovered in testing https://github.com/nix-community/nixvim/pull/2602
> plugins/trouble: fix originalName

- plugins/by-name/codecompanion/default.nix
- tests/test-sources/plugins/by-name/codecompanion/default.nix
Add support for [codecompanion.nvim](https://github.com/olimorris/codecompanion.nvim), an AI coding integration plugin.
Fixes #2569
> plugins/codecompanion: init

- plugins/by-name/dotnet/default.nix
- tests/test-sources/plugins/by-name/dotnet/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2511
> plugins/dotnet: init

- plugins/cmp/sources/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2621
> plugins/cmp/sources: add cmp-vimtex

- plugins/by-name/remote-nvim/default.nix
- tests/test-sources/plugins/by-name/remote-nvim/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2546
> plugins/remote-nvim: init

- plugins/by-name/grug-far/default.nix
- tests/test-sources/plugins/by-name/grug-far/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2133
> plugins/grug-far: init

- flake-modules/dev/default.nix
- plugins/by-name/conform-nvim/default.nix
- plugins/by-name/neotest/default.nix
- plugins/pluginmanagers/lazy.nix
- wrappers/_shared.nix
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
Adding https://github.com/astro/deadnix through our git-hooks.nix pre-commit hooks.
https://github.com/cachix/git-hooks.nix/blob/c2b3567b03baf0999a1dd14f7e7ab34b46297d68/modules/hooks.nix#L283-L338
> flake-modules/dev: add deadnix

- plugins/by-name/dap-lldb/default.nix
- tests/test-sources/plugins/by-name/dap-lldb/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2400
> plugins/dap-lldb: init

- flake-modules/dev/list-plugins.py
- **dev/list-plugins: fix spacing in plugin printing (deprecation warning)**
- **dev/list-plugins: add symbol for 'MISC' type plugins**
- **dev/list-plugins: update EXCLUDES and KNOWN_PATHS variables**
> list-plugins: improve script

- docs/mdbook/default.nix
- docs/user-configs/default.nix
- docs/user-configs/list.toml
- docs/user-configs/tests.nix
- docs/user-guide/config-examples.md
- flake-modules/tests.nix
- tests/default.nix
This should help to maintain uniformity and hopefully make contributions easier.
I would like to add tests for robustness and to avoid regressions. Any ideas on what to test and/or how would be great.
If there's any toml validation that needs to happen, maybe we could have a test for that too? This could then be included in the pre-commit hooks.
EDIT: I added some regression tests that ensure it is able to handle a few edge-cases.
> docs/config-examples: generate dynamically from a toml list

- flake-modules/dev/devshell.nix
- flake-modules/dev/new-plugin.py
Allows quickly creating new plugins to help fulfill plugin creation requests.
> flake-modules/new-plugin: init

- flake-modules/dev/list-plugins.py
Remove hardcoded exclusions that were recently migrated
> dev/list-plugins: cleanup migrated plugins

- flake-modules/dev/list-plugins.py
- plugins/by-name/floaterm/default.nix
- tests/test-sources/plugins/by-name/floaterm/default.nix
> plugins/floaterm: move to mkVimPlugin

- flake-modules/dev/default.nix
- flake-modules/dev/devshell.nix
- flake-modules/dev/list-plugins.py
- flake-modules/dev/list-plugins/default.nix
- flake-modules/dev/list-plugins/list-plugins.py
- **dev/list-plugins: properly error out when parsing is unsuccessfull**
- **dev/list-plugins: make it a proper package**
- **dev/list-plugins: add --root-path argument**
- **dev/list-plugins: add flake check**
> dev/list-plugins: various improvements

- docs/user-configs/list.toml
Adds my nixvim configuration to the configuration examples
> user-configs: add HeitorAugustoLN's configuration

- flake-modules/dev/list-plugins/default.nix
> dev/list-plugins: conditionally create devshell only if devshell input is present

- plugins/by-name/blink-compat/default.nix
- tests/test-sources/plugins/by-name/blink-compat/default.nix
Depends on NixOS/nixpkgs#365782
> plugins/blink-compat: init

- docs/user-configs/list.toml
user-configs: add @r6t's config
> user-configs: add @r6t's config

- plugins/by-name/molten/default.nix
- plugins/by-name/wezterm/default.nix
- tests/test-sources/plugins/by-name/wezterm/default.nix
Continuation of https://github.com/nix-community/nixvim/pull/2597
> plugins/wezterm: init 

- lib/options.nix
- plugins/by-name/flutter-tools/default.nix
- tests/test-sources/plugins/by-name/flutter-tools/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2470
> plugins/flutter-tools: init

- flake-modules/dev/new-plugin.py
> flake/dev/new-plugin: add '# TODO' next to the maintainers line

- plugins/by-name/csvview/default.nix
- tests/test-sources/plugins/by-name/csvview/default.nix
Add support for [csvview.nvim](https://github.com/hat0uma/csvview.nvim), a Neovim plugin for CSV file editing.
Fixes #2409
> plugins/csvview: init

- lib/options.nix
- plugins/by-name/copilot-chat/default.nix
- plugins/by-name/copilot-lua/default.nix
- plugins/by-name/coverage/default.nix
- plugins/by-name/fidget/default.nix
- plugins/by-name/lspsaga/default.nix
- plugins/by-name/neotest/options.nix
- plugins/by-name/twilight/default.nix
- plugins/by-name/zen-mode/default.nix
- plugins/colorschemes/catppuccin.nix
- plugins/colorschemes/nightfox.nix
- plugins/colorschemes/tokyonight.nix
- **lib/options: add defaultNullOpts.mkProportion**
- **plugins.*: use defaultNullOpts.mkProportion wherever possible**
Basically:
```nix
mkProportion = mkNullable (types.numbers.between 0.0 1.0)
```
If you have a better name suggestion, please go for it.
> lib/options: add defaultNullOpts.mkProportion

- flake-modules/dev/list-plugins/list-plugins.py
- plugins/by-name/telescope/extensions/default.nix
- plugins/by-name/telescope/extensions/project.nix
- tests/test-sources/plugins/by-name/telescope/project.nix
Follow up to https://github.com/nix-community/nixvim/pull/2791
https://github.com/nvim-telescope/telescope-project.nvim to provide user's with an alternative.
> plugins/telescope: add project extension

- plugins/by-name/neoconf/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2346
> plugins/neoconf: setup before lspconfig

- plugins/by-name/lir/default.nix
- plugins/by-name/lir/settings-options.nix
- tests/test-sources/plugins/by-name/lir/default.nix
Add support for [lir.nvim](https://github.com/tamago324/lir.nvim), a Neovim file explorer.
Fixes #2316
> plugins/lir: init

- plugins/by-name/projections/default.nix
- tests/test-sources/plugins/by-name/projections/default.nix
Add support for [projections.nvim](https://github.com/GnikDroy/projections.nvim), a tiny project + sessions manager for neovim.
> plugins/projections: init

- plugins/by-name/sg/default.nix
- tests/test-sources/plugins/by-name/sg/default.nix
Add support for [sg.nvim](https://github.com/sourcegraph/sg.nvim), experimental Sourcegraph + Cody plugin for Neovim.
Fixes #2106
> plugins/sg: init

- plugins/by-name/llm/default.nix
- plugins/by-name/llm/settings-options.nix
- tests/test-sources/plugins/by-name/llm/default.nix
Add support for [llm.nvim](https://github.com/huggingface/llm.nvim), LLM powered development for Neovim.
Fixes #2205
> plugins/llm: init

- docs/user-guide/helpers.md
- lib/modules.nix
Document the `lib` overlay added in #2731
> docs/user-guide: document nixvim's lib overlay

- docs/default.nix
- docs/mdbook/default.nix
> docs: enable `warningsAreErrors`

- plugins/by-name/alpha/default.nix
- plugins/by-name/clangd-extensions/default.nix
- plugins/by-name/efmls-configs/default.nix
- plugins/by-name/firenvim/default.nix
- plugins/by-name/flutter-tools/default.nix
- plugins/by-name/gitsigns/default.nix
- plugins/by-name/glance/default.nix
- plugins/by-name/headlines/default.nix
- plugins/by-name/lir/default.nix
- plugins/by-name/molten/default.nix
- plugins/by-name/neoclip/default.nix
- plugins/by-name/neotest/adapters.nix
- plugins/by-name/notebook-navigator/default.nix
- plugins/by-name/rest/default.nix
- plugins/by-name/vim-matchup/default.nix
- plugins/by-name/yanky/default.nix
- plugins/by-name/zk/default.nix
Follow-up of #2848.
I have no idea why those changes have not been included in the first PR...
> treewide: use mkWarnings wherever possible

- .github/workflows/update-other.yml
- .github/workflows/update.yml
Minor cleanup, following #2882
> ci/update: cleanup names & comments

- plugins/by-name/quicker/default.nix
- plugins/by-name/quicker/settings-options.nix
- tests/test-sources/plugins/by-name/quicker/default.nix
Add support for [quicker.nvim](https://github.com/stevearc/quicker.nvim), improved UI and workflow for the Neovim quickfix.
Closes #2810
> plugins/quicker: init

- plugins/by-name/gx/default.nix
- tests/test-sources/plugins/by-name/gx/default.nix
Initialize [gx.nvim](https://github.com/chrishrb/gx.nvim), a plugin to replace netrw's gx functionality. 
I added an extra option for actually disabling netrw's gx setting as per the example from the gx docs.
> plugins/gx: init

- .github/workflows/update.yml
Very minor cosmetic followup to #2900
> ci/update: slightly simplify jq query

- plugins/colorschemes/base16/default.nix
> plugins/base16: fix packPathName

- flake/dev/list-plugins/list-plugins.py
> dev/list-plugins: remove outdated overrides

- plugins/by-name/blink-copilot/default.nix
- tests/test-sources/plugins/by-name/blink-copilot/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2915
> plugins/blink-copilot: init

- plugins/by-name/easy-dotnet/default.nix
- tests/test-sources/plugins/by-name/easy-dotnet/default.nix
Add support for [easy-dotnet.nvim](https://github.com/GustavEikaas/easy-dotnet.nvim), support for .Net projects in Neovim.
Fixes #2826
> plugins/easy-dotnet: init

- plugins/by-name/bullets/default.nix
- tests/test-sources/plugins/by-name/bullets/default.nix
Add [bullets.vim](https://github.com/bullets-vim/bullets.vim) plugin.
> plugins/bullets: init

- plugins/by-name/aw-watcher/default.nix
- tests/test-sources/plugins/by-name/aw-watcher/default.nix
Depends on https://github.com/NixOS/nixpkgs/pull/390520
> plugins/aw-watcher: init

- plugins/by-name/minuet/default.nix
- tests/test-sources/plugins/by-name/minuet/default.nix
Add support for [minuet-ai.nvim](https://github.com/milanglacier/minuet-ai.nvim), a plugin providing LLM-based code completion.
Closes #3041
> plugins/minuet: init

- plugins/by-name/jdtls/settings-options.nix
- tests/test-sources/plugins/by-name/jdtls/default.nix
> plugins/jdtls: allow rawLua in settings.cmd

- plugins/by-name/parrot/default.nix
- tests/test-sources/plugins/by-name/parrot/default.nix
Add support for [parrot.nvim](https://github.com/frankroeder/parrot.nvim), a stochastic parrot for Neovim.
Closes #3137
> plugins/parrot: init

- modules/dependencies.nix
- plugins/by-name/codeium-nvim/default.nix
- plugins/by-name/codeium-nvim/deprecations.nix
- **plugins/codeium-nvim: remove rename warnings**
- **plugins/codeium-nvim: remove settings options**
- **modules/dependencies: add coreutils, gzip and util-linux**
- **plugins/codeium-nvim: use dependencies**
> plugins/codeium-nvim: remove rename warnings, remove options, use dependencies

- CONTRIBUTING.md
We're putting more emphasis on examples than settings-options, so it may be helpful to have a section on this in our contributing guide.
> contributing: add "Writing option examples" section

- plugins/by-name/indent-tools/default.nix
- tests/test-sources/plugins/by-name/indent-tools/default.nix
Add support for [indent-tools.nvim](https://github.com/arsham/indent-tools.nvim), a plugin for dealing with indentations.
Closes #3072
> plugins/ident-tools: init

- docs/user-configs/list.toml
user-configs: add @LudovicDeMatteis's config
> user-configs: add @LudovicDeMatteis's config

- modules/dependencies.nix
- plugins/by-name/claude-code/default.nix
- tests/test-sources/modules/dependencies.nix
- tests/test-sources/plugins/by-name/claude-code/default.nix
https://github.com/greggh/claude-code.nvim
> plugins/claude-code: init module

- plugins/by-name/visual-whitespace/default.nix
- tests/test-sources/plugins/by-name/visual-whitespace/default.nix
https://github.com/mcauley-penney/visual-whitespace.nvim
> plugins/visual-whitespace: init module

- plugins/by-name/whitespace/default.nix
- tests/test-sources/plugins/by-name/whitespace/default.nix
https://github.com/johnfrankmorgan/whitespace.nvim
> plugins/whitespace: init module

- plugins/by-name/dap-view/default.nix
- tests/test-sources/plugins/by-name/dap-view/default.nix
https://github.com/igorlfs/nvim-dap-view
> plugins/dap-view: init module

- plugins/by-name/dbee/default.nix
- tests/test-sources/plugins/by-name/dbee/default.nix
Add support for [nvim-dbee](https://github.com/kndndrj/nvim-dbee), interactive database client for Neovim.
Closes #1931
> plugins/dbee: init

- .github/workflows/build_documentation.yml
- README.md
- docs/user-guide/faq.md
- docs/user-guide/install.md
- tests/platforms/hm-extra-files-byte-compiling.nix
- tests/platforms/hm.nix
- tests/platforms/nixos.nix
- **ci/docs: build documentation for the nixos-25.05 branch**
- **treewide: replace mentions of 24.11 with 25.05**
> treewide: prepare nixos-25.05 release

- flake/dev/launch-test.sh
To improve performance and reduce memory usage, have the `tests` command run tests in batches of 20.
This is similar in principal to us grouping the test flake outputs into small batches, however that is done for buildbot's benefit while this is done for local users running the `tests` command.
> dev/tests: run tests in groups

- lib/builders.nix
This should fix potential "argument list too long" errors from bash when writing large files.
It looks like we have minimal test coverage for lib/builders currently, likely because we can't really test derivation content in our "lib-test". There is some coverage in the performance module tests, but no unit tests for the functions themselves.
We can test them using `pkgs.testers.testEqualContents` and `pkgs.testers.testBuildFailure`, but I don't have time to do that right now.
Without unit tests, I may have missed some edge-cases. I simply went through the `lib/builders.nix` file and added `passAsFile = ["text"]` to any instances of `inheret text`.
cc @khaneliman: can you still reproduce your issue?
> lib/builders: pass text as file

- plugins/by-name/mini-git/default.nix
- tests/test-sources/plugins/by-name/mini-git/default.nix
This pull request introduces a new Neovim plugin module for the `mini.git`, along with corresponding test cases.
> plugins/mini-git: init

- plugins/by-name/mini-fuzzy/default.nix
- tests/test-sources/plugins/by-name/mini-fuzzy/default.nix
This pull request introduces a new Neovim plugin module for the `mini.fuzzy`, along with corresponding test cases.
> plugins/mini-fuzzy: init

- plugins/by-name/mini-trailspace/default.nix
- tests/test-sources/plugins/by-name/mini-trailspace/default.nix
This pull request introduces a new Neovim plugin module for the `mini.trailspace`, along with corresponding test cases.
> plugins/mini-trailspace: init

- plugins/by-name/mini-align/default.nix
- tests/test-sources/plugins/by-name/mini-align/default.nix
This pull request introduces a new Neovim plugin module for the `mini.align`, along with corresponding test cases.
> plugins/mini-align: init

- plugins/by-name/lzn-auto-require/default.nix
- tests/test-sources/plugins/by-name/lzn-auto-require/default.nix
Includes end-to-end test
https://github.com/horriblename/lzn-auto-require
> plugins/lzn-auto-require: init

- flake/dev/devshell.nix
- flake/dev/diff-plugins.py
- flake/dev/list-plugins/default.nix
- flake/dev/list-plugins/list-plugins.py
- flake/dev/locate-lsp-packages.py
- flake/dev/new-plugin.py
Helps with https://github.com/nix-community/nixvim/pull/3513#discussion_r2173435209
> flake/dev: use nix-shell shebangs for scripts

- .github/workflows/website.yml
- docs/mdbook/book.toml
- docs/mdbook/custom.css
- docs/mdbook/default.nix
- https://github.com/nix-community/nixvim/pull/3481
- https://github.com/nix-community/nixvim/pull/3484
- https://github.com/nix-community/nixvim/pull/3485
- https://github.com/nix-community/nixvim/pull/3496
Some of these have no noticeable effect on the 25.05 branch, but backporting them helps to avoid merge-conflicts.
> [backport nixos-25.05]: recent docs commits

- flake/ci.nix
If the `ci` options are a set of options rather than a single option, then the module system cannot lazily override it via `mkForce`.
In practice, this means that the dev partition gets evaluated strictly, when the module system "pushes down" the `ci` definitions to its options.
Instead, we must ensure that each attribute listed in `partitionedAttrs` corresponds to an actual option which can be directly defined, with no "pushing down" required.
This can be tested by making the dev partition throw, warn, or trace:
```diff
diff --git a/flake/default.nix b/flake/default.nix
index 36875c31..a5316703 100644
--- a/flake/default.nix
+++ b/flake/default.nix
@@ -6,6 +6,8 @@
...
}:
{
+  debug = true;
+
imports = [
./flake-modules
./ci.nix
@@ -25,7 +27,7 @@
partitions = {
dev = {
-      module = …
```
> flake/ci: fix lazy eval of dev partition

- plugins/lsp/lsp-packages.nix
starpls-bin is an alias since Nov 2024
https://github.com/nixos/nixpkgs/commit/0b7768a68c751c2765c36f38e36eaec89a7dd76f
> lsp-packages: rename starpls-bin to starpls

- plugins/by-name/faster/default.nix
- tests/test-sources/plugins/by-name/faster/default.nix
https://github.com/pteroctopus/faster.nvim/
This plugin is very useful when working with large files.
> plugins/faster: init

- plugins/by-name/comfy-line-numbers/default.nix
- tests/test-sources/plugins/by-name/comfy-line-numbers/default.nix
add support for [comfy-line-numbers.nvim](https://github.com/mluders/comfy-line-numbers.nvim)
Resolve #3545
> plugins/comfy-line-numbers: init

- docs/user-configs/list.toml
Hello! 
Thank you for taking the time to put maintain this project. Ive finally cleaned up my dotfiles enough to feel comfortable sharing them and would love to be a part of the example configuration
> Added nicklundin08/dots user config

- docs/user-configs/list.toml
Originally I had my repo split into two branches. I have since consolidated them and updated my README to explain how to use the repo as a flake or purely standalone.
> Removing old repo

- plugins/by-name/unified/default.nix
- tests/test-sources/plugins/by-name/unified/default.nix
an inline, unified diff viewer for neovim
https://github.com/axkirillov/unified.nvim
> unified: add module

- plugins/by-name/patterns/default.nix
- tests/test-sources/plugins/by-name/patterns/default.nix
A simple pattern viewer for Neovim with support for Lua patterns & regex.
https://github.com/OXY2DEV/patterns.nvim
Oxy has insane customization options available.. limited to just a few in the defaults case.
> patterns: add module

- plugins/by-name/opencode/default.nix
- tests/test-sources/plugins/by-name/opencode/default.nix
Seamlessly integrate the opencode AI assistant with Neovim — convenient and editor-aware research, reviews, and requests.
https://github.com/NickvanDyke/opencode.nvim
> opencode: add module

- plugins/by-name/notify/default.nix
one render style was still missing
> plugins/nvim-notify: add more render styles

- modules/dependencies.nix
- plugins/by-name/opencode/default.nix
Pulling out of https://github.com/nix-community/nixvim/pull/3743
> modules/dependencies: add gemini and opencode; plugins/opencode: add opencode dependency

- plugins/by-name/neogen/default.nix
- plugins/by-name/neogen/deprecations.nix
- tests/test-sources/plugins/by-name/neogen/default.nix
Tracking: https://github.com/nix-community/nixvim/issues/2638
> plugins/neogen: migrate to mkNeovimPlugin

- modules/dependencies.nix
- plugins/by-name/sidekick/default.nix
- tests/test-sources/plugins/by-name/sidekick/default.nix
Adding support for new folke plugin https://github.com/folke/sidekick.nvim
Some of the latest functionality needs a bump, but this is a freeform settings module with cli dependencies that come with it for using functionality. 
Closes https://github.com/nix-community/nixvim/issues/3742
Created https://github.com/NixOS/nixpkgs/pull/447571 for bumping to latest functionality but depends on https://github.com/NixOS/nixpkgs/pull/446983 making it to our flake.lock.
> plugins/sidekick: init module

- plugins/by-name/copilot-lsp/default.nix
- tests/test-sources/plugins/by-name/copilot-lsp/default.nix
https://github.com/copilotlsp-nvim/copilot-lsp
> plugins/copilot-lsp: add module

- modules/dependencies.nix
- plugins/by-name/roslyn/default.nix
- tests/test-sources/modules/dependencies.nix
- tests/test-sources/plugins/by-name/roslyn/default.nix
https://github.com/seblyng/roslyn.nvim
> plugins/roslyn: init module

- modules/dependencies.nix
- plugins/by-name/rzls/default.nix
- tests/test-sources/plugins/by-name/rzls/default.nix
https://github.com/tris203/rzls.nvim
> plugins/rzls: init module

- plugins/by-name/ollama/default.nix
- plugins/by-name/ollama/deprecations.nix
- tests/test-sources/plugins/by-name/ollama/default.nix
https://github.com/nix-community/nixvim/issues/2638
> plugins/ollama: migrate to mkNeovimPlugin

- plugins/by-name/kiwi/default.nix
- tests/test-sources/plugins/by-name/kiwi/default.nix
Add [kiwi.nvim](https://github.com/serenevoid/kiwi.nvim), a stripped down VimWiki for Neovim.
Closes #3615
> plugins/kiwi: init

- plugins/by-name/blame-nvim/default.nix
- tests/test-sources/plugins/by-name/blame-nvim/default.nix
https://github.com/FabijanZulj/blame.nvim
> plugins/blame-nvim: init
