plugins/default.nix, plugins/utils/bufdelete.nix, tests/test-sources/plugins/utils/bufdelete.nix
Simple plugin with only one config option and a handful of commands & lua functions.
See its [README](https://github.com/famiu/bufdelete.nvim/?tab=readme-ov-file).
Fixes #1833
=> plugins/bufdelete: init

flake-modules/tests.nix, lib/maintainers.nix, plugins/utils/dashboard.nix, plugins/utils/refactoring.nix, plugins/utils/tmux-navigator.nix, tests/maintainers.nix
Would it make sense for this to be a custom CI workflow instead of a flake check?
I'm wondering if there's an out-of-sync nixpkgs lock scenario where it being a check could cause issues.
If we can't think of any, then this is fine and we can deal with issues as they come up.
=> tests: add check for nixpkgs maintainers

plugins/languages/rust/rustaceanvim/default.nix, plugins/languages/rust/rustaceanvim/settings-options.nix, tests/test-sources/plugins/languages/rust/rustaceanvim.nix
There is not much more than we can do than print a warning, due to the complication of using submodules.
We may want to have a more generic framework to handle removal/renaming of options.
Fixes #1847
=> plugin/rustaceanvim: Handle rust-analyzer settings rename

flake-modules/dev/default.nix
This prevents ruff to look for personal config files when running `nix fmt`.
=> flake/dev/formatting: run ruff format in isolated mode

plugins/utils/intellitab.nix
```
trace: warning: hrmny profile: The option `plugins.treesitter.indent' defined in `/nix/store/i14h4i6hra9b046ywr8p4n53mk7481wd-source/plugins/utils/intellitab.nix' has been renamed to `plugins.treesitter.settings.indent.enable'.
```
=> fix: update intellitab treesitter config to fix deprecation

plugins/languages/treesitter/treesitter.nix, tests/test-sources/plugins/languages/treesitter/treesitter.nix
Resolves https://github.com/nix-community/nixvim/issues/1849
We default to null for settingsOptions to respect plugin defaults. The nvim-treesitter plugin also has a null default for parser_install_dir, but the fallback of package path isn't a writeable directory on NixOS. This provides a sane default for NixOS users.
=> plugins/treesitter: fix parser_install_dir default

plugins/languages/treesitter/treesitter.nix
opts getting wiped out by setting entire set as default instead of each attribute
=> plugins/treesitter: fix folding

plugins/languages/treesitter/treesitter.nix
The plugin allows passing either the string `"all"` or a list of languages.
Issue reported on Matrix.
=> plugins/treesitter: fix `ensure_installed` to allow `"all"`

.github/workflows/update.yml
This will be paired with a PR refactoring the workflow on the main branch, but nothing should block merging this early since we do not currently run the workflow _on_ the stable branch.
This PR syncs the update workflow with `main`'s, but doesn't include the parts where we generate files.
It also removes the inputs and schedule parts of the workflow, as the intention is a new `call-update.yml` workflow will be added to call each branch's `update.yml` workflow.
=> github/update: run on current branch

plugins/languages/treesitter/treesitter.nix
I think this got erroneously changed in #1801.
Having a fold at every function is rather annoying to work with and having to unfold many things in every file.
=> plugins/treesitter: disable folding by default

.github/workflows/update.yml, flake-modules/updates/default.nix
The main goal of this PR is to remove the branches matrix and instead run the update CI only for the workflow's branch. This is paired with #1862 and should fix issues where the CI fails due to branch differences such as `generate-files` being missing.
It is still possible to update both branches at once, using the "also update nixos-24.05" checkbox. When ticked (or when the workflow is `scheduled`), a conditional step will trigger the other branch's workflow using the `gh workflow run` command.
- Run the `update.yml` workflow on the triggered branch, replace the job matrix with a conditional step that runs update on nixos-24.05.
- Added a `cancel-in-progress` concurrency group.
- Disabled committing in PR action (using negative add-paths).
- Improve summary for generated files.
- Fixed …
=> github/update: run `update` on the respective branch

.github/workflows/update.yml
> Unable to request reviewers.
> If requesting team reviewers a 'repo' scoped PAT is required.
I missed this when testing on my fork, as I had to disable team-reviews there because it was a fork.
(I stopped buildbot as this is a yaml only change)
=> github/update: remove broken team-reviewers

.github/workflows/update.yml
Sync update workflow with `main` again, following #1863 and #1869
(buildbot is having issues, but I probably would've cancelled a yaml only change from building anyway)
=> [nixos-24.05] github/update: sync with main

README.md
nixFlakes is an alias to just nix.stable for a good while and all currently supported nixos releases have it.
=> Simplify flakes instructions

plugins/none-ls/_mk-source-plugin.nix
Either strLua, or a structured `attrsOf anything`.
I resisted the urge to make this a submodule with options, but maybe it'd make sense to link the upstream documentation.
=> plugins/none-ls/sources: structured "with" settings

tests/default.nix, tests/fetch-tests.nix, tests/test-derivation.nix, tests/test-sources/plugins/completion/coq.nix
This PR reduces the number of test derivations, only creating one derivation per plugin instead of one test derivation per test configuration
#1878
=> tests: Reduce the size of the test derivation link farm

modules/lua-loader.nix, tests/test-sources/modules/lua-loader.nix
This changes `luaLoader.enable` option's type to allow null and sets its default to null.
Why? First, most important: it's not expected to have vim.loader configuration in `files` submodules. Changing default to null fixes that. Second, as I understand, the goal of this project is to not configure anything by default. I don't particularly like this extra line in `init.lua`.
My goal is to make `files` submodules to produce empty configs by default. When I do
```nix
files."ftplugin/nix.lua".localOpts.shiftwidth = 2;
```
I expect `ftplugin/nix.lua` will have only this option, and nothing else.
If somehow it's not desired, maybe a compromise can be made. Set it to `false` somewhere in the `top-level` modules, so that the default in `files` stays null.
Current behavior is completely undesired. …
=> modules/lua-loader: allow null value, do not configure by default

plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/lsp/language-servers/vls.nix
Option `plugins.lsp.servers.vls.autoSetFiletype` adds filetype extension by default, even when `plugins.lsp.servers.vls.enable = false`. I think this is not intended behavior.
My main goal is to make `files` submodules to produce empty configs by default. When I do
```nix
files."ftplugin/nix.lua".localOpts.shiftwidth = 2;
```
I expect `ftplugin/nix.lua` to have only this option, and nothing else.
=> modules/lsp/servers/vls: do not add filetype extension if not enabled

README.md
In the standalone example, I think `environment.systemModules` was intended to be `environment.systemPackages`.
=> systemModules should be systemPackages in README example

modules/filetype.nix, tests/test-sources/modules/filetypes.nix
`helpers.mkIfNonNull'` checks only for value = null, but I noticed that when there is anywhere something like `mkIf false config.filename = {}` (like with vlang filetype currently in nixvim, see also #1907), value of `config.filetype` is not null, but has all attrs with null values. It can be debugged with `nix repl`:
```
nix-repl> c = makeNixvim {}
nix-repl> :p c.options.filetype.definitions
[ { extension = { _type = "if"; condition = false; content = { v = "vlang"; }; }; } ]
nix-repl> :p c.config.filetype
{ extension = null; filename = null; pattern = null; }
```
Notice that `condition = false`, but the value is not null.
This PR changes mkIf condition to account for that.
NOTE: Test `checks.x86_64-linux.tests.entries.modules-filetypes` will fail until #1907 is merged.
=> modules/filetype: ensure that modules does not provide empty settings

lib/to-lua.nix, tests/lib-tests.nix
Fixes #1888
Without the changes in `lib`, the new tests fail with inf recursion. It'd be nice if they failed gracefully, but it seems `lib.runTests` doesn't handle that.
This means there's we just get:
```
evaluating derivation 'git+file:///home/matt/nixvim.git/drv_to_lua#checks.x86_64-linux.lib-tests'error: stack overflow (possible infinite recursion)
```
Instead of a _proper_ error message listing all failures and printing the expected & resulting values
_With_ the changes in `lib/to-lua.nix` the lib-tests all pass ok.
Ping: @SuperSandro2000
=> lib/to-lua: handle derivations as path strings

lib/neovim-plugin.nix, lib/utils.nix, modules/autocmd.nix, modules/diagnostics.nix, modules/highlights.nix, modules/keymaps.nix, modules/opts.nix, modules/output.nix, modules/top-level/output.nix, tests/test-sources/modules/output.nix
This PR removes empty
```lua
vim.cmd([[
]])
```
block from config.
I know that this is already handled by #1889, but I've added tests to make sure that this is the behavior. Also I added the test to make sure that all extraConfigs are outputted.
This also changes various places in other modules with the intention of not setting `extraConfig*` options to empty strings (more specifically whitespace only strings).
NOTE: The tests will fail until #1906, #1907 and #1908 are merged.
=> modules/output: produce empty files by default

lib/maintainers.nix, plugins/default.nix, plugins/languages/cmake-tools.nix, tests/test-sources/plugins/languages/cmake-tools.nix
This PR adds the cmake-tools plugin to nixvim.
A substantial part of this plugin's default config sets options for external plugins such as dap or overseer (optional), therefore I didn't create nixvim options for these and used generic attribute sets instead as they seem to be beyond the scope of cmake-tools itself and aren't exhaustive. Please let me know if this is not the right approach - one issue I noticed is that large attribute set default values don't render well in the docs.
=> plugins/cmake-tools: init

modules/default.nix, modules/performance.nix, modules/top-level/files/default.nix, modules/top-level/output.nix, plugins/languages/treesitter/treesitter.nix, plugins/telescope/default.nix, plugins/telescope/extensions/fzf-native.nix, plugins/telescope/extensions/fzy-native.nix, tests/test-sources/modules/performance/combine-plugins.nix, tests/test-sources/plugins/languages/treesitter/combine-plugins.nix, tests/test-sources/plugins/telescope/default.nix, tests/test-sources/plugins/telescope/fzf-native.nix, tests/test-sources/plugins/telescope/fzy-native.nix
Hey. I'm the one from [this comment](https://github.com/nix-community/nixvim/issues/421#issuecomment-1646834969) in [[Feature] Lazy loading](https://github.com/nix-community/nixvim/issues/421) issue. I decided to give nixvim a try, but since I don't want to lose my performance optimizations, I implemented them in nixvim. Since my comment have got a couple of upvotes, here I am with a PR. I don't know if this would be merged, since this feature have caveats. But if it works for your config, you'll get a free performance boost (startup time and every time you `:e` a buffer). It's optional, so it shouldn't brake existing configs. I still think that this is more important than trying to lazy load everything (but for some specific cases lazy loading is also useful).
I'm planning to implement …
=> modules/performance: add an option to combine plugins to a single plugin pack

docs/user-guide/helpers.md, wrappers/_shared.nix
[NixOS](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/lib.nix?rgh-link-date=2024-07-08T17%3A09%3A50Z), [HM](https://github.com/nix-community/home-manager/blob/master/modules/misc/lib.nix), & [Darwin](https://github.com/LnL7/nix-darwin/blob/master/modules/misc/lib.nix) provide a `lib` option.
This option exists because the nixpkgs `lib` cannot be modified within an evaluating module system. Therefore it exists as an alternative place where functions and other attrs can be defined, used & shared by modules.
> [!NOTE]
> The [`lib` _option_](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/lib.nix) is **completely unrelated** to the `lib` specialArg [added by `evalModules`](https://github.com/NixOS/nixpkgs/blob/97f336bc91e53b59371ed405c22936a62740d4fe/lib/modul …
=> wrappers: make `helpers` available via `lib` option

lib/maintainers.nix, plugins/default.nix, plugins/utils/guess-indent.nix, tests/test-sources/plugins/utils/guess-indent.nix
Added https://github.com/NMAC427/guess-indent.nvim
=> plugins/guess-indent: init

docs/default.nix, docs/mdbook/SUMMARY.md, docs/mdbook/default.nix, flake-modules/dev/devshell.nix, flake-modules/dev/server.py, flake-modules/packages.nix, flake.lock, flake.nix
This option search is availaible in the `/search/` sub path.
It's provided by [NuschtOS/search](https://github.com/NuschtOS/search).
=> docs: Add an option search to our documentation

wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix
Update internal usage from the deprecated `nixvim.helpers` option to the new `lib.nixvim` option name.
See https://github.com/nix-community/nixvim/commit/216d64c158da5523d5b3db0895e1345175c21502#commitcomment-144629377
=> wrappers: use `lib.nixvim` option

plugins/languages/otter.nix
Follow up to https://github.com/nix-community/nixvim/issues/1854
=> plugins/otter: add warning if treesitter highlight not enabled

.github/workflows/build_documentation.yml
The path has only been moved in main, not on the stable branch
=> github: Fix stable doc path

plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/lsp/_lsp.nix
This adds the Eclipse JDT language server for Java. The existing Java LSP, "Java Language Server" was not suiting my use case. JDT seems to work better for me, so this adds that functionality to the list of LSPs.
=> plugins/lsp/jdtls: add Eclipse JDT language server for Java

lib/autocmd-helpers.nix, lib/deprecation.nix, lib/helpers.nix, lib/keymap-helpers.nix, lib/neovim-plugin.nix, lib/options.nix, lib/types.nix, lib/utils.nix, lib/vim-plugin.nix
This ended up being a fairly small change, but the result is much cleaner.
Instead of naming each part of `helpers` and passing those sections to the other parts that need them, we can build `helpers` in a let-block and pass `helpers` itself to parts of `helpers` while building `helpers`.
I also made use of `callPackageWith autoArgs` to clean up some of the repetitive boilerplate.
=> lib/helpers: build recursively

plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/lsp/_lsp.nix
Adds `nextls` the language server for Elixir that just works.
=> plugins/lsp/nextls: init

plugins/utils/which-key.nix, tests/test-sources/plugins/utils/which-key.nix
These have been replaced in v3 with a new spec.
This is an **interim** solution until we have time to fully migrate which-key to rfc42 freeform settings.
I've done this because the warning shown when starting vim is kinda obnixious and without this the only way to avoid it is to remove all registrations.
As we will (hopefully) migrate which-key to `settings` options soon, I've named the new option `settings.spec` so that we do not need to "rename" it again.
This PR **does not** actually add a freeform settings option.
The old option (`registrations`) is deprecated, when defined it will print:
```
trace: evaluation warning: nixvim (plugins.which-key):
The option definition `plugins.which-key.registrations' in `<unknown-file>' has been deprecated in which-key v3; please remove it.
You …
```
=> plugins/which-key: deprecate v2 registrations

flake-modules/wrappers.nix, lib/builders.nix, modules/files.nix, modules/performance.nix, modules/top-level/files/default.nix, modules/top-level/output.nix, tests/fetch-tests.nix, tests/modules/hm-extra-files-byte-compiling.nix, tests/test-sources/modules/performance/byte-compile-lua.nix, tests/test-sources/modules/performance/files/file.lua, wrappers/_shared.nix
This PR implements a second item from [this comment](https://github.com/nix-community/nixvim/issues/421#issuecomment-1646834969).
It can be merged only on top of #1886.
It introduces an option `performance.byteCompileLua`, that, when enabled, byte compiles lua files. It can be configured what to compile. By default it's user configs. But also plugins and neovim itself can be compiled.
=> modules/performance: add byteCompileLua option

flake-modules/updates/default.nix
`echo` pipes all its output at once, so `wc -l` always counts 1 line.
See https://stackoverflow.com/questions/60954221
=> flake/generate-files: fix `--commit` line count

tests/test-sources/plugins/completion/cmp-all-sources.nix, tests/test-sources/plugins/languages/otter.nix
- **tests/cmp-all-sources: disable the otter source as it triggers a warning when treesitter is missing**
- **tests/otter: add treesitter to avoid warning**
=> otter: ensures no warning is shown when running tests

lib/helpers.nix, lib/options.nix
This is a small step towards later refactoring our custom `lib`, but doesn't yet make any breaking changes.
All subsections within `helpers` are now available as scoped (nested) attrs, e.g. `helpers.options.defaultNullOpts` or `helpers.utils.mkRaw`.
Everything that was previously accessible from the "top-level" of `helpers` still is, via aliases defined in `helpers.nix`.
In a future PR we should add `lib.warn` to some of those aliases, before later dropping them altogether.
We can discuss in the future which aliases should be deprecated/dropped and if anything else should be moved/renamed.
=> lib/helpers: scope all subsections, but keep top-level aliases

docs/default.nix, docs/mdbook/default.nix, lib/extend-lib.nix, lib/helpers.nix, lib/modules.nix, modules/top-level/files/default.nix, tests/test-sources/extended-lib.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
lib/extend-lib.nix returns a nixpkg's `lib`, extended with our own helpers available as `lib.nixvim`.
The extended lib also merges our maintainer list into `lib.maintainers`.
This is exposed as `helpers.extendedLib`, but when evaluating our modules it should be assigned to `specialArgs.lib`.
Outside of our modules you must still access our helpers via `config.lib.nixvim` or `config.lib.nixvim.extendedLib`.
Within helpers' sub-sections, `lib` is the extended lib.
I added a test, but currently it is only run with a standalone build. For completeness it'd be nice to also run the test with out other module wrappers, but I'm not sure the best way to go about this.
This PR makes **no restructuring changes** to the lib's layout, as discussed in the doc. #1962 is a first step towards doing that, …
=> lib: provide an "extended lib" to our modules

flake.lock
```
Flake lock file updates:
• Updated input 'flake-parts':
'github:hercules-ci/flake-parts/9227223f6d922fee3c7b190b2cc238a99527bbb7' (2024-07-03)
→ 'github:hercules-ci/flake-parts/8471fe90ad337a8074e957b69ca4d0089218391d' (2024-08-01)
• Updated input 'home-manager':
'github:nix-community/home-manager/58cef3796271aaeabaed98884d4abaab5d9d162d' (2024-07-31)
→ 'github:nix-community/home-manager/afc892db74d65042031a093adb6010c4c3378422' (2024-08-02)
• Updated input 'nix-darwin':
'github:lnl7/nix-darwin/0413754b3cdb879ba14f6e96915e5fdf06c6aab6' (2024-07-27)
→ 'github:lnl7/nix-darwin/f7142b8024d6b70c66fd646e1d099d3aa5bfec49' (2024-08-02)
• Updated input 'nixpkgs':
'github:NixOS/nixpkgs/52ec9ac3b12395ad677e8b62106f0b98c1f8569d' (2024-07-28)
→ …
```
=> [main] Update flake.lock & generated files

flake.nix, tests/test-sources/modules/output.nix
Unfortunately this will print a confirmation when first using the flake:
```
do you want to allow configuration setting 'allow-import-from-derivation' to be set to 'false' (y/N)?
```
This is no different to the cachix configs though.
=> flake: disable `allow-import-from-derivation`

plugins/snippets/luasnip/default.nix, tests/test-sources/plugins/snippets/luasnip.nix
- **plugins/luasnip: rename extraConfig to settings (more consistent with RFC-42)**
- **plugins/luasnip: add tests**
=> plugins/luasnip: rename extraConfig to settings (more consistent with RFC-42) + add tests

plugins/utils/spectre.nix
This adds the `warn` engine option to be able to silence messages when an executable is missing from the PATH. See https://github.com/nvim-pack/nvim-spectre/pull/242 for the upstream change.
=> plugins/spectre: set freeformType for engine options

lib/maintainers.nix, plugins/default.nix, plugins/snippets/nvim-snippets.nix, tests/test-sources/plugins/snippets/nvim-snippets.nix
Adds support for [nvim-snippets](https://github.com/garymjr/nvim-snippets).
=> plugins/nvim-snippets: init

plugins/default.nix, plugins/pluginmanagers/lz-n.nix, tests/test-sources/plugins/pluginmanagers/lz-n.nix
This is the first PR of splitting PR #1866.
This PR adds:
- `plugins.lz-n` and its options for lazy-loading plugins using [lz.n](https://github.com/nvim-neorocks/lz.n).
- Tests for `plugins.lz-n`.
=> plugins/lz-n: init

plugins/neotest/adapters-list.nix, tests/test-sources/plugins/neotest/default.nix, tests/test-sources/plugins/neotest/golang.nix
Add [neotest-golang](https://github.com/fredrikaverpil/neotest-golang/). Which seems to resolve some issues with the current neotest-go adapter most people use. 
Fixes: #1995
=> plugins/neotest: add neotest-golang

plugins/utils/which-key.nix, tests/test-sources/plugins/utils/which-key.nix
Working on converting this and there are a few breaking changes for data types of config options https://github.com/folke/which-key.nvim/pull/624/files#diff-a8347a13956b70b044d3e091cd3115e2fcfb44d4ebde516ff03223b2e84c7a7b. 
~- One being the `triggers` option which used to be string or list of strings, but is now a list of attribute sets like the registrations change. What should we do in that case?~
**Very niche setting, continuing with breaking change.**
~- Another issue I was hoping for clarification on is nested properties moving to settings and moving to a different path within settings.~
**Resolved, most can be just parent level rename. Manually specified those that wouldn't be handled properly for nested.**
~- `plugins -> presets -> textObjects` moved and changed from camel to snake …
=> plugins/which-key: migrate to mkNeovimPlugin

plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/lsp/_lsp.nix
Adding bufls language server to the lsp plugin.
Tested with `checks`, as well as editing protobuf files with my own config, pointed at my fork. Seems to work as expected.
=> plugins/lsp/bufls: init

plugins/utils/firenvim.nix, tests/test-sources/plugins/utils/firenvim.nix
Follow up to #1983
Needed to use `options.*.settings` instead of `config.*.settings`.
I was concerned that the test-case didn't pick up on this, so I added an new test case with some basic assertions.
=> plugins/firenvim: fix aliasing `settings` into `globals`

plugins/default.nix, plugins/filetrees/yazi.nix, tests/test-sources/plugins/filetrees/yazi.nix
Adding module for https://github.com/mikavilpas/yazi.nvim
NOTE: It looks like it has a dependency on telescope in the builtin functions for searching. Should that be a warning or added as an extra plugin automatically? To make this more complex, technically a person can setup the integrations property to change the grep behavior to not rely on it..
=> plugins/yazi: init

generated/rust-analyzer.nix, plugins/lsp/language-servers/rust-analyzer-config.nix, update-scripts/default.nix, update-scripts/rust-analyzer.nix, update-scripts/rust-analyzer/default.nix, update-scripts/rust-analyzer/heading_filter.lua
A newly introduced option added two unhandled cases:
- Sub-module like `properties`
- Descriptions containing markdown headings
In order to avoid shelling out to pandoc to filter _each_ markdown description we only check if there _could_ be an header, and call pandoc in that case. This currently results in pandoc being only called for the newly introduced option
=> update-scripts: Adapt to rust-analyzer option changes

lib/helpers.nix, lib/to-lua.nix, tests/lib-tests.nix
=> lib/lua: support nixpkg's "lua-inline" type

lib/deprecation.nix, lib/helpers.nix, lib/neovim-plugin.nix, lib/types.nix, lib/vim-plugin.nix, plugins/bufferlines/bufferline.nix, plugins/utils/which-key.nix, tests/test-sources/plugins/bufferlines/bufferline.nix
Resolves https://github.com/nix-community/nixvim/issues/1890
Also added support:
-  `separator_style` for the custom separator declaration using an array of 2 strings. 
-  `indicator.style` allow for `none`
Changed:
- `diagnostics` no longer accepts true. Plugin only accepts `false`, `nvim_lsp`, or `coc`.
- `diagnosticsUpdateInInsert` uses `vim.diagnostic.config` instead of passing into options table. 
- Updated some descriptions with notes from upstream docs on usage.
=> plugins/bufferline: migrate to mkNeovimPlugin

tests/test-sources/plugins/utils/spectre.nix
The `module 'plenary.job' not found` issue has been resolved and tests can be executed on Darwin.
Tests should be updated for Darwin to handle the missing sed warning (`ERROR: You need to install gnu sed 'brew install gnu-sed'`) as soon as #1952 is resolved. (e.g. [this failure](https://buildbot.nix-community.org/#/builders/495/builds/44/steps/1/logs/stdio))
=> tests/plugins/utils/spectre: enable tests on Darwin

flake-modules/dev/devshell.nix
Use a consistent behavior of getopt in launchtests.sh. Wasn't able to use tests command on macbook without including this because the macOS getopt didn't support our usage.
=> flake-modules/devshell: add getopt runtimeInput

modules/top-level/output.nix
In preparation for next flake update. Required to prevent errors due to missing license information in neovim-wrapper when using `performance.byteCompileLua.nvimRuntime`.
I was seeing this error due to missing required meta attributes:
```
error: attribute 'license' missing
at /nix/store/sfycwi72zfjsspidinx56ajaiffpyh17-source/pkgs/applications/editors/neovim/wrapper.nix:210:9:
209|         mainProgram
210|         license
|         ^
211|         maintainers
```
=> top-level/output: include meta in package

tests/test-sources/modules/lua-loader.nix
Getting invalid regex expression on `aarch64-darwin`, this passes on both `aarch64-darwin` and `x86_64-linux`, for me. I saw that the builtins.match has different behaviors between each platform in https://github.com/NixOS/nix/issues/1537 and https://github.com/NixOS/nix/issues/4758.
=> tests/lua-loader: builtins.match -> lib.hasInfix 

.github/workflows/update.yml
Resolves https://github.com/nix-community/nixvim/issues/2006
Tested running workflow on my repo: 
- Using upstream as repo check (skips running) https://github.com/khaneliman/nixvim/actions/runs/10426474651
- Using my own repo check (runs update) https://github.com/khaneliman/nixvim/actions/runs/10426526382/job/28879614530
=> workflows/update: only run upstream

tests/default.nix, tests/test-derivation.nix
- **tests: use a link-farm again, but only per-file**
- **Revert "tests: Allow to test multiple derivations in a single test derivation"**
This is one change picked from #1989, which reduces the scope of that refactoring PR.
This doesn't take any steps to reduce the number of checks we have on the flake, but it does remove some fragile derivation code that was attempting to optimise derivation-count in an area where (AFAICT) this should not affect buildbot.
cc @zowoq (buildbot maintainer) @traxys (reverted commit author)
=> tests: use a link-farm again, but only per-file

lib/keymap-helpers.nix, modules/keymaps.nix, plugins/bufferlines/barbar.nix, plugins/lsp/default.nix, plugins/lsp/wtf.nix, plugins/utils/tmux-navigator.nix
- Replace nullable lua option with a no-default option.
- Made it so the deprecated option is only declared when `lua = true` is passed.
- Replace `normalizeMappings` with a `removeDeprecatedMapAttrs` helper.
- Added warnings for **all options** that historically had `lua` support.
This supersedes and closes #1795
I'd like to do something like this directly in `mkMapOptionSubmodule`, however it doesn't seem to do what you'd expect...
```nix
type // {
merge = loc: defs: builtins.removeAttrs (type.merge loc defs) [ "lua" ];
};
```
Therefore I've instead added `apply` functions to each keymap option that removes the `lua` attr.
See this [message on matrix](https://matrix.to/#/!wfudwzqQUiJYJnqfSY:nixos.org/$UjMlZGRb5mPCxWdvv6DDGOnuk95ahtuX3TzSHr5dO-w?via=nixos.org&via=matrix.org&via=nixos.dev) …
=> modules/keymap: improve `lua` deprecation

lib/keymap-helpers.nix
This is needed to allow plugins to add bespoke features to their keymap submodules without having to re-implement the whole thing.
cc @khaneliman as this may be useful in todo-comments
=> lib/keymap: allow extra options/modules in `mkMapOptionSubmodule`

flake-modules/dev/devshell.nix, flake-modules/dev/launch-test.sh, lib/helpers.nix, lib/utils.nix, tests/default.nix, tests/lib-tests.nix
- **tests/lib-test: correctly print expected/result**
- **lib/util: add `groupListBySize`**
- **tests: group tests by 10**
- **flake-modules/devshell: update tests command with link-farm support**
In an attempt to strike a balance between having one very intensive test and _many_ smaller tests at the `checks.<system>.*` level, this PR groups the tests into bundles of 10, currently resulting in 28 `checks.<system>.test-*` link farms and 46 _total_ checks.
Quoting https://github.com/nix-community/nixvim/pull/2015#issuecomment-2285508636:
> On the old hardware we were using 16 workers for eval, now we are using 32. Only splitting the linkfarm up a bit (e.g. into 4) likely won't help much as they will still end up being evaluated at the same time but by more than that or by path should work. …
=> tests: group tests into several link-farms (10 tests per farm)

plugins/utils/todo-comments.nix
Follow up to https://github.com/nix-community/nixvim/pull/2030 can now be done since https://github.com/nix-community/nixvim/pull/2040 is implemented.
=> plugins/todo-comments: migrate keymaps to mkMapOptionSubmodule

lib/modules.nix, wrappers/standalone.nix
Evaluates a nixvim config, by default also checking warnings and assertions.
This used internally by the standalone wrapper.
I'm planning to use this to refactor the tests implementation:
- The tests don't need a "full" standalone build
- The tests should be able to expect/reject warnings/assertions
- Warnings should fail tests (unless marked as expected)
But I figured it'd be easier to test/review if I push this as a separate PR.
=> lib/modules: add `evalNixvim`

lib/autocmd-helpers.nix, lib/extend-lib.nix, lib/helpers.nix, lib/keymap-helpers.nix, lib/options.nix, lib/types.nix, lib/utils.nix
- **lib/types: merge into `extendedLib`**
- **lib: migrate `helpers.nixvimTypes` -> `lib.types`**
As discussed in https://github.com/nix-community/nixvim/pull/1975#discussion_r1702774343
I think this is the cleanest way for us to have custom option types, however we do loose some clarity. You can no longer tell at a glance whether a type is from nixvim or nixpkgs.
@GaetanLepage seems on board, what's your view @traxys?
=> lib/types: merge into `extendedLib`

docs/user-guide/helpers.md, wrappers/_shared.nix
Make our custom "helpers" lib available to host modules as `_module.args.nixvimLib`, as an alternative to accessing via `config.lib`.
We didn't do this before because `helpers` was too generic of a name, but `nixvimLib` should be ok.
e.g:
```nix
{ lib, nixvimLib, ... }:
{
programs.nixvim.someOption = nixvimLib.mkRaw "print('Hi')";
}
```
Should we consider also making the alias available to nixvim modules? Can always be done later.
I've made it so that the `nixvimLib` arg in the host modules is equivalent to the `lib` arg in the nixvim modules; i.e. nixvim's "extended" nixpkgs lib.
=> wrappers: add our lib to the host's `_module.args`

plugins/neotest/adapters.nix, plugins/neotest/default.nix, plugins/neotest/options.nix
Was just looking at this module while checking something else out and saw it was still using helpers. Migrating to use lib.nixvim reference, instead.
=> plugins/neotest: migrate helpers -> lib.nixvim

lib/tests.nix, modules/top-level/test.nix, tests/test-sources/plugins/lsp/schemastore.nix, tests/test-sources/plugins/utils/nvim-osc52.nix
Extracted from #1989 to reduce its scope. Also based on earlier work from #1986.
This PR moves responsibility for assertions/warnings in tests to the test derivation, instead of printing/throwing them.
They are still printed/thrown when building a non-test nixvim build.
Additionally, two new options are added to control this behaviour. Both default to `true`:
- `test.checkWarnings`: Whether to check `config.warnings` in the test.
- `test.checkAssertions`: Whether to check `config.assertions` in the test.
> [!NOTE]
> Only _module_ warnings/assertions defined using the respective options from `assertions.nix` are checked.
> Anything printed manually with `lib.warn`, `builtins.trace`, etc, or errors thrown with `assert`, `throw`, `abort`, etc _will not_ be handled correctly by the test.
> - …
=> modules/test: check warnings/assertions

tests/test-sources/plugins/lsp/_lsp.nix, tests/test-sources/plugins/lsp/jsonls.nix, tests/test-sources/plugins/lsp/schemastore.nix
Follow up to [flake.lock update](https://github.com/nix-community/nixvim/pull/2056). Looks like nixpkgs was updated so we can now re-enable tests on the `vscode-langservers-extended` based lsps mentioned in https://github.com/nix-community/nixvim/issues/2043.
=> tests/plugins/lsp: re-enable tests

plugins/neotest/adapters.nix
| Field        | Description |
|--------------|-------------|
| Plugin       | `neotest`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 
When attempting to build this configuration snippet:
```nix
{ config, lib, pkgs, ... }: {
config = {
programs.nixvim.plugins.neotest = {
enable = true;
adapters = {
rspec = {
enable = true;
settings = {
root_files = [ "README.md" "flake.lock" "flake.nix" "README.mkd" ];
};
};
};
};
};
}
```
I had an error:
```shell
error:
… while calling the 'head' builtin
at /nix/store/j8pbrsb3nybdap3hhg9kw0ffqd4rlbx6-source/lib/attrsets.nix:1575:11:
1574|         || pred here (elemAt values 1) (head values) then
1575|           head values
|           ^
1576|         else
… while evaluating the attribute 'value'
at …
```
=> bug: add missing `helpers` import

docs/mdbook/default.nix
Long descriptions for plugins will shove the plugin's source link and maintainer information far down the page. Since those are fairly short and the description is a variable size. Moving below to maintain consistent placement.
Before:
After:
=> docs/mdbook: move description to bottom

modules/opts.nix, modules/top-level/output.nix, plugins/languages/rust/rustaceanvim/default.nix, plugins/lsp/default.nix
Rustaceanvim will throw an error if the configuration is sourced after initialization. Our globals are defined at the top of the init.lua so moving the settings to leverage the globals option scope. If lsp is is enabled, we append the on_attach function to the config as a callback function so that it can be accessed properly on the global config.
An example of running into this can be had while configuring `plugins.neotest.settings.adapters` for usage with rustaceanvim. The setup involves initializing rustaceanvim before our lsp configuration is configured.
```lua
require('neotest').setup {
-- ...,
adapters = {
-- ...,
require('rustaceanvim.neotest')
},
}
```
I am able to just set the mkOrder/mkBefore for the lsp `extraConfigLua` but, it would still be nice to not have to worry about …
=> plugins/rustaceanvim: fix checkhealth error

plugins/languages/nvim-jdtls.nix
Make it possible to set data directory with lua, so it can be project-dependent.
JDTLS requires separate data directory for every project.
This PR enables users to set e.g.
```nix
data.__raw = "vim.fn.stdpath 'cache' .. '/jdtls/' .. vim.fn.fnamemodify(vim.fn.getcwd(), ':t')";
```
and thus satisfy this requirement.
=> plugins/nvim-jdtls: allow lua on nvim-jdtls.data

plugins/lsp/conform-nvim.nix
Additional fixes to #2086, since the settings name have been renamed, the example config is outdated
=> plugins/lint: fix conform incorrect option description

lib/tests.nix
Since cbd1003d9d3dcc371f0602a66ff32af9f8c14490 I'm able to add _some_ invalid config definitions to modules the tests are using and get no build error.
For example `extraConfigLua = null;` should produce an invalid type error, but doesn't.
One less visible change in that commit is the move away from using the "standalone" wrapper (`makeNixvimWithModule`), which implicitly sets `wrapRc = true`.
Adding back `wrapRc` to the tests seems to fix the issue, however this makes me wonder if there's an underlying issue with wrapping/not-wrapping?
Perhaps we've simply uncovered a long-standing eval issue that is masked over by using `wrapRc`?
=> tests: fix tests by enabling `wrapRc`

flake-modules/tests.nix, tests/failing-tests.nix
Adds a regression test for #2076. This test ensures that `extraConfigLua` is used in `finalPackage` and that the test will fail correctly when running `nvim` results in unexpected output.
I was hoping to also test more explicitly that an eval failure would be triggered when `extraConfigLua` is set to something invalid, but verifying the `"Hello, world!"` string makes it into the build log should cover most of those cases too.
At the very least this regression test ensures:
- `extraConfigLua` is used in the `init.lua` used to run `nvim` in the test
- `test.runNvim` correctly fails when neovim prints unexpected stdout
I used [`pkgs.testers.testBuildFailure`](https://nixos.org/manual/nixpkgs/unstable/#tester-testBuildFailure) as a helper, to aid in expecting a derivation build to fail.
=> tests: test the tests fail when expected

plugins/utils/which-key.nix
Which-key implemented proper icon support, utilize the icon attribute to properly override/set icons so that alignment doesn't get thrown off and it's inherited with child mappings did something similar in my own config to fix the weird rendering https://github.com/khaneliman/khanelivim/commit/13a38e596f092c2afbfa34d6e4f1a7b05137733d
=> plugins/which-key: fix icon examples

modules/top-level/test.nix
It was bothering me that the test used the fully blown `stdenv.mkDerevation` despite only needing to run a few commands. Therefore I've replaced it with `runCommand`. More specifically, `runCommandNoCCLocal` which should pull in fewer unnecessary build dependencies.
Additionally, I needed to add some pass-through attrs when debugging #2076, so I've created this PR to persist those. Maybe other stuff should be passed through too?
=> modules/test: use `runCommand` and add `passthru`s

flake-modules/tests.nix, tests/failing-tests.nix
Follow up to #2097, #2076, & #2048.
Expand "failing-tests" to also ensure warnings & assertions are correctly handled by `mkTestDerivationFromNixvimModule`.
Also did some minor cleanup:
- Call `failing-tests.nix` using `pkgs.callPackage`
- Replace repetive use of `testBuildFailure` with a wrapper
`mkFailingNixvimTest`
You can run just the "failing" tests by using:
```shell
nix build .#checks.x86_64-linux.failing-tests
nix build --show-trace --print-build-logs --verbose \
.#checks.x86_64-linux.failing-tests
```
You can also use the `entries` passthu to access a specific sub-test:
```shell
nix build .#checks.x86_64-linux.failing-tests.entries.fail-on-assertions
```
_(tab-completion can help here)_
See also, [`linkFarmFromDrvs`](https://github.com/NixOS/nixpkgs/blob/0fefe244b14d6f140d98dff6dd …
=> tests: add regression test for warnings + assertions

tests/default.nix, tests/fetch-tests.nix
Simplify by reducing the number of transformations done to the test-files' test-case modules attr.
Since `pkgs.linkFarm` can accept _either_ a list or an attrset, we don't need to transform the attrset into a list.
This has no functional change, and only slightly simplifies some internals. It may end up being redundant if we re-structure the tests again, but I spotted the slight over-complication while working on #2100 so figured I'd make a PR.
=> tests: simplify fetch-tests slightly

docs/default.nix, tests/default.nix, tests/fetch-tests.nix
Since we normally provide a value, the default never gets used and therefore the typo never got detected.
=> docs: fix typo in `pkgs` arg default value

plugins/bufferlines/barbar.nix, plugins/bufferlines/bufferline.nix, plugins/filetrees/chadtree.nix, plugins/filetrees/neo-tree.nix, plugins/filetrees/nvim-tree.nix, plugins/git/diffview.nix, plugins/lsp/lspsaga.nix, plugins/lsp/trouble.nix, plugins/utils/alpha.nix, plugins/utils/fzf-lua.nix, tests/test-sources/plugins/bufferlines/barbar.nix, tests/test-sources/plugins/bufferlines/bufferline.nix, tests/test-sources/plugins/filetrees/chadtree.nix, tests/test-sources/plugins/filetrees/neo-tree.nix, tests/test-sources/plugins/filetrees/nvim-tree.nix, tests/test-sources/plugins/git/diffview.nix, tests/test-sources/plugins/lsp/lspsaga.nix, tests/test-sources/plugins/lsp/trouble.nix, tests/test-sources/plugins/utils/alpha.nix, tests/test-sources/plugins/utils/fzf-lua.nix
Follow up to discussion https://github.com/nix-community/nixvim/issues/2107#issuecomment-2316603375 to standardize how we handle the icons dependencies. Setting a default `iconsPackage` for each module that has been adding it as an `extraPlugins` and deprecating options that used to be a boolean specifically for this behavior. 
I see a few occurrences for `gitPackage` outside of the scope of my `iconsPackage` change, I will address those in a follow up PR.
=> treewide: standardize iconsPackage

README.md
There was a [commit](https://github.com/nix-community/nixvim/commit/eac092c876e4c4861c6df0cff93e25b972b1842c) a couple of days ago that intended to fix this, but forgot to fix the text before the code block.
=> readme: fix incorrect description

plugins/git/gitgutter.nix, tests/test-sources/plugins/git/git-worktree.nix, tests/test-sources/plugins/git/gitgutter.nix
Resolves https://github.com/nix-community/nixvim/issues/2124 and adds some of the package assertions @MattSturgeon and I were playing around with in https://github.com/nix-community/nixvim/pull/2121
Looks like it needs to be refactored to newest standards, as well. But, that will be a different PR.
=> plugins/gitgutter: fix grepPackage

plugins/lsp/language-servers/efmls-configs-pkgs.nix, plugins/none-ls/packages.nix
See #2125
due to https://github.com/NixOS/nixpkgs/pull/337521
This has already been merged in `unstable` and thus `nixvim` will fail on up-to-date `home-manager` or `NixOS` deployments, but not on older configs. Unfortunately, `nixpkgs`  missed to apply an alias for the package.
Due to this change `nix flake check --all-systems` fails with 
```
… while checking flake output 'checks'
at «none»:0: (source not available)
… while checking the derivation 'checks.x86_64-linux.extend'
at «none»:0: (source not available)
(stack trace truncated; use '--show-trace' to show the full trace)
error: attribute 'prisma' missing
at /nix/store/cvgwzs7pal633x4q03lp6wzcrk7g66q9-source/plugins/none-ls/packages.nix:158:23:
157|       phpcs = pkgs.phpPackages.php-codesniffer;
158|       prisma_format = …
```
=> plugins/none-ls: fix due to upstream renaming prisma

flake-modules/dev/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1945
I didn't see an ini formatter that we could use for this file, so we can just ignore it like we do a few other files.
=> flake-modules/dev: treefmt ignore .editorconfig

lib/maintainers.nix, plugins/default.nix, plugins/languages/nvim-orgmode.nix, tests/test-sources/plugins/languages/orgmode.nix
I want to add this plugin to Nixvim: https://github.com/nvim-orgmode/orgmode.
It is already in Nixpkgs here: https://search.nixos.org/packages?channel=24.05&show=vimPlugins.orgmode&from=0&size=50&sort=relevance&type=packages&query=orgmode.
I followed the following docs: https://github.com/nix-community/nixvim/blob/main/CONTRIBUTING.md.
I hope I did everything right.
Furthermore, I especially have doubts about the `tests` parts of the docs, I am not that good at Nix to understand what is said there.
Thanks in advance for reviewing this PR.
=> plugins/nvim-orgmode: init

lib/pkg-lists.nix, plugins/lsp/language-servers/efmls-configs-pkgs.nix, plugins/lsp/language-servers/efmls-configs.nix, plugins/none-ls/_mk-source-plugin.nix, plugins/none-ls/packages.nix, tests/generated.nix
- **plugins/efmls: use `mkPackageOption`**
- **plugins/none-ls: use `defaultText` in package options**
Extracted from #2150 to reduce its scope.
This PR refactors the efmls and none-ls package list files to use package names/paths instead of _actual_ package derivations. This then allows us to show a useful `defaultText` in the resulting package options.
=> plugins/{efmls,none-ls}: use `mkPackageOption` and/or `defaultText`

plugins/default.nix, plugins/utils/repeat.nix, tests/test-sources/plugins/utils/repeat.nix
This PR adds the following: https://search.nixos.org/packages?channel=24.05&show=vimPlugins.vim-repeat&from=0&size=50&sort=relevance&type=packages&query=vim-repeat.
https://github.com/tpope/vim-repeat/
Thanks in advance.
=> plugins/vim-repeat: init

plugins/default.nix, plugins/utils/autosource.nix, tests/test-sources/plugins/utils/autosource.nix
This PR add this plugin: https://search.nixos.org/packages?channel=24.05&show=vimPlugins.vim-autosource&from=0&size=50&sort=relevance&type=packages&query=vim-autosource.
https://github.com/jenterkin/vim-autosource/
Thanks in advance.
=> plugins/vim-autosource: init

plugins/snippets/luasnip/default.nix
I created this commit some time ago (under @nawordar account), but I drive NixOS stable and the `main` branch of NixVim is not compatible anymore (missing cmp-ai package).
=> plugins/luasnip: backport SnipMate loader

flake-modules/dev/default.nix
Follow up to #1846, which added the test. Currently the test only checks that nixpkgs maintainers don't redundantly add themselves to nixvim's maintainer list.
This PR adds a custom `pre-commit` hook that runs the test whenever `lib/maintainers.nix` has changes staged for commit.
> [!NOTE]
> This was developed in parallel with a similar hook in #2164, that one runs the `plugins-by-name` test when `plugins/by-name` or `tests/test-sources/plugins/by-name` is staged for commit.
E.g. if I attempt to revert 497ce4759383d72a028b720468ebed78520c1012 and then commit, I get the following:
```nix
$ git commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/matt/.cache/pre-commit/patch1725667052-916231.
deadnix................................................................ …
```
=> flake/pre-commit: check maintainers when modified

plugins/colorschemes/base16/default.nix, plugins/statuslines/lualine.nix, tests/test-sources/example-configurations/issues.nix, tests/test-sources/plugins/statuslines/lualine.nix
Resolves https://github.com/nix-community/nixvim/issues/2191
Migrating to the current standards. Required using a transitionType for the component options that will help keep existing configurations working, but recommend switching to the new way of being explicit in your configuration to match upstream plugin declaration.
=> plugins/lualine: migrate to mkNeovimPlugin

tests/default.nix, tests/fetch-tests.nix
Set `_file` in test-case modules, to avoid `<unknown-file>` messages.
Since the module system is importing an anonymous fnOrAttr module, instead of a `path` type module, it doesn't have enough context to figure out the module's file automatically.
Usually such non-path modules would just inherit their importer's `_file`, however this doesn't apply when passing modules directly to `lib.evalModules` since there is no importer to inherit from.
Adding `foo = ""` to a test case in `tests/test-sources/examples.nix` produces the following errors:
Without the change:
```
error: The option `foo' does not exist. Definition values:
- In `<unknown-file>': ""
```
With the change:
```
error: The option `foo' does not exist. Definition values:
- In …
```
=> tests: set `_file` to avoid `<unknown-file>` messages

plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/lsp/_lsp.nix
Adds the [basedpyright](https://detachhead.github.io/basedpyright) language server for Python.
Fixes #2180
=> plugins/lsp: add basedpyright

plugins/none-ls/packages.nix
Partially Resolves:
https://github.com/nix-community/nixvim/issues/2197
i think some of these just got messed up with a regex change or something
Prisma is due to the nixpkgs revision, but the other 2 I'm not sure... I can checkout that branch and run a nix build of them.
=> plugins/none-ls: fix pkg names

plugins/by-name/hex/default.nix, tests/test-sources/plugins/by-name/hex/default.nix
Adds [hex.nvim](https://github.com/RaafatTurki/hex.nvim).
Fixes #2187
=> plugins/hex: init

plugins/by-name/hardtime/default.nix
Was omitted from #2193 due to confusion with our `enable` option.
See https://github.com/m4xshen/hardtime.nvim#options
Fixes #2203
=> plugins/hardtime: add missing rename for `settings.enabled`

docs/user-guide/faq.md
Follow up to https://github.com/nix-community/nixvim/pull/2150, https://github.com/nix-community/nixvim/pull/2160, and https://github.com/nix-community/nixvim/pull/2139.
Since starting to use `lib.mkPackageOption` throughout nixvim, users will see a slightly different error message when encountering mismatched nixpkgs channel errors.
Also fleshed out some recommendations.
The example error message is taken from [this build](https://buildbot.nix-community.org/#/builders/1042/builds/1022/steps/1/logs/nix_error) from a PR that uses a package not yet in our locked nixpkgs revision.
=> docs/user-guide: update "not found in pkgs" FAQ

docs/0001-Output-GFM-admonition.patch, docs/default.nix
Follow up to https://github.com/nix-community/nixvim/pull/2213
Initial work towards #2217
This patches `nixos-render-docs` to use GFM-style alerts when rendering admonitions to markdown.
By default, it renders them as `**<kind>:** <text>`.
This **does not** add support for _parsing_ GFM-style alerts as admonitions in option descriptions, so the nixpkgs-style syntax should be used there for now.
For example, the following renders as:
```md
Install the man pages for NixVim options.
::: {.warning}
This is a warning!
:::
```
=> docs: patch nixos-render-docs to output GFM alerts

plugins/colorschemes/modus.nix, tests/test-sources/plugins/colorschemes/modus.nix
The `hide_inactive_statusline` option is available in newer versions of the theme.
=> colorschemes/modus: add new configuration option

.github/mergify.yml
- **mergify: use @nix-infra-bot to update queued PRs**
As per this discussion https://github.com/Mergifyio/mergify/discussions/5117, using a regular user for updating PRs feels wrong; we are essentially lying about who made the rebased commits.
After [raising this on matrix](https://matrix.to/#/!PbtOpdWBSRFbEZRLIf:numtide.com/$jwKmsz34yobKlwQHl7a0Qy71uVBIFpdcwlJu-m6JBBk?via=blad.is&via=matrix.org&via=nixos.dev), @nix-infra-bot was logged into mergify dashboard and granted write access to nixvim. Thanks @zowoq!
- **mergify: fix "update PR" logic**
We can no longer simply check the files list matches `[ flake.lock ]`, since we now also touch `generated/` files.
Mergify conditions cannot be checked against "all" list items; checks are always applied against "any" item. Therefore we need some …
=> mergify: update config

docs/default.nix, lib/extend-lib.nix, lib/types.nix
- **docs: remove unused `oneOfRecursive`**
This function is not used anywhere in nixvim, and was never even included in our `lib/types.nix`.
- **lib/types: simplify `eitherRecursive` by defining it only once**
Overriding the implementation in the docs is redundant. We can do the same thing directly in `lib/types.nix`.
=> lib/types: simplify `eitherRecursive` by defining it only once

flake-modules/tests.nix, lib/builders.nix, lib/default.nix, lib/modules.nix, modules/files.nix, modules/top-level/files/submodule.nix, modules/top-level/output.nix, tests/test-sources/modules/performance/byte-compile-lua.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
Splits everything that depends on a `pkgs` instance into an `optionalAttrs`, allowing `helpers.nix` to be bootstrapped without `pkgs`. The separated functions may be deprecated later, depending on how other refactoring pans out.
This required some refactoring:
- `modules.specialArgs` is only available when `pkgs` is used
- `modules.specialArgsWith` now requires `defaultPkgs` be provided
- `builders.*` now have `*With` variants that take `pkgs` as an argument
This is the first small step towards https://github.com/nix-community/nixvim/discussions/2186, #2210, and related refactoring.
=> lib: segregate and deprecate functions that need `pkgs`

plugins/by-name/wtf/default.nix, tests/test-sources/plugins/by-name/wtf/default.nix
While working on https://github.com/nix-community/nixvim/pull/2235 I found these 2 in the docs for the plugin and they weren't supported.
=> plugins/wtf: add history and grep_history keymaps

plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/lsp/_lsp.nix
Adds the Idris 2 LSP implementation. Tested successfully locally.
=> plugins/lsp/idris2-lsp: init

flake-modules/legacy-packages.nix, flake-modules/tests.nix, tests/package-options.nix, tests/plugins-by-name.nix
This was already used in a couple test cases, however having it as a flake output allows for 
1. easier debugging using `nix repl` or `nix eval` 
2. doing things like `nix eval .#nixvimConfiguration.config.plugins --apply builtins.attrNames --json` to very quickly get a JSON list of all plugins.
This would be useful in a CI task that looks for newly added plugins, for example.
NOTE: it has to go in `legacyPackages` and not `packages` because the latter can only contain derivations. Non-drv attrsets will throw an error when included in `packages`.
=> flake: add an empty `nixvimConfiguration` to the `legacyPackages` output

plugins/by-name/glow/default.nix, tests/test-sources/plugins/by-name/glow/default.nix
Forgot we created a module for this while trying to create modules for plugins in my config. I pass in a style path in my glow config to load a custom style and the module didn't support it.
=> plugins/glow: remove helpers; support custom styles

plugins/by-name/otter/default.nix
I no longer use nixvim
BTW otter no longer requires CMP; see https://github.com/nix-community/nixvim/discussions/2243
=> plugins/otter: remove myself as maintainer

plugins/colorschemes/tokyonight.nix
Default style since tokyonight v4.0.0. See https://github.com/folke/tokyonight.nvim/commit/766be08803922a5761551500c09d4be4c3366b71#diff-2118ce7f3d4c28292bfec01fd0828fa01ea8b5505df921c874452e35997939c5R9
=> plugins/tokyonight: add moon style to settings

plugins/by-name/nvim-surround/default.nix, plugins/by-name/vim-surround/default.nix, plugins/deprecation.nix, tests/test-sources/plugins/by-name/nvim-surround/default.nix, tests/test-sources/plugins/by-name/surround/default.nix, tests/test-sources/plugins/by-name/vim-surround/default.nix
Resolves https://github.com/nix-community/nixvim/issues/1346
Closes https://github.com/nix-community/nixvim/pull/1371
Rename surround to vim-surround and init nvim-surround.
=> plugins/nvim-surround: init

plugins/by-name/alpha/default.nix, tests/test-sources/plugins/by-name/alpha/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2273
Resolves https://github.com/nix-community/nixvim/issues/1382
Documentation states that we need to call require('alpha.term') to support a terminal type. Tested without using a terminal type and didn't see any negative side effects to just including it without having to parse through a user's layout configuration. But, in the rewrite it might be nice to properly check if it's even needed.
=> plugins/alpha: rawLua support; remove helpers and with lib; fix terminal type

lib/utils.nix, tests/lib-tests.nix
These functions had very similar bugs: they didn't check if their chosen "close token" was already present in the string they're escaping.
I went ahead and did the work implied by the TODOs: search for a "close token" that is *not* in the original string. Pretty simple concept, but it turned into an annoying amount of code. I couldn't find anything in upstream nixpkgs lib, or some clever insight about lua/vimscript that makes this work unecessary, but I'll be thrilled (and a little bummed about a wasted afternoon) to learn about something.
=> lib: fix escaping bugs in wrapVimscriptForLua and wrapLuaForVimscript

lib/neovim-plugin.nix, lib/types.nix, lib/utils.nix, plugins/by-name/ccc/default.nix, plugins/by-name/coq-nvim/default.nix, plugins/by-name/hydra/default.nix, plugins/by-name/mini/default.nix, plugins/by-name/rustaceanvim/default.nix, plugins/by-name/telescope/default.nix, plugins/by-name/treesitter/default.nix, plugins/by-name/which-key/default.nix, plugins/by-name/yanky/default.nix, plugins/cmp/default.nix, plugins/colorschemes/ayu.nix, plugins/colorschemes/base16/default.nix, plugins/colorschemes/onedark.nix, plugins/colorschemes/vscode.nix, plugins/none-ls/default.nix, plugins/pluginmanagers/lz-n.nix, plugins/utils/rest.nix, tests/test-sources/plugins/lua-config.nix
Resolves https://github.com/nix-community/nixvim/issues/1407
This commit adds a `plugins.<name>.config` section controlling the plugin specific configuration.
The section contains the internal `init` option, containing the plugin's initialization code.
It also contains the public `pre` and `post` options, that allow to add code before & after the `init` section
Finally, it contains the `final` option, being the concatenation of the three previous options.
I would have like to have a `location` option that allows to specify where to add the configuration option, it could be useful for rustaceanvim that needs to put the config in different places depending on `plugins.lsp.enable`, but that ended up in infinite recursions.
This option could also have been useful for lazy loading, as it may …
=> lib/neovim-plugin: Introduce `plugins.*.luaConfig.*` options

lib/types.nix
Follow up to https://github.com/nix-community/nixvim/pull/1876#discussion_r1770586071
- Have `pre` and `post` default to `null`
- Only merge them into `content` when non-null
- Mention this in `content`'s description
cc @traxys
=> lib/types/pluginLuaConfig: only merge `pre` and `post` when defined

docs/default.nix, flake-modules/legacy-packages.nix, flake-modules/lib.nix, flake-modules/tests.nix, lib/default.nix, lib/tests.nix, wrappers/_shared.nix, wrappers/standalone.nix
In the two places where our "helpers" lib is exclusively internal (flake module args and building the docs), we no longer supply `pkgs`.
In the other 4 locations, we now note why we still provide a `pkgs` in a comment.
Additionally, this refactors the work done in #2231 by _always_ including the deprecated functions.
When `pkgs` is provided they are wrapped in `lib.warn`; when `pkgs` is missing, they are stubs that `throw` a deprecation message instead.
For the `nixpkgs` module, I'm thinking we'll need to supply either a `pkgsPath` (`inputs.nixpkgs`) or our flake `inputs`. This could be optional, but `evalNixvim` may not work as intended when it isn't provided.
If we ever get to the point where the "standalone" wrapper is fully part of our lib, then we may also need to provide the flake …
=> treewide: avoid passing `pkgs` to our lib

lib/types.nix
This may slightly increase performance by reducing work done by the module system.
Recommended by @stasjok in https://github.com/nix-community/nixvim/pull/2294#issuecomment-2369115145
I don't really know a good way to test performance here though. I guess I'll re-read [Nix Evaluation Performance](https://nixos.wiki/wiki/Nix_Evaluation_Performance) and skim over https://www.youtube.com/watch?v=LXhYWEuwigo again...
=> lib/types/pluginLuaConfig: use `lib.optional` instead of `lib.mkIf`

plugins/by-name/otter/default.nix, plugins/cmp/auto-enable.nix
Cmp integration is no longer needed for this plugin.
Here is a quote from their README:
> If you previously used the otter nvim-cmp source, you can remove it, as the completion results now come directly via the cmp-nvim-lsp source together with other language servers.
Fixes #2243
=> plugins/otter: Remove cmp

tests/package-options.nix
This is often an intended behaviour, so just assume any option whose default throws is not a package-type option
Extracted from #2022
=> tests/package-options: allow option defaults to throw

plugins/by-name/luasnip/default.nix
Follow up to #1987, fixes #2303
=> plugins/luasnip: fix function name `extend_filetypes` to `filetype_extend`

modules/misc/assertions.nix, modules/misc/default.nix, modules/misc/meta.nix
Based on the modules we previously imported from NixOS. I've re-formatted the files, removed `with lib` and re-wrote a couple things to better fit the code-style in nixvim. You can view the upstream files for comparison:
- https://github.com/NixOS/nixpkgs/blob/814a4e48/nixos/modules/misc/assertions.nix
- https://github.com/NixOS/nixpkgs/blob/814a4e48/nixos/modules/misc/meta.nix
This will allow us to drop the `defaultPkgs` specialArg and avoids needing the proposed `pkgsPath` specialArg.
It could also lead to future divergence from upstream (intended or otherwise), for example as suggested in #2309.
=> modules/misc: include `assertions` and `meta` modules in the repo

wrappers/_shared.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix
- **wrappers: move assertion propagation to `_shared.nix`**
These options were propagated to the host modules in all wrappers (other than standalone), so we can move the implementation to `_shared.nix`.
- **wrappers/shared: only propagate files when nixvim is enabled**
These files should only be defined when nixvim is enabled. Currently the files are always created if `wrapRc` is false.
=> wrappers: move assertion propagation to `_shared.nix` & only propagate files when nixvim is enabled

modules/top-level/files/default.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
This simplifies the wrapper modules, adding a little consistency.
Rather than passing all the same stuff to `types.submoduleWith` that we do internally in `evalNixvim`, we can just use `evalNixvim` itself and then inherit its [`type`](https://github.com/NixOS/nixpkgs/blob/b4cde4d7f1fc84f6ff41ad165dab793dedaedfa0/lib/modules.nix#L327-L329) output.
This also means `modules.specialArgsWith` is now entirely internal and could be removed from out public API before we branch off 24.11.
This also fixes #2305 because we no longer enable `shorthandOnlyDefinesConfig`. We added that a while ago because we had an `options` option, however we renamed that to `opts` in #1342 so we no longer benefit from it.
=> wrappers: use `(evalModules {}).type` for nixvim submodule

wrappers/_shared.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix
This won't be detected automatically, since the modules are all returned from function calls instead of being path references.
=> wrappers: explicitly set `_file` for wrapper modules

modules/top-level/output.nix, wrappers/hm.nix, wrappers/modules/darwin.nix, wrappers/modules/nixos.nix, wrappers/modules/standalone.nix, wrappers/standalone.nix
- **modules/output: clarify `wrapRc` default**
- **modules/output: add `impureRtp` option**
- **modules/output: don't remove "site" dir when `impureRtp` is disabled**
Instead of assuming `wrapRc` implies we don't want impurities, configure this separately.
Additionally, the "site" dir is required for storing the state of several things, such as spell files.
Fixes #2297
=> modules/output: add `impureRtp` option & don't remove "site" dir

lib/tests.nix, modules/top-level/default.nix, modules/top-level/files/default.nix, modules/top-level/output.nix, modules/top-level/readonly-renames.nix, modules/top-level/test.nix, tests/extra-files.nix, tests/test-sources/modules/performance/byte-compile-lua.nix, tests/test-sources/modules/performance/combine-plugins.nix, wrappers/_shared.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
- **modules/output: move outputs to `build` scope**
- **modules/output: add `build.initSource` option**
This PR refactors our output options by moving anything we're "building" to `config.build.*`. This is also used as an opportunity to rename some of the options. Feedback on the names chosen is appreciated!
The intention is adding some structure to our output options, allowing for growth without things getting too messy..
#2313 is also based on this, since otherwise I'd have to re-write it to resolve merge conflicts.
=> modules/output: move outputs to `build` scope

flake-modules/legacy-packages.nix, lib/modules.nix, lib/tests.nix, modules/top-level/output.nix, modules/top-level/test.nix, tests/test-sources/modules/performance/combine-plugins.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix
Instead of `evalNixvim` checking `config.assertions` and `config.warnings`, this can be done when reading the `config.build.package` option.
This is intended to simplify `evalNixvim`, the wrappers, and the test derivation
This is similar to the approach used by NixOS, where assertions are [checked](https://github.com/NixOS/nixpkgs/blob/2af19cfb6aa40768c4bbefd801a136270e099191/nixos/modules/system/activation/top-level.nix#L62-L68) while evaluating its `config.system.build.toplevel` [option value](https://github.com/NixOS/nixpkgs/blob/2af19cfb6aa40768c4bbefd801a136270e099191/nixos/modules/system/activation/top-level.nix#L357).
The previously incubating `check = false` argument is now replaced with an "unchecked" package option. This is used by `config.build.test` and by wrapper modules that …
=> modules/output: check warnings+assertions on `build.package` option

docs/default.nix, wrappers/hm.nix, wrappers/modules/hm.nix
By default `lib.evalModules` will check all config definitions match a declared option, leading to errors like:
```
error: The option `wrapRc' does not exist.
```
Defining a [`freeformType`](https://github.com/NixOS/nixpkgs/blob/de38446996523da09e299aee94ceb73bd83a8bb4/lib/modules.nix#L205-L219) would instead check such definitions match the given type, producing mismatched type errors instead of "does not exist".
[`_module.check`](https://github.com/NixOS/nixpkgs/blob/de38446996523da09e299aee94ceb73bd83a8bb4/lib/modules.nix#L198-L203) can disable definition checking entirely, allowing us to evaluate the option declaration without checking the config definitions.
If `_module.check` is disabled, then definitions for missing options will simply not exist in the final merged `config` attrs.
=> docs/home-manager: eval options without checking config definitions

lib/default.nix, plugins/by-name/auto-save/default.nix, plugins/by-name/autosource/default.nix, plugins/by-name/bacon/default.nix, plugins/by-name/baleia/default.nix, plugins/by-name/ccc/default.nix, plugins/by-name/cmake-tools/default.nix, plugins/by-name/committia/default.nix, plugins/by-name/competitest/default.nix, plugins/by-name/coq-nvim/default.nix, plugins/by-name/direnv/default.nix, plugins/by-name/dressing/default.nix, plugins/by-name/guess-indent/default.nix, plugins/by-name/indent-o-matic/default.nix, plugins/by-name/lazygit/default.nix, plugins/by-name/lsp-status/default.nix, plugins/by-name/numbertoggle/default.nix, plugins/by-name/octo/default.nix, plugins/by-name/orgmode/default.nix, plugins/by-name/repeat/default.nix, plugins/by-name/vim-css-color/default.nix, plugins/by-name/virt-column/default.nix, plugins/colorschemes/cyberdream.nix, plugins/colorschemes/dracula-nvim.nix, plugins/colorschemes/everforest.nix, plugins/colorschemes/modus.nix
Remove the `lib.nixvim.maintainers` alias for `lib.maintainers`.
Also cleanup lib usage in several plugins, specifically the plugins that were touched by the main part of the PR:
- removed `with lib`
- migrate `helpers` -> `lib.nixvim`
- remove (most?) `nixvimTypes` usage
=> lib: remove `maintainers` alias

lib/modules.nix
End-users have ran into issues before when attempting to re-use a `lib` from elsewhere in nixvim's configuration.
If a `lib` without the `nixvim` extension is used, the new assertion will explain that this isn't supported.
```
Nixvim requires a lib that includes some custom extensions, however the `lib` specialArg does not have a `nixvim` attr.
Remove `lib` from nixvim's specialArgs or ensure you apply nixvim's extensions to your lib.
```
In the future we can also provide better ways for end-users to overlay their own lib with nixvim's [extensions](https://github.com/nix-community/nixvim/blob/main/lib/extend-lib.nix), but this is not yet implemented. Draft #2328
=> lib/modules: assert that `specialArgs` has a valid `lib`

plugins/by-name/idris2/default.nix, plugins/lsp/language-servers/default.nix, tests/test-sources/plugins/by-name/idris2/default.nix
Adds the `idris2` neovim plugin.
Also changes `idris2-lsp` to enable this new `idris2` plugin when enabled, as it's required for `idris2-lsp` to work at all. I'm not 100% sure this is the best way to achieve this - let me know if you'd prefer this was done another way!
=> plugins/idris2: init

plugins/by-name/render-markdown/default.nix, tests/test-sources/plugins/by-name/render-markdown/default.nix
Add [render-markdown.nvim](https://github.com/MeanderingProgrammer/render-markdown.nvim), a plugin to improve viewing Markdown files in Neovim.
=> plugins/render-markdown: init

plugins/by-name/avante/default.nix, tests/test-sources/plugins/by-name/avante/default.nix
Add support for [avante.nvim](https://github.com/yetone/avante.nvim), an AI companion plugin.
cc @synthe102 for testing
Fixes #2096
=> plugins/avante: init

lib/autocmd-helpers.nix, lib/default.nix, lib/keymap-helpers.nix, lib/neovim-plugin.nix, lib/options.nix, lib/utils.nix, lib/vim-plugin.nix
Simply removes all usage of `helpers` from the internals of `lib.nixvim`. It is also dropped from the available attrs in `call`.
=> lib: remove `helpers` from internal usage

lib/options.nix, lib/types.nix, plugins/by-name/conform-nvim/default.nix, plugins/by-name/edgy/default.nix, plugins/by-name/hydra/settings-options.nix, plugins/by-name/lint/default.nix, plugins/by-name/neotest/default.nix, plugins/by-name/nvim-surround/default.nix, plugins/by-name/obsidian/options.nix, plugins/by-name/startify/options.nix, plugins/by-name/statuscol/default.nix, plugins/by-name/telescope/extensions/_helpers.nix, plugins/by-name/trim/default.nix, plugins/by-name/typescript-tools/default.nix, plugins/cmp/options/settings-options.nix, plugins/cmp/sources/cmp-git.nix, plugins/utils/rest.nix, tests/test-sources/plugins/lsp/efmls-configs.nix
- **lib/types: make `strLua` coerce strings to rawLua**
- **lib/options: remove redundant `mkRaw` `apply` functions**
- **plugins: remove redundant `mkRaw` `apply` functions**
Related to #2003, but does not yet take any steps to deprecate strLua.
This PR simply shifts responsibility for coercing strings to rawLua from the option to the type.
In normal usage, this shouldn't break anything. If an option is also applying `mkRaw` then that is redundant, but idempotent and will do no harm. Also, `apply` happens _after_ the type is merged anyway.
In abnormal usage, this could break things. E.g. if a user is incorrectly using `strLua` in their own option, but **not** expecting the value to be coerced to rawLua... While worth noting, I don't think we need to be concerned about such incorrect …
=> lib/types: make `strLua` coerce strings to rawLua

lib/to-lua.nix
Spotted this while debugging another PR
=> lib/to-lua: fix `allowUnkeyedAttrs` option

plugins/by-name/web-devicons/default.nix, tests/test-sources/plugins/by-name/web-devicons/default.nix
Support configuring icon overrides and the default icon easier.
=> plugins/web-devicons: support custom icons and default icon

plugins/by-name/earthly/default.nix, tests/test-sources/plugins/by-name/earthly/default.nix
Added the <https://github.com/earthly/earthly.vim> plugin and its tests. No configuration is required.
=> plugins/earthly: add plugin

docs/modules/standalone.md
Typing `makeNixvimWithModule` by hand is challenging.
=> docs: fix typo in standalone.md (`makeNixvimWithModule`)

plugins/by-name/lsp-status/default.nix
added options to lsp-status that aren't documented in the packages readme
options in plugin [source](https://github.com/nvim-lua/lsp-status.nvim/blob/54f48eb5017632d81d0fd40112065f1d062d0629/lua/lsp-status.lua#L1)
=> plugins/lsp-status: add undocumented options

flake-modules/tests.nix, tests/default.nix, tests/lsp-servers.nix
Follow up to cab6b0c9febfecd96e4cda3dfe4ec8675f6d9ddb from #2365, which intended to ungroup the "all servers" lsp test for performance reasons. This does that more explicitly, by handling the test in the same way as other "loose" tests outside of `tests/test-sources`.
=> tests/lsp-servers: de-couple from grouped tests

wrappers/_shared.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix
- **wrappers: move `programs.nixvim` declaration to `_shared.nix`**
- **wrappers: define `pkgs` default within type declaration**
The first commit refactors the `programs.nixvim` option declaration so that it can be centralised to `wrappers/_shared.nix`, the second commit then moves the `nixpkgs.pkgs = pkgs` definition into the `evalNixvim` call.
This means `nixpkgs.pkgs` is defined in a module that is considered part of `programs.nixvim`'s type. Config definitions are not part of the type, and therefore are not part of `type.getSubModules` or `type.getSubOptions`.
Fixes #2378
=> wrappers: define `pkgs` default within type declaration

modules/top-level/output.nix, tests/test-sources/modules/output.nix
This:
* restores modules/output generated init.lua tests removed in 3d1224a039d70098c78d263b0867352d95f2194b, but without IFD.
* changes where generated plugin configs are obtained. Instead of using the result of `makeNeovimConfig`, generated config is obtained from `wrappedNeovim.initRc`. This should avoid breaking after NixOS/nixpkgs#344541 is merged. See also conversation in #2343.
=> modules/output: obtain plugin configs from wrapped neovim

plugins/lsp/language-servers/default.nix, plugins/lsp/language-servers/hls.nix, tests/lsp-servers.nix
Ensures `lsp.servers.hls` (haskell language server) users make an explicit choice regarding whether the required GHC dependency is installed or not.
This is the same approach as in `lsp.servers.rust_analyzer`.
Fixed #2413
=> plugins/lsp/hls: handle automatic installation of required GHC

plugins/by-name/telescope/extensions/live-greps-args.nix
Function `to_fuzzy_refine` in examples is part of Telescope, not the `live-greps-args` extension.
=> plugins/telescope/live-greps-args: fix `to_fuzzy_refine` example

flake-modules/tests.nix, tests/default.nix, tests/enable-except-in-tests.nix, tests/extend.nix, tests/extra-args.nix, tests/extra-files.nix, tests/lib-tests.nix, tests/main.nix, tests/maintainers.nix, tests/no-flake.nix
- **tests: move test derivations to `tests/default.nix`**
- **tests: use `callTest` pattern**
- **tests: cleanup tests to better use `callTest` pattern**
This takes ideas from #2104 (reducing the scope of that PR) and is required for #2430, as otherwise the auto-formatting leads to an unnecessarily large diff.
This PR contains two key ideas in its refactoring:
- use the `callPackage` pattern with a nixvim-specific `callTest` variant
- rename `tests/default.nix` -> `tests/main.nix` since there are other tests in `tests/` not "owned" by `default.nix`
- move the builk of the implementation in `flake-modules/test.nix` to a new `tests/default.nix`, so that we minimize the implementation details contained within `flake-modules` and allow `tests/` to take responsibility for all its test …
=> tests: refactor to use `callTest(s)` pattern + move calls to `tests/default.nix`

plugins/cmp/sources/default.nix, tests/test-sources/plugins/cmp/all-sources.nix
Add [cmp-nixpkgs-maintainers](https://github.com/GaetanLepage/cmp-nixpkgs-maintainers) source for `cmp`.
It auto-completes nixpkgs maintainers' GH handles when editing PR messages.
=> plugins/cmp: add cmp-nixpkgs-maintainers source

modules/top-level/nixpkgs.nix, tests/main.nix, tests/test-sources/modules/nixpkgs.nix
- **modules/nixpkgs: restructure `nixpkgs.pkgs.isDefined` assertion**
- **modules/nixpkgs: add `overlays` option**
Follow up to #2301 and working towards #1784; this PR adds the `nixpkgs.overlays` option.
This change is supported by some related refactoring to the existing assertion to a) reduce future indentation changes to the module and b) ensure the assertion message is actually shown to users. Without this change, `_module.args.pkgs` being absent will cause other errors that get thrown before we are able to check the module assertions.
Additionally, I've added a test to ensure the new option works correctly.
I would like a better option example for `nixpkgs.overlays`. Currently I'm using the same example as NixOS. Perhaps we could do something using the `vimPlugins = …
=> modules/nixpkgs: add `overlays` option

docs/mdbook/SUMMARY.md, docs/mdbook/index.md, docs/user-guide/install.md
Based of the README for now, with a small additional "welcome to the docs" section.
Perhaps in future, we could re-use the README.md verbatim? Perhaps with some additional post-processing.
I think we'd want to dramatically reduce its size first though.
Neither of these are in scope for this PR though.
By having a dedicated homepage outside of `user-guide`, this fixes #1625
=> docs: introduce a dedicated homepage

docs/default.nix, docs/mdbook/SUMMARY.md, docs/mdbook/default.nix, docs/modules/hm.md, docs/modules/wrapper-options.md, docs/user-guide/install.md
Refactor the previous `hm.md` docs to cover platform-specific options for _all_ wrappers.
In the future, we could factor out "common" options, but I think that is best done if we end up with lots of them. For now it is probably simpler to keep things as-is; i.e. common options are displayed multiple times.
We probably also want the hm-specific options to be available on all platforms. This may be best achieved by upstreaming `vimdiff` alias to the nixpkgs vim wrapper, as discussed in https://github.com/nix-community/nixvim/pull/1353 (tracked in https://github.com/nix-community/nixvim/issues/1621).
=> docs: refactor wrapper-options docs

docs/mdbook/default.nix, docs/modules/wrapper-options.md, wrappers/modules/darwin.nix, wrappers/modules/enable.nix, wrappers/modules/hm.nix, wrappers/modules/nixos.nix, wrappers/modules/shared.nix
- ~~**docs: move `user-guide` and `modules` into `mdbood` dir**~~
- **docs: simplify `mdbook.nixvimOptions` impl**
- **wrappers/modules: move `enable` to `shared.nix`**
- **wrappers: add `meta.wrappers` options to wrappers**
I've moved `modules/` to `wrappers/` in docs URLs. `modules/` felt confusing, but I'm not convinced `wrappers/` is right either. Maybe `platforms/` would be better? If we're gonna change the URLs let's try and get it right first time, or postpone the change for later.
I've introduced a `meta.wrappers.name` option, that is only present on wrapper modules (i.e. not currently in standalone). If standalone ever wanted to be part of the "wrapper" docs maybe it should also get the option, but that's easily refactored.
This option is used to set the "human readable" name of …
=> {docs,wrappers}: refactor to prepare for separated wrapper-option doc pages

plugins/by-name/lsp-format/default.nix, tests/test-sources/plugins/by-name/lsp-format/default.nix
Not sure if anyone is familiar with a good way to represent the submodule options for the top level language options. I decided to just do a rename from setup -> settings and mention the configuration through a description and examples.
=> plugins/lsp-format: migrate to mkNeovimPlugin

plugins/by-name/rust-tools/default.nix, plugins/by-name/rustaceanvim/settings-options.nix, plugins/deprecation.nix, plugins/lsp/language-servers/default.nix, plugins/lsp/language-servers/rust-analyzer-config.nix, tests/test-sources/plugins/by-name/rust-tools/default.nix
This repo has been archived and is no longer maintained... Do we even care to migrate everything seamlessly for this plugin or should be just deprecate the module, too? Could probably just wait to do it after 24.11 is cut if we want to keep it around for that release, at least.
=> plugins/rust-tools: deprecate plugin

plugins/lsp/default.nix
Because by calling we do not get the function reference but its return
value, instead.
=> plugins/lsp: no call fn in keymaps.extra example

plugins/by-name/typescript-tools/default.nix, tests/test-sources/plugins/by-name/typescript-tools/default.nix
Plugin already had a settings option that can't take advantage of rename module option functionality, so we're using the deprecated settings options warning behavior introduced in previous plugin version upgrades to alert the user when they are using options that should be moved.
=> plugins/typescript-tools: migrate to mkNeovimPlugin

CONTRIBUTING.md, plugins/by-name/notebook-navigator/default.nix, tests/test-sources/plugins/by-name/notebook-navigator/default.nix
Add support for [NotebookNavigator.nvim](https://github.com/GCBallesteros/NotebookNavigator.nvim), a neovim plugin to navigate and execute code cells.
Fixes #2449
=> plugins/notebook-navigator: init

plugins/by-name/nui/default.nix, tests/test-sources/plugins/by-name/nui/default.nix
I added the <https://github.com/MunifTanjim/nui.nvim/> plugin. It was already packed at nixpkgs and up-to-date on unstable
=> plugins/nui: add nui and its test

plugins/by-name/blink-cmp/default.nix, tests/test-sources/plugins/by-name/blink-cmp/default.nix
Hi there, this is my first contribution to a Nix related project (besides some flake configs).  I try to add this plugin: https://github.com/Saghen/blink.cmp which wants to be an alternative to nvim-cmp.
I'd like to hear any feedback and tips for improvements. Also how can I actually test this locally? Many thanks!
=> pluginst/blink: add blink.nvim

plugins/by-name/scrollview/default.nix, tests/test-sources/plugins/by-name/scrollview/default.nix
Add [nvim-scrollview](https://github.com/dstein64/nvim-scrollview), a plugin that displays interactive vertical scrollbars and signs.
Fixes #2467.
=> plugins/scrollview: init

plugins/lsp/language-servers/rust-analyzer.nix
Adds an option to automatically install rustfmt when using rust-analyzer. This is a draft as I was not sure exactly how to define the option so any suggestions on how to better implement it are welcome. Thanks!
=> plugins/lsp: enable auto-installing rustfmt

plugins/by-name/muren/default.nix, tests/test-sources/plugins/by-name/muren/default.nix
Add support for [muren.nvim](https://github.com/AckslD/muren.nvim), a plugin to do multi-replacements.
Fixes #2482
=> plugins/muren: init

docs/mdbook/book.toml, docs/mdbook/default.nix
This should fix the 404 page's relative links and styling being relative to `/`.
This works by telling mdbook to set the `<base href>` tag to `"/nixvim/"` instead of `"/"`. This is used as the "base" of relative paths.
I added it as a derivation attr, so we could do something like this to apply a different site-url to the stable branch once this is available on a stable branch:
```
nix build --impure --expr '(builtins.getFlake "github:nix-community/nixvim/nixos-24.11").outputs.packages.${builtins.currentSystem}.docs.overrideAttrs { siteURL = "/foo/bar/"; }'
```
=> docs: specify `site-url`

CONTRIBUTING.md
Enhance the documentation to clarify how to run individual tests when developing new plugins. Update the instructions for executing the full test suite to improve clarity.
#2503
=> docs/contributing: update documentation for running single tests

plugins/by-name/none-ls/prettier.nix, plugins/by-name/none-ls/prettierd.nix, plugins/by-name/none-ls/sources.nix
Add a new option (and warning) to disable the typescript-language-server (ts_ls) formatting just like with prettier.
```nix
none-ls = {
enable = true;
sources = {
formatting.prettierd = {
enable = true;
disableTsServerFormatter = true;
};
};
};
```
I simply copied the implementation from prettier, to keep the source code more readable. If you'd like me to make this more generic instead I could create a function that reduces repetition.
=> plugins/prettierd: add disableTsServerFormatter like for prettier

lib/options.nix, plugins/by-name/fastaction/default.nix
As we plan to move away from `mkLua` and `mkLuaFn` options, declaring options that only accept a `rawLua` value will be more and more common.
This PR adds the `defaultNullOpts.mkRaw` and `defaultNullOpts.mkRaw'` helpers to create such options easily.
Example:
```nix
custom_func = defaultNullOpts.mkNullable types.rawLua { __raw = "function(x) return x + 1 end"; } ''
Description.
'';
custom_func = defaultNullOpts.mkRaw "function(x) return x + 1 end" ''
Description.
'';
```
=> options: add defaultNullOpts.mkRaw

modules/clipboard.nix, tests/test-sources/modules/clipboard.nix
Allows raw lua in the `clipboard.register` option, so something like this can be set:
```nix
{
clipboard.register.__raw = ''vim.env.SSH_TTY and "" or "unnamedplus"''
}
```
=> modules/clipboard: allow raw lua code in `register` option

lib/default.nix, lib/options.nix, lib/utils.nix, tests/lib-tests.nix
Creates a `literalExpression` equivalent to using `lib.nixvim.mkRaw`.
This can be used in place of `{ __raw = "foo"; }` in option docs and provides us with a central place where we would be able to switch to documenting [`lib.generators.mkLuaInline`](https://noogle.dev/f/lib/generators/mkLuaInline) instead.
Design considerations:
- The name: I went with `literalLua` instead of `literalMkRaw` because it seems likely we'll want to transition away from `mkRaw` in the future.
I am a little concerned that end-users will stumble upon `literalLua` and not realize it is intended for documentation though...
- I've used the full `lib.nixvim.mkRaw` path for clarity. But this has its own issues since non-standalone users will have a different path.
Perhaps just `mkRaw` would be better? Either way, …
=> lib/utils: add `literalLua` & `nestedLiteralLua` option docs

lib/types.nix
Another step towards #1935, allowing `types.rawLua` and `strLua` to accept `_type = "lua-inline"` values as an alternative to our custom `__raw` values.
It may be nice to also implement some "merge" functionality allowing otherwise "equal" definitions to not conflict based on which wrapper type they're using. I.e. currently having an option defined as `mkRaw "foo"` in multiple places merges fine using `mergeEqualOption`, but having a `mkInlineLua "foo"` would not merge.
Maybe we'll deal with that when we get around to coercing `__raw` -> `lua-inline`? As currently we'd need to only coerce if there's multiple definitions of different types.
=> lib/types: allow inline-lua in `rawLua` type

plugins/lsp/lsp-packages.nix
buf-language-server is officially deprecated and removed from `nixpkgs/master` [here](https://github.com/NixOS/nixpkgs/pull/356199). Removing it here to allow nixvim to continue to build.
I don't know enough about the main-project `buf` to know how to make the language server actually work, if someone else does feel free to close this PR!
=> plugins/lsp: remove buf-language-server

docs/mdbook/book.toml, docs/mdbook/default.nix
Selectively backport changes from:
- a92339d83bdc47f6d42998a5ac96020f9dd7c2d6 #2507
- cdbda982f04bd021cfa8d549896410c5caf84fdf #2536
Unblocks #2537 by adding the overridable `baseHref` arg to the `docs` package.
=> [backport-24.05] docs: specify `site-url`

.github/workflows/build_documentation.yml, docs/mdbook/default.nix, flake-modules/dev/server.py
By shifting the responsibility to set the `baseHref` from the docs to the CI workflow, we remove the need for the docs to know where they will be installed.
- This reverts #1930
- This relies on #2538
=> docs: only set base-href in CI built docs

.github/workflows/build_documentation.yml
Apparently `environment` is something entirely unrelated to `env`, and the workflow was actually invalid!
=> ci/docs: fix `env` vs `environment` error

.github/workflows/build_documentation.yml
Everything now seems to be working, other than the docs being incorrectly nested at `/nixvim/nixvim/*`!
- https://nix-community.github.io/nixvim/ (404)
- https://nix-community.github.io/nixvim/nixvim/
- https://nix-community.github.io/nixvim/nixvim/stable/
We don't need to specify `/nixvim/` as part of our install path as that is where gh-pages uploads to by default.
Rather, we only need to specify the full `/nixvim/foo/` in the base-href and the install path should just be `/foo`.
=> docs/ci: fix docs being installed to `nixvim/nixvim/<subdir>`

plugins/lsp/language-servers/_mk-lsp.nix
There were two bugs in the lsp server modules:
- They unconditionally evaluated extraConfig
- They did not take into account if the global lsp plugin was enabled or not
Fixes #2543
=> plugins/lsp: Fix enable conditions

modules/opts.nix
Currently, we generate the lua code as soon as the value of the option is not an empty attrs.
However, a case where the attrs only contains `null` values (`nord_colorscheme = null; nord_foo = null;}` would pass the `if` condition, but the generated lua table would still be empty because `toLua` filters out those values.
Hence, we should directly check if the attrs would be translated to an empty lua table or not to decide whether we should generate the lua snippet or not.
=> modules/opts: fix code generation condition to prevent false positives

docs/user-guide/install.md
Tiny update. Noticed the `master` branch does not exist.
=> docs: no longer using `master` but `main`

.github/workflows/build_documentation.yml, .github/workflows/update.yml
The new docs CI (#2554) relies on `--arg-from-file`, which was [added in 2.24](https://nix.dev/manual/nix/2.25/release-notes/rl-2.24#release-2240-2024-07-31).
nix-install-action [v26](https://github.com/cachix/install-nix-action/releases/tag/v26) installs nix 2.20.5, updating to [v30](https://github.com/cachix/install-nix-action/releases/tag/v30) will install nix 2.24.9.
=> ci: bump nix-install-action (**fixes** docs build)

plugins/by-name/vim-colemak/default.nix, tests/test-sources/plugins/by-name/vim-colemak/default.nix
Integrate the [vim-colemak](https://search.nixos.org/packages?channel=24.05&show=vimPlugins.vim-colemak&from=0&size=50&sort=relevance&type=packages&query=vim-colemak) plugin.
=> plugins/vim-colemak: init

plugins/lsp/default.nix, tests/test-sources/plugins/lsp/_lsp.nix
Use `attrsOf` instead of `attrs` to ensure recursive merging, otherwise things like `extraOptions.settings = lib.mkIf` will not be unwrapped by the module system.
Added a small regression test to ensure "wrapped" values are properly unwrapped.
Fixes #2562
=> plugins/lsp: fix `enabledServers.extraOptions` type merging

plugins/by-name/image/default.nix
ueberzug is not maintained anymore and is not working.
[ueberzugpp](https://github.com/jstkdng/ueberzugpp) is a active fork, that I think , should be used as default
=> plugins/image.nvim: ueberzugPackage default to ueberzugpp

.github/workflows/build_documentation.yml
This doesn't work because we can only deploy docs from the main branch.
=> ci/docs: remove on 24.05 branch

README.md, docs/user-guide/faq.md, docs/user-guide/install.md, tests/modules/hm-extra-files-byte-compiling.nix, tests/modules/hm.nix, tests/modules/nixos.nix
This PR will contain changes needed to be made before the branch-off.
- Add 24.11 to "docs versions" array
- If we don't have a stable -> versioned URL redirect, I think a breaking change is ok here?
=> treewide: replace mentions of 24.05 with 24.11

plugins/by-name/gitlab/default.nix, tests/test-sources/plugins/by-name/gitlab/default.nix
Add support for [gitlab.vim](https://gitlab.com/gitlab-org/editor-extensions/gitlab.vim), GitLab Duo integration in Neovim.
Fixes #2565
=> plugins/gitlab: init

plugins/by-name/aerial/default.nix, tests/test-sources/plugins/by-name/aerial/default.nix
Add support for [aerial.nvim](https://github.com/stevearc/aerial.nvim), a plugin for a code outline window.
Fixes #2514
=> plugins/aerial: init

modules/default.nix, modules/lazyload.nix
Adds a global lazyloading assertion. No module options yet, and none are likely to be added until after we have per-plugin options.
=> modules/lazyload: init w/ assertion

plugins/by-name/nvim-colorizer/default.nix
Adds the always_update, virtualtext_inline and virtualtext_mode options to nvim-colorizer.
=> plugins/nvim-colorizer: add missing options

plugins/by-name/schemastore/default.nix
I was unable to add extra schemas into the schemastore plugin. After some digging I found out that an extra table is created when injected into the LSP server config. Here's an example of what it looks like before this fix:
```lua
local __lspServers = {
{
extraOptions = {
settings = {
yaml = {
schemaStore = { enable = false, url = "" },
schemas = require("schemastore").yaml.schemas({
{
extra = {
{
description = "Kyverno Chainsaw Test Manifest",
fileMatch = { "chainsaw-test.yaml", "chainsaw-test.yml" },
name = "chainsaw-test.yaml",
url = "https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json",
},
},
},
}),
},
},
},
name = "yamlls",
},
````
After this fix:
```lua
local __lspServers = {
{
extraOptions = {
settings = {
yaml = {
schemaStore = { …
```
=> plugins/schemastore: remove table wrapping

plugins/by-name/persisted/default.nix, tests/test-sources/plugins/by-name/persisted/default.nix
Add support for [persisted.nvim](https://github.com/olimorris/persisted.nvim), a plugin for simple session management.
Fixes #2603
=> plugins/persisted: init

plugins/by-name/neotest/adapters.nix
```bash
error: undefined variable 'props'
at /nix/store/hrvknxmyxnhswx4wj7mksix7i08vli8k-source/plugins/by-name/neotest/adapters.nix:49:93:
48|             Nixvim (plugins.neotest.adapters.${name}): This adapter requires `treesitter` to be enabled.
49|             You might want to set `plugins.treesitter.enable = true` and ensure that the `${props.treesitter-parser}` parser is enabled.
|                                                                                             ^
50|           '';
```
Not sure where that value is supposed to come from ? Any ideas?
This change will output 
```bash
evaluation warning: Nixvim (plugins.neotest.adapters.zig): This adapter requires `treesitter` to be enabled.
You might want to set `plugins.treesitter.enable = true` and ensure that the `zig` …
```
=> plugins/neotest: fix adapter warning

plugins/by-name/otter/default.nix, tests/test-sources/plugins/by-name/otter/default.nix
Doesn't actually check if treesitter is enabled.
=> plugins/otter: fix treesitter warning

plugins/colorschemes/catppuccin.nix
Supports lazy loading
Lz-n will look for the colorscheme in packpath by originalName. Without change it will throw an error when trying to lazy load. This plugin has a unique `originalName` because the upstream repo is just `nvim` and upstream package is being added to packpath as `catppuccin-nvim`.
=> colorschemes/catppuccin: add originalName

plugins/pluginmanagers/lz-n.nix
Discovered during testing lazy loading colorscheme that we aren't loading the config early enough to catch all triggers.
=> plugins/lz-n: earlier lua loading

plugins/by-name/lightline/default.nix, plugins/by-name/nvim-autopairs/default.nix, plugins/by-name/treesitter/default.nix
Just replacing the occurrences of extraConfigLua in plugins that have been migrated to use the recommended approach instead of the deprecated approach.
=> {lightline,nvim-autopairs,treesitter}: extraConfigLua -> luaConfig

docs/mdbook/SUMMARY.md, docs/user-guide/lazy-loading.md
Just getting this started and creating a draft PR if anyone has input on what they'd like mentioned.
=> docs/user-guide: add lazy-loading.md

flake-modules/lib.nix, lib/builders.nix, lib/default.nix, lib/tests.nix, wrappers/_shared.nix, wrappers/standalone.nix
We had a few things in `lib.nixvim.builders` that depend on `pkgs` and are therefore also per-system.
These were deprecated in #2231, with a view to fully remove after 24.11 was released.
With these fully removed, the lib now has zero dependency on a `pkgs` instance or a `system`.
Fixes #2186
=> lib: remove dependency on `pkgs`

plugins/by-name/mini/default.nix, plugins/by-name/tiny-devicons-auto-colors/default.nix, plugins/by-name/web-devicons/default.nix, tests/test-sources/plugins/by-name/tiny-devicons-auto-colors/default.nix
Resolves https://github.com/nix-community/nixvim/issues/2381
~Attempted to see if it would work with mini mockDevicons and it still seemed to throw an error.~
Looked like a load order issue from dependencies, manually inserting setupCode in corresponding plugin's `luaConfig.post` until we can handle `mkOrder` or `dag` https://github.com/nix-community/nixvim/issues/2292 is available
=> plugins/tiny-devicons-auto-colors: init

flake-modules/lib.nix, lib/default.nix, lib/modules.nix, lib/tests.nix, modules/top-level/nixpkgs.nix, tests/main.nix, wrappers/_shared.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
Expose our locked nixpkgs as the `nixpkgs.source` module options.
This only happens when `evalNixvim` is part of a lib that was provided `flake` as an argument.
Stubbed the `nixpkgs.source` option for now. Eventually, this will be used to construct `pkgs` internally. For now, it's purely informational.
This is another small step towards #1784. See also #2022
=> lib/modules: pass `inputs.nixpkgs` into `evalNixvim`

flake-modules/dev/devshell.nix, flake-modules/dev/locate-lsp-packages.py
This script generates a list on stdout of possible matches for nvim-lspconfig servers.
It can't easily generate something more advanced because a lot of lsp servers have false positives, for example groovy's default command is `java -jar .....`, this would match the `java` package, not the groovy language server.
=> update-scripts: Add a script to search for nvim-lspconfig server packages

plugins/colorschemes/palette.nix, tests/test-sources/plugins/colorschemes/palette.nix
the option is declared as settings.customPalettes, but is accessed as settings.custom_palettes;
corrected the tests as well;
=> plugins/palette: fix minor typo;

plugins/by-name/obsidian/default.nix
add missing word in description of option
`plugins.obsidian.settings.workspaces.*.path`
DIdn't run fmt or checks since it's just a small addition.
=> plugins/obsidian: add missing word in description

flake-modules/dev/list-plugins/list-plugins.py, lib/vim-plugin.nix, modules/output.nix, plugins/by-name/openscad/default.nix, plugins/by-name/openscad/fuzzy-finder-plugin-option.nix, plugins/by-name/openscad/renamed-options.nix, tests/test-sources/plugins/by-name/openscad/default.nix
- **lib/vim-plugin: expose new helpers `settingsOptionDescription` and `processPrefixedGlobals`**
- **modules: let extraPlugins accept null values**
- **plugins/openscad: migrate to mkVimPlugin**
=> plugins/openscad: migrate to mkVimPlugin

lib/neovim-plugin.nix, lib/vim-plugin.nix
- **lib/{neovim,vim}-plugin: use `loc` throughout**
- **lib/{neovim,vim}-plugin: remove redundant parens**
Purely cosmetic, assuming tests pass 😅
=> lib/{neovim,vim}-plugin: use loc throughout & cleanup parens

modules/keymaps.nix
This feels more correct to me: I believe we were registering a keymap for all buffers, even if only some of them have experienced the relevant autocmd.
I don't know if it's guaranteed here that `args.buf` always exists (but maybe it's not a problem if it doesn't exist, because we'll still register a keymap for all buffers?).
This fixes https://github.com/nix-community/nixvim/issues/2711
=> modules/keymap: include buffer when registering `keymapsOnEvents`

plugins/cmp/sources/_mk-cmp-plugin.nix
This reverts commit 6a9d840370647abb0c980ff1bb8e47edd1255789.
It is not really needed anymore.
=> Revert "plugins/cmp/sources: use mkNeovimPlugin instead of mkVimPlugin for source plugins"

modules/keymaps.nix
There are some codepaths out there in the wild that seem to be explicitly setting a buffer at build time. I'm not convinced that's a sane thing to do, but I don't have time to dig any further right now.
See the discussion starting here:
https://github.com/nix-community/nixvim/pull/2712#issuecomment-2556330101 for more context.
=> modules/keymap: quickfix, use "keep" rather than "error"

plugins/by-name/treesitter/default.nix
Moved `extraPlugins` option from `programs.nixvim.plugins` to `programs.nixvim` set.
=> plugins/treesitter: update docs for custom grammar installation

docs/default.nix, flake-modules/lib.nix, flake-modules/packages.nix, lib/default.nix, lib/tests.nix, wrappers/_shared.nix, wrappers/standalone.nix
- make overrideable (`override` function is added by `makeOverridable`)
- make nixvim-lib extendable (`extend` function is added by `makeExtensible`)
- treewide: access nixvim-lib via flake instead of directly importing it
Add a non-system specific `<flake>.lib.nixvim` output, which is equivalent to the existing `<flake>.lib.<system>.helpers` output.
A warning is traced when the per-system output is used.
This is now also wrapped with `lib.makeOverridable` to allow overriding the function args used to construct the nixvim-lib. Additionally, `lib.fix` was replaced with `lib.makeExtensible`, allowing nixvim's sub-lib to be directly extended via overlays.
Throughout the codebase, nixvim-lib now comes from the flake outpets, rather than being imported manually. Where `_nixvimTests` needs to …
=> lib: mk overridable & extendable; also move flake output

lib/tests.nix
As this was an internal option, I don't see a reason to keep it around forever.
=> lib/tests: remove deprecated dontRun

lib/modules.nix
- **lib/modules: remove assertion message for removed `check` arg**
- **lib/modules: `flake` is now required**
=> lib/modules: remove assertion message for removed `check` arg

lib/modules.nix, modules/misc/context.nix, modules/top-level/nixpkgs.nix, modules/top-level/output.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
- **modules/context: `flake` option, provides access to our flake**
- **modules/output: add `manDocsPackage`**
Rather than only providing the configuration with access to `<flake>.inputs.nixpkgs`, we should probably pass the entire `<flake>` in. This is made available by a new `flake` option declared in `modules/misc/context.nix` and the default is set within `evalNixvim` in `lib/modules.nix`.
We then use this context option to define the default for `nixpkgs.source` and to enable a new `build.manDocsPackage`, exposing the man-docs package as part of the configuration.
Having the `manDocsPackage` as part of the module configuration will enable having the standalone package also be part of the configuration and/or having the locally installed docs be based on the local modules, rather than …
=> modules: add `flake` and `build.manDocsPackage`

CONTRIBUTING.md
Fixes a couple issues I found while learning how to add a plugin.
direnv had a dead link to it (moved to `plugins/by-name/direnv/default.nix`)
lsp-lines linked to a commit with several changes, including the move to `plugins/by-name/lsp-lines/default.nix`, instead of the file itself.
I also added a template link immediately following the example code, as that is logically when someone would want it.
Something of note: most files are linked by reference but the two under `mkVimPlugin` are permalinks. Would it be preferable if all the files were linked as permalinks or that these are switched to relative?
=> docs/contributing: fix hyperlink issues

lib/default.nix, lib/options.nix, lib/plugins/mk-neovim-plugin.nix, lib/plugins/mk-vim-plugin.nix, lib/plugins/utils.nix
I thought nixvim was already doing this when lazy-loading were implemented, since it was in `lz.n` documentation. But few days ago, I noticed it was not being done. So this PR makes plugins optional when lazy-loading is enable, instead of just lazy-loading plugins when they require setup for loading, which some don't.
=> lib/plugins: make plugin optional when lazy-loading

modules/top-level/test.nix, tests/failing-tests.nix, tests/test-sources/plugins/by-name/nvim-osc52/default.nix, tests/test-sources/plugins/by-name/rust-tools/default.nix
- **modules/test: allow not building nixvim config**
- **modules/test: allow arbitrary warning/assertion expecations**
- **tests: use warning-expectations options**
Long overdue options for "expecting" warnings or assertions to match arbitrary predicates.
Common use-cases can de defined declaratively using an enum of pre-defined predicates, while more advanced use-cases can provide an arbitrary predicate function.
Also made it possible to write a test that does not build nixvim's "wrapped" nvim w/config, although I wonder if such tests are better off written manually using runCommand & evalNixvim?
=> modules/test: allow arbitrary warning/assertion expecations

tests/fetch-tests.nix
If the test file is `default.nix`, we don't need to append the filename
to the test namespace.
=> tests: omit `default` suffix in test names

modules/top-level/test.nix
Small followup to #2752, kept separate to avoid further bloating that PR
=> modules/test: document possible types for expectation `value`

docs/mdbook/default.nix
`internal` options are intended to be implicitly not `visible`. This is already handled correctly by the nixos tooling, but our custom tooling did not correctly handle the edge case.
This lead to strange cases where an internal option is not included in the docs, but its sub-options were still visible.
For example, the new internal option `test.namedExpectationPredicates` is not in the docs, but its sub-options are:
<details><summary>Without this PR</summary>
<p>
</p>
</details> 
<details><summary>With this PR</summary>
<p>
</p>
</details>
=> docs: treat internal options as invisible

modules/top-level/test.nix
TBH these should probably be removed entirely and/or throw rather than warn, but for now we should at least hide them from the public docs.
=> modules/test: hide the deprecated `check*` options

plugins/by-name/blink-cmp/default.nix
When using nix to install blink-cmp plugin version 0.8.2 or higher, the plugin fails to load because it cannot find the git hash or tag used during build. So we force define the current version based on the current package version.
=> plugins/blink-cmp: force version for blink.cmp >= 0.8.2

lib/options.nix
Currently, an option created with `mkListOf type` allows only
- `null`
- A list of elements of type "type" or `rawLua`
According to me, it should also accept `rawLua` values directly, like all other options.
=> lib/options: mkAttrsOf, mkListOf, mkAttributeSet should accept raw values

plugins/by-name/fugit2/default.nix, tests/test-sources/plugins/by-name/fugit2/default.nix
Add support for [fugit2.nvim](https://github.com/SuperBo/fugit2.nvim), Neovim git GUI powered by `libgit2`.
Fixes #2739
=> plugins/fugit2: init

plugins/by-name/distant/default.nix, tests/test-sources/plugins/by-name/distant/default.nix
Add support for [distant.nvim](https://github.com/chipsenkbeil/distant.nvim), a plugin to edit files, run programs, and work with LSP on a remote machine from the comfort of the local environment.
Fixes #2757.
=> plugins/distant: init

flake.nix
Remove `inputs.git-hooks.inputs.nixpkgs-stable.follows`, see https://github.com/cachix/git-hooks.nix/pull/543
=> flake: remove unneeded follows after git-hooks dropped their nixpkgs-stable input

plugins/by-name/treesj/default.nix, tests/test-sources/plugins/by-name/treesj/default.nix
Add support for [treesj](https://github.com/Wansmer/treesj): a plugin that splits and joins blocks of code, such as arrays and argument lists.
=> plugins/treesj: init

plugins/by-name/vimux/default.nix, plugins/by-name/vimux/settings-options.nix, tests/test-sources/plugins/by-name/vimux/default.nix
Add support for [vimux](https://github.com/preservim/vimux), a plugin for easing vim-tmux interactions.
Fixes #1499
=> plugins/vimux: init

plugins/by-name/treesitter/injections.scm
Played around with `:InspectTree` and writing injections to support our `luaConfig` attributes for writing lua. This supports `luaConfig.pre|post|content` and `luaConfig = { pre|post|content }`
=> plugins/treesitter: injections support luaConfig strings

plugins/lsp/default.nix, plugins/lsp/language-servers/_mk-lsp.nix
- Migrated LSP to mkNeovimPlugin
- Added support for setting mode in non-extra lsp keymaps
It should probably be fine, since I didn't change anything besides support for mode
=> plugins/lsp: migrate to mkNeovimPlugin

plugins/by-name/smear-cursor/default.nix, plugins/by-name/smear-cursor/settings-options.nix, tests/test-sources/plugins/by-name/smear-cursor/default.nix
Add support for [smear-cursor.nvim](https://github.com/sphamba/smear-cursor.nvim), a Neovim plugin to animate the cursor with a smear effect in all terminals.
Fixes #2747
=> plugins/smear-cursor: init

plugins/colorschemes/monokai-pro.nix, plugins/default.nix, tests/test-sources/plugins/colorschemes/monokai-pro.nix
Add support for the [monokai-pro.nvim](https://github.com/loctvl842/monokai-pro.nvim/) colorscheme.
Fixes #2795
=> colorschemes/monokai-pro: init

plugins/by-name/fidget/default.nix, plugins/by-name/fidget/deprecations.nix, tests/test-sources/plugins/by-name/fidget/default.nix
- Migrated fidget.nvim to mkNeovimPlugin
- Added renames from old options to new ones (with the exception of the submodules, because I didn't find a way to)
- Added new options, etc.
- Updated tests to new format too
=> plugins/fidget: migrate to mkNeovimPlugin

plugins/by-name/blink-cmp/settings-options.nix
=> plugins/blink-cmp: fix `sources.per_filetype` option type

plugins/by-name/blink-cmp/default.nix
Forgot to remove this after I submitted the patch in nixpkgs
=> plugins/blink-cmp: remove forced version override

plugins/by-name/persistence/default.nix, tests/test-sources/plugins/by-name/persistence/default.nix
- Converted the plugin to use mkNeovimPlugin
- Removed some arguments that have been removed upstream and have no effect. I wasn't sure how to handle this. Right now enabling those options throws an error, but maybe there should just be a warning?
=> plugins/persistence: convert to mkNeovimPlugin and fix settings

plugins/by-name/inc-rename/default.nix, tests/test-sources/plugins/by-name/inc-rename/default.nix
- Converted the inc-rename plugin to use `mkNeovimPlugin`
- Added a missing option `save_in_cmdline_history`
- Changed description slightly.
=> plugins/inc-rename: convert to mkNeovimPlugin and add option

plugins/by-name/dropbar/default.nix, plugins/by-name/dropbar/settings-options.nix, tests/test-sources/plugins/by-name/dropbar/default.nix
Add support for [dropbar.nvim](https://github.com/Bekaboo/dropbar.nvim), a polished, IDE-like, highly-customizable winbar for Neovim with drop-down menu support and multiple backends.
Fixes #2594
=> plugins/dropbar: init

plugins/by-name/blink-cmp/default.nix, plugins/by-name/blink-cmp/settings-options.nix, tests/test-sources/plugins/by-name/blink-cmp/default.nix
https://github.com/Saghen/blink.cmp/releases/tag/v0.10.0
Can be merged after next flake update with new version. 
> [!TIP] 
> Workaround for users not tracking nixvim nixpkgs.
> ```nix
>            plugins.blink-cmp.settings = {
>              completion.list.selection.__raw = ''{auto_insert = true, preselect = false}'';
>            };
> ```
=> plugins/blink-cmp: update completion.list.selection type 

plugins/by-name/visual-multi/default.nix, plugins/by-name/visual-multi/settings-options.nix, tests/test-sources/plugins/by-name/visual-multi/default.nix, typos.toml
Add support for [vim-visual-multi](https://github.com/mg979/vim-visual-multi), a multiple cursors plugin for vim/neovim.
Fixes #2232
=> plugins/visual-multi: init

plugins/by-name/lazydev/default.nix, tests/test-sources/plugins/by-name/lazydev/default.nix
Adds [lazydev.nvim](https://github.com/folke/lazydev.nvim) to nixvim
=> plugins/lazydev: init

plugins/by-name/cornelis/default.nix, tests/test-sources/plugins/by-name/cornelis/default.nix
Add support for [cornelis](https://github.com/agda/cornelis), a plugin providing agda-mode for neovim.
Fixes #2280
=> plugins/cornelis: init

plugins/by-name/tailwind-tools/default.nix, tests/test-sources/plugins/by-name/tailwind-tools/default.nix
Add support for [tailwind-tools.nvim](https://github.com/luckasRanarison/tailwind-tools.nvim), an unofficial Tailwind CSS integration and tooling for Neovim.
Fixes #2709
=> plugins/tailwind-tools: init

plugins/by-name/femaco/default.nix, tests/test-sources/plugins/by-name/femaco/default.nix, typos.toml
Add support for [nvim-FeMaco.lua](https://github.com/AckslD/nvim-FeMaco.lua), a small plugin allowing to edit injected language trees with correct filetype in a floating window.
Fixes #2009
=> plugins/femaco: init

tests/default.nix, tests/main.nix, tests/nixpkgs-module.nix
We don't need a full test that actually _builds_ or _runs_ nixvim. All we need is some assertions on the result of a nixvim configuration.
Currently #2738 needs to change the module tests to construct their own `pkgs` instance, so that we can test how the module behaves. However this is likely to have a performance hit since we are repeatedly instanciating `pkgs` again for each test case. It's probably better to use a single `pkgs` instance for all test case modules, but move the nixpkgs-module tests to their own dedicated test derivation.
This PR does that, moving the existing tests to a dedicated link-farm.
This also allows creating some bespoke helpers to streamline writing the tests and _may_ improve performance slightly because we don't need to also build `config.build.package` for …
=> tests/nixpkgs: move nixpkgs module test to dedicated drv

modules/top-level/test.nix, tests/nixpkgs-module.nix
In an effort to reduce the scope of #2738, I've extracted a handful of the refactoring, minor fixes, and general prep commits into this PR.
=> tests: fixes & refactoring for nixpkgs-module

lib/modules.nix
`lib.evalModules` will automatically add `lib` to the module args internally. Doing it explicitly is redundant.
`specialArgs.modulesPath` can be used to allow users to manually import modules relative to our `./modules` directory.
It is also used by the module system to provide a base path for relative `disabledModules` paths.
=> lib/modules: clean `specialArgs`: drop `lib`, add `modulesPath`

modules/top-level/test.nix, tests/test-sources/plugins/by-name/nvim-osc52/default.nix, tests/test-sources/plugins/by-name/rust-tools/default.nix
Allow `test.warnings` and `test.assertions` to be defined as either a list, or a function coerced to a list.
When defined as a function, it is supplied an `expect` function which provides some syntactic-sugar for defining simple expectations.
This is an alternative to the current approach of defining that `expect` function on an ad-hoc basis.
I prefer this to adding `expect` to nixvim's lib because:
1. That would require having access to `lib`
2. IDK where in `lib` such a specialized function should live
Note: this can also be used in #2738
=> modules/test: provide access to `expect` function

flake-modules/legacy-packages.nix, flake-modules/lib.nix, flake-modules/wrappers.nix, lib/modules.nix, lib/tests.nix, modules/top-level/nixpkgs.nix, templates/simple/flake.nix, tests/main.nix, tests/nixpkgs-mock.nix, tests/nixpkgs-module.nix, wrappers/_shared.nix, wrappers/modules/nixpkgs.nix, wrappers/modules/shared.nix, wrappers/standalone.nix
This PR finally gets the `nixpkgs` module to a fully functional state. If `nixpkgs.pkgs` is not defined, then an instance of nixpkgs is constructed from `nixpkgs.source`.
Constructing nixpkgs also requires knowing which system to target, so the `hostPlatform` and `buildPlatform` options are included.
I also included the `nixpkgs.config` option. This could just be `attrsOf anything`, but I've used the upstream option-type because it handles some special cases while merging definitions.
I've also added the non-standalone option `nixpkgs.useGlobalPackages`, which automatically sets `nixpkgs.pkgs` to the "host" or "global" packages; i.e. the `pkgs` arg in use by the outer module eval.
Most implementation is directly based on https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/nixpk …
=> modules/nixpkgs: complete the MVP

generated/rust-analyzer.nix, update-scripts/rust-analyzer/default.nix
Some new options triggered un-handled cases in the generation script. This PR also adds more diagnostics to be help debugging future issues of the sort.
I'd recommend reading the PR commit by commit for readability. Note that there are large indenting changes that obscure the real additions
Closes #2828
=> update-scripts: Fix rust-analyzer update script

plugins/by-name/flutter-tools/default.nix, plugins/by-name/flutter-tools/settings-options.nix, tests/test-sources/plugins/by-name/flutter-tools/default.nix
Add support for [flutter-tools.nvim](https://github.com/nvim-flutter/flutter-tools.nvim), a plugin to help create flutter apps in Neovim using the native lsp.
Fixes #2042.
=> plugins/flutter-tools: refactoring

.github/workflows/build_documentation.yml, .github/workflows/update.yml
24.05 has reached end-of-life. Let's not auto-update its lockfile or generated docs for it anymore.
I've kept the ability to manually trigger updating its lockfile.
Closes #2856
=> ci: drop 24.05 support

docs/mdbook/index.md, modules/top-level/nixpkgs.nix, wrappers/modules/nixpkgs.nix
Rather than waiting for a technically impossible migration strategy, let's just bite the bullet and change the default.
This PR also adds a "breaking changes" notice to the docs homepage, since we don't have a better way to inform users.
=> modules/nixpkgs: `useGlobalPackages` default to false

README.md, docs/mdbook/default.nix, docs/mdbook/index.md
Reduce duplication by defining a section of the README that'll be automatically included in the docs
=> docs: use README as a source for the docs

flake/default.nix, flake/flake-modules/default.nix, flake/flake-modules/nixvimConfigurations.nix, flake/flake-modules/nixvimModules.nix, flake/legacy-packages.nix, flake/nixvim-configurations.nix
- **flake: add initial flake-parts module**
- **flake: add `nixvimConfigurations` flake-parts module**
- **flake: add `nixvimModules` flake-parts module**
This adds flake-parts modules for declaring `flake.nixvimModules` and `perSystem.nixvimConfigurations`. A `default` module imports both of these.
This is currently undocumented. It should be possible to document these modules in a similar way to how we document platform-wrappers. We may also want to document our flake-parts modules on the flake.parts website?
@traxys also [proposed](https://github.com/nix-community/nixvim/pull/2854#issuecomment-2600121408) having some auto-configuration, which I agree is a good idea. However I'd like to keep the scope of this PR small, so let's postpone that for now.
=> flake: initial flake-parts modules

flake/flake-modules/auto.nix, flake/flake-modules/default.nix
When enabled, automatically sets up packages and/or checks for all `nixvimConfigurations`
Both options currently default to false. See https://github.com/nix-community/nixvim/pull/2854#discussion_r1921623854
A `nameFunction` can be configured for transforming nixvimConfiguration names into package/check names. Maybe prefix & suffix string options would be simpler?
Originally from #2854
=> flake: add `auto` flake-parts module

flake/lib.nix, lib/default.nix
- `lib.nixvim.evalNixvim`
- aka `<nixvim>.lib.nixvim.evalNixvim`
- `<nixvim>.lib.evalNixvim` (flake output)
- Maybe this isn't needed?
Originally from #2854
=> lib: export `evalNixvim` as top-level alias

lib/default.nix, lib/utils.nix, plugins/by-name/haskell-scope-highlighting/default.nix, plugins/by-name/nvim-autopairs/default.nix, plugins/by-name/obsidian/default.nix, plugins/by-name/rustaceanvim/default.nix, plugins/by-name/twilight/default.nix, plugins/cmp/auto-enable.nix, plugins/colorschemes/monokai-pro.nix, tests/lib-tests.nix
This aims to provide more consistency for our warnings.
- **lib/utils: add mkWarnings**
- **treewide: use mkWarnings wherever possible**
Before:
```nix
warnings = lib.optional COND ''
Nixvim (plugins.foo): MESSAGE
'';
```
After:
```nix
warnings = lib.nixvim.mkWarnings "plugins.foo" {
condition = COND; # Or `cond = `, to be discussed
message = "MESSAGE";
};
```
- The second argument of `mkWarnings` can either be a single _conditional warning_ or a list of several ones.
- A _conditional warning_ is either a string (i.e. non-conditional) or a `{ condition = ...; message = ...; }` attrs.
=> lib/utils: add mkWarnings

modules/top-level/output.nix, modules/top-level/test.nix, tests/test-sources/modules/performance/combine-plugins.nix, wrappers/darwin.nix, wrappers/hm.nix, wrappers/nixos.nix, wrappers/standalone.nix
- **modules/output: move `symlinkJoin` to `build.package`**
- **wrappers/standalone: simplify `extend`**
Should work better with #2854
=> modules/output: move `symlinkJoin` to `build.package`

flake/flake-modules/auto.nix
This seems like a simpler/saner default.
See https://github.com/khaneliman/khanelivim/pull/12#discussion_r1921824152 for prior discussion.
=> flake/auto: `nameFunction` default to `lib.id`

flake/wrappers.nix, tests/default.nix, tests/platforms/darwin.nix, tests/platforms/default.nix, tests/platforms/hm-extra-files-byte-compiling.nix, tests/platforms/hm.nix, tests/platforms/nixos.nix
Moved the platform integration tests out of `flake/wrappers.nix`. It makes more sense to set these up within `tests/`.
Now, they are owned by `tests/platforms/default.nix`, which is included by `tests/default.nix`.
Also:
- Renamed `tests/modules` -> `tests/platforms`
- Refactored to use `callTest`
- Used `isLinux` instead of `!isDarwin`
- Used `stdenv.hostPlatform`
=> tests: clean up/refactor wrapper/platform tests

lib/modules.nix, tests/platforms/default.nix, tests/platforms/hm-submodule-merge.nix
Includes a regression test.
Reverts commit b5efe91c5215aaaeefbb117d1951ea773e96ddd1 from #2841
Fixes #2879
=> lib/modules: work-around a submodule type-merging issue

flake/templates.nix, templates/experimental-flake-parts/README.md, templates/experimental-flake-parts/config/bufferline.nix, templates/experimental-flake-parts/config/default.nix, templates/experimental-flake-parts/flake.nix
Adds an experimental flake template that configures Nixvim directly using `evalNixvim` rather than the current standalone functions.
- #2210
- #2858
- #2867
- #2868
- https://github.com/khaneliman/khanelivim/pull/12
Since this is experimental/draft, we don't need to tick off everything above before merging.
=> experimental configuration-based nixvim template

README.md, flake.lock, flake.nix, templates/simple/flake.nix, tests/default.nix
Since #2862, `useGlobalPackages` defaults to `false`.
This will hopefully significantly reduce the number of 'out-of-sync' issues for users.
It also allows us to move to a _fresher_ channel without disrupting the workflow of users.
Hence, I propose to switch our reference channel from `nixos-unstable` to `nixpkgs-unstable`.
This proposition is motivated by two reasons:
1. `nixpkgs-unstable` makes more sense as our reference channel as the job set required for its bump involves building a bunch of packages **on all four platforms**.
Conversely, `nixos-unstable`'s job set is linux-only and include additional NixOS-related tests that do not really matter for us.
2. `nixpkgs-unstable` is fresher in average compared to `nixos-unstable`.
In conjunction to increasing our _bump frequency_ (to be …
=> flake.nix: follow nixpkgs-unstable instead of nixos-unstable

.github/workflows/update-other.yml, .github/workflows/update.yml
Split scheduling other branches into a dedicated workflow. The main update workflow is no longer responsible for triggering the workflow on _other_ branches.
It may also be nice to have the workflow stop when nixpks is not one of the inputs being bumped, to reduce force-push spam to the update branches. That is not part of this PR.
=> ci/update: schedule main branch daily, other branches weekly

.github/workflows/update.yml
This should help mitigate spammy force-pushes that don't actually update the nixpkgs input.
This only affects _scheduled_ runs. Manually triggered updates will always force-push to the update branch.
I've tested out the `nix eval` commands locally with some canned examples, but as ever with CI workflows I'm unable to fully verify this works in production.
=> ci/update: cancel scheduled runs that don't bump nixpkgs

plugins/by-name/markdown-preview/default.nix, plugins/by-name/markdown-preview/deprecations.nix
Was looking at stuff and saw it could use some cleaning up with statements and moving deprecations to separate file.
=> plugins/markdown-preview: modernize

.github/workflows/update.yml
If there's no open PR, there's no reason to run the "check if the input changed" step.
Knowing about the open PR also allows us to link to it in the summary.
Follow up: it may be nice for _cancelling_ the workflow to not show up as an error. This could be done by having the follow-up steps be conditional on a `steps.check.outputs.stop` output, _instead of_ exiting non-zero.
=> ci/update: check whether a PR is already open

.github/workflows/update-other.yml
- **ci/update-other: pass `--repo` to `gh`**
- **ci/update-other: remove redundant condition**
- **ci/update-other: use a job matrix**
I noticed [today's scheduled run](https://github.com/nix-community/nixvim/actions/runs/12964986550/job/36164270237) failed because `gh` was unable to figure out what repo it should target.
This happens when `gh` is used outside of a git repo. The workflow is affected because we don't checkout a repo.
However, we don't need to checkout one. We can just specify it using `--repo`.
While I was working on the workflow, I noticed a couple things that can be improved. E.g. the list of branches to trigger `update.yml` on can be a job-matrix.
=> ci/update-other: fix & improve

docs/user-guide/lazy-loading.md
Add another example of using before loading to trigger dependencies when lazy loading to avoid race conditions.
=> docs/lazy-loading: add extra examples

plugins/by-name/clangd-extensions/default.nix, tests/test-sources/plugins/by-name/clangd-extensions/default.nix
The setting has been removed upstream:
https://github.com/p00f/clangd_extensions.nvim/commit/db28f29be928d18cbfb86fbfb9f83f584f658feb.
=> plugins/clangd-extensions: remove inlay_hints option

.github/workflows/update.yml
As discussed https://github.com/nix-community/nixvim/pull/2921#issuecomment-2618861242, it'd be good for the CI to check for differences against the base branch when there is no PR currently open.
Additionally, I've cleaned up some stuff:
- Added a checkbox for manually enabling the "check for `nixpkgs` changes" (previously enabled only on scheduled runs)
- Replaced `exit 1` with a graceful cancellation
- Improved the "print summary" steps
=> ci/update: also check base branch, +cleanup

plugins/by-name/zellij-nav/default.nix, tests/test-sources/plugins/by-name/zellij-nav/default.nix
Add support for [zellij-nav.nvim](https://github.com/swaits/zellij-nav.nvim), a plugin granting seamless navigation between Neovim windows and Zellij panes.
Fixes #1915
I explicitly used `mkNeovimPlugin` although this plugin does not have any option.
It does have a `setup(opts)` function, so let's expose it just in case.
=> plugins/zellij-nav.nvim: init

plugins/by-name/zotcite/default.nix, tests/test-sources/plugins/by-name/zotcite/default.nix
Add support for [zotcite](https://github.com/jalvesaq/zotcite), a Neovim plugin for integration with Zotero.
Fixes #2811
=> plugins/zotcite: init

flake/dev/default.nix, plugins/by-name/blink-cmp-copilot/default.nix, plugins/by-name/copilot-cmp/default.nix, plugins/by-name/fidget/default.nix, plugins/by-name/flutter-tools/default.nix, plugins/by-name/gitsigns/default.nix, plugins/by-name/glance/default.nix, plugins/by-name/lazydev/default.nix, plugins/by-name/lean/default.nix, plugins/by-name/lir/default.nix, plugins/by-name/lspsaga/default.nix, plugins/by-name/neoclip/default.nix, plugins/by-name/neogit/default.nix, plugins/by-name/nvim-autopairs/default.nix, plugins/by-name/obsidian/default.nix, plugins/by-name/twilight/default.nix, plugins/colorschemes/monokai-pro.nix, plugins/lsp/language-servers/hls.nix, plugins/lsp/language-servers/rust-analyzer.nix
Alternative to #2929
- **misc/statix: disable the "bool_comparison" lint**
- **treewide: use boolean comparison to simplify the code base**
Closes #2929
=> treewide: use boolean comparison to simplify the code base

lib/plugins/mk-neovim-plugin.nix, lib/plugins/mk-vim-plugin.nix, lib/plugins/utils.nix
=> lib/plugins: introduce `mkMetaModule`

plugins/by-name/lexima/default.nix, plugins/by-name/lexima/settings-options.nix, tests/test-sources/plugins/by-name/lexima/default.nix
Add support for [lexima.vim](https://github.com/cohama/lexima.vim), a plugin to auto close parentheses.
Fixes #1880
=> plugins/lexima: init

docs/mdbook/default.nix
=> docs/mdbook: support `visible = "shallow"`

.github/workflows/update.yml
The simpler `[[ ]] &&` construct can exit non-zero, causing the workflow to fail.
=> ci/update: use `if then else` for setting `cancelled` step output

.github/workflows/update.yml
We can create/update PRs using the `gh pr` command, no need for a third party dependency.
=> ci/update: drop dependency on peter-evans/create-pull-request

.github/workflows/update.yml
Only users can be assigned to PRs, not teams.
See failure: https://github.com/nix-community/nixvim/actions/runs/13059278606/job/36437988175#step:10:73
Testing locally:
```
$ gh pr create --assignee nix-community/nixvim
Creating pull request for MattSturgeon:ci/dont_assign_team into main in nix-community/nixvim
X operation failed. To restore: gh pr create --recover /tmp/gh565857481.json
GraphQL: Could not resolve to a User with the login of 'nix-community/nixvim'. (u000)
```
```
$ gh pr create --reviewer nix-community/nixvim --assignee MattSturgeon
Creating pull request for MattSturgeon:ci/dont_assign_team into main in nix-community/nixvim
https://github.com/nix-community/nixvim/pull/2936
```
=> ci/update: don't assign a team to the PR

.github/workflows/update.yml
@github-actions doesn't have access to nix-community teams, so it can't request @nix-community/nixvim review the PR.
See failed run: https://github.com/nix-community/nixvim/actions/runs/13059569225/job/36438936010#step:10:71
=> ci/update: don't request review on the PR

.github/workflows/update.yml
Using `git cherry-pick`, we can re-apply any manually committed changes in the already open PR. "Manually committed" is defined as any commit _after_ the most recent commit authored by `github-actions[bot]`.
We can also check if any files have differences before pushing.
This removes the `inputs.nixpkgs` revision checking added in #2885, because the new file-differences check is simpler and more useful.
A major benefit of re-applying the additional commits is that they are no longer lost when the CI force-pushes its updates.
This has been tested:
- https://github.com/nix-community/nixvim/actions/runs/13061369469/attempts/1
- https://github.com/nix-community/nixvim/actions/runs/13061542819/attempts/1
- https://github.com/nix-community/nixvim/actions/runs/13061542819/attempts/2
Also: the …
=> ci/update: re-apply manual commits from open PR

lib/default.nix, lib/options.nix, plugins/by-name/none-ls/_mk-source-plugin.nix, plugins/lsp/language-servers/_mk-lsp.nix, tests/lsp-servers.nix, tests/test-sources/plugins/by-name/none-ls/default.nix
If such a package is used by an end user an error will be raised with a message of the form:
```
error: Nixvim (plugins.none-ls.sources.formatting.textlint.package): No package is known for textlint, install externally and set this option to null
```
I'm open to changing that to a warning and returning null instead, though this would complicate the implementation as we would now need to check the priorities
=> lib,lsp,none-ls: Add a standard way to handle automatic installation of packages that may not exist in nixpkgs

plugins/by-name/blink-cmp/provider-config.nix, tests/test-sources/plugins/by-name/blink-cmp/default.nix
Adds the raw lua type to `plugins.blink-cmp.settings.sources.providers.enabled` so that the given example in the [documentation](https://nix-community.github.io/nixvim/plugins/blink-cmp/settings/sources/providers.html) actually works.
TODO:
=> plugins/blink-cmp: support raw lua for settings.sources.providers.enabled

plugins/by-name/java/default.nix, tests/test-sources/plugins/by-name/java/default.nix
Add support for [nvim-java](https://github.com/nvim-java/nvim-java), a plugin for Java development.
Fixes #1780
=> plugins/java: init

plugins/by-name/typescript-tools/default.nix, tests/test-sources/plugins/by-name/typescript-tools/default.nix
When lazy loading, we need to isolate the plugin's config otherwise it will fail because the generated config is still loaded immediately in lspconfig's lua.
=> plugins/typescript-tools: use plugin's luaConfig

plugins/by-name/blink-cmp/default.nix, plugins/by-name/blink-cmp/provider-config.nix
Couldn't set the config how I wanted and noticed a lot of these options didn't support rawLua. Changed the ones that have an upstream type that support a function.
=> plugins/blink-cmp: add rawLua support more provider options

modules/top-level/nixpkgs.nix, wrappers/_shared.nix
See https://github.com/NixOS/nixpkgs/pull/376988
Cherry-picked from #2964. There's no reason why we can't merge this early, to benefit users who have a nixpkgs revision ahead of ours.
Fixes #2967
=> modules/nixpkgs: don't assign elaborated platforms

.github/workflows/update.yml
We need to reverse the `rev-list` output so that the commits are re-applied in the correct order; oldest first.
=> ci/update: fix re-apply commit order

.github/workflows/update.yml
Backport changes from `main`.
This keeps the 24.11 workflow in-sync with the workflow on main.
The main feature being backported is re-applying additional commits from an already open update PR.
Note: the `on.schedule` event is ignored on non-default branches, so backporting that part of the workflow has no real effect (other than keeping the file content identical, which may aid future backports). This is also why I haven't backported the `update-other` workflow; doing so would be pointless since it'll only ever trigger on the default branch (`main`).
=> [24.11] ci/update: backport changes from `main`

.editorconfig, lib/options.nix, plugins/by-name/nvim-ufo/default.nix, tests/test-sources/plugins/by-name/nvim-ufo/default.nix
Following the [installation procedure of `nvim-ufo`](https://github.com/kevinhwang91/nvim-ufo/blob/main/README.md#minimal-configuration), it require to configure the LSP capabilities
=> plugins/nvim-ufo: Set lsp capabilities

plugins/by-name/schemastore/default.nix
The JSON language server has the following [configuration structure](https://github.com/microsoft/vscode/blob/6fef251f8f0e9f74b7adb4ed310e35eabb97afdf/extensions/json-language-features/server/src/jsonServer.ts#L167-L179):
```ts
// The settings interface describes the server relevant settings part
interface Settings {
json?: {
schemas?: JSONSchemaSettings[];
format?: { enable?: boolean };
validate?: { enable?: boolean };
resultLimit?: number;
};
http?: {
proxy?: string;
proxyStrictSSL?: boolean;
};
}
```
So, we should be mkDefault'ing `validate.enable` instead of `validate`, as `validate` is expected to be an `Object` containing `enable` as a boolean.
This is also reflected in the schemastore readme, which offers this configuration example:
```lua
require('lspconfig').jsonls.setup { …
```
=> plugins/schemastore: set the correct jsonls option

docs/fix-links/filter.lua
Follow up to https://github.com/nix-community/nixvim/pull/3010, in particular it resolves https://github.com/nix-community/nixvim/pull/3010#discussion_r1955547292.
=> docs/fix-links: handle `#anchor` targets on the same page

README.md, lib/keymap-helpers.nix
- **readme: use `:h map-table` for mapping modes**
- **lib/keymaps: replace `modes` attrs with list**
Small cleanup in preparation for fixing #3012
=> {readme,lib/keymaps}: cleanup `modes` docs/impl

README.md, lib/keymap-helpers.nix
See https://neovim.io/doc/user/usr_24.html#_abbreviations
and https://learnvimscriptthehardway.stevelosh.com/chapters/08.html
Fixes #3012
=> lib/keymaps: add abbreviation support to `modes` enum

lib/keymap-helpers.nix
- **lib/keymaps: add a link to `:h map-modes`**
- **lib/keymaps: make `mode` type's description more readable**
Only list the enum values once, instead of twice.
=> lib/keymaps: make mode type description more readable

plugins/by-name/lightline/default.nix
Found another small problem in the docs.
=> plugins/lightline: fix formatting of code example

.github/workflows/update.yml, default.nix, flake.lock, flake.nix, flake/default.nix, flake/dev/default.nix, flake/dev/devshell.nix, flake/dev/flake.lock, flake/dev/flake.nix, flake/dev/list-plugins/default.nix, flake/dev/package-tests.nix, flake/dev/template-tests.nix, flake/dev/tests.nix, flake/packages.nix, flake/templates.nix, tests/no-flake.nix
By _partitioning_ our "dev" dependencies, they will not be added to end-user's lockfiles. Instead, they will be fetched lazily when flake outputs that _actually_ need them are evaluated.
E.g. evaluating `nixvim.nixvimModules` will not fetch dev dependencies, however evaluating `nixvim.checks` or `nixvim.devShells` will.
This removes the need for end-users to manually set `nixvim.inputs.devshell.follows = ""` (etc). In fact, these optional inputs are no longer part of the root flake at all. I believe any user that currently has such inputs will get an error or warning notifying them that they are following a non-existent input.
We offload evaluation of some of our flake modules into a "partition" submodule. When its not needed, this submodule is not evaluated. When it is needed, it fetches …
=> flake: partition dev dependencies

.github/workflows/update.yml
Need to use raw output to avoid having a quoted string, otherwise we end up with a malformed flakeref:
```
error: in URL 'github:NixOS/nixpkgs/"2d068ae5c6516b2d04562de50a58c682540de9bf"',
'"2d068ae5c6516b2d04562de50a58c682540de9bf"' is not a commit hash or branch/tag name
```
=> ci/update: fix `inputs.nixpkgs.rev` eval

docs/fix-links/default.nix
We are essentially writing GFM e.g. inline HTML comments and GFM alerts. So tell pandoc to parse/render as such. This resolves issues such as `> [!TIP]` being escaped to `> \[!TIP\]`.
Fixes #3033
=> docs/fix-links: pandoc `markdown` -> `gfm`

.github/workflows/update.yml
Write the PR body more dynamically, by writing to a `body.md` file.
Add a link to the workflow run.
Add documentation for how to run another update on the PR, either using the github website or the `gh` command.
Demo of this working: https://github.com/nix-community/nixvim/pull/3039
=> ci/update: document how to re-update in PR body

docs/fix-links/filter.lua
- Strip trailing `?query` and/or `#anchor`
- Strip leading `./` recursively
- Check if what's left is `""` or `"."`
Any link that targets the current page should be left as-is (no-op).
Follow up to https://github.com/nix-community/nixvim/pull/3031 and https://github.com/nix-community/nixvim/pull/3010
=> docs/fix-links: generalise checks for links targeting `.`

plugins/by-name/octo/default.nix, tests/test-sources/plugins/by-name/octo/default.nix
The snacks picker is also a valid choice now:
https://github.com/pwntester/octo.nvim/blob/631776a36c12724ba1db5ed8549cad35f70134dc/lua/octo/config.lua#L418
=> plugins/octo: add snacks picker to picker options

plugins/by-name/image/default.nix
Hi there! First of all, thanks for providing and maintaining Nixvim! This tiny contribution updates the _image_ plugin to expose the [resolve_image_path](https://github.com/3rd/image.nvim?tab=readme-ov-file#integrations) options, enabling users to modify how images path are resolved within their projects (typical use case: when using obsidian.nvim with a custom directory for images).
=> plugins/image: add resolveImagePath option

plugins/lsp/lsp-packages.nix
Not ready yet, flake.lock still tracking old nixpkgs (I'll rebase after a lock file update)
- dolmenls added in https://github.com/NixOS/nixpkgs/pull/380805
- ocamllsp was packaged long time ago
=> plugins/lsp: enable dolmenls and ocamllsp

plugins/by-name/diagram/default.nix, tests/test-sources/plugins/by-name/diagram/default.nix
Add support for [diagram.nvim](https://github.com/3rd/diagram.nvim), a plugin for rendering diagrams.
Fixes #3085
=> plugins/diagram: init

plugins/by-name/faust/default.nix, tests/test-sources/plugins/by-name/faust/default.nix
Add support for [faust.nvim](https://github.com/madskjeldgaard/faust-nvim), a plugin for writing Faust DSP code.
Fixes #2997
=> plugins/faust: init

plugins/by-name/avante/default.nix
Closes https://github.com/nix-community/nixvim/issues/3104
Looks like it was initialized incorrectly from inception. Renaming to match the option name upstream.
Wasn't a valid option before, so not even putting a rename warning in.
=> plugins/avante: fix incorrect option name

tests/main.nix
- **tests: drop use of `mkTestDerivationFromNixvimModule`**
- **tests: add useful attrs to test passthru**
I found it annoying when debugging that I had no access to the nixvim configuration that produced the test. I've resolved that by adding all useful attrs from the configuration to the test's passthru.
It's still a little cumbersome, since you have to step through two layers of linkFarm `entries` to get to the actual test derivation:
```
nix-repl> :lf .
Added 29 variables.
nix-repl> checks.x86_64-linux.test-1.entries.env.entries.env-variables.passthru
{
_module = { ... };
class = null;
config = { ... };
extendModules = «lambda extendModules @ /nix/store/4z177m7dr7rkib4d13mn0j6sh5vvhlnc-source/lib/modules.nix:317:23»;
file = "/nix/store/6cmww5libbnzkad096xjxh94792rxkm8-test-sources/env. …
```
=> tests: add `passthru` and drop `mkTestDerivationFromNixvimModule`

.github/workflows/update.yml, flake/dev/flake.nix
Rename `inputs.nixpkgs` to `inputs.dev-nixpkgs` to avoid shadowing the root flake's `inputs.nixpkgs`.
Having the dev flake shadow an input can be confusing, since overriding the root flake's input will have no effect when evaluating outputs that depend on the dev partition (i.e. outputs listed in [`partitionedAttrs`](https://flake.parts/options/flake-parts-partitions.html#opt-partitionedAttrs)).
The only reason we specify a nixpkgs input in the dev flake at all, is so the other inputs can follow it.
---
Once nix 2.26 is more prevalent, we can follow the root flake's inputs using a `"path:../.."` input. See [2.26 release notes](https://discourse.nixos.org/t/nix-2-26-released/59211) and https://github.com/NixOS/nix/pull/10089.
This may also require changes in …
=> flake/dev: rename `nixpkgs` input to avoid shadowing

flake/dev/flake.lock
Apply changes from 8e732cfac1e99dd53822c4e536d09e242ef9fd2a (#3121)
I forgot to run `nix flake lock ./flake/dev` (oops)
```
Flake lock file updates:
• Added input 'dev-nixpkgs':
'github:NixOS/nixpkgs/1750f3c1c89488e2ffdd47cab9d05454dddfb734?narHash=sha256-oDJGK1UMArK52vcW9S5S2apeec4rbfNELgc50LqiPNs%3D' (2025-03-24)
• Updated input 'devshell/nixpkgs':
follows 'nixpkgs'
→ follows 'dev-nixpkgs'
• Updated input 'git-hooks/nixpkgs':
follows 'nixpkgs'
→ follows 'dev-nixpkgs'
• Updated input 'home-manager/nixpkgs':
follows 'nixpkgs'
→ follows 'dev-nixpkgs'
• Updated input 'nix-darwin/nixpkgs':
follows 'nixpkgs'
→ follows 'dev-nixpkgs'
• Removed input 'nixpkgs'
• Updated input 'treefmt-nix/nixpkgs':
follows 'nixpkgs'
→ follows 'dev-nixpkgs'
```
=> flake/dev/flake.lock: apply changes from #3121

lib/keymap-helpers.nix, tests/test-sources/modules/keymaps.nix
https://neovim.io/doc/user/lua.html#vim.keymap.set()
- **lib/keymap-helpers (mapConfigOptions): use mkNullOrStr for desc**
- **modules/keymaps: add replace_keycodes keymap sub-option**
Fixes #3067
=> modules/keymaps: add replace_keycodes keymap sub-option

plugins/by-name/copilot-lua/default.nix
Got bumped in: https://github.com/zbirenbaum/copilot.lua/commit/f96d8e6d8f1a2de565657b6f4cd184c38a97e56d
=> plugins/copilot-lua: bump node.js to 20.x version

plugins/by-name/highlight-colors/default.nix, tests/test-sources/plugins/by-name/highlight-colors/default.nix
Add support for [nvim-highlight-colors](https://github.com/brenoprata10/nvim-highlight-colors), highlight colors for Neovim.
Fixes #3127
=> plugins/highlight-colors: init

tests/main.nix
Nix can only build attrsets with a `type = "derivation"` attr.
Having the configuration's option-type as a passthru attr breaks the ability to build specific test entries, since they are no longer `type = "derivation"`.
Renamed `passthru.type` -> `passthru.optionType` to work around this.
=> tests: remove `type` passthrough

plugins/by-name/hlchunk/default.nix, tests/test-sources/plugins/by-name/hlchunk/default.nix
Add support for [hlchunk.nvim](https://github.com/shellRaining/hlchunk.nvim), a plugin to highlight the indent and the code chunk according to the current cursor position.
Fixes #2894
=> plugins/hlchunk: init

plugins/by-name/colorful-menu/default.nix, tests/test-sources/plugins/by-name/colorful-menu/default.nix
Add support for [colorful-menu.nvim](https://github.com/xzbdmw/colorful-menu.nvim), a plugin making completion menus fancy.
Fixes #3004
=> plugins/colorful-menu: init

plugins/colorschemes/github-theme.nix, plugins/default.nix, tests/test-sources/plugins/colorschemes/github-theme.nix
Add support for the [github-nvim-theme](https://github.com/projekt0n/github-nvim-theme) colorscheme.
Fixes #3006
=> colorschemes/github-theme: init

plugins/by-name/hurl/default.nix, tests/test-sources/plugins/by-name/hurl/default.nix
Add [hurl.nvim](https://github.com/jellydn/hurl.nvim), plugin designed to run HTTP requests directly from `.hurl` files.
Fixes #3131
=> plugins/hurl: init

plugins/by-name/tinygit/default.nix, tests/test-sources/plugins/by-name/tinygit/default.nix
Add support for [nvim-tinygit](https://github.com/chrisgrieser/nvim-tinygit), a lightweight bundle of commands focussed on swift and streamlined git operations.
Fixes #3132
=> plugins/tinygit: init

flake/dev/list-plugins/list-plugins.py, plugins/by-name/telescope/extensions/advanced-git-search.nix, plugins/by-name/telescope/extensions/default.nix, tests/test-sources/plugins/by-name/telescope/advanced-git-search.nix
Add [advanced-git-search](https://github.com/aaronhallaert/advanced-git-search.nvim), an advanced git search extension for Telescope.
Fixes #2833
=> plugins/telescope/advanced-git-search: init

plugins/by-name/modicator/default.nix, tests/test-sources/plugins/by-name/modicator/default.nix
Add support for [modicator.nvim](https://github.com/mawkler/modicator.nvim), a cursor line number mode indicator plugin.
Closes #3135
=> plugins/modicator: init

plugins/by-name/codecompanion/default.nix
Fix broken link to upstream documentation
=> plugins/codecompanion: fix broken link

lib/deprecation.nix, plugins/by-name/treesitter/default.nix
- **plugins/treesitter: fix `treesitterPackage` deprecation warning**
Fix the issue reported by @SuperSandro2000 [on matrix](https://matrix.to/#/!iBrKeqhFRZaBBGodLH:matrix.org/$9eSGQIDaa0a4Wx5_cTh6sXxcBkPM2wH6t-C-0wTdVvI?via=matrix.org&via=vhack.eu&via=familleboyer.net).
`dependencies.treesitter` should be `dependencies.tree-sitter`.
- **plugins/treesitter: cleanup build-grammar deps impl**
Minor improvements to the impl.
- **lib/deprecations: use real option paths in `mkRemovedPackageOptionModule`**
Minor improvements to the deprecation notice; use the actual option `loc`s that include `prefix` etc.
- **lib/deprecations: assert option is correct in `mkRemovedPackageOptionModule`**
109f47f561cd08473da53205c2d06f9c0fc9dd06
This commit ~~can be~~ _(has been)_ dropped, it was included to …
=> plugins/treesitter: fix `treesitterPackage` deprecation message; modules/deprecation: improve mkRemovedPackageOptionModule impl

modules/dependencies.nix, tests/test-sources/modules/dependencies.nix
Follow up to #3174
Embed the actual package as an attr in the `example`'s literal expression, so that we don't need to convert to and from human-readable attr paths in the test.
This also fixes the "foo not found in pkgs" error from incorrectly saying "pkgs.foo not found in pkgs" and looking up `pkgs.pkgs.foo` for the actual package.
Additionally, this means that weird edge-cases (like packages with non-alphabetic chars in their attr-path) will be handled correctly.
=> modules/dependencies: refactor `all-examples` test

lib/deprecation.nix, tests/test-sources/modules/dependencies.nix
Follow up to https://github.com/nix-community/nixvim/pull/3162, in particular https://github.com/nix-community/nixvim/pull/3162#discussion_r2031191608.
Allows most existing configs to continue building; defining or reading the old `plugins.*.*Package` options will now continue to work, but result in a warning.
An error is still possible when definitions cannot be merged. E.g: \
`plugins.a.fooPackage = null` and `plugins.b.fooPackage = pkgs.foo` would effectively result in `dependencies.foo.enable = mkMerge [ true false ]`.
Generally, `plugins.a.fooPackage = null` will be an alias for `dependencies.foo.enable = false` while `plugins.a.fooPackage = pkgs.foo` is an alias for `dpendencies.foo.enable = true` and `dependencies.foo.package = pkgs.foo`.
The alias is two-way; if a user _reads_ …
=> lib/deprecation: implement aliases for `mkRemovedPackageOptionModule`

plugins/by-name/molten/default.nix
Without this dependency, commands like `:MoltenInit` causes the error message "[Molten] Unable to find any kernels to launch"
It seems like people (including myself) are implementing workarounds to this missing dep:
https://github.com/alisonjenkins/neovim-nix-flake/pull/51/commits/8b2b387b3d0d3fab465c81a662ed1240e99a2703
https://gitlab.com/p6s/vi/-/commit/792df862ea6f1a60683d3a870ea2593aa2533e36
Let's just include it with the default list of extra python dependencies.
=> plugins/molten: add ipykernel python dependency

modules/dependencies.nix
This adds flexibility to the `dependencies` module in prevision for future refactors.
Instead of statically declaring all the possible packages, this PR introduces an internal `__depPackages` option.
For now, it doesn't change much, but the idea is for plugin modules to "declare" their own dependencies.
=> modules/dependencies: introduce top-level (internal) __depPackages option

plugins/by-name/lilypond-suite/default.nix, tests/test-sources/plugins/by-name/lilypond-suite/default.nix
Add support for [nvim-lilypond-suite](https://github.com/martineausimon/nvim-lilypond-suite), a plugin for writing [LilyPond](https://lilypond.org) scores.
Closes #3189
=> plugins/lilypond-suite: init

modules/dependencies.nix
Minor fixes and cleanup following #3191
- **modules/dependencies: add description to `__depPackages`**
- **modules/dependencies: add `__depPackages` example**
- **modules/dependencies: coerce `__depPackages` attr-paths to list**
- **modules/dependencies: restore literal expression example support**
cc @GaetanLepage
=> modules/dependencies: minor cleanup

CONTRIBUTING.md, plugins/TEMPLATE.nix
Seeing as we are (now) often advising contributors to remove the `settingsOptions` they have already spent time and effort writing, I think we should reduce the emphasis on this in our contributing guide & plugin template.
- Add an additional caution in `CONTRIBUTING.md#declaring-plugin-options`
- Remove `settingsOptions` from `plugins/TEMPLATE.nix`
=> contributing: reduce emphasis on `settingsOptions`

tests/lsp-servers.nix
This reverts commit e1e0e6f0240327143d82086ccff5142b0f463685.
=> Revert "tests/lsp: disable golangci_lint_ls"

docs/mdbook/index.md
Hi folks. Thanks for the fantastic package. I was reading through the docs and on the home page there appears to be a tiny typo in the markdown link. Thought I'd just send a quick commit to fix it up.
It's just the removal of the extra `]` char.
=> docs: fix typo

plugins/lsp/default.nix
Use Neovim's native `vim.lsp` API instead of legacy `require('lspconfig').*.setup()`.
[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) aims to become a bank of configuration for popular language servers.
Its API has been deprecated in favor of Neovim 0.11's new `vim.lsp` native one.
Hence, we need to adapt how we configure `nvim-lspconfig` in lua and migrate it to the new API.
I have not yet really understand how `nvim-lspconfig` interacts with the native API to inject its configs.
> [!NOTE]
> This is a parallel effort of #3203
> Ultimately, we should be able to use our top-level `lsp` module in `plugins.lsp`'s (`nvim-lspconfig`) implementation.
- Quid of `plugins.lsp.servers.*.capabilities`? Do we need to provide them to `vim.lsp.config`?
- …
=> plugins/lsp: use vim.lsp native API

lib/utils.nix
`lib.generators.toPretty` has bespoke handling for rendering nix strings using either the `" "` or `'' ''` syntax, based on some heuristics.
Using `toPretty` instead of `toJSON` improves how literal-lua examples render in the docs.
```
nix-repl> lib.nixvim.literalLua "hi"
{
_type = "literalExpression";
text = "lib.nixvim.mkRaw \"hi\"";
}
nix-repl> lib.nixvim.literalLua "hi\nthere\n"
{
_type = "literalExpression";
text = "lib.nixvim.mkRaw ''\n  hi\n  there\n''";
}
nix-repl> lib.nixvim.literalLua "hi\nthere"
{
_type = "literalExpression";
text = "lib.nixvim.mkRaw ''\n  hi\n  there''";
}
```
=> lib/utils: fix `literalLua` multiline rendering

modules/diagnostics.nix, tests/test-sources/modules/diagnostics.nix
The `only_current_line` option for `vim.diagnostic.Opts.VirtualLines` doesn't exist. This PR changes the example diagnostic configuration to use `current_line` instead.
The relevant nvim docs are [here](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.Opts.VirtualLines).
=> modules/diagnostics.nix: Fix nonexistent virtual line option example

plugins/lsp/language-servers/_mk-lsp.nix, tests/test-sources/plugins/lsp/_lsp.nix
Users on matrix have reported issues when `rootDir` is defined.
nvim-lspconfig historically used `root_dir`, along with util functions like `root_pattern`.
Now that neovim's own LSP API is used, `root_dir` _appears_ to be subtly different and `root_markers` is introduced to replace `util.root_pattern`. _(?)_
Since we cannot easily warn about the `root_dir` differences, it can usually be replaced with `root_markers`, and can still be manually configured via `extraOptions` if needed; the simplest approach here is to remove the `rootDir` option.
```
The option definition `plugins.lsp.servers.tinymist.rootDir' in `/nix/store/via5xff0d3fbwg5nfxwpy0lijxbg9n3i-test-sources/plugins/lsp/_lsp.nix' no longer has any effect; please remove it.
nvim-lspconfig has switched from its own `root_dir` …
```
=> plugins/lsp/servers: replace `rootDir` with `rootMarkers`

plugins/lsp/default.nix
@MattSturgeon and I have observed that enabling inlay hints globally has the same effect as our current implementation, which enabled it locally for every server that supports it.
Simply adding `vim.lsp.inlay_hint.enable(true)` in the config file will enable inlay hints for all servers that support them.
=> plugins/lsp: simplify implementation of inlayHints

modules/performance.nix, plugins/lsp/default.nix
- **modules/performance: update runtimepath `pathsToLink`**
- **modules/performance: document `pathsToLink` default**
- **plugins/lsp: remove `standalonePlugins` default**
See https://github.com/nix-community/nixvim/issues/3211#issuecomment-2831943140
This should be tested by someone who has LSP and `combinePlugins` in their config:
You can test by updating your nixvim input to point at this PR:
```sh
nix flake lock --override-input nixvim 'github:nix-community/nixvim?ref=pull/3223/head'
```
Fixes #3211 :crossed_fingers: 
cc @jolars
=> modules/performance: update runtimepath `pathsToLink`

plugins/by-name/telescope/extensions/media-files.nix, tests/test-sources/modules/dependencies.nix, tests/test-sources/plugins/by-name/telescope/media-files.nix
- **plugins/telescope/media-files: remove old rename warnings**
- **plugins/telescope/media-files: use the top-level dependencies option**
=> plugins/telescope/media-files: use the top-level dependencies option

modules/performance.nix, modules/top-level/plugins/mk-plugin-pack.nix, tests/test-sources/modules/performance/byte-compile-lua.nix, tests/test-sources/modules/performance/combine-plugins.nix
Alternative to #3099.
Fixes #3140
Closes #3099
Plugins from luarocks (e.g. telescope-nvim) have dependencies specified in propagatedBuildInputs. These dependencies are not added as plugins in Nvim runtime. They are added to LUA_PATH env var for wrapped neovim. This PR collects all propagatedBuildInputs from input plugin list and puts them in the combined plugin.
Note that such dependencies are never combined or byte-compiled, because they are not plugins. Also it can lead to double plugins (e.g. one plenary-nvim as plugin dependency and another one in LUA_PATH). This is not nixvim issue, this is how it works in nixpkgs at this moment.
Most of the work for this PR was done to tests. Because of the changes in nixpkgs to plugin dependencies (especially to plenary.nvim) many tests weren't …
=> modules/performance/combinePlugins: propagate lua dependencies

plugins/by-name/luasnip/default.nix
This dependency is already handled in nixpkgs. And now it works with `combinePlugins` enabled too.
Also this is tested in nixpkgs (this happened to be one of primary examples where lua deps were needed in the first place):
https://github.com/NixOS/nixpkgs/blob/d99c55d7c10924d671c4fd61f264c207ae75695f/pkgs/applications/editors/neovim/tests/default.nix#L399-L404
=> plugins/luasnip: remove redundant jsregexp dependency

modules/default.nix, modules/lsp.nix, plugins/lsp/default.nix, tests/test-sources/modules/lsp.nix
Introduce a top-level `lsp` Nixvim module to wrap Neovim's `vim.lsp` API.
Example:
```nix
lsp.servers = {
luals.enable = true;
clangd = {
enable = true;
config = {
cmd = [
"clangd"
"--background-index"
];
root_markers = [
"compile_commands.json"
"compile_flags.txt"
];
filetypes = [
"c"
"cpp"
];
};
};
};
```
References:
- https://gpanders.com/blog/whats-new-in-neovim-0-11/#lsp
- https://neovim.io/doc/user/lsp.html#lsp-quickstart
Note: this is distinct from our `plugins.lsp` module which is backed by [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).
=> modules/lsp: init

modules/lsp/default.nix, plugins/by-name/lspconfig/default.nix, tests/test-sources/plugins/by-name/lspconfig/default.nix
A simplified replacement for `plugins.lsp`, without any additional configuration options or initialisation.
This plugin module only has 5 options:
```nix
nix-repl> nixvimConfigurations.x86_64-linux.default.options.plugins.lspconfig
{
autoLoad = { ... };
enable = { ... };
lazyLoad = { ... };
package = { ... };
packageDecorator = { ... }; # internal
}
```
Eventually, once the new `lsp` and `plugins.lspconfig` modules are mature, the old `plugins.lsp` module will be deprecated and/or aliased. I decided it was simpler to introduce the new plugin now and deprecate the old one in a _future_ PR to allow the new one to incubate before we instruct our users to migrate.
This is not very useful without https://github.com/nix-community/nixvim/pull/3203, although it's not technically _blocked_ by it.
=> plugins/lspconfig: init

plugins/by-name/dial/default.nix, tests/test-sources/plugins/by-name/dial/default.nix
Add support for [dial.nvim](https://github.com/monaqa/dial.nvim), an extended increment/decrement plugin for Neovim.
Closes #3235
=> plugins/dial: init

docs/mdbook/default.nix
This isn't a fully correct fix, but it's much closer to the intended behaviour.
> FIXME: We incorrectly remove `_freeformOptions` here.
>
> However we can't fix the bug because we derive page names from attrnames;
> the correct behaviour would be to ignore attrnames and use option `loc`s.
>
> As a workaround, merge the freeform options at the top of these attrs,
> however this can run into name conflicts 😢
>
> We should move this workaround to where we decide the page name and
> whether to nest into a sub-page, so that we can keep the original
> `_freeformOptions` attr as intended.
From https://github.com/nix-community/nixvim/pull/3243:
> I've noticed that the freeformtype's suboptions don't seem to get documented. I haven't checked yet if this is an issue with submodule, freeformtype, or …
=> docs: don't remove freeform sub-options

plugins/by-name/goto-preview/default.nix, tests/test-sources/plugins/by-name/goto-preview/default.nix
Add support for [goto-preview](https://github.com/rmagatti/goto-preview), a small plugin for previewing definitions using floating windows.
Closes #3236
=> plugins/goto-preview: init

plugins/by-name/actions-preview/default.nix, tests/test-sources/plugins/by-name/actions-preview/default.nix
Add support for [actions-preview.nvim](https://github.com/aznhe21/actions-preview.nvim), a fully customizable previewer for LSP code actions.
Closes #3136
=> plugins/actions-preview: init

modules/lsp/default.nix, modules/lsp/server.nix, tests/test-sources/modules/lsp.nix
The wildcard server ("*") should have its config set, but not be enabled through `vim.lsp.enable()`. Calling `vim.lsp.enable("*")` causes an error.
=> modules/lsp: don't enable wildcard server

plugins/by-name/vimade/default.nix, tests/test-sources/plugins/by-name/vimade/default.nix
Add support for [vimade](https://github.com/TaDaa/vimade), a plugin to dim, fade, tint, animate, and customize colors in windows and buffers.
Closes #3133
=> plugins/vimade: init

docs/mdbook/default.nix, modules/lsp/default.nix, modules/lsp/server-base.nix, modules/lsp/server.nix
- **docs: ensure path is escaped when copying module docs**
Found this bug in the docs when declaring the `*` option
- **modules/lsp: declare a stripped down `servers."*"` option**
Split the `server.nix` module into `server.nix` and `server-base.nix`. \
The latter is used by the `server.nix` module internally, and also used directly by the new `lsp.servers."*"` option's type.
This allows us to omit the options that only relate to "real" servers from the `lsp.servers."*"` option, while keeping them in the freeform options and the known-server options.
EDIT: This last part will be done in a follow-up:
- **modules/lsp: enable `servers."*"` by default**
Change the `lsp.servers."*".enable` to default to true. \
~~Fixes~~ https://github.com/nix-community/nixvim/issues/3256
=> modules/lsp: declare a stripped down `*` option

modules/lsp/default.nix, modules/lsp/server-base.nix, tests/test-sources/modules/lsp.nix
- **modules/lsp: check if server `settings` is empty**
Avoid writing `vim.lsp.config(...)` to `init.lua` when `server.settings == {}`
- **modules/lsp: enable `servers."*"` by default**
Change the `lsp.servers."*".enable` to default to true.
- Extracted from https://github.com/nix-community/nixvim/pull/3258
- Fixes https://github.com/nix-community/nixvim/issues/3256
=> modules/lsp: avoid empty config & enable `servers."*"` by default

plugins/by-name/tiny-inline-diagnostic/default.nix, tests/test-sources/plugins/by-name/tiny-inline-diagnostic/default.nix
Add support for [tiny-inline-diagnostic.nvim](https://github.com/rachartier/tiny-inline-diagnostic.nvim), a plugin that display prettier diagnostic messages.
Closes #3266
=> plugins/tiny-inline-diagnostic: init

plugins/by-name/schemastore/default.nix, tests/test-sources/plugins/by-name/schemastore/default.nix
I have been seeing these warnings 
```
evaluation warning: Nixvim (plugins.schemastore): You have enabled `json` schemas, but `plugins.lsp.servers.jsonls` is not enabled.
evaluation warning: Nixvim (plugins.schemastore): You have enabled `yaml` schemas, but `plugins.lsp.servers.yamlls` is not enabled.
```
when using the new lsp module. This PR adapts the schemastore module to work with the new lsp module as well and updates the tests to include testing against the new lsp module.
=> plugins/schemastore: adapt to new lsp module

plugins/by-name/clangd-extensions/default.nix, tests/test-sources/plugins/by-name/clangd-extensions/default.nix
Adapt warnings, default settings, and tests to the new lsp module. Also change the previous warning, which I think should target the clangd server directly, and just not `plugins.lsp`, since the clangd server is necessary for clangd-extensions to function and a user might have disabled it on their end.
I made `lsp.servers.clangd` true by default now, but maybe it would be better to retain having `plugins.lsp.clangd` being set to default while the module matures?
=> plugins/clangd-extensions: adapt to new lsp module

modules/lsp/default.nix, modules/lsp/keymaps.nix
Initial LSP keymaps option, inspired by `keymapsOnEvent` and `plugins.lsp.keymaps`.
Users can define `lspBufAction` instead of `action` if they wish to use a `vim.lsp.buf.<action>` callback.
---
I initially had a `diagnosticAction` option too, however looking at the manual there aren't many `vim.diagnostic.<action>` functions that'd be useful here.
Previously, `goto_prev` and `goto_next` fit well here, however 0.11 [deprecated](https://neovim.io/doc/user/deprecated.html#deprecated-0.11) those in favour of passing `count=1` or `count=-1` to `jump`, which can't easily be represented by a `diagnosticAction` option.
<details><summary><code>diagnosticAction</code></summary>
```nix
{ config, options, ... }:
{
options = {
lspBufAction = lib.mkOption {
type = types.nullOr types.str;
description = …
```
=> modules/lsp/keymaps: init

plugins/by-name/lf/default.nix, tests/test-sources/plugins/by-name/lf/default.nix
Fixes: #3124.
I went with calling this `lf` instead of `lf-nvim` because I do not think that supporting the packaging of `lf.vim` in the future is needed, as both effectively share the same features.
Unfortunately, I could not finish a run of `nix flake check --all-systems --option max-jobs 1` as it consistently OOMed my system (and that is with ~28GB of available ram), but I came rather close to finishing it and the change seems rather straight forward.
=> plugins/lf: init

plugins/colorschemes/kanagawa-paper.nix, plugins/default.nix, tests/test-sources/plugins/colorschemes/kanagawa-paper.nix
this PR introduces the kanagawa-paper colorsheme config via nixvim.
the package is already on nixpkgs-unstable and nixos-unstable.
PR in nixpkgs: https://github.com/NixOS/nixpkgs/pull/403656
testing wise im encountering some issues with tests being "killed"
=> colorschemes/kanagawa-paper: init

plugins/by-name/blink-copilot/default.nix
`copilot-lua` is not needed by `blink-copilot` anymore.
Reference: https://github.com/fang2hou/blink-copilot/commit/bdc45bbbed2ec252b3a29f4adecf031e157b5573
Fixes #3283.
=> plugins/blink-copilot: Mention in the description that copilot-lua is enabled by default

plugins/by-name/lsp-format/default.nix, tests/test-sources/plugins/by-name/lsp-format/default.nix
Upstream still documents the now-deprecated
`require("lspconfig").<name>.setup` mechanism. I believe the modern alternative is to register a `LspAttach` autocmd. For more context, see:
- https://github.com/lukas-reineke/lsp-format.nvim/issues/98
- https://github.com/lukas-reineke/lsp-format.nvim/pull/99
=> Port lsp-format to use non-deprecated setup instructions

modules/lsp/default.nix, modules/lsp/on-attach.nix, plugins/by-name/lsp-format/default.nix, tests/test-sources/plugins/by-name/lsp-format/default.nix
Similar to `plugins.lsp.onAttach`, implement a "global" equivalent to the per-server `on_attach` callback.
The implementation is simpler than `plugins.lsp.onAttach`, by using a `LspAttach` autocmd. The old impl was to propagate the global _onAttach_ lines into each server's `on_attach` callback.
The old impl should be able to migrate to using the new option under the hood, or even become an alias of it.
Alternatively, we might decide we don't want this at all? Although it seems convenient.
Perhaps in future it'd be nice to have a similar per-server `onAttach` option? When the per-server `onAttach` option is defined, `settings.on_attach` would be derived from it, using it as the function body.
=> modules/lsp: add `onAttach` option

plugins/by-name/rust-tools/default.nix, plugins/by-name/rustaceanvim/default.nix, plugins/by-name/rustaceanvim/settings-options.nix, plugins/by-name/typescript-tools/default.nix, plugins/lsp/default.nix
Follow up to #3280
Simplify the impl by doing global on-attach logic in `lsp.onAttach` (i.e. a `LspAttach` autocmd) instead of adding lua lines to each server's individual `on_attach` callback function.
This is effectively a `mkAliasOptionModule [ "plugins" "lsp" "onAttach" ] [ "lsp" "onAttach" ]` alias, but it is only applied when `plugins.lsp.enable` is true.
=> plugins.lsp: alias `onAttach` to new `lsp.onAttach`

plugins/lsp/default.nix
This PR has no code changes, but it corrects an incorrect and misleading comment in #3295.
Previously I said we alias the definitions instead of the value to allow `mkOrder` to work correctly. That is incorrect, as order-priorities are already sorted in `<opt>.definitions`.
The actual reason to use the definitions instead of the final value is to avoid inf-recursion. The "from" option's `apply` function reads the "to" option's value, which would be defined based on the "from" option's value, which is set by the "from" option's apply function...
For a one-way binding, `mkDerivedConfig` is best. For a two-way binding, `mkAliasAndWrapDefsWithPriority` is necessary.
=> plugins/lsp: correct motivation for `onAttach` alias impl

plugins/by-name/oil-git-status/default.nix, tests/test-sources/plugins/by-name/oil-git-status/default.nix
this PR adds oil-git-status to nixvim, since it recently got into master branch of nixpkgs
https://github.com/refractalize/oil-git-status.nvim
=> plugins/oil-git-status: init

plugins/pluginmanagers/lz-n.nix, tests/test-sources/plugins/pluginmanagers/lz-n.nix
Add a new `keymaps` option to the lz-n plugin that allows users to define
keymaps that use lz.n's keymap(<plugin>).set functionality. This enables 
users to create keymaps that lazy-load plugins when specific keys are pressed,
using the familiar vim.keymap.set() API style.
The implementation:
- Adds a new `keymaps` option using mkMapOptionSubmodule with a custom plugin property
- Exposes a simple and consistent interface for configuring lazy-loaded keymaps
- Processes these keymaps to generate corresponding Lua code with require('lz.n').keymap().set()
- Cleanly separates plugin specs from keymap definitions while preserving their relationship
=> plugins/lz-n: add support for keymap(<plugin>).set API

plugins/by-name/oil-git-status/default.nix, tests/test-sources/plugins/by-name/oil-git-status/default.nix
- **plugins/oil-git-status: fix whitespace in desc**
- **plugins/oil-git-status: update `signcolumn` instructions**
- **plugins/oil-git-status: improve `signcolumn` warning**
- **plugins/oil-git-status: set `signcolumn` sane default**
Minor follow ups to #3292, cc @FKouhai
For ease, please review one commit at a time.
This plugin requires you configure `plugins.oil` to allow at least 2 sign columns:
> Change the `oil` configuration to allow at least 2 sign columns
> ```lua
> require("oil").setup({
>  win_options = {
>    signcolumn = "yes:2",
>  },
> })
> ```
> — https://github.com/refractalize/oil-git-status.nvim#configuration
Looking at oil's docs, the `win_options` are options to apply to the oil buffer, so `signcolumn` is a vim setting (set by oil), not an actual oil setting.
The …
=> plugins/oil-git-status: improve desc; improve warning; set sane default

flake.lock, flake.nix
Users can specify which systems to use by having our `systems` input follow a different file or flake:
```nix
{
inputs = {
inputs.systems.url = "path:./systems.nix";
inputs.systems.flake = false;
inputs.nixvim.url = "github:nix-community/nixvim";
inputs.nixvim.inputs.systems.follows = "systems";
};
outputs = inputs: {
};
}
```
```nix
[
"x86_64-linux"
]
```
Alternatively, instead of users listing systems in a local file, they
can use an external flake, e.g.:
- `github:nix-systems/default`
- Exposes aarch64 and x86_64 for linux and darwin
- `github:nix-systems/default-linux`
- Exposes aarch64 and x86_64 for linux
- `github:nix-systems/default-darwin`
- Exposes aarch64 and x86_64 for darwin
- `github:nix-systems/aarch64-darwin`
- `github:nix-systems/aarch64-linux`
- …
=> flake: add overridable `systems` input

lib/maintainers.nix, plugins/by-name/hunk/default.nix, tests/test-sources/plugins/by-name/hunk/default.nix
Add support for [hunk.nvim][1], a plugin for splitting diffs.
Also add myself as a maintainer for it.
[1]: https://github.com/julienvincent/hunk.nvim
=> plugins/hunk: init

tests/fetch-tests.nix
Previously path was concatenated using string interpolation. This commit switches from string interpolation to path interpolation.
The problem is nix will copy the "${directory}" to a new store object, meaning anything outside its root won't be available.
From the nix manual:
> A path in an interpolated expression is first copied into the Nix
> store, and the resulting string is the store path of the newly created
> store object.
https://nix.dev/manual/nix/2.28/language/string-interpolation#interpolated-expression
This commit is cherry-picked from #3314, cc @stasjok
See prior discussion: https://github.com/nix-community/nixvim/pull/3314#discussion_r2083632273
=> tests/fetch-tests: avoid unnecessary copy-to-store

modules/performance.nix, modules/top-level/output.nix, modules/top-level/plugins/byte-compile-lua-lib.nix, modules/top-level/plugins/byte-compile-plugins.nix, modules/top-level/plugins/combine-plugins.nix, modules/top-level/plugins/default.nix, modules/top-level/plugins/mk-plugin-pack.nix, modules/top-level/plugins/utils.nix, tests/platforms/hm-extra-files-byte-compiling.nix, tests/test-sources/modules/performance/byte-compile-lua.nix, tests/test-sources/modules/performance/combine-plugins.nix, tests/test-sources/modules/performance/files/file.lua, tests/utils/plugin-stubs.nix
This PR:
- Introduces `performance.byteCompileLua.luaLib` option. When enabled, it'll byte-compile lua libraries in LUA_PATH. Specifically: `extraLuaPackages` and plugins `propagatedBuildInputs`.
- Adds `tests/utils/plugin-stubs.nix` with a shared plugin stubs and generated lua code for using in performance tests.
- Once again refactors performance tests using shared plugin stubs.
=> modules/performance: add ability to byte-compile lua packages and lua dependencies

docs/mdbook/index.md
The use of `follows` in a flake can cause issues even if `useGlobalPackages` is set.
Highlight this in the doc.
=> Add explanation on follow

flake/dev/default.nix, flake/dev/devshell.nix
- **flake: use pre-configured treefmt package in git-hooks**
- **flake/devshell: run treefmt directly in `format` command**
- **flake/devshell: add treefmt to shell**
Avoid running `nix fmt` within the shell; we already have evaluated and built our wrapped `treefmt`, so use that instead of re-evaluating the flake by calling `nix fmt`.
=> flake: use the same treefmt package throughout

flake/dev/default.nix, flake/dev/flake.nix, lib/maintainers.nix
- **flake: add `keep-sorted` to treefmt**
- **maintainers: enforce sorting**
- **flake/dev: sort flake inputs**
Enable https://github.com/google/keep-sorted in treefmt, and use it to keep a few things sorted:
1. Treefmt prograns
2. Dev flake inputs
3. Maintainers
This matches the new impl in nixpkgs, since https://github.com/NixOS/nixpkgs/pull/405684, and is incredibly simple and performant.
From upstream's README:
Surround the lines to keep sorted with `keep-sorted start` and
`keep-sorted end` in comments.
<details><summary>Details</summary>
Pre-sorting options tell keep-sorted what content in your file constitutes a
single logical line that needs to be sorted.
By default, keep-sorted will interpret increasing indentation as a line
continuation and group indented lines with the lines …
=> {flake,maintainers}: enforce sorting

docs/mdbook/book.toml, docs/mdbook/default.nix
Adds a ToC for all headings on the page.
https://github.com/slowsage/mdbook-pagetoc
=> docs/mdbook: add page ToC

docs/man/default.nix, docs/man/filter.lua
- Move lua filter to separate file
- Use a subshell to write `nixvim-header.5`
- Use bash function to avoid repetition
Cherry picked from #3049
=> docs/man: minor cleanup

flake/dev/devshell.nix, flake/dev/launch-test.sh
Allows using the `tests` devshell command to discover the full attrpath of a test.
e.g.
```
$ tests --attr modules-lsp plugins-by-name-lazygit
Printing 2 tests: modules-lsp plugins-by-name-lazygit
Full attr paths:
- checks.x86_64-linux.test-2.entries.modules-lsp
- checks.x86_64-linux.test-18.entries.plugins-by-name-lazygit
```
=> dev/tests: add `--attr` option to print full attrpath of tests

plugins/by-name/neo-tree/default.nix
According to the docs, focus is not an accepted value for this field, it's also a pretty common wish to have tabs layout centered.
Reference: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/main/doc/neo-tree.txt#L893
=> plugins/neo-tree: correct contentLayout allowed options

plugins/by-name/vim-test/default.nix, tests/test-sources/plugins/by-name/vim-test/default.nix
Add support for [vim-test](https://github.com/vim-test/vim-test), a plugin to run tests directly from Neovim.
Fixes #1497
=> plugins/vim-test: init

.github/workflows/build_documentation.yml, docs/mdbook/default.nix
This fixes a regression introduced by https://github.com/nix-community/nixvim/pull/3349; that PR serves the docs from the root of the docs derivation, however docs are actually installed to `$out/share/doc`.
IMO there's no reason to put a MDBook website in `share/doc/`, so rather than fixing `serve-docs`' `--chdir` I've instead changed the docs to install to the root of `$out`.
=> docs/mdbook: install directly to `$out`

MAINTAINING.md, docs/mdbook/SUMMARY.md, docs/mdbook/default.nix
- **maintaining: init**
- **maintaining: add sub "Deprecation" section**
- **maintaining: initial "Releasing" section**
This PR adds an initial `MAINTAINING.md` file, along with a stub for a "Deprecation" section and an initial pass on a "Releasing" section.
If I find more motivation, I'll try to flesh out the "Deprecation" section, but it may be better to merge the file with a stub and flesh it out in a dedicated PR that can get nit-picky over the details of the wording.
=> maintaining: init

.github/workflows/backport.yml
Adds a GitHub workflow to create backport PRs when merged PRs have a "backport" label.
This uses the very flexible https://github.com/korthout/backport-action and is based on the [workflow used by nixpkgs](https://github.com/NixOS/nixpkgs/blob/2566f9dc/.github/workflows/backport.yml), which is also [used by Stylix](https://github.com/nix-community/stylix/blob/0512b0f/.github/workflows/backport.yml). See [how it works](https://github.com/korthout/backport-action#how-it-works).
Currently, the workflow [will assume](https://github.com/korthout/backport-action#label_pattern) our backport labels follow the regex `backport ([^ ]+)$` (e.g. `backport nixos-25.05`), however we could customise that by assigning any regex we like to `with: label_pattern`.
Mergify also [has backport …
=> ci/backport: init

buildbot-nix.toml, flake/ci.nix, flake/default.nix, flake/dev/devshell.nix, flake/dev/package-tests.nix, flake/dev/tests.nix, tests/default.nix
I've long complained that buildbot is too tightly coupled to our flake's `checks` output; the same one used by `nix flake check`. Being unable to customise what buildbot builds has been a pain point for a while.
Turns out around seven months ago buildbot added a per-repo config file in https://github.com/nix-community/buildbot-nix/pull/318.
The available options are documented on its readme, [here](https://github.com/nix-community/buildbot-nix#per-repository-configuration). Currently only `lock_file` and `attribute`, but the latter enables this PR!
This PR adds an explicit `ci.buildbot` output to the flake, which we configure buildbot to use instead of the default `checks` output via a `buildbot-nix.toml` file.
This allows us to specify a different set of tests for `nix flake check` and …
=> flake: add `ci.buildbot` output

modules/top-level/plugins/combine-plugins.nix, tests/test-sources/modules/performance/combine-plugins.nix
Previously, specifying plugins as packages in the
`performance.combinePlugins.standalonePlugins` option did not work when
the `performance.byteCompileLua` option was also enabled. This issue was
due to several package transformations performed by the
`byteCompileLua`.
There are at least three methods to fix the issue:
- Change transformation order: combine plugins first, then byte-compile
them.
- Compare every possible transformation when determining if plugins are
standalone.
- Get the name of the package and use it for comparison.
The first method did not work because the current `byteCompileLuaDrv`
implementation does not support symlinks to directories. The second
method appears too fragile. This commit implements the third method, as
it requires minimal code changes and is …
=> modules/performance: fix issues with combining standalonePlugins and byte compilation

plugins/by-name/treesitter/default.nix, tests/test-sources/plugins/by-name/treesitter/combine-plugins.nix
Originally nvim-treesitter was added to standalonePlugins as workaround for https://github.com/NixOS/nixpkgs/pull/321550.
Nvim-treesitter from nixpkgs don't include queries from upstream parsers anymore since https://github.com/NixOS/nixpkgs/pull/344849.
If the user has some other plugin containing treesitter queries, this
change can cause a build failure due to collisions. But since it is
easier to add the plugin to standalonePlugins compared to removing it, I
think this should be the default.
=> plugins/treesitter: don't exclude nvim-treesitter from combining by default

lib/default.nix, lib/lua-types.nix, lib/options.nix
The types in `lua-types` are inspired by `pkgs.formats`, allowing for a more appropriate option type than `types.anything`.
The intention is that we will replace usage of `types.anything` in 90% of cases treewide with `lua-types.anything` (see #3208). Currently there are ~270 instances of `anything` treewide.
All types in `lua-types` support inline-lua and raw-lua.
`lua-types.tableOf` will also serve as a good place to implement merging lists defs and attrs defs into a mixed table, at some point in the future. Ideally we can upstream something similar to nixpkgs too. Again, see #3208 and also https://github.com/NixOS/nixpkgs/compare/master...MattSturgeon:nixpkgs:table.
=> lib/lua-types: init

plugins/by-name/treesitter/injections.scm
Fixes the issue I was having with wrong commenting/uncommenting with nixvim injections
=> plugins/treesitter: prevent mkRaw over-injection by removing injection.combined

update-scripts/update.nix
- **update-scripts/update: fix call to `version-info`**
- **update-scripts/update: fix 'has changed' condition when not committing**
As per https://github.com/nix-community/nixvim/pull/3382/files#r2127406819, I spotted the last update failed because `./result` is not where the `version-info` script is installed. Instead it is at `./result/bin/version-info`.
```
/result/bin/update: line 41: ./result: Is a directory
```
- https://github.com/nix-community/nixvim/actions/runs/15417040422
- https://github.com/nix-community/nixvim/actions/runs/15442028271
Additionally, I've added some fixes & refactoring so that the script works properly when _not_ committing, as without this it was failing in other scenarios when testing it locally.
I've now tested locally: with and without `--commit`; and …
=> update-scripts/update: fix call to `version-info` & 'has changed' when not committing

plugins/by-name/neotest/settings-options.nix, tests/test-sources/plugins/by-name/neotest/quickfix_open_raw.nix
Noticed that `quickfix.open` in the `neotest` plugin says it can be a function, but the option type didn’t actually support that — if you tried setting a Lua function with string, just got treated as a string. And if you tried setting it a `__raw` it would fail to build.
This just switches the option to use `mkNullableWithRaw` so it actually accepts raw Lua like the docs suggest.
Also added a quick test to make sure it works.
=> plugins/neotest: allow raw lua for `quickfix.open` setting

modules/output.nix, modules/top-level/output.nix, tests/test-sources/modules/output.nix
Allow users to add packages to the end of `PATH` in the neovim wrapper. This is useful for LSP versions that might need to be overriden based on the environment, e.g. `haskell-language-server` versions provided by a project's devshell.
=> output: add extraPackagesAfter option

plugins/by-name/kitty-navigator/default.nix, tests/test-sources/plugins/by-name/kitty-navigator/default.nix
Add support for [vim-kitty-navigator](https://github.com/knubie/vim-kitty-navigator), a plugin offering seamless navigation between kitty panes and vim splits.
Closes #3438
=> plugins/kitty-navigator: init

.github/workflows/update-other.yml
Uses a [sparse-checkout](https://github.com/actions/checkout#scenarios) to download only the `version-info.toml` file, then uses the [`yq-go`](https://github.com/mikefarah/yq) action to extract the "other" branches as a JSON array.
This means we no longer need to manually update the workflow file when adding/removing stable branches. 🎉
Fixes #3432
---
This can be seen running on my fork in this workflow run: https://github.com/MattSturgeon/nixvim/actions/runs/15597236191
Notice that the branch matrix was created correctly, and both updates attempted. Each update failed because my fork doesn't have the relevant branches.
I created one of the branches on my fork and ran it again: https://github.com/MattSturgeon/nixvim/actions/runs/15597329168
This time notice that the `nixos-25.05` branch's …
=> ci/update-other: generate branch list from version-info

plugins/by-name/toggleterm/default.nix
single backslash is not rendered right now:
=> escape backslash

.github/workflows/website.yml
Fix typo in #3466: `inputs.ref` → `matrix.ref`.
This caused an empty string to be assigned to the checkout action's `ref` input, meaning it used its default value `github.ref`.
Therefore all "versions" of the docs were actually building `main` 😂
If you look closely at [the logs](https://github.com/nix-community/nixvim/actions/runs/15667598257/job/44133783630#step:4:66), you can see that the 25.05 job's "checkout" step actually checked out `main`.
Instead, we actually want to checkout the ref from the job's `matrix`.
Ironically, I noticed the issue because the [workflow run](https://github.com/nix-community/nixvim/actions/runs/15667598257) was _successful_, when I expected it to fail as the backports haven't been merged yet. Those backports will be queued shortly, so let's merge this after …
=> ci/docs: fix build ref

plugins/lsp/language-servers/_mk-lsp.nix, plugins/lsp/language-servers/hls.nix, plugins/lsp/language-servers/rust-analyzer.nix, tests/test-sources/plugins/lsp/_lsp.nix
> Maybe we should add some kinda "fallback" boolean-type option for lsp.servers.* options in a followup PR that controls whether the package is installed to --prefix or --suffix?
https://github.com/nix-community/nixvim/pull/3445#pullrequestreview-2908615597
Add a `packageFallback` option to allow overriding LSP versions from local PATH.
=> plugins/lsp: add packageFallback option

.github/workflows/website.yml
Follow up to #3466, this PR implements auto-generated version info for the build matrix and "other versions" list.
Tested on my fork: https://github.com/MattSturgeon/nixvim/actions/runs/15687456783
Fixes #3433
=> ci/docs: use `version-info.toml`

plugins/colorschemes/solarized-osaka.nix, plugins/default.nix, tests/test-sources/plugins/colorschemes/solazized-osaka.nix
Add support for the [solarized-osaka.nvim](https://github.com/craftzdog/solarized-osaka.nvim) colorscheme.
Closes #3446
=> colorschemes/solarized-osaka: init

.github/workflows/website.yml
I noticed that since merging #3481, both stable versions of the docs "think" they are 24.11.
I.e., both render the list like this:
For some context, the docs render the `availableVersions` list into a markdown list, and compare each entry's `baseHref` against the `baseHref` supplied to the docs. When building in CI, the top-level `baseHref` comes from the job matrix, while the `availableVersions` is passed in directly.
https://github.com/nix-community/nixvim/blob/7ff884527ecbb722e3b6b9f89025d1ee2065792b/docs/mdbook/default.nix#L457-L463
https://github.com/nix-community/nixvim/blob/7ff884527ecbb722e3b6b9f89025d1ee2065792b/.github/workflows/website.yml#L104-L105
---
For some reason, when updating `base-href` using `+=`, yq updates _all_ entries matching the LHS selection. This means that …
=> ci/docs: fix `base-href` in matrix

.github/workflows/website.yml, docs/mdbook/book.toml, docs/mdbook/custom.css, docs/mdbook/default.nix
This PR adds "channel status" to the "other docs" links, when that status is either "beta" or "deprecated". This matches the behaviour on [NixOS Search](https://search.nixos.org/packages).
> [!Caution]
> The changes to the `docs` directory will need backporting. Until then, the status will not be displayed in links back from the older docs versions.
>
> I'm unsure if this can be done automatically, or if there will be conflicts.
As the last CI-related version-info todo item, this closes #3431 :tada: 
---
The styles for the info/warning labels are based on those used by NixOS Search, although I didn't implement anything different for dark/light theme.
Frankly, I'm not sold on my UI design here. Maybe it'd be better to integrate the _status_ into the text of the line, e.g.:
- The [`main` …
=> docs: add status to beta/deprecated version links

lib/maintainers.nix, plugins/colorschemes/moonfly.nix, plugins/default.nix, tests/test-sources/plugins/colorschemes/moonfly.nix
Add support for the [moonfly](https://github.com/bluz71/vim-moonfly-colors) colorscheme.
This relies on https://github.com/NixOS/nixpkgs/pull/417405
Also, sorry to GaetanLepage with the presumption of them maintaining this.  I copied to from another colorscheme and didn't know what I am supposed fill for the maintainer(if I need to fill anything)
=> colorschemes/moonfly: init

plugins/by-name/mini-surround/default.nix, tests/test-sources/plugins/by-name/mini-surround/default.nix
This pull request introduces a new Neovim plugin module for the `mini.surround`, along with corresponding test cases.
=> plugins/mini-surround: init

plugins/by-name/mini-statusline/default.nix, tests/test-sources/plugins/by-name/mini-statusline/default.nix
This pull request introduces a new Neovim plugin module for the `mini.statusline`, along with corresponding test cases.
=> plugins/mini-statusline: init

plugins/by-name/mini-keymap/default.nix, tests/test-sources/plugins/by-name/mini-keymap/default.nix
This pull request introduces a new Neovim plugin module for the `mini.keymap`, along with corresponding test cases.
=> plugins/mini-keymap: init

plugins/by-name/mini-bufremove/default.nix, tests/test-sources/plugins/by-name/mini-bufremove/default.nix
This pull request introduces a new Neovim plugin module for the `mini.bufremove`, along with corresponding test cases.
=> plugins/mini-bufremove: init

plugins/by-name/mini-ai/default.nix, tests/test-sources/plugins/by-name/mini-ai/default.nix
This pull request introduces a new Neovim plugin module for the `mini.ai`, along with corresponding test cases.
Doing it for each `mini.nvim` module, so users can use them separately if they want to.
=> plugins/mini-ai: init

plugins/by-name/mini-icons/default.nix, tests/test-sources/plugins/by-name/mini-icons/default.nix
This pull request introduces a new Neovim plugin module for the `mini.icons`, along with corresponding test cases.
=> plugins/mini-icons: init

plugins/by-name/mini-colors/default.nix, tests/test-sources/plugins/by-name/mini-colors/default.nix
This pull request introduces a new Neovim plugin module for the `mini.colors`, along with corresponding test cases.
=> plugins/mini-colors: init

plugins/colorschemes/gruvbox-material.nix, plugins/default.nix, tests/test-sources/plugins/colorschemes/gruvbox-material.nix
Gruvbox-material is a colorscheme in pure lua: https://github.com/f4z3r/gruvbox-material.nvim. It is highly customizable and supports a wide variety of plugins.
=> Add gruvbox-material colorscheme

ci/efmls-configs.nix, docs/default.nix, generated/efmls-configs.nix, plugins/by-name/efmls-configs/default.nix, tests/test-sources/plugins/by-name/claude-code/default.nix, tests/test-sources/plugins/by-name/efmls-configs/default.nix, tests/test-sources/plugins/by-name/none-ls/default.nix, tests/test-sources/plugins/by-name/vimtex/default.nix
This pull request introduces several changes to improve configuration handling, simplify code, and remove platform-specific restrictions. The most notable updates include restructuring language tools in `ci/efmls-configs.nix`, simplifying expressions in `docs/default.nix`, and removing Darwin-specific exceptions in plugin configurations.
* [`ci/efmls-configs.nix`](diffhunk://#diff-b23aa4e05c041b2fa0219fdee605957fc8307cfadf5595de4416fab692885459L16-R43): Refactored the handling of language tools by grouping languages by lowercase names and merging their tools. This ensures canonical naming and avoids case-sensitive duplication. Also, merged linters and formatters across case variations for better consistency.
* [`docs/default.nix`](diffhunk://#diff-eb8d49802027f9ca035129d9b6dca2489d8de2643b …
=> treewide: re-enable darwin sandbox disablements

flake/dev/devshell.nix, flake/dev/diff-plugins.py
Prints the plugins added or removed when compared to a particular nixvim revision.
This is intended as a starting point for automatically generating the matrix announcements, as attempted in #2255 and #2593.
I may consider moving the python script into the `ci/` directory to make sparse-checkout easier if it ends up being used by CI workflows. Although, saying that the full checkout would be needed to compare its plugins to the other anyway...
A CI workflow can use this script by supplying `github.event.before`, which for `on: push` events comes from the [`push` webhook event payload](https://docs.github.com/en/webhooks/webhook-events-and-payloads#push). Alternatively we might use `github.event.pull_request.merge_commit_sha` or `github.event.pull_request.head.sha` from …
=> flake: add diff-plugins command

modules/dependencies.nix, plugins/by-name/telescope/extensions/default.nix, plugins/by-name/telescope/extensions/zf-native.nix
Add support for [telescope-zf-native.nvim](https://github.com/natecraddock/telescope-zf-native.nvim), providing native telescope bindings to zf for sorting results.
=> plugins/telescope-zf-native-nvim: init

.github/workflows/pr-merged.yml, flake/dev/diff-plugins.py
Adds a workflow that runs when a PR is merged. The plan is to use this to do things like sending the matrix announcement messages, however for now it is just printing things to the markdown workflow run "summary".
My plan is to let this run whenever a PR is closed and come back later to look at what was printed. I'm especially interested in how merge commits and base commits are calculated when the merge queue is used, and when multiple PRs are merged as one queue group.
I can't easily test queues, because they can only be enabled on _org_ repos, not on personal repos or forks.
I've tested as much as I can on my fork, here's an example run: https://github.com/MattSturgeon/nixvim/actions/runs/15928141828?pr=18
=> ci: add WIP pr-merged workflow

plugins/by-name/linediff/default.nix, tests/test-sources/plugins/by-name/linediff/default.nix
Add support for [linediff.vim](https://github.com/AndrewRadev/linediff.vim), a vim plugin to perform diffs on blocks of code.
Closes #3520
=> plugins/linediff: init

modules/top-level/output.nix
This PR works towards https://github.com/nix-community/nixvim/issues/3518
When not including `printInitPackage`, evaluation time and build time gets a small boost
I ran a small benchmark of changing some Nixvim config then building it, 5 times for each scenario. On my "dev" nixvim package (which includes the tweaks in the aforementioned PR) this improved the time from 12.97s to 12.30s (-5.16%) and my "prod" nixvim package (which is likely what most people use) it goes down from 33.91s to 33.06s (-2.5%)
=> top-level/output: add enablePrintInit option

plugins/colorschemes/gruvbox-material.nix, tests/test-sources/plugins/colorschemes/gruvbox-material.nix
The gruvbox-material plugin deprecated the `signs.highlight` option and introduced other options in its stead (see https://github.com/f4z3r/gruvbox-material.nvim/releases/tag/v1.7.0).
=> Update to gruvbox-material example configuration due to changes in plugin

plugins/by-name/codecompanion/default.nix
I found some missing adapters [here](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua) and an obsolete `opts` part, that doesn't exist [here](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/config.lua#L533-L543).
The maintainer should look at it. Maybe the differences are intentional.
=> update adapters and opts, cleanup prompt example

modules/files.nix
Following https://github.com/nix-community/nixvim/issues/2418#issuecomment-2413714276
https://vi.stackexchange.com/questions/26169/difference-between-adding-vim-after-ftplugin-vs-vim-ftplugin/26170#26170
=> Fix example for option `extraFiles` on file `ftplugin/nix.lua`

.github/workflows/tag-maintainers.yml, ci/tag-maintainers/extract-maintainers.nix, ci/tag-maintainers/extract-maintainers.py, flake/dev/generate-all-maintainers/generate-all-maintainers.py
- **ci: run treefmt**
- **ci/tag-maintainers: split nix into separate file**
- **ci/tag-maintainers: pass changed file to nix as json**
- **ci/tag-maintainers: minor cleanup**
Two issues I've spotted but not resolved:
The `hasSuffix` check assumes that the "changed file" has a `/default.nix` component on the end that is not present in the `maintainers` file key; which is usually true but isn't guaranteed. Maybe it'd be best to always import `default.nix` files explicitly? That way docs links would also correctly link to the actual file...
If the number of changed files gets too large, the _changed files_ JSON might exceed the shell arg length limit. It might be worth writing the changed files list to a file and passing that in instead.
=> ci/tag-maintainers: split nix into separate file + minor tweaks

flake/dev/devshell.nix, flake/dev/launch-test.sh, flake/dev/tests.nix, tests/default.nix, tests/main.nix
- **tests: take responsibility for flakecheck/buildbot split**
- **tests: use a single link-farm for flake-checks**
- **tests: use a nested attrset for buildbot**
This is some of the originally planned refactoring that was kept out of the initial switch to a dedicated `buildbot` flake output.
Not using the `checks` output means a few things.
For example, we are not restricted to the "flat" package hierarchy required by `packages` and `checks`, instead we can use a recursive hierarchy similar to `legacyPackages`.
Having a recursive hierarchy means we don't need all the "test groups" at the top-level.
Since buildbot (and `nix-eval-jobs`) doesn't need to eval the `checks` output, we can simplify the user-facing tests back to a single `tests` linkFarm. This change also simplifies the `tests` …
=> tests: refactor buildbot outputs

.github/workflows/tag-maintainers.yml
We can't distinguish between manual review requests and requests created by CI, so let's avoid removing any review requests.
So far there's been a few examples of PRs with no matching maintainers (or no touched plugin files) having review requests removed the next time the PR is updated.
=> ci/tag-maintainers: don't remove review requests

.github/workflows/tag-maintainers.yml, ci/tag-maintainers/manage-reviewers.py
Closes https://github.com/nix-community/nixvim/issues/3546
Move to separate script that looks at history of requests to determine who needs to be removed. We will not remove reviews from those who were manually requested.
Won't work until `extract-maintainers` is fixed, though. Tested in home-manager https://github.com/khaneliman/home-manager/pull/591 Was testing in my nixvim fork but realized the extraction of maintainers was broken in https://github.com/nix-community/nixvim/pull/3543
=> ci/tag-maintainers: refactor managing reviewers

lib/maintainers.nix, plugins/by-name/spider/default.nix, plugins/by-name/spider/deprecations.nix, tests/test-sources/plugins/by-name/spider/default.nix
Related tracking issue: https://github.com/nix-community/nixvim/issues/2638
I moved `skipInsignificantPunctuation` under settings since it is not a nixvim related option.
I kept the keymap option the same because i'm not sure if it should be removed or not.
A similar option existed for harpoon and was removed on migration, should the same happen here?
This is my first (substantial) pr to a major repo. Sorry for any stupid mistakes.
=> plugins/spider: migrate to mkNeovimPlugin

ci/tag-maintainers/manage-reviewers.py, flake/dev/default.nix
- **ci/tag-maintainers: run treefmt**
- **ci/buildbot: build treefmt checks**
This got missed when we added the `ci.buildbot` flake output. The treefmt flake-parts module adds its check to the `checks` output, but we also want it added to `ci.buildbot`.
This means we haven't been enforcing formatting since we split flakecheck and buildbot tests.
=> ci/buildbot: build treefmt checks

lib/maintainers.nix, plugins/by-name/no-neck-pain/default.nix, tests/test-sources/plugins/by-name/no-neck-pain/default.nix
Requesting to add one of my favourite Neovim plugins: No Neck Pain. It centers the buffer to the middle of the screen.
This is my first time contributing to Nixvim, so let me know if there's any conventions I've missed. I assume I will have to add myself as a maintainer?
=> plugins/no-neck-pain: init

.editorconfig
> When opening a file, EditorConfig plugins look for a file named .editorconfig (all lowercase) in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.
>
> -- https://editorconfig.org/#file-location
=> editorconfig: set root

plugins/by-name/comment/default.nix
case sensitive path name so that lz.n finds it on case sensitive file systems
Closes https://github.com/nix-community/nixvim/issues/3594
=> plugins/comment: fix lazy loading

LICENSE
including "the \<project\> contributors" or similar in the copyright notice is best practice, also updating the year is too obviously
=> license: various fixes 

plugins/colorschemes/gruvbox-material-nvim.nix, plugins/default.nix, plugins/deprecation.nix, tests/test-sources/plugins/colorschemes/gruvbox-material-nvim.nix
- **plugins/deprecation: reformat**
- **plugins/deprecation: allow renaming/removing different plugin scopes**
- **colorschemes/gruvbox-material: rename to gruvbox-material-nvim**
As discussed in https://github.com/nix-community/nixvim/pull/3495#issuecomment-3066706409, this is to allow adding a `colorschemes.gruvbox-material` that uses the non-lua plugin [`vimPlugins.gruvbox-material`](https://search.nixos.org/packages?channel=unstable&show=vimPlugins.gruvbox-material).
Included some cleanup and refactoring to enable deprecating colourschemes in `plugins/deprecation.nix`.
=> colorschemes/gruvbox-material: rename to gruvbox-material-nvim

lib/maintainers.nix
As per https://github.com/orgs/nix-community/discussions/1908#discussioncomment-13972992
> * nixvim
>   * `Bodleum` -> [api.github.com/user/60107449](https://api.github.com/user/60107449) -> `daniellaing`
>   * `janurskremer` -> [api.github.com/user/79042825](https://api.github.com/user/79042825) -> `jukremer`
=> maintainers: update out-of-date github usernames

plugins/by-name/telescope/default.nix
without this change, the docs just show `null` as the default for this option.
=> plugins/telescope: add defaultText for highlightTheme

plugins/by-name/copilot-chat/default.nix
it seems that gpt-4 is no longer supported
https://docs.github.com/en/copilot/reference/ai-models/supported-models
using gpt-4 throws 400 Bad Request errors
fixes nix-community#3623
=> fix(copilot-chat): fix default model to one supported

plugins/by-name/aider/default.nix, tests/test-sources/plugins/by-name/aider/default.nix
Adds `aider.nvim` plugin. Example is from their README, tests are of their default `M.config` and the example.
Resolves #3570
=> plugins/aider: init

ci/nvim-lspconfig/default.nix, modules/top-level/output.nix
This implements the change suggested in https://github.com/nix-community/nixvim/issues/3518
It skips the fixup phase on our nixvim deriviations which almost halves build times.
I've been running this setup myself for a week or so, and did not spot any issues related to it.
This could also be implemented as an overlay instead of overriding on each call.
=> treewide: Disable fixup phase for builds

tests/all-package-defaults.nix, tests/default.nix, tests/main.nix, tests/test-sources/plugins/by-name/none-ls/default.nix
Motivated by a future removal of the generated tests on non-`x86_64-linux` platforms, let's add a test that ensures all of our package dependencies correctly build on all platforms.
- **tests: move pkgsForTests definition to tests/default.nix**
- **tests: add all-package-defaults**
- **tests/none-ls: typo**
=> tests: add all-package-defaults

tests/all-package-defaults.nix, tests/default.nix
This was missed in #3665, let's see if it actually builds on all platforms currently...
=> ci: build all-packages-defaults on all platforms

tests/default.nix, tests/lsp-servers.nix, tests/test-sources/modules/dependencies.nix, tests/test-sources/plugins/by-name/cmp-tabnine/default.nix, tests/test-sources/plugins/by-name/dbee/default.nix, tests/test-sources/plugins/by-name/efmls-configs/default.nix, tests/test-sources/plugins/by-name/godot/default.nix, tests/test-sources/plugins/by-name/none-ls/default.nix, tests/test-sources/plugins/by-name/openscad/default.nix, tests/test-sources/plugins/by-name/papis/default.nix, tests/test-sources/plugins/by-name/telescope/media-files.nix, tests/test-sources/plugins/cmp/all-sources.nix
Similar to 939a4428334e880eec7608c452a01b8c8b499aae by @zowoq, but with #3666 we will be more confident only running these tests on a single platform; as outlined by #3238.
As part of reducing these test cases to a single platform, I've also gone through and removed the now-redundant disablements.
=> ci: only build "grouped" tests on x86_64-linux

flake/dev/package-tests.nix
As a temporary solution, we only include the `packages` output in the `ci.buildbot` output on x86_64-linux.
At some point, we should consider explicitly copying each package to `ci.buildbot`, and maybe omitting some.
Some packages may be better off being built on GHA, such as the docs.
cc @MattSturgeon (I cherry-picked your commit from #3647)
=> ci: only build packages on x86_64-linux

plugins/by-name/harpoon/default.nix
Lazy loading needs the correct name for finding the plugin in `opt`. With change to `harpoon2` as the default, we need to fix the `packPathName` to match.
=> plugins/harpoon: fix pack path name

modules/performance.nix, modules/top-level/plugins/byte-compile-plugins.nix, modules/top-level/plugins/default.nix
This option is a sister option to `standalonePlugins`in `combinePlugins`. It allows the user to skip some plugins from byte compilation.
This is a needed change because some plugins (I know of at least faster and conform) break when byte compiled. With this option users don't have to choose between having byte compilation, having broken functionality or not using certain plugins. It allows for a compromise where only the problematic plugins are skipped, meanwhile the rest is still compiled.
I've tested that adding`faster.nvim` to the exception list (either as a package or name) fixes https://github.com/nix-community/nixvim/issues/3659
Things of note:
1. This breaks all existing configurations that set `performance.byteCompileLua.plugins` to a boolean.
I could not figure out a way to …
=> modules/performance: add uncompiledPlugins option to plugin byte compilation

plugins/by-name/alpha/default.nix, plugins/by-name/barbar/default.nix, plugins/by-name/bufferline/default.nix, plugins/by-name/diffview/default.nix, plugins/by-name/fzf-lua/default.nix, plugins/by-name/lspsaga/deprecations.nix, plugins/by-name/neo-tree/default.nix, plugins/by-name/nvim-tree/default.nix, plugins/by-name/telescope/default.nix, plugins/by-name/trouble/default.nix
Prevent the `web-devicons` enablement when using the `mini-icons` module.
=> treewide: support `mini-icons.mockdevIcons`

lib/maintainers.nix, plugins/by-name/rhubarb/default.nix, tests/test-sources/plugins/by-name/rhubarb/default.nix
Rhubarb extends fugitive.vim with GitHub integration, allowing you to open GitHub files or URLs directly from Vim using `:GBrowse`.
=> rhubarb: init

plugins/by-name/colorful-winsep/default.nix, tests/test-sources/plugins/by-name/colorful-winsep/default.nix
[Upstream](https://github.com/nvim-zh/colorful-winsep.nvim) did a refactor of the codebase making our test and example out of date. This updates them according to the changes.
I should have caught this earlier but I stopped using the plugin due to it having a nasty bug. It got fixed a few weeks ago but I just found out about that now.
=> plugins/colorful-winsep: account for upstream changes

modules/lsp/servers/default.nix, modules/lsp/servers/server.nix, tests/test-sources/modules/lsp.nix
Added to `plugins.lsp` in #3450
We need parity in the new `lsp` module if we want to be able to convert `plugins.lsp` into a thin wrapper.
I've copied the `plugins.lsp` `package-fallback` test case over to the new lsp module's tests, so that we still have test coverage when that test is dropped.
=> modules/lsp: port `packageFallback` option from plugins.lsp

modules/lsp/keymaps.nix, modules/top-level/test.nix, tests/test-sources/modules/lsp.nix
- **modules/test: add `extraInputs` option**
- **tests/modules/lsp: test lsp keymaps**
- **modules/lsp: print keymaps table multiline**
- **modules/lsp: select relevant fields in keymaps table**
Follow up to #3737, this PR adds a test to assert the expected autoCmd is created for LSP keymaps. Follow-up commits then tweak the output to be more readable by printing a multiline table and omitting irrelevant fields.
My nvim knowledge is too weak to come up with a way to verify the lua code at runtime, which would be nice for catching syntax errors. The issue is the lua code only runs when the `LspAttach` autocmd event is triggered, and I don't know how to do that in our headless test environment. For now, I just set `test.runNvim = false`, but any ideas for a better solution would be great. …
=> modules/lsp: test lsp keymaps & cleanup lua table

plugins/by-name/marks/default.nix, plugins/by-name/marks/deprecations.nix, tests/test-sources/plugins/by-name/marks/default.nix
Intentionally not deprecating the "bookmarks" option because unless I'm mistaken it never worked.
The assertion for it requires names of the attrset to be integers, but names in Nix can only be strings so it always fails.
tracking: https://github.com/nix-community/nixvim/issues/2638
=> plugins/marks: migrate to mkNeovimPlugin

ci/generate.nix, ci/nvim-lspconfig/default.nix, ci/nvim-lspconfig/unsupported.nix, generated/unsupported-lspconfig-servers.json, plugins/lsp/language-servers/default.nix, tests/lsp-servers.nix
In #3733 we refactored `plugins.lsp` to use the new `lsp` module under the hood. This means `plugins.lsp` switched from using nvim-lspconfig's deprecated `require('lspconfig')` API to neovim's new API.
Unfortunately, not _all_ server configs have been migrated to the new API. We can detect this by reading files in the respective _new_ and _old_ directories. If a server config module exists in the old directory but not the new directory, then it only supports the old API. The reverse is also true for servers only in the new directory, but that's a separate issue we will solve in #3748.
A new update script will check which "old" files do not have an equivalent "new" file, then the plugins.lsp module will create a removal assertion for any servers that are listed in the generated file.
=> plugins.lsp: automatically remove unsupported servers

plugins/by-name/telescope/extensions/fzf-native.nix
=> plugins/telescope/extensions/fzf-native: remove old renamed warnings

plugins/by-name/ethersync/default.nix, tests/test-sources/plugins/by-name/ethersync/default.nix
Add [ethersync-nvim](https://github.com/ethersync/ethersync/tree/main/nvim-plugin), a neovim plugin for  [Ethersync](https://github.com/ethersync/ethersync)-compatible collaborative software.
Closes #3625
=> plugins/ethersync: init

tests/lsp-servers.nix
This is extracted from (unpushed) work on #3748
Currently none of the server packages we build are unfree, however if any unfree defaults are added then this test will fail.
When adding some defaults for the new servers added in #3748, at least one of them is unfree.
The two solutions are:
1. Filter out unfree packages
- Either set `enable = false` or `package = null`
2. Allow building unfree packages
- By setting `nixpkgs.config.allowUnfree = true`
For now, I've gone with option 1.
=> tests/lsp-servers: disable building unfree default packages

plugins/lsp/lsp-packages.nix, tests/all-package-defaults.nix, tests/lsp-servers.nix
26 new LSPs were added when we updated the update script in https://github.com/nix-community/nixvim/pull/3748
Add a package association for all the new LSPs I was able to find a package for.
This is a draft until #3748 and #3759 are merged.
=> plugins/lsp/lsp-packages: add defaults for new LSPs

plugins/by-name/rainbow-delimiters/default.nix, plugins/by-name/rainbow-delimiters/deprecations.nix, tests/test-sources/plugins/by-name/rainbow-delimiters/default.nix
tracking: https://github.com/nix-community/nixvim/issues/2638
Things of note:
I'm deprecating "default" for `""` as i think that was a hack for us not converting "" to proper lua.
Sadly i'm not sure how I can shove this deprecation into `deprecations.nix`
Keeping the old strategies option overall because I think it's nice to make users not write Lua for that.
Users can define both `strategies` and `settings.strategies` which leads to mkMerge errors. I think that's okay and is clear enough to the user.
=> plugins/rainbow-delimiters: migrate to mkNeovimPlugin

plugins/by-name/ts-context-commentstring/default.nix, plugins/by-name/ts-context-commentstring/deprecations.nix, tests/test-sources/plugins/by-name/ts-context-commentstring/default.nix
tracking: https://github.com/nix-community/nixvim/issues/2638
defaults: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/blob/1b212c2eee76d787bbea6aa5e92a2b534e7b4f8f/lua/ts_context_commentstring/config.lua#L48C1-L48C2
Keeping the 2 extraOptions because I find it weird that this plugin has some config in globals and some in the setup function. This abstracts this weirdness away from the user.
=> plugins/ts-context-commentstring: migrate to mkNeovimPlugin
