- nixvim.nix
If colorscheme is not set nixvim will not work.
This is because the default is null.
In this PR I have just added an extra check to see if colorscheme is null.
However we might want to change the type of colorscheme itself to only support strings and set the defualt to `""`.
Edit:
Here is the error I am getting, for reference.
```
error: cannot coerce null to a string
at /nix/store/95s39kpv3cg61qshwxd98lxvfr7hib4d-source/nixvim.nix:208:23:
207|         customRC = cfg.extraConfigVim + (optionalString (cfg.colorscheme != "") ''
208|           colorscheme ${cfg.colorscheme}
|                       ^
209|         '') + ''
(use '--show-trace' to show detailed location information)
```
> Check if colorscheme is set to null

- nixvim.nix
- plugins/colorschemes/nord.nix
- plugins/default.nix
This PR adds the nord colorscheme as a module with the [`nord-nvim`](https://github.com/shaunsingh/nord.nvim) package
> added nord colorscheme

- plugins/utils/nvim-tree.nix
Currently the options `plugins.nvim-tree.git.enable` expects null or a string.
However, this is not correct and results in an error when starting neovim, when nvim-tree is enabled.
This PR changes the option to expect a boolean.
> nvim-tree: git.enable expects a boolean

- plugins/completion/nvim-cmp/cmp-helpers.nix
- plugins/completion/nvim-cmp/default.nix
- plugins/completion/nvim-cmp/sources/default.nix
- plugins/default.nix
This pull request is a draft just to share my initial work on this.
As a user of nvim-cmp, I think it would be nice to have cmp as a module which this pull request aims to add.
If you have any inputs to this or any suggestions on how to improve it, please add a comment.
I will probably finish this over the next couple of days.
Config options completed:
> Adding nvim-cmp plugin

- plugins/default.nix
- plugins/null-ls/default.nix
- plugins/null-ls/helpers.nix
- plugins/null-ls/servers.nix
This PR adds the base work null-ls to work with nixvim.
I have made it easy to add new servers, so we can make new PRs for those.
Any improvements or suggestions are welcome.
> null-ls: init with prettier and flake8

- plugins/null-ls/servers.nix
This PR adds two new formatting servers to null-ls
> null-ls: added alejandro and nixfmt

- plugins/telescope/default.nix
- plugins/telescope/media-files.nix
Just sharing my initial work on telescope media_files extension.
The only problem with this is that the plugin does not exist in nixpkgs yes, so we can either wait for that or depend on https://github.com/m15a/nixpkgs-vim-extra-plugins
But I am marking it as draft until it is added in nixpkgs or we decide to depend on vim-extra-plugins.
A word of appreciation:
A nice thing about nixvim is that we can directly add dependencies such as `überzug` which makes it much easier for the user to configure and not have to manually add it to their list of packages.
Issue in nixpkgs:
NixOS/nixpkgs#182734
> telescope.media_files: init

- modules/output.nix
In NixOS 22.05, the runtimepath is set depending on the `configure.packages` argument to `makeNeovimConfig`. This argument has since been removed and the runtimepath is now set by an argument in the wrapper. To support 22.05 we check for its presence using `functionArgs` and set it appropriately.
Should fix #40
> Make sure the runtimepath is set in NixOS 22.05

- plugins/statuslines/lualine.nix
The original implementation has several flaws:
- Each section may have only one component. However, lualine supports multiple components in the same section. E.g. `lualine_b = {'branch', 'diff', 'diagnostics'},` in default settings.
- The output format is incorrect. It outputs `{ mode = 'filename', icons = ... }` while lualine expects something like `{ 'filename', file_status = true, ... }`.
- There are many extra settings lualine accepts other than the ones specified in the spec. Adding them to the nixvim managed config results in a type error.
The new implementation changes the accepted section type from `submodule` to `listOf (oneOf str submodule)`, generates the correct output, and adds a new `extraConfig` field for unknown upstream flags.
> lualine: fix components config

- plugins/completion/copilot.nix
- plugins/default.nix
Copilot-vim needs node 16.x or 17.x to work.
> Add new plugin: copilot

- plugins/completion/nvim-cmp/default.nix
- plugins/helpers.nix
My original goal was to try and fix the cmp issue in #52, but it did not help.
This pull request adds a helper function that will wrap a string (or more preferably lua code) in a `do ... end`.
It also uses this helper in nvim-cmp.
> New wrapDo helper and wrapping nvim-cmp in do ... end

- plugins/languages/treesitter.nix
This option is required if a user opts out nixGrammars because the plugin directory is located in the nix store and is read-only.
However, with this patch, not everything is working due to https://github.com/nvim-treesitter/nvim-treesitter/issues/3605. All tree-sitter plugins will be installed repeatedly.
> treesitter: allow specifying custom parser install dir  @PhotonQuantum

- plugins/utils/nvim-tree.nix
Adds new option to nvim-tree.
Also I am not sure what to do with old options. updateCwd should be changed to sync_root_with_cwd, but I don't think we should remove the old option, since it would break some configs.
> nvim-tree: added new option

- plugins/default.nix
- plugins/helpers.nix
- plugins/snippets/luasnip/default.nix
Also added support for paths in `toLuaObject`.
I am not sure how to know what the path of the runtime dir is, but if it is possible I think we should add an option that can include the path of the runtime dir in the paths array.
nonetheless, the plugin module works in my tests.
> luasnip: init plugin

- plugins/nvim-lsp/basic-servers.nix
`vue-language-server` is deprecated and `vls` should be used instead.
> vuels: using non deprecated version

- plugins/nvim-lsp/default.nix
onAttach function have bufnr as its passed argument just like the suggested configurations in [nvim-lspconfig docs](https://github.com/neovim/nvim-lspconfig#suggested-configuration)
> lsp: add bufnr to passed argument

- modules/output.nix
Adds options to alias `vi` and `vim` to `nvim`
> options: add viAlias and vimAlias

- plugins/colorschemes/tokyonight.nix
The global variables don't work for applying configuration, we need to switch to using the 'setup' function. This also aligns the default option values in tokyonight upstream.
> tokyonight: Fix configuration and align more with defaults

- README.md
- flake.nix
- wrappers/standalone.nix
The `build` function has be changed to the `makeNixvim` function. This also adds a full example of flake that allows to include nixvim.
> Wrappers: Extend and document the `makeNixvim` function

- plugins/default.nix
- plugins/plugin-defs.nix
- plugins/utils/magma-nvim.nix
[magma-nvim ](https://github.com/dccsillag/magma-nvim) allows you to execute python files as if they were Jupyter notebooks right from inside Neovim. I have added all global options as well, with documentation. I am using the [magama-nvim-goose](https://github.com/WhiteBlackGoose/magma-nvim-goose) fork until their upstream merges their [#69](https://github.com/dccsillag/magma-nvim/pull/69) which allows for external kernels. 
(unrelated, this is my first open source pull request, so am a little excited)
> add `magma-nvim` to plugins

- plugins/null-ls/servers.nix
As this is not an external command but a plugin it adds the gitsigns plugin if enabled.
> null-ls: Add gitsigns code action

- plugins/default.nix
- plugins/languages/treesitter-refactor.nix
- plugins/languages/treesitter.nix
As treesitter-refactor is a treesitter module we need a way to pass extra configuration options to the treesitter setup. This is done through a `moduleConfig` attrset. This set should not be used outside nixvim.
> treesitter: Add module for treesitter-refactor

- plugins/utils/nvim-tree.nix
In the implementation, the option `updateFocusedFile` was not written correctly:
`updateFocusedFile` --> `update_focused_file`
> nvim-tree: typo in option updateFocusedFile

- plugins/nvim-lsp/basic-servers.nix
- plugins/nvim-lsp/helpers.nix
Some of those LSP clients support configuration options.
This commit adds a way to pass configuration options to lsp, using two fields in the mkLsp function:
- extraOptions: allows to define Nix module options
- settings: Translate the config of those options to the settings structure expected by the LSP
> Add support for several LSP clients

- modules/keymaps.nix
- tests/flake.nix
This is a very basic edit to `modules/keymaps.nix` to adopt the Lua API way of setting keymaps, i.e. `vim.keymap.set`.
I do not know if it is necessary nor possible to make this depend on neovim version.
If so, here is what it would look like:
```
config =
let
mappingFunctionString = if NEOVIM_IS_NEWER_THAN_0_7
then
"vim.keymap.set(map.mode, map.key, map.action, map.config)"
else
"vim.api.nvim_set_keymap(map.mode, map.key, map.action, map.config)"
;
mappings =
(helpers.genMaps "" config.maps.normalVisualOp) ++
(helpers.genMaps "n" config.maps.normal) ++
(helpers.genMaps "i" config.maps.insert) ++
(helpers.genMaps "v" config.maps.visual) ++
(helpers.genMaps "x" config.maps.visualOnly) ++
(helpers.genMaps "s" config.maps.select) ++
(helpers.genMaps "t" config.maps.terminal) ++ …
```
> modules/keymaps: switch to lua API vim.keymap.set

- plugins/languages/treesitter.nix
Currently, the `nixGrammars = true` method for installing parsers is [broken](https://github.com/pta2002/nixvim/issues/102).
Fortunately, nixvim also supports the _legacy_ way of installing parsers.
The problem is that treesitter tries to put the parsers in its package directory which is not writable when using NixOS.
This can be overcome by setting a custom directory using the `parserInstallDir` option.
This PR proposes to change the default value for this option **when `nixGrammar` is set to `false`** to `$XDG_DATA_HOME/nvim/treesitter`.
Hence, when a NixOS user wants to use the legacy way of installing parsers, he only has to set `nixGrammar` to `false`.
> plugins/languages/treesitter: change default value for parserInstallDir

- plugins/languages/treesitter.nix
When setting a custom `parserInstallDir` in treesitter, the given path [has to be added to the vim runtimepath](https://github.com/nvim-treesitter/nvim-treesitter/issues/3605#issuecomment-1299954399).
Otherwise, the parsers are not getting detected by treesitter who is reinstalling them at each startup of neovim.
This was already done in the module, but **after** the `require('nvim-treesitter.configs').setup()` call.
But this needs to be **before**.
This PR adds the path to the vim runtimepath before calling the `treesitter` setup function.
> plugins/languages/treesitter: fixed parsers installation when not using nixGrammars

- flake.lock
This PR updates the flake's `nixpkgs` input.
Unfortunately it doesn't seem to solve the [treesitter parser bug](https://github.com/pta2002/nixvim/issues/102)...
> update flake nixpkgs input

- plugins/languages/treesitter.nix
The grammars in the tree-sitter package and nvim-treesitter package are not the same. The grammars in the nvim-treesitter package are directly taken from the grammars supported by the plugin, whereas tree-sitter grammars are hard-coded in nixpkgs.
This means that there are more tree-sitter grammars available from nvim-treesitter rather than tree-sitter.
> tree-sitter: Switch to using nvim-treesitter grammars

- plugins/utils/nvim-tree.nix
The `auto_close` option of `nvim-tree` was removed in upstream by [this commit](https://github.com/nvim-tree/nvim-tree.lua/commit/524758a207f9c5bf3888b446d9f93192a837b8a7).
The plugin author suggests to implement it using the following autocommand:
```vim
autocmd BufEnter * ++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif
```
This is what this PR does.
~~**WARNING:** This code uses the non-merged-yet `nixvim.autoCmd` module. Hence, [this other PR](https://github.com/pta2002/nixvim/pull/120) has to be merged before.~~
> plugins/utils/nvim-tree: change implementation of autoClose

- plugins/completion/nvim-cmp/default.nix
The option `auto_enable_sources` of the `plugins.nvim-cmp` module is lacking the type declaration.
> plugins/completion/nvim-cmp: add missing type of option "auto_enable_sources"

- plugins/utils/startify.nix
The nix option `customHeader` should map to the global `startify_custom_header` and not `startify_custom_headers` (extra 's' at the end)
> plugins/utils/startify: fix wrongly named option: startify_custom_header

- plugins/default.nix
- plugins/languages/rust.nix
- plugins/nvim-lsp/default.nix
rust-analyzer implements a number of extensions. The rust-tools plugins allows to use them in neovim.
This re-uses the configuration options of the rust-analyzer server.
> plugins/rust-tools: Add a plugins for LSP extensions for rust-analyzer

- plugins/default.nix
- plugins/helpers.nix
- plugins/nvim-lsp/nvim-lightbulb.nix
nvim-lightbulb is a plugin showing if code actions are available under the cursor.
> plugins: Add nvim-lightbulb

- plugins/nvim-lsp/basic-servers.nix
- plugins/nvim-lsp/helpers.nix
Those two options don't control the server settings, and trying to add them in a settings object can result in strange (and broken) behaviour.
Fixes #135
> nvim-lsp: Put LSP settings options in their own namespaces

- lib/helpers.nix
- plugins/git/gitsigns.nix
This adds a few helpers for enums to refactor gitsigns.
It changes all options to be nullable, significantly (by 80 lines) reducing the length of an init.lua that only enables gitsigns.
> Refactor gitsigns to use nullable options

- plugins/utils/nvim-tree.nix
Some nvim-tree options have been deprecated.
See: https://github.com/nvim-tree/nvim-tree.lua/wiki/Open-At-Startup#legacy-migration
This PR marks them as deprecated.
In the wiki, they suggest implementations that a user could put in his config to replicate these behaviors.
Maybe we could implement them and restore the corresponding options later.
This is not the goal of this PR.
> plugins/utils/nvim-tree: marked setup options as deprecated

- modules/autocmd.nix
This PR adds the `autoGroups` option.
Example:
```nix
programs.nixvim.autoGroups = {
my_augroup = {};
my_augroup1 = { clear = true; };
my_augroup2 = { clear = false; };
};
```
> modules: add autoGroups + refactoring

- plugins/utils/indent-blankline.nix
The `enable` option of the indent-blankline plugin was wrongly implemented which was causing a bug when building any nixvim configuration:
```
error: ‘mkIf’ called with a non-Boolean condition
```
The bug was introduced in https://github.com/pta2002/nixvim/commit/89bf2d660b6696b7548214e22f74d343397c9d4e.
> plugins/utils/indent-blankline: fix enable option

- modules/options.nix
By setting the options on `vim.opt` instead of `vim.o` we are able to use table values (dictionaries/lists) when specifying options.
> modules/options: use vim.opt instead of vim.o

- plugins/bufferlines/barbar.nix
The module for the barbar plugin was missing the configuration options.
This PR fixes https://github.com/pta2002/nixvim/issues/70.
> plugins: barbar: add configuration options

- plugins/nvim-lsp/basic-servers.nix
I think we changed this a while back, but this should be correct.
When looking at search.nixos.org for vls [link to search for vls](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=vls) and [link to search for vue-language-server](https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=vue-language-server), the homepage link is the same, but versions are different.
Looking at [npm for vls](https://www.npmjs.com/package/vls) we can see the version matches with the vls package.
> Fixed vuels dependency

- modules/autocmd.nix
The `callback` option in `nvim_create_autocmd()` can be either a string or a lua function.
The previous implementation of the `autoCmd` module did not support the latest.
This PR changes the type of this option from `str` to either `str` or `rawType`.
> modules/autocmd: autoCmd.callback: support raw value

- plugins/nvim-lsp/basic-servers.nix
The sumneko language server was renamed:
- The language server package: `pkgs.sumneko-lua-language-server` -> `pkgs.lua-language-server`:
https://github.com/NixOS/nixpkgs/pull/215057
- The server name in the nvim-lsp plugin: `sumneko_lua` -> `lua_ls`
https://github.com/neovim/nvim-lspconfig/pull/2439
> plugins/nvim-lsp: sumneko_lua was renamed to lua_ls (both nix package and nvim-lsp server name)

- plugins/completion/nvim-cmp/default.nix
- plugins/default.nix
- plugins/nvim-lsp/default.nix
As the [`nvim-cmp` documentation states](https://github.com/hrsh7th/nvim-cmp#recommended-configuration), the LSP servers need to be made aware of the lsp capabilities:
```lua
-- Set up lspconfig.
local capabilities = require('cmp_nvim_lsp').default_capabilities()
-- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
capabilities = capabilities
}
```
This PR automatically injects this lua code when the `cmp-nvim-lsp` plugin is enabled.
> nvim-lsp: added nvim-cmp completion capabilities

- plugins/languages/treesitter.nix
`:checkhealth` for `treesitter` complains that no compiler is available.
Hence, I added `pkgs.gcc` in the dependencies.
> plugins/languages/treesitter: add pkgs.gcc in extraPackages

- plugins/nvim-lsp/basic-servers.nix
Add the [`pylsp`](https://github.com/python-lsp/python-lsp-server)  for python.
> plugins/nvim-lsp: add the pylsp server

- lib/helpers.nix
- modules/keymaps.nix
Right now, it is not possible to bind a raw lua function to a key.
Well, it is possible by doing this:
```nix
maps.normal.x = ":lua my_lua_func()<cr>";
```
which is not very pleasant.
This PR adds a new field to the action submodule for mappings. The example above would become:
```nix
maps.normal.x.luaFunc = "my_lua_func";
```
> modules/keymaps: bind lua function calls

- plugins/completion/nvim-cmp/sources/cmp-tabnine.nix
- plugins/completion/nvim-cmp/sources/default.nix
This allows the user to provide options to the setup function of `cmp-tabnine`.
> plugins/completion/nvim-cmp: add extraOptions option for the cmp-tabnine plugin

- plugins/nvim-lsp/helpers.nix
This way, the user is not limited to options exposed in `lsp.servers.<server-name>.settings`.
> plugins/nvim-lsp: add an exraSettings option to each language server

- plugins/telescope/default.nix
Before:
```nix
maps.normal = {
"<leader>fg" = {
action = ":lua require('telescope.builtin').live_grep()<cr>";
silent = true;
};
"<C-p>" = {
action = ":lua require('telescope.builtin').git_files()<cr>";
silent = true;
};
};
```
After:
```nix
plugins.telescope  = {
keymapsSilent = true;
keymaps = {
"<leader>fg" = "live_grep";
"<C-p>" = "git_files";
};
};
```
> plugins/telescope: add keymaps and keymapsSilent options

- plugins/nvim-lsp/language-servers/default.nix
Added the most useful options for `lua_ls` and initialized the defaults as recommended by the [`nvim-lsp` documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#lua_ls).
> plugins/nvim-lsp: added options for lua_ls

- lib/helpers.nix
A bug was introduced in https://github.com/pta2002/nixvim/pull/178.
This PR fixes it.
> modules/keymaps: fix bug in keymaps generation

- plugins/languages/ledger.nix
The `enabled` option description was wrongly specified.
> plugins/ledger: correct enable option description

- plugins/nvim-lsp/trouble.nix
Just a minor typo which prevents the `signs` options to work.
> plugins/nvim-lsp/trouble: typo

- plugins/nvim-lsp/language-servers/default.nix
I forgot to set the settings generation function option which led the pylsp settings declared in `pylsp.nix` ignored.
> plugins/nvim-lsp/pylsp: fix bug in settings generation

- plugins/statuslines/lualine.nix
While refactoring I mis-defined the type of option `color` for the components.
`str or (attrsOf str)` --> `attrsOf str`
> plugins/statuslines/lualine: fix type of color option

- flake.lock
Update flake inputs.
plenary-nvim was added as a dependency to harpoon in nixpkgs (https://github.com/NixOS/nixpkgs/pull/218291).
> flake.nix: update inputs

- plugins/utils/floaterm.nix
Looks like the refactor broke things.
We should really have CI that at least tries to evaluate all plugins.
> plugins: floaterm: fix options

- plugins/nvim-lsp/helpers.nix
This is a proposal to implement the `plugins.lsp.servers.<name>.cmd` option.
This lets the user provide a custom command to run the language servers.
For some language servers, nixvim sets a default value for it. For others, it is left to `null`.
> plugins/nvim-lsp: Add a user option to set the cmd of each language server

- plugins/statuslines/lualine.nix
`nvim-web-devicons` is an optional dependency of `lualine` so I guess we can install it by default.
> plugins/lualine: add nvim-web-devicons to extraPlugins

- plugins/nvim-lsp/language-servers/default.nix
The lua language server package has been renamed [in nixpkgs](https://github.com/NixOS/nixpkgs/pull/215057) and thus also [in nixvim](https://github.com/pta2002/nixvim/pull/169).
However, the users following a stable version of nixpkgs should be using the old name.
Now, nixvim should be robust to both stable/unstable state of nixpkgs.
> plugins/nvim-lsp: add a fallback for the lua LS package

- lib/option-warnings.nix
As it was left as a TODO, I implemented (very naively) the `mkRemovedOption`.
> lib/option-warnings: add mkRemovedOption

- lib/helpers.nix
At the moment, toLuaObject ignores empty objects, leading to some settings like `neorg`'s modules not working
> helpers: fix toLuaObject ignoring empty objects

- flake.nix
- tests/checks.nix
- tests/plugins/default.nix
- tests/plugins/tokyonight.nix
The tests can be executed using `nix flake check`, they check that modules can be built, and they execute in neovim without any errors.
This commit only implements tests for tokyonight-nvim upstream defaults
> tests: Implement a way to test nixvim

- plugins/bufferlines/bufferline.nix
Changes `error_dagnostic` to `error_diagnostic` for bufferline.nvim, to prevent Bufferline from not recognizing the option of `error_dagnostic`.
> plugins/bufferline: fix typo in 'error_diagnostic'

- plugins/utils/nvim-autopairs.nix
I went through the [nvim-autopairs](https://github.com/windwp/nvim-autopairs) plugin and cleaned the module:
- new options
- increased use of helpers for more concise code
- removed deprecated options
> plugins/nvim-autopairs: refactor + update options

- plugins/bufferlines/bufferline.nix
- plugins/telescope/default.nix
Removed useless manual definitions of `extraOptions` and replaced them with `helpers.extraOptionsOptions`.
> plugins/{telescope,bufferline}: make use of helpers.extraOptionsOptions

- plugins/languages/vimtex.nix
Change `extraConfig` default from `null` to `{}` to fix this plugin in the case where no options are set.
> plugins/vimtex: fix error when user does not set any extraConfig option

- README.md
- flake.nix
- lib/check.nix
- lib/default.nix
- templates/simple/README.md
- templates/simple/config/bufferline.nix
- templates/simple/config/default.nix
- templates/simple/flake.nix
- tests/checks.nix
I have added a flake template, which I think can be beneficial for new Nixvim users and users who do not yet use standalone.
I have also exposed some of the lib in the flake. This allows the template to use the check function defined in lib.
Another benefit of exposing lib is that it might be more intuitive to use the helpers this way, compared to the current one where you need to access `config.nixvim.helpers`, instead you can use `inputs.nixvim.lib.helpers`.
> Added flake template

- README.md
Since the options set could be treated as options for a module, it should be wrapped with config to work, when using makeNixvimWithModule.
> Added caveat section to options

- lib/helpers.nix
We often need to create nested options.
Most of the time, it is done like this:
```nix
parentOption = {
subOption1 = ...;
subOption2 = ...;
...
};
```
This has two problems:
1. It is not possible to provide a description for the parent option.
2. When the user sets non of the child options, the parent option has value `{}` [which is ambiguous to translate to lua in this case](https://github.com/pta2002/nixvim/pull/213).
The alternative is using the following syntax:
```nix
parentOption = helpers.mkNullOrOption
(types.submodule {
options = {
subOption1 = ...;
subOption2= ...;
...
};
})
DESCRIPTION
;
```
This fixes both of the previous issues. However, it is more verbose and annoying to write.
Hence, this PR introduces a wrapper that leads to the following syntax:
```nix
parentOption = …
```
> helpers: add mkCompositeOption

- lib/helpers.nix
> helpers: typo (mkCompositeOptions -> mkCompositeOption)

- plugins/languages/markdown-preview.nix
https://github.com/pta2002/nixvim/pull/213 introduced a regression in the markdown-preview plugin.
Now fixed.
> plugins/markdown-preview: fixed regressions introduced in #213

- plugins/completion/nvim-cmp/default.nix
Adds missing `helpers.` in a `helpers.mkRaw` utilisation.
> pugins/nvim-cmp: fix the completion.autocomplete option

- lib/helpers.nix
Add a way to declare several keymaps without having to duplicate the defaults for each one of them:
```nix
maps = config.nixvim.helpers.mkMaps { silent = true; } {
normal = {
...
};
visual = {
...
};
};
```
Or for a single mode:
```nix
maps.normal = config.nixvim.helpers.mkModeMaps { silent = true; } {
...
};
```
> helpers: add mkMaps and mkModeMaps

- lib/helpers.nix
> lib/helpers: fix typo in mkModeMaps

- plugins/utils/todo-comments.nix
- tests/plugins/todo-comments.nix
The `highlight.pattern` and `search.pattern` options were not exported as pure lua code.
Added `mkRaw` to fix this.
> plugins/todo-comments: fix missing mkRaw for pattern options

- plugins/completion/nvim-cmp/default.nix
- tests/plugins/nvim-cmp.nix
Refactoring of the `nvim-cmp` plugin.
It now doesn't suffer from the [new `toLuaObject` behavior](https://github.com/pta2002/nixvim/pull/213).
I also made sure that all of the options were correct regarding upstream.
> plugins/nvim-cmp: refactor + tests

- plugins/completion/nvim-cmp/default.nix
- tests/plugins/nvim-cmp.nix
Add an enum type for the `snippet.expand` option which sets the underlying option with the relevant function.
Before:
```nix
snippet.expand = ''
function(args)
require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
end
'';
```
After:
```nix
snippet.expand = "luasnip";
```
> plugins/nvim-cmp: add enum type for option snippet.expand

- plugins/utils/nvim-tree.nix
- tests/plugins/nvim-tree.nix
Refactoring of the `nvim-tree` plugin.
It now doesn't suffer from the [new `toLuaObject` behavior](https://github.com/pta2002/nixvim/pull/213).
I also made sure that all of the options were correct regarding upstream.
Note: I had to remove a `mkRenamedOption` statement because it does not work with the new way we do nested options (i.e. sub options are now options in a `submodule` type).
> plugins/nvim-tree: fix regressions introduced in #213 + tests

- plugins/nvim-lsp/language-servers/pylsp.nix
There was an error happening when the user was not setting any plugin option.
> plugins/nvim-lsp: fix pylsp error when no plugins set

- plugins/nvim-lsp/helpers.nix
Add the `filetypes` and `autostart` options for each language server.
Fixes https://github.com/pta2002/nixvim/issues/96.
> plugins/nvim-lsp: add filetypes and autostart options for LS

- plugins/nvim-lsp/default.nix
- tests/plugins/nvim-lsp.nix
Add keymaps options for nvim-lsp:
```nix
plugins.lsp = {
enable = true;
keymaps = {
silent = true;
diagnostic = {
"<leader>k" = "goto_prev";
"<leader>j" = "goto_next";
};
lspBuf = {
"gd" = "definition";
"gD" = "references";
"gt" = "type_definition";
"gi" = "implementation";
"K" = "hover";
};
};
};
```
> plugins/nvim-lsp: keymaps options

- lib/helpers.nix
Fix bug introduced in https://github.com/pta2002/nixvim/pull/256.
> helpers/keymap: fix noremap bug

- lib/check.nix
- tests/checks.nix
Some plugins don't really play nicely with being launched in a headless sandboxed environment. This adds the pseudo option 'tests.dontRun' to avoid running those tests
> tests: Allow to skip running neovim

- plugins/_sources/generated.json
- plugins/_sources/generated.nix
- plugins/default.nix
- plugins/nvfetcher.toml
- plugins/plugin-defs.nix
- plugins/utils/nvim-osc52.nix
- tests/plugins/nvim-osc52.nix
nvim-osc52 is a plugin that allows to copy from neovim using OSC52 control sequences (works through SSH for example)
> plugins/nvim-osc52: init + tests

- plugins/_sources/generated.json
- plugins/_sources/generated.nix
- plugins/default.nix
- plugins/nvfetcher.toml
- plugins/plugin-defs.nix
- plugins/utils/inc-rename.nix
- tests/plugins/inc-rename.nix
inc-rename is a plugin that allows to show incrementally an LSP renaming (like %s)
> plugins/inc-rename: init + tests

- lib/check.nix
- tests/plugins/netman.nix
Netman tries to call 'docker -v' and it hangs neovim if the docker command is not found. This adds the docker binary to the derivation running checks
> tests: Fix netman tests by including docker

- plugins/pluginmanagers/packer.nix
When not providing any lua_rocks plugin, avoid to write `use_rocks {}` in the config.
> plugins/packer: improve lua generation

- modules/output.nix
- plugins/snippets/luasnip/default.nix
The lua dependency is required to perform transforms (luasnip can fallback to a simpler algorithm if it's absent). This requires us to expose the `extraLuaPackages` option of makeNeovimConfig.
> plugin/luasnip: Add jsregexp lua dependency

- lib/helpers.nix
- plugins/languages/ledger.nix
- plugins/utils/emmet.nix
- plugins/utils/goyo.nix
- plugins/utils/startify.nix
Avoid to repeat `plugin_name_` in front of every `global` when declaring a `mkPlugin` plugin.
> helpers: add globalPrefix to mkPlugin

- plugins/utils/notify.nix
`nvim-notify` uses `background_colour` rather than `background_color`
See: https://github.com/rcarriga/nvim-notify/blob/50d037041ada0895aeba4c0215cde6d11b7729c4/doc/nvim-notify.txt#L23
This PR additionally renames the configuration option to the correct camelCase name, and uses `optionWarnings.mkRenamedOption` to both warn about this change and map the old option to the new one.
> plugins/notify: Fix typo for background_colour option

- flake.nix
- tests/lib-tests.nix
This PR adds basic testing for Nix expressions using nixpkgs' `lib.runTests`,
as well as some unit tests for `helpers.toLuaObject`.
They'll run automatically with `nix flake check`, but can also be ran via `nix
repl` to reduce the number of checks to run:
```console
Welcome to Nix 2.14.1. Type :? for help.
Loading installable 'git+file:///home/rummik/Source/pta2002/nixvim#'...
Added 10 variables.
nix-repl> :b checks.${builtins.currentSystem}.lib-tests
This derivation produced the following outputs:
out -> /nix/store/9p6svspj4hbn1jd1xnb5vbd3y7qqc690-lib-tests-success
nix-repl>
```
It also pretty-prints the output from `lib.runTests`:
```console
nix-repl> :b checks.${builtins.currentSystem}.lib-tests
error: builder for '/nix/store/hn8m43v0ixanyzd8cf497wyx90vdjpsh-lib-tests-failure.drv' …
```
> tests/lib: Add basic unit tests for `helpers.toLuaObject`

- plugins/default.nix
- plugins/languages/openscad.nix
- tests/test-sources/plugins/languages/openscad.nix
The plugin was recently introduced in nixpkgs, so it required to update the nixpkgs input.
> plugins/openscad: init + tests

- wrappers/standalone.nix
Assertions (which are used for deprecated and renamed options) where properly handled when using nixvim with home-manager and NixOS but not in standalone mode.
This is now fixed by applying the same logic as in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/62d5fcc12cca592022133807ff01e642c9e15a91/nixos/modules/system/activation/top-level.nix#L122-L126).
> wrappers/standalone: handle assertions

- plugins/languages/nvim-jdtls.nix
- tests/test-sources/plugins/languages/nvim-jdtls.nix
Add the `data` and `configuration` options which act on the **default value** of the `cmd` option.
This is inspired from [what `nvim-lsp` does](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jdtls)
> plugins/nvim-jdtls: add data and configuration options

- lib/helpers.nix
- tests/lib-tests.nix
This PR makes `toLuaObject` ignore empty attrs like it was the case before #213.
The current version of `toLuaObject` (which translates empty attrs to an empty table in lua (`{}`) prevents us from using conventional nested options.
Although the _composite option_ (i.e. an option which has `submodule` as type, provided for example by `helpers.mkCompositeOption`) is working fine in most cases, it is preventing us from properly exposing renamed/removed/deprecated options.
This PR does not introduce any regression apart from eventual users which were setting options to empty attribute sets.
This PR also introduces an `{ __empty = ...; }` value to explicitly set an empty table. (Also available thanks to `helpers.emptyTable`.
> helpers/lib: toLuaObject ignore empty attrs

- lib/helpers.nix
- modules/keymaps.nix
This is an opinionated refactoring of the keymaps module:
1. Moved the `genMaps` function from `lib/helpers.nix` to `modules/keymaps.nix` as the letter is the only place where this function is used.
2. Factorized a bit the `genMaps` code
3. Renamed option `description` -> `desc`. No one will notice I hope as it was broken until know anyway.
> modules/keymaps: refactoring + fix bug in keymaps generation

- plugins/bufferlines/bufferline.nix
This is to not forget about removing deprecation warnings after a while.
> plugins/bufferline: add TODO to remove warnings

- plugins/completion/nvim-cmp/default.nix
Since this means cmp is active in prompts, e.g. telescope
https://www.reddit.com/r/neovim/comments/vtw4vl/disable_nvimcmp_in_telescopes_buffer/
> nvim-cmp: do not pass in enabled = true

- modules/lua-loader.nix
- tests/test-sources/modules/lua-loader.nix
Add support for the experimental lua-loader introduced in neovim 0.9.
Documentation: https://neovim.io/doc/user/lua.html#lua-loader
> modules/lua-loader: add support for the new lua-loader

- plugins/default.nix
- plugins/utils/conjure.nix
- tests/test-sources/plugins/utils/conjure.nix
Creates an option for [Conjure](https://github.com/Olical/conjure). No options,
because there really isn't anything to configure.
> plugins/conjure: init plugin

- modules/output.nix
- wrappers/_shared.nix
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/modules/files.nix
- wrappers/modules/output.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
This is an attempt at solving #49 . It separates options into file-level (ie options that add to a file), and global options (that controls how nvim is instantiated). All plugins are file-level options. Using file-level options at the top-level adds to `init.lua`, but those options can also be used in `files.*` to create other files in the config. For example, one could do:
```nix
{
programs.nixvim = {
files."ftdetect/myft.lua".autoCmd = [
{
event = [ "BufRead" "BufNewFile" ];
pattern = [ "*.myft" ];
command = "set ft=myft";
}
];
};
}
```
By using options in `ftplugin/ft.lua` files, it allows setting options only in for some filetypes. Furthermore, it supports generating both lua and vim files (and guess which one to use depending on the extension of the file).
Notes:
- It should be …
> Enable creation of other config files than init.lua

- modules/output.nix
- tests/test-sources/modules/extra-files.nix
- wrappers/_shared.nix
- wrappers/modules/files.nix
To enable some features (like adding tree-sitter queries) we need to add files to specific directories in the runtime path (queries/lang/file.scm for tree-sitter queries for example).
This commit adds support for specifying such files. You must be careful to not have any collisions between `files` and `extraFiles`.
> modules/output: Allow to specify text to add as extra files

- plugins/languages/treesitter/treesitter.nix
- tests/test-sources/plugins/languages/treesitter/treesitter.nix
This can look something like this:
> plugins/treesitter: Add injections to highlight lua in nixvim options

- modules/clipboard.nix
- tests/test-sources/modules/clipboard.nix
Add a new module that lets the user easily manage the clipboard.
It allows to add a provider package.
> modules/clipboard: add new module to manage clipboard option and provider

- flake.lock
- plugins/filetrees/nvim-tree.nix
- tests/test-sources/plugins/filetrees/nvim-tree.nix
- Update flake inputs
- Deprecate `view.mappings` option in `nvim-tree` because it has been deprecated upstream
> flake: update inputs + fix nvim-tree option change

- plugins/statuslines/lualine.nix
- tests/test-sources/plugins/statuslines/lualine.nix
`theme` can be a lua table, for customization;
`disabledFiletypes` contain lists of filetypes.
> lualine: allow attrs in theme and fix disabledFiletypes

- plugins/nvim-lsp/helpers.nix
- tests/test-sources/plugins/nvim-lsp/nvim-lsp.nix
Some `nvim-lsp` language servers need to be configured with options that are not explicitly wrapped by nixvim.
This commit adds an `extraOptions` to each language server.
Example:
```nix
plugins.nvim-lsp.servers = {
ruff-lsp = {
enable = true;
extraOptions = {
init_options.settings.args = [
"--config=/path/to/config.toml"
];
};
};
};
```
> plugins/nvim-lsp: add extraOptions for nvim-lsp language servers

- plugins/nvim-lsp/helpers.nix
The warning introduced in #351 was getting triggered even if the user was not defining the option in question.
This commit fixes that by removing the default value for that option.
> plugins/nvim-lsp: fix extraSettings option warning

- flake.lock
- plugins/nvim-lsp/language-servers/default.nix
- tests/test-sources/plugins/nvim-lsp/nvim-lsp.nix
Add the the [sourcekit language server](https://github.com/apple/sourcekit-lsp), for Swift and C/C++/Objective-C.
The package currently fails to build, so let's wait before merging.
> plugins/nvim-lsp: add sourcekit language server

- .envrc
For direnv users, just using `direnv allow` will not always work
We could also consider removing the use flake function from `.envrc` since it should be built into direnv.
> envrc will now create .direnv folder

- .github/workflows/check.yml
- flake.nix
- lib/default.nix
- templates/_wrapper/README.md
- templates/_wrapper/simple/.gitignore
- templates/_wrapper/simple/flake.nix
- templates/simple/flake.nix
- tests/default.nix
- tests/test-derivation.nix
lib/default.nix was missing the check file, which is now moved to test-derivation.nix.
Here it was important to export both functions as the config for mkTestDerivation does not support imports from a configuration.
the check workflow also got a test for the template so we can keep it up to date, when making some breaking changes.
> Added test for template and fixed check export for lib

- plugins/bufferlines/barbar.nix
- plugins/bufferlines/bufferline.nix
- plugins/filetrees/nvim-tree.nix
- plugins/lsp/language-servers/default.nix
- plugins/utils/floaterm.nix
- plugins/utils/magma-nvim.nix
- plugins/utils/mark-radar.nix
- plugins/utils/notify.nix
Those warnings in various plugins are 1 month old or older.
I now suggest that we remove them.
> misc: remove deprecated/renamed options warnings

- modules/keymaps.nix
- tests/test-sources/plugins/utils/which-key.nix
With these changes I can create bindings without a action attribute when which-key is enabled.
This is helpful for nested bindings.
Example: 
\<leader>ff = something
\<leader>fw = something_else
In which key when you press \<leader> it'll show "\<leader>f" as `+prefix`. We can now do
```nix
"<leader>f" = {
desc = " Files";
};
```
so it shows the desc in which-key instead of just `+prefix`
> feat: register mapping with no actions in which-key when enabled

- plugins/lsp/helpers.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Fixes the `package` option for the language servers:
```
error: A definition for option `extraPackages."[definition 1-entry 1]"' is not of type `package'. Definition values:
- In `/nix/store/llszkbhrsv3sscnhw8mn00m3id363wd8-source/plugins/lsp/language-servers': null
```
Also add a test to avoid any regression.
> nvim-lsp: fix package option (null) + test

- plugins/lsp/helpers.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
By default, for each enabled `plugins.lsp.servers`, `nixvim` installs the corresponding language server thanks to `nixpkgs`.
For some reason, a user might want to disable this behavior and limit the role of `nixvim` to wrap the `nvim-lspconfig` options without interfering more.
Hence, this PR adds a `installLanguageServer` option (defaulting to `true`) that, if disabled sets the `cmd` option default value to `null` and ignores the `package` option value.
Please note that the `package` option does not accept `null` anymore.
> nvim-lsp: add installLanguageServer option for servers

- plugins/bufferlines/barbar.nix
The config was requiring 'bufferline' instead of 'barbar', as pointed out in #380. This fixes that.
> barbar.nvim: fix 'requires' (fixes #380)

- .github/workflows/check.yml
So, this _should_ get cachix working, at least for commits from maintainers. Since it requires a secret, I think that PRs won't commit tests to the cache unless they're made from maintainers, but any push should still keep the test cache up-to-date, so only the thing that changed will get rebuilt anyway.
Let's see how this goes :)
> Initialize cachix

- plugins/lsp/helpers.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Maps the `nvim-lspconfig` common `root_dir` option for each language server.
> plugins/nvim-lsp: add rootDir option for language servers

- plugins/completion/nvim-cmp/default.nix
- tests/test-sources/plugins/completion/nvim-cmp.nix
- The `source[n].max_item_count` option has been removed upstream. Hence, remove the corresponding `maxItemCount` option
- Add missing `performance` options: `asyncBudget` and `maxViewEntries`
> plugins/nvim-cmp: update options

- plugins/completion/copilot.nix
Fixes #394
nodejs-16 is EOL and has been marked as insecure in nixpkgs. This change makes copilot use nodejs-18 which is the current LTS
I've used and tested this change all week-end and found no issues
> plugins/completion/copilot: use nodejs-18_x

- plugins/default.nix
- plugins/languages/treesitter/treesitter-context.nix
- plugins/languages/treesitter/treesitter.nix
- plugins/languages/treesitter/ts-autotag.nix
- tests/test-sources/plugins/languages/treesitter/ts-autotag.nix
Add support for the  [nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag) plugin.
Fixes #402.
> plugins/ts-autotag: init + test

- plugins/languages/treesitter/treesitter.nix
- tests/test-sources/plugins/languages/treesitter/treesitter.nix
Add a wrapper option to the `vim.treesitter.language.register` option.
This allows to map specific parsers to one or more filetypes.
I don't know if the name I chose (`parsersToFiletypes`) is a good idea.
I thought about `register`, but it is more adpated to a function name (an action) rather than this option which allows to do several _registrations_ (i.e. an attrs).
> plugins/treesitter: add parsersToFiletypes option

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add [`java`](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#java_language_server) language server.
This throws an error in my config:
```shell
Error executing vim.schedule lua callback: ...rapped-0.9.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:122: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
[C]: in function 'ipairs'
...rapped-0.9.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:122: in function 'handler'
...eovim-unwrapped-0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1057: in function ''
vim/_editor.lua: in funvtion <vim/_editor.lua:0>
```
But the language server still works and I don't think it's related to the PR.
> plugins/nvim-lsp: add java language server

- plugins/completion/nvim-cmp/sources/crates-nvim.nix
- plugins/completion/nvim-cmp/sources/default.nix
The `crates-nvim` which provides the `crates` source for `nvim-cmp` requires its `setup` function to be called.
Fixes #425
> plugins/nvim-cmp: fix crates-nvim source plugin

- plugins/default.nix
- plugins/utils/cursorline.nix
- tests/test-sources/plugins/utils/cursorline.nix
Add support for the [`nvim-cursorline`](https://github.com/yamatsum/nvim-cursorline) plugin.
Fixes #422.
> plugins/cursorline: init + test

- plugins/lsp/language-servers/ccls.nix
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/ccls.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for the [`ccls`](https://github.com/MaskRay/ccls) language server.
Note: This LS is configured through the `init_options` key, not the `settings` one.
Fixes #429.
> plugins/lsp: add ccls language server

- plugins/ui/noice.nix
I think `views` option was accidentally omitted from actually being plumbed into the config.
> plugins/ui: plumb `views` through

- plugins/ui/noice.nix
- tests/test-sources/plugins/ui/noice.nix
Judging by [the routes example in noice readme](https://github.com/folke/noice.nvim#-routes) and by [`route.lua` using `list_extend` on it](https://github.com/folke/noice.nvim/blob/a3318600bc1eba2cca84e879048c1ab8d4a0262d/lua/noice/config/routes.lua#L13), it seems to me that `plugins.noice.routes` is supposed to be a list.
> plugins/noice: turn routes into a list

- flake.nix
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nixd.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for the [`nixd`](https://github.com/nix-community/nixd) language server.
~~It required propagating the flake's inputs to the module and the doc.~~
A [PR](https://github.com/NixOS/nixpkgs/pull/236675) has been made to package `nixd` directly in nixpkgs.
--> Let's wait for it to be merged so that we do not have to propagate the flake's inputs.
> plugins/lsp: add nixd language server

- plugins/utils/toggleterm.nix
- tests/test-sources/plugins/utils/toggleterm.nix
- Fix a bug of documentation formatting in the `highlights` option
- Fix the implementation of the `openMapping` key binding.
Thank you @MarkusLohmayer for the catch !
> plugins/toggleterm: fix openMapping and documentation bug

- plugins/colorschemes/kanagawa.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/kanagawa.nix
Add support for the [kanagawa](https://github.com/rebelot/kanagawa.nvim) colorscheme.
Fixes https://github.com/pta2002/nixvim/discussions/443.
> colorscheme/kanagawa: init + test

- plugins/default.nix
- plugins/utils/coverage.nix
- tests/test-sources/plugins/utils/coverage.nix
Add support for the [nvim-coverage](https://github.com/andythigpen/nvim-coverage) plugin.
Note: A [PR](https://github.com/NixOS/nixpkgs/pull/238544) is currently open on nixpkgs. The present PR will be kept as a draft [until the latter makes its way in `nixos-unstable`](https://nixpk.gs/pr-tracker.html?pr=238544).
> plugins/coverage: init + test

- lib/helpers.nix
- plugins/completion/nvim-cmp/default.nix
- plugins/languages/clangd-extensions.nix
- plugins/languages/rust.nix
- plugins/languages/sniprun.nix
- plugins/null-ls/default.nix
- plugins/utils/nvim-ufo.nix
- plugins/utils/oil.nix
- plugins/utils/toggleterm.nix
- plugins/utils/which-key.nix
Introduced a new helper function called `mkBorder` that simplifies the process of creating border options for plugins that use `nvim_open_win`.
> helpers.defaultNullOpts: add mkBorder

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for the [cmake language server](https://github.com/regen100/cmake-language-server).
Fixes #450.
> plugins/nvim-lsp: add cmake LS

- flake.lock
- tests/test-sources/plugins/lsp/nixd.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
`nixd` is now working properly on darwin.
> plugins/nvim-lsp: enable now working nixd tests on darwin 

- flake.lock
- plugins/utils/neorg.nix
- tests/test-sources/plugins/utils/neorg.nix
Some changes on the `neorg` plugin:
- Some refactors that have no impact on the end user
- Add testing
- Add support for plugin/neorg module [`neorg-telescope`](https://github.com/nvim-neorg/neorg-telescope)
> plugins/neorg: refactor + test + neorg-telescope

- plugins/null-ls/servers.nix
- tests/test-sources/plugins/null-ls.nix
Added support for following new sources in null-ls:
Diagnostics:
- vale
- vulture
- alex
- protolint
- hadolint
- luacheck
- mypy
- pylint
Formatting:
- isort
- jq
- markdownlint
- protolint
- rustfmt
- sqlfluff
> plugins/null-ls: added support for multiple new sources

- plugins/dap/dap-go.nix
- plugins/dap/dap-python.nix
- plugins/dap/dap-ui.nix
- plugins/dap/dap-virtual-text.nix
- plugins/dap/dapHelpers.nix
- plugins/dap/default.nix
- plugins/default.nix
- tests/test-sources/plugins/dap/dap-go.nix
- tests/test-sources/plugins/dap/dap-python.nix
- tests/test-sources/plugins/dap/dap-ui.nix
- tests/test-sources/plugins/dap/dap-virtual-text.nix
- tests/test-sources/plugins/dap/nvim-dap.nix
Added support for [nvim-dap](https://github.com/mfussenegger/nvim-dap) and the following extensions:
- [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui/)
- [nvim-dap-virtual-text](https://github.com/theHamsta/nvim-dap-virtual-text/)
- [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python/)
- [nvim-dap-go](https://github.com/leoluz/nvim-dap-go/)
> plugins/dap: init + extensions + tests

- flake.lock
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for the [csharp-ls](https://github.com/razzmatazz/csharp-language-server) language server.
~~We have to wait for https://github.com/NixOS/nixpkgs/pull/241185 to make its way to `nixos-unstable`.
Status: https://nixpk.gs/pr-tracker.html?pr=241185~~
> plugins/nvim-lsp: add csharp-ls language server

- plugins/colorschemes/oxocarbon.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/oxocarbon.nix
Added support for the oxocarbon-nvim colorscheme.
Homepage: https://github.com/nyoom-engineering/oxocarbon.nvim
I have tested and formatted my code.
> plugins/colorschemes/oxocarbon: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
adds config for enabling the Elm language server
> plugins/nvim-lsp: add elm-language-server

- plugins/colorschemes/catppuccin.nix
- tests/test-sources/plugins/colorschemes/catppuccin.nix
The `colorOverrides` had the wrong type (`attrsOf str` instead of `attrsOf (attrsOf str)`).
I also added a test for non-regression.
Fixes #478
> colorschemes/catpuccin: fix type for option colorOverrides

- plugins/lsp/language-servers/default.nix
`plugins​.lsp​.servers​.lua-ls​.settings​.workspace​.library` is supposed to be an array of library paths.
> plugins/nvim-lsp: fix lua_ls workspace library attribute type

- plugins/telescope/default.nix
- tests/test-sources/plugins/telescope/default.nix
Allow more flexibility in keymaps declared in `telescope`.
Also adds a test case for the `telescope` plugin.
> plugins/telescope: allow key mappings to be attrs

- lib/helpers.nix
- modules/highlights.nix
Many plugins expose options to define highlight groups.
In this case, we can now use the new `highlightType` which represents an `attrs` that will be later provided to `nvim_set_hl`.
> helpers: add highlightType and defaultNullOpts.mkHighlight

- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/svelte.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
- tests/test-sources/plugins/lsp/svelte.nix
Add support for the [svelte language server](https://github.com/sveltejs/language-tools/tree/master/packages/language-server).
Fixes #497 
@rupurt, if you have the possibility to test it on your setup, it would be great !
> plugins/lsp: add svelte language server

- wrappers/nixos.nix
When using nixvim through the NixOS module, it seems that the config is not properly loaded.
This is not surprising as nixvim places the config in `/etc/nvim/sysinit.lua` which is not supported (https://github.com/neovim/neovim/issues/22595).
Hence, setting `wrapRc` to `true` is a working solution to overcome this situation.
Fixes https://github.com/nix-community/nixvim/issues/79 and https://github.com/nix-community/nixvim/issues/508
> wrappers/nixos: set wrapRc to true

- plugins/lsp/lspsaga.nix
- tests/test-sources/plugins/lsp/lspsaga.nix
Since https://github.com/NixOS/nixpkgs/pull/247916, the `vimPlugins.lspsaga-nvim` is now fetching https://github.com/nvimdev/lspsaga.nvim.
The previously supported plugin is now unmaintained and this new one seems to be the most used version currently.
Hence, this PR changes the options of `plugins.lspsaga` accordingly.
I have taken care of marking all the removed options as such.
An explicit warning will provided to relevant users.
> plugins/lspsaga: change backend plugin

- wrappers/nixos.nix
Backport the fix shipped by https://github.com/nix-community/nixvim/pull/515 to the `nixos-23.05` branch.
> [backport] wrappers/nixos: set wrapRc to true

- plugins/dap/dap-go.nix
- plugins/dap/dap-python.nix
- plugins/dap/dap-ui.nix
- plugins/dap/dap-virtual-text.nix
- plugins/dap/default.nix
This pull request fixes issues with `nvim-dap` and extensions that add custom configurations/adapters to `nvim-dap`. All extensions now load after `nvim-dap` is initialized to prevent user-defined settings from overriding the configurations added by them.
> plugins/dap: ensure extensions load after the main plugin

- lib/helpers.nix
- plugins/completion/nvim-cmp/default.nix
- plugins/filetrees/nvim-tree.nix
- tests/test-sources/plugins/completion/nvim-cmp.nix
This plugin has been written a while ago and this PR cleans its implementation.
No breaking changes have been introduced.
The `sources` option takes only a list of sources and refuse the before-permitted list of list values.
This had no real sense of existing.
Related: #494
> plugins/nvim-cmp: refactoring

- .github/workflows/check.yml
- CONTRIBUTING.md
We are now relying on the [nix-community cachix](https://app.cachix.org/cache/nix-community).
> misc: change cachix namespace to nix-community

- plugins/filetrees/neo-tree.nix
The `plugins.neo-tree.filesystem.filteredItems` is creating the respective option in the neovim config incorrectly. it should be `filtered_items` instead of `filteredItems`. This PR fixes that.
> plugins/neo-tree: fix incorrect option - filtered_items

- .github/workflows/update.yml
Implements https://github.com/DeterminateSystems/update-flake-lock#with-a-personal-authentication-token.
> workflow/update-flake-action: add GH_TOKEN to bypass GH limitation and directly run tests

- lib/helpers.nix
This allows the type to be rendered as `raw lua code` instead of `submodule` in the documentation.
> lib: Use mkOptionType for `rawType`

- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/nixd.nix
If the user explicitly sets `plugins.lsp.servers.nixd.settings.formatting.command = "nixpkgs-fmt"`, then `pkgs.nixpkgs-fmt` will be automatically added to `extraPackages`.
Context: #573
> plugins/nixd: automatically add `nixpkgs-fmt` if needed

- docs/default.nix
This makes the script generated by `pkgs.writeShellScript` terminate documentation build on error
> docs: terminate build on shell-script error

- plugins/colorschemes/dracula.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/dracula.nix
PR to add nixvim option for the [dracula-vim colorscheme](https://draculatheme.com/vim)
> colorschemes/dracula: add plugin + test

- wrappers/hm.nix
- wrappers/modules/output.nix
- wrappers/nixos.nix
This PR adds `defaultEditor` option from home-manager's `neovim` module
> feat(options): add `defaultEditor` option

- wrappers/hm.nix
- wrappers/nixos.nix
Currently, the HM module (and probably the NixOS one too) fails with:
```
error:
… while calling the 'head' builtin
at /nix/store/6s86padm2iikrwhlq8nwfv0lw9d1sbvq-source/lib/attrsets.nix:820:11:
819|         || pred here (elemAt values 1) (head values) then
820|           head values
|           ^
821|         else
… while evaluating the attribute 'value'
at /nix/store/6s86padm2iikrwhlq8nwfv0lw9d1sbvq-source/lib/modules.nix:800:9:
799|     in warnDeprecation opt //
800|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
|         ^
801|         inherit (res.defsFinal') highestPrio;
(stack trace truncated; use '--show-trace' to show the full trace)
error: The option `home-manager.users.gaetan.defaultEditor' does not exist. Definition values: …
```
> misc: fix defaultEditor option for HM and NixOS modules

- plugins/ui/noice.nix
This PR fixes a typo in noice (`sigature` -> `signature`)
> plugins/ui/noice: fix typo

- modules/autocmd.nix
Currently, the `autoCmd` declarations provide a `description` attribute, but this is wrongly named.
The correct attribute name is `desc`.
-> Rename the option to `desc` to match the name of the underlying `nvim_create_autocmd`.
Fixes #610
> modules/autocmd: rename autoCmd.*.description to desc

- plugins/lsp/language-servers/default.nix
hls just crashed everytime i tried to use it, because it's missing the `--lsp` flag to work correctly.
> plugins/lsp/hls: add missing --lsp cmd flag

- modules/autocmd.nix
#611 has introduced a flawed deprecation notice.
This PR fixes that by using an assertion instead.
> modules/autocmd: better handling of 'desc' option rename

- lib/helpers.nix
- lib/keymap-helpers.nix
- modules/keymaps.nix
- plugins/languages/typst/typst-vim.nix
- plugins/utils/vim-bbye.nix
- tests/test-sources/modules/keymaps.nix
Move some useful declarations/functions from `modules/keymaps.nix` to `lib/keymap-helpers.nix`.
Like so, a plugin could use them to define some keymap-related options.
> modules/keymaps: factor out helper functions for use in plugins

- plugins/filetrees/nvim-tree.nix
- tests/test-sources/plugins/filetrees/nvim-tree.nix
nvim-tree has [deprecated the `hide_root_folder` option](https://github.com/nvim-tree/nvim-tree.lua/pull/2431); it cannot be set anymore.
Also adds missing option to specify a boolean for `rootFolderLabel`. Setting it to `false` will do the same thing as what `hideRootFolder` used to do.
> nvim-tree: removes deprecated 'hideRootFolder' option

- CONTRIBUTING.md
- plugins/colorschemes/gruvbox.nix
- plugins/completion/coq.nix
- plugins/git/gitmessenger.nix
- plugins/git/gitsigns.nix
- plugins/languages/clangd-extensions.nix
- plugins/languages/treesitter/treesitter-refactor.nix
- plugins/lsp/fidget.nix
- plugins/snippets/luasnip/default.nix
- plugins/telescope/file-browser.nix
- plugins/telescope/fzf-native.nix
- plugins/telescope/fzy-native.nix
- plugins/telescope/media-files.nix
- plugins/utils/comment-nvim.nix
- plugins/utils/easyescape.nix
- plugins/utils/hardtime.nix
- plugins/utils/presence-nvim.nix
- plugins/utils/tmux-navigator.nix
- plugins/utils/todo-comments.nix
- plugins/utils/undotree.nix
- plugins/utils/vim-matchup.nix
- wrappers/hm.nix
- wrappers/nixos.nix
noticed some grammatical discrepancies throughout the repo and decided to fix them :)
> docs: fix grammar, spelling, and text for `enable` options

- lib/helpers.nix
- plugins/filetrees/neo-tree.nix
- plugins/pluginmanagers/packer.nix
- plugins/statuslines/lualine.nix
- plugins/utils/oil.nix
- tests/lib-tests.nix
so that neovim (treesitter) highlight groups can start with "@".
this may break existing configs which use "@" for key-less table entries.
i'm open to other solutions or a different prefix name :)
closes #627
> fix(helpers): use "__unkeyed" prefix instead of "@" in `toLuaObject`

- plugins/colorschemes/melange.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/melange.nix
Implement [melange](https://github.com/savq/melange-nvim) colorscheme for neovim. It's important to notice that to use the light variant the `set background=light` is needed. So the change between light and dark variant will be automatically if your terminal sets the `background` neovim option automatically.
> [Colorscheme] Melange support

- lib/keymap-helpers.nix
- modules/keymaps.nix
- remove possibility to add a str mapping to the `keymap` option
- remove possibility to add a keymap without an action
> modules/keymaps: fix option

- modules/keymaps.nix
We do not have to bother to set `options` to `"{}"` as if the attribute is missing, `nil` will be used.
> module/keymaps: no need to set options = {}

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
* Add fsautocomplete from the unstable channel as a language server.
* Add test enabling fsautocomplete.
```
Checking style in 316 files using 6 threads.
Congratulations! Your code complies with the Alejandra style.
⭐ If Alejandra is useful to you, please add your star to the repository.
Thank you! https://github.com/kamadorueda/alejandra
```
```
Please, use the new `keymaps` option which works as follows:
keymaps = [
{
key = "<C-m>";
action = ":!make<CR>";
}
{
mode = "n";
key = "<leader>p";
action = "require('my-plugin').do_stuff";
lua = true;
options = {
silent = true;
desc = "My plugin does stuff";
};
}
];
trace: warning: The `maps` option will be deprecated in the near future.
Please, use the new `keymaps` option which works as follows:
keymaps = [
{
key = "<C-m>";
action = …
```
> fsautocomplete: init

- plugins/utils/harpoon.nix
At the moment if your config doesn't specify `enableTelescope` in the harpoon options you get the following:
Harpoon config:
```
harpoon = {
enable = true;
tmuxAutocloseWindows = true;
keymaps = {
addFile = "<leader>ha";
toggleQuickMenu = "<leader>ht";
navNext = "<leader>hn";
navPrev = "<leader>hp";
};
};
```
Error:
```bash
error:
… while evaluating a branch condition
at /nix/store/4smdp3v5a9bcg1hpdhl2hs70rq385ykq-source/lib/lists.nix:57:9:
56|       fold' = n:
57|         if n == len
|         ^
58|         then nul
… while calling the 'length' builtin
at /nix/store/4smdp3v5a9bcg1hpdhl2hs70rq385ykq-source/lib/lists.nix:55:13:
54|     let
55|       len = length list;
|             ^
56|       fold' = n:
(stack trace truncated; use '--show-trace' to show the full trace)
error:
Failed …
```
> fix: harpoon telescope integration

- plugins/default.nix
- plugins/none-ls/default.nix
- plugins/none-ls/helpers.nix
- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
`null-ls` was archived [some time ago](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621) and [`none-ls`](https://github.com/nvimtools/none-ls.nvim) is a fork and a drop-in replacement.
`none-ls` is packaged but not merged onto unstable yet (https://nixpk.gs/pr-tracker.html?pr=258774), so I am marking this as a draft.
This pr just replaces the default package with `none-ls`. I don't think this requires any deprecations or warnings because it doesn't make any breaking changes, plus the package is still configurable. From the `none-ls` readme:
```
Only the repo name is changed for compatibility concerns.
All the API and future changes will keep in place as-is.
```
FWIW, `LazyVim` has also migrated to `none-ls`: https://github.com/LazyVim/LazyVim/pull/1517
> plugins/null-ls: migrate `null-ls` to `none-ls`

- README.md
- templates/simple/config/default.nix
- templates/simple/flake.nix
- wrappers/standalone.nix
> standalone: Allow to pass extraSpecialArgs

- plugins/colorschemes/catppuccin.nix
- tests/test-sources/plugins/colorschemes/catppuccin.nix
This PR adds support for `no_underline` option of catppuccin colorscheme.
> plugins/catppuccin: add `disableUnderline` option

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
* Adds the fantomas formatter for F#, which is used by fsautocomplete and vim-Ionide.
> fantomas: init

- tests/test-sources/plugins/none-ls.nix
`fantomas` is not available on darwin, so disable the corresponding test.
> plugins/none-ls: disable fantomas test for darwin

- plugins/telescope/undo.nix
As was pointed out in this PR: [plugins/telescope.undo](https://github.com/nix-community/nixvim/pull/654). The style I used for the undo telescope extension plugin was the older style in the code base. I'd rather not add more "tech-debt" to this project :sweat:. 
So I decided to do a quick refactor of that plugin into the 'newer' style I have written other plugins with :).
Thanks
> plugins/telescope.undo: refactor

- flake.nix
This adds an overlay containing both makeNixvim functions. This simplifies usage of the functions, as well as enabling you to use your own preinstantiated package set, instead of the one from this flake.
> flake: add overlay as an alternative to legacyPackages

- plugins/utils/harpoon.nix
fix keybinding where the action was being called at the time of creation of the keybind instead of when the keybind was triggered
> plugins/harpoon: fix busted keybind

- flake.nix
With this change `helpers` can be imported using `{pkgs, lib, helpers, ...}` instead of requiring to `import` it.
> fix: Enable `helpers` to be passed as an argument in nixvim

- plugins/utils/todo-comments.nix
- tests/test-sources/plugins/utils/todo-comments.nix
This re-uses the keymap options defined in the keymaps module to allow to define the options of todo-comments key mappings.
Fixes #598
> plugins/todo-comments: Allow to pass keymap options

- README.md
- flake.nix
- modules/doc.nix
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
Install man pages when installing nixvim. Depends on #686
> docs: Install man pages

- plugins/colorschemes/catppuccin.nix
- tests/test-sources/plugins/colorschemes/catppuccin.nix
This PR updates catppuccin integrations and sorts them to alphabetical order
> plugins/catppuccin!: update integrations

- plugins/default.nix
- plugins/languages/lean.nix
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/languages/lean.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
- add `plugins.lsp.servers.lean` ([leanls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#leanls))
- add `plugins.lean` ([lean.nvim](https://github.com/Julian/lean.nvim))
> Add support for the Lean language

- plugins/dap/dap-go.nix
- tests/test-sources/plugins/dap/dap-go.nix
We are missing the `build_flags` config option, https://github.com/leoluz/nvim-dap-go#configuring
> plugins/dap-go: add buildFlags option

- plugins/lsp/language-servers/efmls-configs.nix
This adds a few missing tools, and adds the following behaviours: 
- Warning when selecting a tool nixvim is not able to install (it is either too new and was not added, or not packaged in nixpkgs)
- Allow to override tool packages (this is usefull for example for `mdformat` that can have plugins added to it)
> plugins/efmls-configs: Improve tool installation

- tests/fetch-tests.nix
- tests/test-sources/plugins/lsp/efmls-configs.nix
This requires to pass the efmls-configs file to the derivation helpers, if we try to import it from the test file directly it fails.
We then look into the types to find the available languages & corresponding tools, to enable them all.
We then filter out the broken tools or the unpackaged tools, in order to detect more easily the introduction of future tools.
> tests: Install all efmls-configs tools

- plugins/lsp/language-servers/efmls-configs.nix
- tests/test-sources/plugins/lsp/efmls-configs.nix
We provide one option for each linter/formatter of `efmls-configs` that is packaged in `nixpkgs`.
Unfortunately, the (in)compatibility of those packages and the user's system (`x86-darwin`, `aarch64-linux`...) is not checked.
This patch aims at disabling this option for incompatible packages.
> plugins/lsp/efmls-configs: respect tool packages availability

- plugins/filetrees/neo-tree.nix
Currently, using e.g. `filesystem.window.mappings.ga = "git_add_file"` results in an invalid configuration which contains two layers of mappings:
```
347   │     ["filesystem"] = {
348   │         ["window"] = {
349   │             ["mappings"] = { ["mappings"] = { ["ga"] = "git_add_file" } },
350   │         },
```
This PR fixes that by correctly removing the mappings layer in the `processWindowMappings` function
> fix(neo-tree): per-source window mappings had two table layers called "mappings"

- plugins/filetrees/neo-tree.nix
In current code, `filesystem.window.mappings`, when set, became `filesystem.window.mappings.mappings`.
`document_symbol` can also receive its own custom mappings.
> neo-tree: add window.mappings to document_symbol

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
* Enable ktlint as a none-ls formatter
* Enable ktlint as a none-ls diagnostics tool
* Add tests for both cases
> ktlint: enable formatter and diagnostics

- plugins/lsp/helpers.nix
I feel like this was over-engineered.
And it is unused as well.
> plugins/lsp: remove unused generic extraPackages behaviour

- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/rust-analyzer.nix
- tests/test-sources/example-configurations/issues.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
`rust_analyzer` relies on both `cargo` and `rustc`.
This patch adds the `installCargo` and `installRustc` options which can have 3 values:
- `null` (default): does not install the package but show a warning.
- `false`: explicitly disables installing the packages.
- `true`: explicitly enables installing the packages (the user might then eventually use the `cargoPackage`/`rustcPackage` option).
Fixes #674
> plugins/lsp: enable auto-installing rustc and cargo

- plugins/default.nix
- plugins/languages/treesitter/treesitter-context.nix
- plugins/languages/treesitter/treesitter-textobjects.nix
- tests/test-sources/plugins/languages/treesitter/treesitter-textobjects.nix
Add support for [treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects).
Fixes #722.
> plugins/treesitter-textobjects: init

- plugins/languages/rust.nix
Nixvim uses a common function for the on attach function of lsp, __lspOnAttach. With the current implementation the function was not taken into account if no server options were present, this fixes this issue.
> plugin/rust-tools: Correctly take into account on_attach

- wrappers/standalone.nix
Patching the derivation forces a rebuild of neovim, which is undesirable
> wrapper: Use symlink join to install man pages for standalone

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for [emmet-ls](https://github.com/aca/emmet-ls).
> plugins/lsp: add emmet_ls language server

- plugins/languages/treesitter/ts-context-commentstring.nix
This TS module has changed the way it should be initialized.
With this patch, we follow their latest setup guidelines.
Fixes #748
> plugins/ts-context-commentstring: use new setup-based init

- lib/helpers.nix
- plugins/none-ls/default.nix
- tests/test-sources/plugins/none-ls.nix
This PR adds an option in `none-ls` to configure the use of `lsp-format` with it.
I also changed the behavior of `mkRaw` to ensure that `mkRaw ""` gives `null` instead of `""`.
Fixes #755
> plugins/none-ls: add enableLspFormat option

- .github/workflows/build_documentation.yml
- .github/workflows/check.yml
cachix-action v13 has just been released. We can now use it instead of following the master branch.
> ci: use cachix-action@v13

- lib/keymap-helpers.nix
- modules/keymaps.nix
- tests/test-sources/modules/keymaps.nix
The `maps` option has been marked as deprecated in favor of `keymaps` in #605 (Sept. 26).
It is now time to finally get rid of it.
> modules/keymaps: deprecate maps option

- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/modules/output.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
This patch creates a `nixvim-print-init` binary which shows the content of the generated `init.lua` configuration file.
> wrappers: add nixvim-print-init package

- plugins/utils/mini.nix
If you use the example, nvim will throw an error that surrounds does not exist. `surround` is also used in the test.
> fix: typo in mini module example

- flake.nix
- tests/extra-args.nix
- wrappers/standalone.nix
This commit fixes the usage of `extraSpecialArgs` for standalone nixvim installations and adds a test to ensure this.
Fixes #779
> standalone: Fix extraSpecialArgs

- plugins/statuslines/lualine.nix
From lualine documentation the icons can be configure more than just an string 
https://github.com/nvim-lualine/lualine.nvim#general-component-options
example 
```lua
{'branch', icon = {'', align='right', color={fg='green'}}}
```
Currently is defined as string which cover for most of the cases but if you want to set a color or more is not possible. I think that adding support for raw type makes more extensible.
I think also setting an object is possible but I lack the knowledge to do so, with this I was able to extend my configuration as I needed.
Let me know what do you think.
Kind regards, thanks for maintaining the project.
> Support more options for icon in lualine

- plugins/utils/which-key.nix
- tests/test-sources/plugins/utils/which-key.nix
I've only just recently started trying to migrate my NeoVim configuration to NixVim. What I'm doing is basically copying LazyVim's configuration since that's what I was using before. however, I've found that the `registrations` option for which-key in NixVim only supports the str type, but the str type can only bind labels for a shortcut key, not a group name for a shortcut key prefix. After looking at the source code I found that it is implemented like this
https://github.com/nix-community/nixvim/blob/c1cbb0012685b69fc6391f93d279975032b37dcf/plugins/utils/which-key.nix#L205-L213
So I think it probably just needs a change in the type restriction for the `registrations`.
I don't know much about writing Nix modules at the moment, so I'm not sure if a type definition like this is in line …
> plugins/which-key: add key group support for registrations 

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/nvim-lsp.nix
Add support for the [gleam language server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#gleam).
Fixes #807
> plugins/lsp: add gleam language server

- plugins/bufferlines/barbar.nix
- plugins/bufferlines/bufferline.nix
- plugins/dap/dap-ui.nix
- plugins/filetrees/nvim-tree.nix
- plugins/languages/markdown-preview.nix
- plugins/languages/rust.nix
- plugins/languages/sniprun.nix
- plugins/lsp/fidget.nix
- plugins/lsp/language-servers/pylsp.nix
- plugins/lsp/trouble.nix
- plugins/statuslines/lualine.nix
- plugins/ui/noice.nix
- plugins/utils/todo-comments.nix
Some overall cleaning of the code base.
Mostly removing useless uses of `mkCompositeOptions`.
Otherwise, changes are only "esthetic".
> plugins: remove mkCompositeOptions from implementation

- plugins/utils/wilder.nix
- tests/test-sources/plugins/utils/wilder.nix
The field in the nixvim config is called `render`, although in wilder it's called `renderer`. This PR fixes that issue
> Fix renderer in wildmenu

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add the [graphql](https://github.com/graphql/graphiql/tree/main/packages/graphql-language-service-server) language server.
Fixes #813
> plugins/lsp: add graphql language server

- plugins/languages/lint.nix
I think that this line stayed commented by mistake...
> plugins/lint: uncomment autoCmd config line

- plugins/default.nix
- plugins/languages/debugprint.nix
- tests/test-sources/plugins/languages/debugprint.nix
Add support for the [debugprint.nvim](https://github.com/andrewferrier/debugprint.nvim) plugin.
Fixes #763
> plugins/debugprint: init

- plugins/languages/debugprint.nix
- tests/test-sources/plugins/languages/debugprint.nix
Add missing `createCommands` option.
Follows: https://github.com/nix-community/nixvim/pull/821
> feat(plugins/languages/debugprint): add missing `createCommands` option

- plugins/lsp/language-servers/pylsp.nix
I have this specified in my config: 
```nix
pylsp_mypy = {
enabled = true;
overrides = ["--python-executable" (helpers.mkRaw "py_path") true];
};
extraConfigLuaPre = ''
local venv_path = os.getenv('VIRTUAL_ENV') or os.getenv("CONDA_PREFIX")
local py_path = nil
if venv_path ~= nil then
py_path = venv_path .. "/bin/python3"
else
py_path = vim.g.python3_host_prog
end
'';
```
since most people wouldn't have globally installed python packages(and that won't even work in nix), mypy will never find the required packages and not work. so I have some lua code to look if currently in a python virtual environment. if yes then use python executable from that environment else just use vim's python. This would have all the dependencies inside the project available to it. Then I can simply provide this …
> change type of pylsp_mypy.overrides

- lib/helpers.nix
- plugins/filetrees/nvim-tree.nix
- plugins/languages/treesitter/rainbow-delimiters.nix
- plugins/languages/treesitter/treesitter.nix
- plugins/lsp/conform-nvim.nix
- plugins/none-ls/default.nix
- plugins/utils/neorg.nix
- plugins/utils/notify.nix
- tests/test-sources/plugins/lsp/conform-nvim.nix
- tests/test-sources/plugins/utils/notify.nix
Add those two new options which properly wrap the values from `vim.log.levels` and `vim.diagnostic.severity`.
> helpers/options: add defaultNullOpts.mkLogLevel and defaultNullOpts.mkSeverity

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Add more options for linters and formatters when using go.
* Add revive
* Add staticcheck
* Add goimports
* Add golines
Have added corresponding tests for all the packages.
> plugins/none-ls: add go linters and formatters

- plugins/utils/illuminate.nix
This confuses the documentation, as mentioned in the function definition.
> plugin/illuminate: Avoid using mkAttrsOf with submodules

- plugins/lsp/fidget.nix
- tests/test-sources/plugins/lsp/fidget.nix
fidget.nvim [has been rewritten](https://github.com/j-hui/fidget.nvim/pull/143).
Hence, the options have changed significantly.
This PR updates our module to fit the upstream options.
> plugins/fidget: adapt to latest rewrite of the plugin

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Hi there,
I propose to add the [marksman language server for Markdown](https://github.com/artempyanykh/marksman).
Best,
Markus
> plugins/lsp: add marksman language server

- lib/helpers.nix
- plugins/languages/clangd-extensions.nix
- plugins/lsp/fidget.nix
- plugins/utils/auto-save.nix
- plugins/utils/nvim-autopairs.nix
This makes it such that defaultNullOpts.mkStr never represents a lua string, easing documenting where a string is a lua string vs lua code.
> helpers: Add mkLua,mkLuaFn (defaultNullOpts or not)

- .github/workflows/check.yml
As right now, the CI runs on my self-hosted runner, it is using the remote builders configured on this system.
This only slows down the build.
> ci/check: prevent CI from using remote builders

- lib/helpers.nix
This allows to display `lua function string` and `lua code string` in the documentation for related options.
> helpers: Add types for lua function & lua code

- lib/helpers.nix
- plugins/colorschemes/ayu.nix
- plugins/dap/dap-python.nix
- plugins/dap/dapHelpers.nix
- plugins/filetrees/neo-tree.nix
- plugins/languages/lint.nix
- plugins/languages/treesitter/treesitter-textobjects.nix
- plugins/lsp/fidget.nix
- plugins/telescope/undo.nix
- plugins/utils/better-escape.nix
- plugins/utils/mkdnflow.nix
- plugins/utils/toggleterm.nix
- plugins/utils/wilder.nix
Those types needed the following code in apply:
if builtins.isString value
then mkRaw value
else value
This commit avoids this boilerplate, and clarifies that the `str` is lua code in the documentation.
> helpers: Add option helpers for types that are either a lua str or a value

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
This adds an option for enabling Dagger's Cue LSP.
> plugins/lsp: add dagger language server (for cuelang)

- flake-modules/wrappers.nix
As described in #898, it is currently not possible to use the wrappers. It seems to be cause by a relative import from the current directory, while the wrappers are actually stored in a top-level folder. This should hopefully fix these imports.
Fixes #898
> Update wrapper imports (fixes #898)

- plugins/colorschemes/palette.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/palette.nix
Add support for [palette.nvim](https://github.com/roobert/palette.nvim).
Fixes #829
> colorschemes/palette: init

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Adds lsp support for [templ](https://templ.guide), the HTML templating language for Go.
> plugins/lsp: add templ language server

- modules/output.nix
- tests/test-sources/examples.nix
- wrappers/modules/output.nix
This wraps the `python3Env` option of the `wrapNeovimUnstable` wrapper:
https://github.com/NixOS/nixpkgs/blob/7e1b59c34a13b15df2c10792398131833486ccb0/pkgs/applications/editors/neovim/wrapper.nix#L23
> modules: add python options to specify the python environment

- plugins/default.nix
- plugins/utils/obsidian.nix
- plugins/utils/ollama.nix
- tests/test-sources/plugins/utils/obsidian.nix
Add support for [obsidian.nvim](https://github.com/epwalsh/obsidian.nvim).
We need to wait for [nixpkgs#277537](https://github.com/NixOS/nixpkgs/pull/277537) to land on `nixos-unstable`.
Fixes #846
> plugins/obsidian: init

- plugins/utils/molten.nix
fixes the option for `imageProvider` to match [configuration](https://github.com/benlubas/molten-nvim/tree/main#configuration) of molten (use "image.nvim" instead of "image_nvim")
> misc: correct molten image provider options

- tests/extra-args.nix
- wrappers/standalone.nix
Currently, `extraSpecialArgs` are assigned to `_module.args` in the standalone wrapper. I would like to pass some arguments that shall be used for imports, so `_module.args` sadly does not work. This PR proposes to change the behavior and align it with what Home Manager for example does: Pass the property `extraSpecialArgs` as `specialArgs` to `lib.evalModules`. This would enable my use case.
Strictly speaking this is a breaking change, but since Nix/NixOS openly advocates the use of `_modules.args` for regular parameters anyway, I assume users are familiar with it and people wanting to retain the current behavior (i.e., overriding values in `extraSpecialArgs`) should hopefully be using `_modules.args` already.
In any case, this change should **not** be backported to the `23.11` branch.
> standalone: pass `extraSpecialArgs` to lib.evalModules directly

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add an option to enable the [bencount-language-server][beanlsp].
`tests/test-sources/plugins/lsp/_lsp.nix` as `beancount.enable = true;` on
`all-servers.plugins.lsp.servers`.
[beanlsp]: <https://github.com/polarmutex/beancount-language-server>
> plugins/lsp: add beancount-language-server

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Support for nushells built-in [language server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#nushell).
> plugins/lsp: add nushell language server

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Adds none-ls' source for [bandit](https://github.com/PyCQA/bandit)
> plugins/none-ls: add bandit source

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for the [prolog_ls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#prolog_ls) language server.
> plugins/lsp: add prolog-ls

- plugins/colorschemes/nord.nix
- tests/test-sources/plugins/colorschemes/nord.nix
- Switch back from using `mkPlugin` (it is a `colorscheme`, so we can't use `mkPlugin` _as is_)
- Update the plugin implementation to new standards (+ some option renames)
- Fix typos
- Add tests
Fixes #941
> colorschemes/nord: fix

- plugins/utils/alpha.nix
- tests/test-sources/plugins/utils/alpha.nix
The alpha doc is misleading: all of the `opts` options should be optional.
However, for buttons, not specifying `opts.shortcut` is causing an error.
This patch fixes the affected examples.
> plugins/alpha: fix example (for buttons)

- modules/commands.nix
- tests/test-sources/modules/commands.nix
Currently, `cmd.options` can be `nil` if no option is set. This is invalid as `nvim_create_user_command` expects a table.
This patch fixes this behavior.
Fixes #954
> modules/commands: fix lua cmd.options value when no options are set

- plugins/statuslines/airline.nix
- tests/test-sources/plugins/statuslines/airline.nix
Switch the [vim-airline](https://github.com/vim-airline/vim-airline) plugin to `mkPlugin`.
Add the many missing options.
The implem for `airline_section_* options is not ideal, but anyway, it was completely unused/ignored in the previous implementation.
> plugins/airline: switch to mkPlugin + refactoring

- plugins/utils/yanky.nix
The layout of the `setupOptions` table was invalid.
Fixes #967
> plugins/yanky: fix wrong definition of setupOptions

- plugins/default.nix
- plugins/utils/clipboard-image.nix
- tests/test-sources/plugins/utils/clipboard-image.nix
Add support for [clipboard-image.nvim](https://github.com/ekickx/clipboard-image.nvim).
Fixes #965
> plugins/clipboard-image: init

- plugins/languages/rustaceanvim.nix
This is useful to display inlay hints in neovim >=0.10 for example
> plugins/rustaceanvim: Allow to add on_attach to rustaceanvim

- plugins/default.nix
- plugins/languages/typescript-tools.nix
- tests/test-sources/plugins/languages/typescript-tools.nix
Adds  typescript-tools: https://github.com/pmizio/typescript-tools.nvim/
Fixes https://github.com/nix-community/nixvim/issues/964
> plugins/typescript-tools: init + test

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Add an option to enable the [bean_format][bean_format] none-ls source.
`tests/test-sources/plugins/none-ls.nix/` as `bean_format.enable = true;` on
`default.formatting`.
[bean_format]: <https://beancount.github.io/docs/running_beancount_and_generating_reports.html#bean-format>
> plugins/none-ls: add bean_format

- plugins/telescope/default.nix
- plugins/telescope/ui-select.nix
- tests/test-sources/plugins/telescope/ui-select.nix
- tests/test-sources/plugins/telescope/undo.nix
Add support for the [telescope-ui-select.nvim](https://github.com/nvim-telescope/telescope-ui-select.nvim/) telescope extension.
Fixes #972
> plugins/telescope: add ui-select extension

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for the [helm-ls](https://github.com/mrjosh/helm-ls) language server for Helm.
Partially fixes #989
> plugins/lsp: add helm-ls

- lib/options.nix
- tests/test-sources/plugins/completion/nvim-cmp.nix
Allows you to do (for instance):
```nix
plugins.nvim-cmp.documentation.border.__raw = "cmp.config.window.bordered()";
```
> helpers/options: allow raw values for border options

- plugins/completion/nvim-cmp/default.nix
- plugins/completion/nvim-cmp/setup-options.nix
This patch goes over the implementation of the `nvim-cmp` plugin.
Those changes are internal only and do not affect any user-facing option.
- For each option, move any "transformation" applied to the value from the `setupOptions` definition to the `apply` key of the option.
- Move the code that creates the `setupOptions` attrs to a separate file to enhance the file readability.
> plugins/cmp: refactoring

- modules/keymaps.nix
- plugins/lsp/default.nix
- plugins/lsp/wtf.nix
- plugins/telescope/default.nix
- plugins/utils/harpoon.nix
- plugins/utils/intellitab.nix
- plugins/utils/nvim-osc52.nix
- plugins/utils/spider.nix
Let's use `action.__raw` instead of `lua = true`.
This has no effect on users (only internal changes).
> keymaps: use 'action.__raw' instead of 'lua = true' internally

- docs/default.nix
- docs/either_recursive.patch
- docs/mdbook/default.nix
- flake-modules/modules.nix
- flake-modules/packages.nix
- lib/types.nix
- plugins/pluginmanagers/packer.nix
This makes the code more maintainable, as it only depends on our small patch, instead of a large number of internals of nixpkgs.
> docs: Use a nixpkgs patch instead of copy/pasting nixpkgs functions

- modules/highlights.nix
Highlights currently get configured in extraConfigLuaPost. Any plugin configs that reference them before they get injected will throw errors. This moves the global highlights to be injected at the beginning of the config with extraConfigLuaPre.
> modules/highlights: post -> pre loading

- plugins/git/gitsigns.nix
gitsigns needs git to operate. Add `pkgs.git` as a dependency.
> plugins/gitsigns: add gitPackage option

- plugins/colorschemes/base16.nix
- tests/test-sources/plugins/colorschemes/base16.nix
> plugins/base16: minor improvements

- docs/default.nix
- docs/mdbook/default.nix
- flake-modules/default.nix
- flake-modules/helpers.nix
- flake-modules/modules.nix
- flake-modules/packages.nix
- flake-modules/wrappers.nix
- wrappers/_shared.nix
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
This PR moves the `helpers` from `_module.args` to `specialArgs`.
This is well more adapted and will allow us to not have to import `helpers.nix` from anywhere in the code base.
> misc: refactor helpers propagation

- CONTRIBUTING.md
- flake-modules/tests.nix
- lib/autocmd-helpers.nix
- lib/helpers.nix
- lib/keymap-helpers.nix
- plugins/completion/nvim-cmp/cmp-helpers.nix
- plugins/completion/nvim-cmp/sources/default.nix
- plugins/dap/dap-go.nix
- plugins/dap/dap-python.nix
- plugins/dap/dapHelpers.nix
- plugins/dap/default.nix
- plugins/helpers.nix
- plugins/languages/treesitter/ts-autotag.nix
- plugins/lsp/helpers.nix
- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/ltex-settings.nix
- plugins/none-ls/helpers.nix
- plugins/none-ls/servers.nix
- tests/default.nix
- tests/fetch-tests.nix
- tests/lib-tests.nix
Get rid of all `helpers = import ../../helpers.nix args;`.
> helpers: simplification accross the codebase

- plugins/utils/emmet.nix
Values such as `"inv"` should be allowed.
> plugins/emmet: remove to strict typing on option 'mode'

- modules/highlights.nix
- tests/test-sources/modules/highlight.nix
Follow up to https://github.com/nix-community/nixvim/pull/1016. Support a new highlight override option that is called in post to allow overriding existing highlight groups.
> modules/highlights: add highlightOverride

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Add an option to enable asmfmt in none-ls sources.
> plugins/none-ls: add asmfmt

- lib/neovim-plugin.nix
- lib/options.nix
- lib/vim-plugin.nix
- Add `helpers.mkSettingsOption` to quickly create a RFC-42 style `settings` option
- Have `helpers.vim-plugin.mkVimPlugin` to call `helpers.mkSettingsOption`
- Have `helpers.neovim-plugin.mkSettingsOption` to call `helpers.mkSettingsOption`
Also have `helpers.neovim-plugin.mkNeovimPlugin` to call `helpers.neovim-plugin.mkSettingsOption`
> helpers/options: add mkSettingsOption

- lib/options.nix
- lib/vim-plugin.nix
This could lead to very tricky bugs.
This function is not meant to accept undefined parameters.
> helpers/vim-plugin/mkVimPlugin: don't accept random parameters

- lib/vim-plugin.nix
This allows us to set `namespace = "colorschemes";`.
> helpers/vim-plugin/mkVimPlugin: add namespace option

- lib/maintainers.nix
- plugins/default.nix
- plugins/git/committia.nix
- tests/test-sources/plugins/git/committia.nix
Will resolve: https://github.com/nix-community/nixvim/issues/1022
* I migrated over to NixOS from Arch Linux in the hope that I would be able to run all the tests however the suggested ```nix flake check --all-systems``` is throwing the error: 
```
❯ nix flake check --all-systems
error:
… while checking flake output 'checks'
at «none»:0: (source not available)
… while evaluating the attribute 'optionalValue.value'
at /nix/store/mcm21fbi7i6m3f189pkm7zcdn4c9xl40-source/lib/modules.nix:856:5:
855|
856|     optionalValue =
|     ^
857|       if isDefined then { value = mergedValue; }
(stack trace truncated; use '--show-trace' to show the full trace)
error: a 'aarch64-linux' with features {} is required to build '/nix/store/rzffqiqwi50nyinpmnaai43qy4a3qqhb-nixpkgs-nixvim-doc.drv', but I am a …
```
> plugins/committia: init

- lib/vim-plugin.nix
Add two options to the `vim-plugin.mkVimPlugin` helpers:
- `extraOptions` allows to add arbitrary options to the plugin module
- `extraConfig` allows to do extra fancy configuration
> helpers/vim-plugin/mkVimPlugin: add extraOptions and extraConfig options

- plugins/completion/nvim-cmp/default.nix
fixes a bug where the default client capabilities are overwritten by nvim-cmp's default capabilities
> plugins/nvim-cmp: fix nvim-cmp lsp completion capabilities

- lib/helpers.nix
- lib/neovim-plugin.nix
- plugins/TEMPLATE.nix
- plugins/colorschemes/gruvbox.nix
This PR introduces a new helper: `helpers.neovim-plugin.mkNeovimPlugin`.
It allows to very quickly create the module for a "conventional" plugin.
By "conventional", I mean a lua plugin which is configured through a `require('plugin-name').setup` function.
> helpers/neovim-plugin: add mkNeovimPlugin

- plugins/languages/treesitter/treesitter-refactor.nix
The keymap options `listDefinitions` and `listDefinitionsToc` were misspelled.
This also adds a renamed option warning for backward compatibility.
> Fix typos in `plugins.treesitter-refactor.navigation.keymaps`

- plugins/lsp/default.nix
`plugins.lsp.servers.${serverName}.package` should be `null` instead of `false`
> docs: Fix deprecation message for installLanguageServer

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Adds [`typos`](https://github.com/crate-ci/typos) to none-ls
> plugins/none-ls: add typos

- docs/helpers.md
- flake-modules/helpers.nix
- flake-modules/lib.nix
- flake-modules/tests.nix
- lib/default.nix
- lib/helpers.nix
- lib/utils.nix
- templates/simple/flake.nix
- tests/default.nix
- tests/enable-except-in-tests.nix
- tests/test-derivation.nix
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
In our basic template we used to provide a check based on `mkTestDerivationFromNvim`. The issue with this check (that is handled correctly internally) is that some plugins _can't_ be used in the test environment, for example image.nvim like in #1085.
This commit introduces a new function to generate such checks, `mkTestDerivationFromNixvimModule`, that wraps a nixvim configuration instead of a built nvim instance.
Then a configuration can rely on the newly added
`helpers.enableExceptInTests` attribute to disable parts of the configuration depending if it is evaluated in tests or in a real final configuration.
Resolves #1085
> tests: Introduce a way to disable options when running in tests

- default.nix
- flake-modules/tests.nix
- flake.lock
- flake.nix
- tests/no-flake.nix
There were issues with handling of store vs non store paths that got ~recently fixed in flake-compat. We now use the flake distribution of flake compat so that it is maintained up-to-date.
Resolves #938.
> Fix issue with non flake import

- plugins/default.nix
- plugins/languages/parinfer-rust.nix
- tests/test-sources/plugins/languages/parinfer-rust.nix
Add support for [parinfer-rust](https://github.com/eraserhd/parinfer-rust). It infers parentheses for Clojure, Lisp and Scheme.
Fixes #1059
> plugins/parinfer-rust: init

- plugins/lsp/default.nix
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Reverts nix-community/nixvim#1105
After a bit of digging, it looks like [statix](https://github.com/nerdypepper/statix) [does not](https://github.com/neovim/nvim-lspconfig/issues/2887) actually implement the lsp.
I suggest we pull this out, or possibly mark it as "broken" to avoid any further confusion.
> Revert "plugins/lsp: Add statix"

- plugins/languages/haskell-scope-highlighting.nix
No incidence on user-facing options. Just internal change to see if `mkVimPlugin` can handle most relevant cases.
> plugins/haskell-scope-highlighting: switch to mkVimPlugin

- plugins/utils/neocord.nix
- tests/test-sources/plugins/utils/neocord.nix
I misclosed #1108.
User couldn't set the logo url, also logo_tooltip didn't allow custom string because of the enum.
> fix: neocord logo and logo_tooltip

- lib/helpers.nix
- lib/vim-plugin.nix
- plugins/completion/copilot-vim.nix
- plugins/languages/ledger.nix
- plugins/languages/markdown-preview.nix
- plugins/languages/tagbar.nix
- plugins/languages/vim-slime.nix
- plugins/languages/zig.nix
- plugins/statuslines/airline.nix
- plugins/utils/emmet.nix
- plugins/utils/goyo.nix
- plugins/utils/instant.nix
- plugins/utils/magma-nvim.nix
- plugins/utils/molten.nix
- plugins/utils/startify.nix
- plugins/utils/undotree.nix
This allows to easily create the necessary renamed warnings.
> helpers/vim-plugin/mkVimPlugin: add optionsRenamedToSettings option

- flake-modules/lib.nix
- lib/default.nix
In my personal configuration, I rely on `nixvim.lib.${system}.helpers` to get access to things like `mkRaw` and `toLuaObject` for use in my extended `lib`.
With the changes made in 6d7e429537ae8143d8405c44a61479248776758c, `nixvim.lib.${system}.helpers` can no longer be accessed directly from the `nixvim` input as `_nixvimTests` is not provided as an input attribute, so loading `helpers.nix` fails.
This small change restores what I *think* is the intended behavior of this module.
> Add _nixvimTests = false to flake.lib output

- docs/man/default.nix
- docs/mdbook/SUMMARY.md
- docs/user-guide/extending-config.md
- flake-modules/tests.nix
- tests/extend.nix
- wrappers/standalone.nix
This adds the `nixvimExtend` attribute to the generated standalone derivation, this attribute takes a module as an argument and returns a new standalone derivation with the initial module & the extended module merged together.
> standalone: Allow to extend a standalone derivation with a new module

- lib/neovim-plugin.nix
This is already the case in `mkVimPlugin`.
> helpers/neovim-plugin/mkNeovimPlugin: allow lists in optionsRenamedToSettings

- plugins/none-ls/servers.nix
- tests/test-sources/plugins/none-ls.nix
Thank you for the amazing project :)
This adds the ruff linter and formatter as a source for none-ls.
I basically copied similar previous PRs and tested locally, so please let me know if you see any issue.
> Add ruff source to none-ls

- plugins/utils/oil.nix
- tests/test-sources/plugins/utils/oil.nix
I added few options that probably were added recently and not updated here, the version on unstable: https://github.com/stevearc/oil.nvim/tree/bf753c3e3f8736939ad5597f92329dfe7b1df4f5?tab=readme-ov-file#options
> plugins/oil.nvim: Update add a few missing options

- plugins/default.nix
- plugins/utils/smart-splits.nix
- tests/test-sources/plugins/utils/smart-splits.nix
First stab at making a (formal) NixVim plugin unlike what I'm doing at my own NixVim config. I'm guessing there is a migration at Nix RFC42-style settings so I did that.
Resolves #1050. (Probably a follow-up PR for [legendary.nvim](https://github.com/mrjones2014/legendary.nvim) as it has integration for it. Also, it looks interesting.)
Also, I cannot test this in my local setup as it always crashes so I hope you don't mind if I fully rely on the CI for the testing.
> plugins/smart-splits: init

- flake-modules/default.nix
- flake-modules/dev/default.nix
- flake-modules/dev/devshell.nix
- flake.lock
- flake.nix
Create a convenient devshell that provides the following commands:
- checks: Run all nixvim checks
- docs: Build nixvim documentation
- format: Format the entire codebase
- menu: prints this menu
- serve-docs: Build and serve documentation locally
- tests: Run nixvim tests
> flake/dev: add a convenient devshell

- plugins/colorschemes/nord.nix
This was wrongly removed in https://github.com/nix-community/nixvim/commit/be87309e0c1da19d99d969625300aaed36ff1b91.
Fixes #1189
> colorschemes/nord: properly set the vim colorscheme to "nord"

- plugins/none-ls/servers.nix
This was previously null or string, but was changed to null or Lua in nix-community/nixvim#1169. Internally, `withArgs` is expected to be a string, but `mkNullOrLua` applies `mkRaw`, leading to a type error when generating the output, as it is attempting to interpolate a set rather than a string.
Additionally, there was an errant extra } when interpolating the args, which led to a broken init.lua.
Tested locally, and verified that it fixes my setup.
> plugins/none-ls: fix withArgs type, syntax

- plugins/statuslines/lightline.nix
The lightline plugin has an option for which components to display in active panes, which is currently supported by nixvim, but it also has an equivalent option for inactive panes. This PR just adds that option.
> plugins/lightline: Add option for inactive components

- plugins/statuslines/lightline.nix
This PR builds upon #1170 by applying the same changes to the `active` option.
> plugins/lightline: Improve types for active option of lightline

- wrappers/modules/output.nix
This allows the neovim wrapper to be built with node plugin support by specifying it in the nixvim config. I confirmed that it is present with `:checkhealth` and that I could load something via a runtimepath `rplugin/node` folder.
`:checkhealth` output:
```
Node.js provider (optional) ~
- Node.js: v18.18.2
- Nvim node.js host: /nix/store/5g13wzq09yx4kp3r6z3w3p913r7y1ik4-neovim-4.11.0/bin/neovim-node-host
- WARNING Package "neovim" is out-of-date. Installed: 4.11.0, latest: 5.0.1
- ADVICE:
- Run in shell: npm install -g neovim
- Run in shell (if you use yarn): yarn global add neovim
- Run in shell (if you use pnpm): pnpm install -g neovim
```
Setting this new option changes the command-line lua argument passed by the neovim wrapper such that `vim.g.loaded_node_provider=0` is not passed …
> expose withNodeJs option to pass to neovim wrapper

- plugins/utils/todo-comments.nix
- tests/test-sources/plugins/utils/todo-comments.nix
Attempting to use todo-comments without `ripgrep` isn't very useful since the plugin won't be able to find comments in your files based on keywords. This commit adds a new option, defaulting enabled, to add `ripgrep` to the resulting neovim build.
> fix: add ripgrep for todo-comments functionality

- plugins/lsp/default.nix
Some servers like `tsserver` conflict with additional LSPs when they are active on the same buffer. Other servers may misreport their capabilities or need tweaking to match user preferences. Previously this needed to be done in a much more ad-hoc way in the user's configuration or bespoke lua config would need to be written to handle these cases. This commit provides a central, nix-based solution for toggling lsp capabilities declaratively.
> feat: add option for customizing lsp capabilities

- plugins/completion/cmp/options/settings-options.nix
An update broke my configuration. I used a negative int in this option before, everything worked fine 🙂
> plugins/cmp: allow negative values in `col_offset`

- plugins/none-ls/servers.nix
Add two assertions to ensure that we declare exactly the tools that are supported upstream (no more, no less).
The big cleaning comes from https://github.com/nvimtools/none-ls.nvim/pull/77.
> plugins/none-ls: automatic check for tools packages declaration

- plugins/lsp/conform-nvim.nix
- tests/test-sources/plugins/lsp/conform-nvim.nix
this is the same change that was performed previously on formatOnSave in https://github.com/nix-community/nixvim/pull/804
With this change it is possible to define a function to be run in formatAfterSave. It makes possible implementing the recipe to run slow formatters asynchronously: https://github.com/stevearc/conform.nvim/blob/master/doc/recipes.md#automatically-run-slow-formatters-async
pd: I found the devshell to be very nice, easing formatting and testing, thanks! I think I'll integrate that as well in some of my projects :D
> plugins/conform: add str type for formatAfterSave

- plugins/default.nix
- plugins/languages/ltex-extra.nix
- plugins/lsp/language-servers/ltex-settings.nix
Add an option to `plugins.lsp.servers.ltex` to enable the [LTeX_extra](https://github.com/barreiroleo/ltex_extra.nvim) plugins which enable LTeX LSP code action, external file handling and more features. 
I let this PR as a draft as I have not properly tested it yet and I am not sure if adding this plugin as an option to `plugins.lsp.servers.ltex` is the preferred way.
> plugins/ltex-extra: init

- plugins/lsp/default.nix
- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add the [ocaml-lsp](https://github.com/ocaml/ocaml-lsp) language server.
> plugins/lsp: add ocamllsp, the language server for OCaml

- plugins/default.nix
- plugins/filetrees/nvim-tree.nix
- plugins/pluginmanagers/lazy.nix
- tests/test-sources/plugins/pluginmanagers/lazy.nix
> plugins/lazy.nvim: new plugin manager

- plugins/completion/cmp/options/default.nix
This example was invalid.
Fixes #1224
> plugins/cmp: fix example for cmdline option

- plugins/lsp/helpers.nix
`attrs` is not merged correctly, this can introduce conflicts with efmls-configs for example when trying to register `efm` sources not defined by efmls-configs.
> plugins/lsp: use `attrsOf anything` instead of `attrs` for extraOptions

- lib/neovim-plugin.nix
- lib/vim-plugin.nix
- plugins/colorschemes/ayu.nix
- plugins/colorschemes/gruvbox.nix
- plugins/colorschemes/nord.nix
As we will use more and more those helpers, we should include the logic regarding colorschemes.
Currently we have a `namespace` argument. This new `colorcheme` boolean argument replaces it.
If `true`, it will:
- Set the namespace to `colorschemes`
- Set the `colorscheme` option to `name` (i.e. the name of the plugin).
This will prevent further mistakes such as forgetting to set the colorscheme.
> helpers/mk[Neo]VimPlugin: add colorscheme argument and factor out logic

- plugins/lsp/language-servers/default.nix
Add `fortls` LSP plugin. 
This plugin features numerous options, some of which are experimental. At the moment, I haven't implemented any `settingsOptions` because I'm not sure it's necessary given that the LSP is entirely configured by its command line arguments (it could then be configured through `fortls.cmd = [ ... ]`. Plus, it can be configured via a configuration file. Adding the options in nixvim would add significant maintenance work. However, I'm not closed to the idea of adding the options if you think it's necessary (as mentioned in the contribution guideline).
As for the default options, I've chosen those selected by [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/fortls.lua) (except for the initialization …
> plugins/lsp: add fortls

- plugins/git/gitsigns.nix
The option `plugins.gitsigns.base` to specify the ref to diff against had no effect because its value wasn't inherited in the setupOptions and thus didn't appear in `init.lua`.
> Fix `plugins.gitsigns.base` option missing in init.lua

- plugins/completion/coq.nix
- tests/test-sources/plugins/completion/coq.nix
This allows the user to define additional options unpackaged by nixvim. No new options were defined, nor any old option was deleted.
Fixes #1114
> plugins/coq: Switch to mkNeovimPlugin

- plugins/utils/alpha.nix
- tests/test-sources/plugins/utils/alpha.nix
> plugins/alpha: Allow `terminal` to not set `val`

- plugins/colorschemes/base16/default.nix
With the rewrite at c2cd3cb7a13c0677c49f46d55a8c65b50b7d9431, the option `useTruecolor` was removed in favor of `options.termguicolors`. `useTruecolor` was set to `true` by default, but this is not done after the removal of this option. This causes the colors to not be set properly. I have set `options.termguicolors` to `true` again to fix this.
Fixes #1264.
> colorschemes/base16: set termguicolors to true

- plugins/completion/cmp/deprecations.nix
As pointed out in #1272, we were lacking the rename warning for `plugins.nvim-cmp.autoEnableSources`.
> plugins/cmp: add missing renamed-option-module for autoEnableSources

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Adds setup for [golangci-lint-langserver](https://github.com/nametake/golangci-lint-langserver).
> plugins/lsp: add golangci-lint-langserver

- lib/keymap-helpers.nix
- modules/keymaps.nix
- tests/test-sources/modules/keymaps.nix
What the title says.
Groups keymaps by new `onEvent` key and loads with an autocmd.
Allows for easy fix of #1219. Not done here because this PR adds a new feature.
This is definitely not the cleanest code - I've only used nix for configuration so far, so I'd appreciate help on that front! I'm also not sure about how good the tests are either.
> Keymaps: Add onEvent key to keymaps to load keymap on specified event

- plugins/colorschemes/onedark.nix
- tests/test-sources/plugins/colorschemes/onedark.nix
Switch the onedark colorscheme to the [onedark.nvim plugin](https://github.com/navarasu/onedark.nvim).
Fixes #1228
> colorschemes/onedark: switch to onedark.nvim + tests

- plugins/neotest/adapters-list.nix
- plugins/neotest/adapters.nix
- tests/test-sources/plugins/neotest/default.nix
- tests/test-sources/plugins/neotest/playwright.nix
Add the playwright neotest adapter.
This one requires the ability to call the adapter differently in the neotest config.
> plugins/neotest: add playwright adapter

- CONTRIBUTING.md
`globalPrefix` is not joined using `"_"`, so it is misleading to have an underscore after it.
> docs: (minor) remove misleading `_` in CONTRIBUTING.md

- docs/default.nix
Nixvim uses "`main`" while nixpkgs uses "`master`".
This fixes the "Branch not found, redirected to default branch" warning shown when clicking "Declared by" [links](https://github.com/nix-community/nixvim/blob/master/modules/doc.nix) in the docs.
> docs: fix github link "branch not found"

- plugins/statuslines/lualine.nix
- tests/test-sources/plugins/statuslines/lualine.nix
Lualine allows you to specify a custom formatter function which can process the final status component string. This can be useful for augmenting existing status components and tweaking the output dynamically.
> feat: allow custom formatting for status components

- docs/mdbook/default.nix
- flake-modules/modules.nix
- lib/neovim-plugin.nix
- lib/vim-plugin.nix
This adds the `description` field to the `nixvimInfo` attrs.
If not empty, it is then used in the documentation generation.
> docs: optionally add a description to plugins

- plugins/completion/cmp/options/default.nix
- tests/test-sources/plugins/completion/cmp.nix
This was not adapted to the new implementation.
> plugins/cmp: fix examples for snippet.expand

- docs/mdbook/default.nix
- lib/maintainers.nix
- plugins/utils/tmux-navigator.nix
- tests/test-sources/plugins/utils/tmux-navigator.nix
This PR ports `tmux-navigator` to the new `mkVimPlugin` system and adds missing options.
The option documentation was re-written based on the docs in [upstream's README](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#configuration).
I have some questions on the best way to approach some stuff:
- Is there a way to add additional documentation to the actual plugin module?
- _Done, using #1297_
- What type should `save_on_switch` use?
- Is there a way to map better named enum values to `1` & `2`?
- Is this even desired?
- Should I add myself to maintainers?
- _Done_
> plugins/tmux-navigator: port to mkVimPlugin & update available options

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for the [sqls](https://github.com/sqls-server/sqls) language server for SQL.
Fixes #1231
> plugins/lsp: add sqls language server

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for the [vhdl_ls](https://github.com/VHDL-LS/rust_hdl) language server for VHDL.
Fixes #1312
> plugins/lsp: add vhdl-ls

- plugins/colorschemes/kanagawa.nix
- tests/test-sources/plugins/colorschemes/kanagawa.nix
"Fixes" #1159 -> By properly unsetting `vim.o.background` (`option.background = "";`) as mentioned in the plugin README, everything works as expected.
> colorschemes/kanagawa: switch to mkNeovimPlugin

- lib/maintainers.nix
- plugins/default.nix
- plugins/utils/vim-css-color.nix
- tests/test-sources/plugins/utils/vim-css-color.nix
Add support for [vim-css-color](https://github.com/ap/vim-css-color).
Fixes #1321
> plugins/vim-css-color: init

- docs/default.nix
- docs/mdbook/SUMMARY.md
- docs/mdbook/default.nix
- docs/modules/hm.md
- wrappers/hm.nix
- wrappers/modules/hm.nix
This commit only adds Home-Manager specific options, we should add sections for the different kind of modules too.
This is _not_ added to the man docs, as it is more complex. If need arises we could look into how to do it.
> docs: Add a section on module specific options

- docs/man/default.nix
- docs/mdbook/SUMMARY.md
- docs/modules/standalone.md
- docs/user-guide/install.md
Building on #1355 and in preparation for documenting #1356, attempt to consolidate some of the standalone usage information into a new platform specific guide.
- **Move standalone usage to modules section**
- **move standalone example to platform usage**
- **add usage tldr**
> docs: consolidate standalone usage

- docs/user-guide/install.md
Looks like I messed up the links in #1361 by assuming the user-guides were in a nested path.
> docs: hotfix module guide links

- plugins/lsp/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Register keymaps defined in `plugins.lsp.keymaps` on `LspAttach`.
Added `plugins.lsp.keymaps.extra` to register arbitrary keymaps.
Fixes #1219
> LSP: Register keymaps on `LspAttach`

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add the [nimls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#nimls) language server for Nim.
Fixes #1363
> plugins/lsp: add nimls language server

- plugins/languages/nvim-jdtls.nix
Fixes incorrectly hard coded binary name for jdtls.
> plugins/jdtls: fix binary name

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for the [lexical](https://github.com/lexical-lsp/lexical) language server (for Elixir).
> plugins/lsp: add lexical language server

- lib/builders.nix
- lib/helpers.nix
- wrappers/modules/output.nix
@GaetanLepage mentioned it'd be nice to format `init.lua` using stylua. This PR does that by introducing a new derivation builder `helpers.writeLua`.
The options parameter is mostly there to allow for unforeseen future use-cases. It's currently unused.
This is currently only used for `init.lua`, the other files (e.g. ftplugins) will also need to migrate to `writeLua` to benefit.
In the future, we could expose an option to have either raw, minified, or prettified lua files, although this probably isn't really necessary.
> Format init.lua using StyLua

- plugins/lsp/language-servers/pylsp.nix
removes `substituteStream(): WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}.` warnings by reaplacing `--replace`
See https://github.com/NixOS/nixpkgs/pull/260776
> plugins/lsp/pylsp: replace "--replace" to remove warnings

- plugins/filetrees/neo-tree.nix
Per NixOS/nixpkgs#237557, which was merged 10 months ago, lib.mdDoc is a no-op. NixOS/nixpkgs#303841 was recently merged which removes the function and now causes an error in plugins/filetrees/neo-tree.nix. This PR simply removes the wrapping lib.mdDoc function.
> plugins/filetrees/neo-tree: remove deprecated lib.mdDoc call

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add the [docker-compose-language-service](https://github.com/microsoft/compose-language-service) language server for Docker Compose.
Fixes #1426
> plugins/lsp: add docker-compose-language-service language server

- modules/options.nix
- tests/test-sources/modules/options.nix
To minimize confusion for users following the docs, we could add an `opts` alias to the stable branches.
Unlike the unstable branch, there's no deprecation warning here.
This should be easy to cherry-pick onto older branches if desired.
See #1324
> Backport `opts` alias to 23.11

- modules/output.nix
- plugins/git/gitsigns/default.nix
- plugins/languages/godot.nix
- plugins/languages/lean.nix
- plugins/languages/ledger.nix
- plugins/languages/rust-tools.nix
- plugins/languages/rustaceanvim.nix
- plugins/languages/treesitter/treesitter.nix
- plugins/languages/vimtex.nix
- plugins/lsp/helpers.nix
- plugins/none-ls/servers.nix
- plugins/utils/clipboard-image.nix
- plugins/utils/todo-comments.nix
=> This is a proposal and expects discussion.
Currently, the `extraPackages` option has type `listOf package`.
Furthermore, we often rely on _optional_ package options (i.e. typed as `nullOr package`) where `null` means: "do not install any package".
Then, the implementation looks like this:
```nix
extraPackages =
optional
(cfg.fooPackage == null)
cfg.fooPackage;
```
Have `extraOptions` to be typed `listOf (nullOr package)`. I.e., make it accept `null`.
- Further reduce boilerplate. Simplify the snippet above to
```nix
extraPackages = [cfg.fooPackage];
```
- Reduction in clarity. -> More prone to errors/omission.
What is your opinion about this ?
> misc: allow null in extraPackages

- plugins/default.nix
- plugins/utils/cloak.nix
- tests/test-sources/plugins/utils/cloak.nix
Add support for [cloak.nvim](https://github.com/laytan/cloak.nvim). Cloak allows you to overlay *'s over defined patterns in defined files.
> plugins/cloak: init

- plugins/default.nix
- plugins/languages/texpresso.nix
- tests/test-sources/plugins/languages/texpresso.nix
There are no configuration options for this package.
This just makes the `texpresso` binary (necessary to use this plugin) available to neovim.
> plugins/languages/texpresso: init

- plugins/lsp/language-servers/ccls.nix
ccls wasn't passing the init options to it's own configuration so they were being ignored..
> plugins/lsp/ccls: fix initOptions

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add support for the [ast-grep](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ast_grep) language server.
Fixes #1463
> plugins/lsp: add ast-grep language server

- plugins/default.nix
- plugins/utils/spectre.nix
- tests/test-sources/plugins/utils/spectre.nix
- typos.toml
Add support for [nvim-spectre](https://github.com/nvim-pack/nvim-spectre).
Note: I didn't implement any auto-installation method for the find/replace tools (`rg`, `ag`, ...).
Fixes #1403
> plugins/spectre: init

- plugins/completion/cmp/sources/cmp-fish.nix
- plugins/completion/cmp/sources/default.nix
Auto-installs `fish` when using the `cmp-fish` completion source.
> plugins/cmp-fish: add fishPackage option

- plugins/colorschemes/cyberdream.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/cyberdream.nix
This PR adds the [cyberdream.nvim](https://github.com/scottmckendry/cyberdream.nvim) colorscheme.
closes #1471
> colorschemes/cyberdream: init

- plugins/completion/lspkind.nix
I think this is what should go there, I was checking and vim_after does not exist.
If I am wrong, feel free to reject the PR.
> plugins/lspkind: vim_after undefined variable

- docs/modules/standalone.md
- wrappers/standalone.nix
This can be used to teach `nixd` about NixVim options.
> standalone: Expose `options`

- plugins/default.nix
- plugins/utils/arrow.nix
- tests/test-sources/plugins/utils/arrow.nix
Add the [arrow-nvim](https://github.com/otavioschwanck/arrow.nvim) plugin.
We are currently ignoring the option `treesitter_context`, which is not  currently  usable, for detail see https://github.com/otavioschwanck/arrow.nvim/pull/43#issue-2236320268
> plugins/arrow: init

- lib/options.nix
This `mkNullableWithRaw` was previously introduced but left unused (and broken).
This PR makes use of it.
> lib/options: make use of previously unused mkNullableWithRaw internally

- plugins/ui/statuscol.nix
- tests/test-sources/plugins/ui/statuscol.nix
The `statuscol.nvim` plugin allows for segments to not specify a `text` attribute (see [example](https://user-images.githubusercontent.com/31730729/230627808-de0b1e97-116d-4016-b4ba-cb709dfcd980.png) in [the plugin's README](https://github.com/luukvbaal/statuscol.nvim/blob/main/README.md).
This PR makes the respective nixvim option nullable and sets it to null by default.
> Fix statuscol.nvim option type

- plugins/languages/rust/rustaceanvim.nix
The rustaceanvim plugin never attaches to lsp-format even though the documentation mentions it should:
```
plugins.rustaceanvim.server.onAttach
Function to call on attach
Plugin default: __lspOnAttach
```
but `__lspOnAttach` is never set when the option is null
> plugins/rustaceanvim: fix onAttach option

- plugins/lsp/lsp-format.nix
- tests/test-sources/plugins/lsp/lsp-format.nix
The `setup` table should have filetypes as keys, not language server names.
So it should be `go` instead of `gopls`.
> plugins/lsp-format: fix setup example

- modules/commands.nix
- tests/test-sources/modules/commands.nix
A couple of minor fixes here. Firstly, nargs needs 0 or 1, it will error if "0" or "1" are passed (as was previously the case). Secondly, `nvim_create_user_command` accepts a Lua function as its `{command}` parameter, e.g.
```lua
function(opts)
local arg = opts.args
...
end
```
A simple tweak to the type of `command` is enough to fix this.
> modules/commands: allow lua commands, fix nargs

- plugins/statuslines/lualine.nix
Option "extensions" was incorrectly output under key "options", but it belongs to the top level of lualine's setup table.
> plugins/lualine: fix extensions option

- plugins/telescope/default.nix
Allow users to add telescope extensions we don't support yet. Replace marking the option as "internal" with explicit warnings and suggestions in the description.
I thought about adding an assertion for `(enabledExtensions != []) -> plugins.telescope.enable`, but this seemed excessive and would need to be added via `imports` to bypass how `mkNeovimPlugin` wraps `extraConfig`.
May resolve #1488
> plugins/telescope: make `enabledExtensions` public

- wrappers/modules/output.nix
This PR fixes an oversight in #1409 that meant the un-formatted `customRC` was still used to set the config option `initContent`, even though `initPath` was pointing to the formatted file.
I also removed the (now redundant) formatting from the `nixvim-print-init` command.
Hopefully, this should mean the `init.lua` is formatted consistently by all wrapper/platforms now 🤞
> wrappers/output: fix `initContent` formatting

- wrappers/modules/output.nix
`makeNeovimConfig` produces a `neovimRcContent` that is _usually_ just a bunch of blank empty lines.
If it's entirely whitespace (matches the regex `[[:space:]]*`) there's no reason to include it.
It may also be nice to _trim_ the start/end of the string for blank lines too, but AFAICT this is non-trivial using nix-lang, so I haven't bothered.
> wrappers/output: omit blank vimrc from `init.lua`

- plugins/utils/refactoring.nix
- tests/test-sources/plugins/utils/refactoring.nix
> plugins/refactoring: switch to mkNeovimPlugin & add telescope support option

- lib/keymap-helpers.nix
- modules/keymaps.nix
This PR deprecates the `lua` keymap submodule option, in favour of using a "raw string" directly on the `action` option.
Since we're not ready to remove it outright just yet the existing option declaration needs to stay, but it can be marked `visible = false`.
A warning will be displayed if the option is defined anyware in a nixvim config, even if explicitly setting `lua = false`.
This warning is printed when using this branch with my config:
```
trace: warning: Nixvim (keymaps): the `lua` keymap option is deprecated.
This option will be removed in 24.11. You should use a "raw" `action` instead;
e.g. `action.__raw = "<lua code>"` or `action = helpers.mkRaw "<lua code>"`.
Found 1 use in /nix/store/7lsacy6wira1l2y6xpxq1nxcigrkxaqp-source/nvim/config/main.nix
```
This PR builds on #1004 and …
> modules/keymaps: deprecate `lua` option

- .github/workflows/update.yml
When triggering manually we can update:
- both branches
- Only the main branch (unstable)
- Only the chosen stable branch
> actions: Update both stable & unstable flake.lock

- plugins/lsp/language-servers/default.nix
- plugins/lsp/language-servers/nil_ls-settings.nix
- tests/test-sources/plugins/lsp/language-servers/nil-ls.nix
Adding some options that were being ignored when I tried to add to config for nil_ls. 
https://github.com/oxalica/nil/blob/main/docs/configuration.md?plain=1
> plugins/lsp/language-servers: nil_ls add nix options

- flake-modules/dev/default.nix
- flake.lock
- flake.nix
The cachix `pre-commit-hooks` was renamed to `git-hooks`.
> flake: rename pre-commit-hooks to git-hooks

- plugins/default.nix
- plugins/utils/trim.nix
- tests/test-sources/plugins/utils/trim.nix
Add support for [trim.nvim](https://github.com/cappyzawa/trim.nvim).
I didn't add a `plugins.trim.keymaps` option (for `:Trim` and `:TrimToggle`) because I didn't feel that it was necessary. I am open to adding it.
Fixes #1556
> plugins/trim: init

- plugins/colorschemes/nightfox.nix
- plugins/default.nix
- tests/test-sources/plugins/colorschemes/nightfox.nix
Add support for the [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim) colorscheme.
Fixes #1542
> colorschemes/nightfox: init

- lib/options.nix
As mentioned previously, it'd be nice for functions like `defaultNullOpts.mkNullable` to accept actual nix values and correctly render it in the docs.
We can achieve this using [`lib.generators.toPretty`](https://github.com/NixOS/nixpkgs/blob/b873fdcdb4a44081c9041878f6d4dc4f2f4e55c6/lib/generators.nix#L326-L341), however I've added a check for `isString` because we currently assume we can pass stringified nix code and have it render as-is. It'd be nice to change that in the future, but the work would be significant to do that now.
I may also push a followup commit to this PR changing `defaultNullOpts.mkStr`'s behaviour to quote & escape the default string using `toPretty`, as I think [`"quoted"`](https://github.com/NixOS/nixpkgs/blob/b873fdcdb4a44081c9041878f6d4dc4f2f4e55c6/lib/tests/misc. …
> lib/options: defaultNullOpts support non-string defaults

- lib/neovim-plugin.nix
- lib/vim-plugin.nix
The nightfox theme has "flavors" that the user is supposed to select from the neovim `colorscheme` option.
We should allow the user to override this value.
> colorschemes: set the colorscheme as mkDefault to allow for overriding

- plugins/telescope/default.nix
- tests/test-sources/plugins/telescope/default.nix
Use the `:Telescope` command instead of relying directly on
`require("telescope.builtin")`.
To quote [upstream docs](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#vim-commands):
> All `telescope.nvim` functions are wrapped in vim commands for easy access, tab completions and setting options.
Fixes #1493
> plugins/telescope: support non-builtin keymaps

- modules/keymaps.nix
Since @GaetanLepage reported false positives, and since I discovered `toPretty` while working on #1580, it may be useful to show users the exact definition that is triggering the warning.
My config now produces the following warning:
```
trace: warning: Nixvim (keymaps): the `lua` keymap option is deprecated.
This option will be removed in 24.11. You should use a "raw" `action` instead;
e.g. `action.__raw = "<lua code>"` or `action = helpers.mkRaw "<lua code>"`.
Found 1 use in /nix/store/14kwid826pc2cm1gbaj7kbp0yvsmf0md-source/nvim/config/main.nix:
[
{
action = ''
function() require("telescope").extensions.refactoring.refactors() end
'';
key = "<leader>rr";
lua = true;
mode = "n";
options = {
desc = "Select refactor";
};
}
]
```
> modules/keymaps: more verbose `lua` deprecation

- lib/options.nix
Detect whether a plugin default is multiline using `hasInfix "\n"`.
This works fairly well, but without trimming the default string we may run into some false-positives. We could borrow the implementation from https://github.com/NixOS/nixpkgs/pull/315411 or wait and see if/when that gets merged. Personally, I don't see this FIXME as a blocker, unless we find it affects a significant portion of the docs.
I also noticed some default strings seem to have excessive indentation, IDK how easily we could remove that or if we should even bother. ~~I left a TODO comment.~~
Here's a screenshot of docs built with this change:
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
Note how 2/3 options have inline plugin defaults, while the first option has a multiline plugin default.
> lib/options: multi-line plugin default strings

- lib/options.nix
Expanding on #1544, since we can't currently let `defaultNullOpts.mkDefaultDesc` render strings properly, we can (for now) handle that in `defaultNullOpts.mkStr`.
<details><summary>Render</summary>
<p>
</p>
</details> 
_Aside:_ looks like we should consider using `toPretty` for _type_ rendering too...
> lib/options: `mkStr` should render quoted default strings

- plugins/languages/debugprint.nix
- tests/test-sources/plugins/languages/debugprint.nix
The `ignore_treesitter` option has been deprecated by upstream (https://github.com/andrewferrier/debugprint.nvim/issues/25#issuecomment-2081407774).
This is the first time (I think) that we have to remove an option from a RFC-42 style plugin.
In those cases, I wouldn't bother taking any extra nix-deprecation measure. The plugin is showing a warning itself at runtime. The whole goal of this paradigm change was to step back from the very tight and constrained option declaration model that we had. So I would say: no warning here.
> plugins/debugprint: remove deprecated ignore_treesitter option

- lib/options.nix
- plugins/lsp/language-servers/ccls.nix
- plugins/utils/molten.nix
- **lib/options: `mkEnum` quote default if string**
- **lib/options: `defaultNullOpts` delegate string rendering**
Other than gradually transitioning away from passing in large pre-rendered strings to `mkNullable` (etc), and then subsequently being able to _also_ delegate string-type rendering in `mkEnum` and `mkStr`, this should conclude this series of PRs adding `toPretty` support to `mkDefaultDesc`.
> lib/options: delegate all non-string default rendering to `mkDefaultDesc`

- flake.nix
I wasn't aware of this `nixConfig` attribute.
> flake: add the nix-community binary cache

- lib/keymap-helpers.nix
This allows to define buffer-local keymaps, which is specially useful when combined with `keymapsOnEvents`.
> modules/keymaps: add "buffer" option to mapConfigOptions

- lib/keymap-helpers.nix
As mentioned here: https://github.com/nix-community/nixvim/pull/1565#discussion_r1614916649
> modules/keymaps: doc: add backticks around special arguments

- flake-modules/wrappers.nix
This allows using `nixvim.homeManagerModules.default` for example.
> flake-modules/wrappers: add default module

- lib/keymap-helpers.nix
- modules/keymaps.nix
It appears that submodule options for list-of submodules are considered "defined" when _actually_ defined, while "plane" submodules (i.e. `plugins.wtf.keymaps`) seem to behave differently...
To work around the issue, I've made the (hidden and deprecated) `lua` keymap option "`nullOr bool`", so that we can assume "`null`" means "unset"...
This could cause an edge-case if a user is _reading_ the `lua` value in their config and assuming it is a non-null boolean though.
> modules/keymaps: fix false-positive `lua` warning

- docs/user-guide/helpers.md
- lib/to-lua.nix
- lib/utils.nix
This allows to have "raw lua" for table keys.
This:
```nix
{
__raw__foo = 1;
bar = 2;
}
```
Would translate into
```lua
{
[foo] = 1;
['bar'] = 2;
}
```
> helpers/toLuaObject: add support for raw keys

- lib/options.nix
This PR adds new variants for all low-lever option factory funcs (`mkNullable`, `mkNullOrOption`, etc), as well as a handful of higher-level factories (`mkAttributeSet`, `mkAttrsOf`, & `mkListOf`).
This is done so that we have easy access to the underlying `lib.mkOption` attributes, such as `example`.
All attributes are passed through blindly, unless they are intentionally modified along the way.
Currently this PR doesn't make any effort to document _required_ arg-attributes.
I made (more or less) every function its own commit because I needed to use `git bisect`.\
This will also make it easier to drop/revert any specific function if we decide it's overkill to have a prime variant of it.\
I'll happily squash once we're ready to merge - how would you like the history structured?
Unrelated …
> lib/options: introduce "prime" fn variants (alt API)

- lib/options.nix
Drop assert because it is no longer needed, and also blocks us from passing in raw types.
If a non-string is passed in, it'll be formatted here. This is okay
because `mkDesc` will not re-format strings anyway.
> lib/options: remove `mkStr` assert

- lib/keymap-helpers.nix
- plugins/lsp/wtf.nix
Make the `key` and `action` options optional, and allow configuring
whether `action` can be a raw type.
Related to #603
> lib/keymap-helpers: refactor `mkMapOptionSubmodule`

- lib/options.nix
- plugins/bufferlines/bufferline.nix
- plugins/dap/dap-python.nix
- plugins/dap/dap-ui.nix
- plugins/filetrees/neo-tree.nix
- plugins/git/diffview.nix
- plugins/languages/rust/rust-tools.nix
- plugins/lsp/inc-rename.nix
- plugins/lsp/language-servers/nil_ls-settings.nix
- plugins/none-ls/default.nix
- plugins/ui/noice.nix
- plugins/ui/statuscol.nix
- plugins/utils/auto-session.nix
- plugins/utils/dressing.nix
- plugins/utils/hydra/hydra-config-opts.nix
- plugins/utils/neocord.nix
- plugins/utils/nvim-ufo.nix
- plugins/utils/presence-nvim.nix
Follow up to #1603
- **plugins: normalise `null` plugin-defaults**
This first commit was needed to satisfy the assertion I added to `mkEnum'`.
I could move this to another PR if needed.\
We could also check each of the files touched to see if other changes ought to be made.
- **lib/options: add more `defaultNullOpts` 'variants**
The meat of this PR - add a prime variant for each `defaultNullOpts` option factory function.
- **lib/options: add `mkEnum'` argument assertions**
I also added some assertions to ensure `mkEnum'` is always used correctly. This could be kept or dropped (after running it through CI) depending on preference.
@GaetanLepage It'd be great if you could run CI with these changes on #1614.
> lib/options: add prime variants for the rest of `defaultNullOpts`

- wrappers/hm.nix
- wrappers/modules/hm.nix
Implement the `programs.neovim.vimdiffAlias` option from HM in nixvim.
Note: this only applies to the HM module.
Fixes #1351
> wrappers/hm: add vimdiffAlias option

- README.md
- **readme: put installation instruction in `<details>`**
- **readme: use `pkgs.system` in standalone example**
- **readme: move "advanced usage" next to "standalone usage"**
- **readme: move "how it works" near the top**
- **readme: add "plugin settings" and "raw lua" sections**
This PR is an attempt to streamline the README slightly and add relevant links to the documentation.
I also made the "how it works" section more prominent and added additional sub-headings to it to hopefully give a clearer first-impression.
Final render https://github.com/MattSturgeon/nixvim/blob/readme/README.md
> readme: minor streamlining

- plugins/languages/treesitter/hmts.nix
This fixes the invalid message in `hmts` plugin whose declaration probably derived from that of the other plugin.
> fix(hmts): correct error message on no `treesitter`

- modules/clipboard.nix
Use a markdown-syntax link so that the docs show a clickable-link.
> modules/clipboard: use md link in description

- .git-blame-ignore-revs
- flake-modules/default.nix
- flake-modules/dev/default.nix
- flake.lock
- flake.nix
This PR includes the less controversial commits from #1629, as well as a couple new commits:
- flake-modules: drop flake-root
- flake-modules: explicitly set the same nixfmt for treefmt + pre-commit
> flake-modules: minor tweaks from #1629

- plugins/utils/dashboard.nix
- tests/test-sources/plugins/utils/dashboard.nix
Switch [nvimdev/dashboard-nvim](https://github.com/nvimdev/dashboard-nvim/blob/master/README.md) to use `mkNeovimPlugin` and update how it is configured from the old `dashboard.<option>` to the current `setup(config)` style (this changed upstream Jan 2023).
Added a few test-cases based on examples in upstream's README, as well as documented defaults and a couple undocumented defaults lifted from the lua implementation.
It hasn't been easy to document the options or establish their defaults, as the upstream documentation is kinda vague. For some options I've had to dig into the source code to find the actual defaults.
Fixes #1432
> plugins/dashboard: switch to mkNeovimPlugin + update options

- plugins/default.nix
- plugins/lsp/schemastore.nix
- tests/test-sources/plugins/lsp/schemastore.nix
Add support for the [SchemaStore.nvim](https://github.com/b0o/SchemaStore.nvim/tree/main) plugin, providing JSON schemas for Neovim.
Fixes #1443
> plugins/schemastore: init

- lib/keymap-helpers.nix
- lib/utils.nix
- plugins/bufferlines/barbar.nix
- plugins/lsp/wtf.nix
- plugins/utils/tmux-navigator.nix
- tests/lib-tests.nix
- tests/test-sources/plugins/utils/tmux-navigator.nix
First time opening a PR here, so let me know if I've missed some etiquette.
- New option `tmuxNavigatorNoMappings` maps to global [`tmux_navigator_no_mappings`](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#custom-key-bindings)
- New attrset `keymaps` maps keymaps to the various `:TmuxNavigate*` commands
- Set of either `enum` or `mapConfigOptions` submodule (with some tweaks)
I don't see why the various options should include the `tmuxNavigator` prefix; that is surely implied by being in the tmux-navigator plugin...
I also think that the `null` or `1` options could be refactored as `bool` options, to make more sense in nix...
I can open this as a separate issue/PR if it warrants discussion, or I could lump it into this PR if that's easier to review?
> plugins/tmux-navigator: Add keymap config options

- lib/options.nix
- **lib/options: `defaultNullOpts` don't require having a default**
Made the `default` and `description` arguments optional for all **prime variants** of `defaultNullOpts` functions.
If neither `default` nor `description` are provided, the option will have no description.
The "Plugin default" line is only added when a `default` argument is present (`args ? default`).
This means we can now use `defaultNullOpts`, even when we explicitly _do not_ want to document a "plugin default".
- **docs: emphasise "Plugin default" to match nixpkgs**
Match the style of similar headings that come from nixpkgs. This tiny commit could be **backported** to 24.05.
<details><summary><strong>Docs render</strong></summary>
<p>
</p>
</details>
> lib/options: `defaultNullOpts` no longer requires a "default" or "description"

- docs/mdbook/default.nix
- flake-modules/modules.nix
- lib/neovim-plugin.nix
- lib/vim-plugin.nix
- plugins/lsp/language-servers/_mk-lsp.nix
- **meta: extend `meta.nixvimInfo` support treewide**
- **docs/lsp: Show LSP server homepage URLs**
> docs/lsp: Display server URLs

- plugins/default.nix
- plugins/utils/wakatime.nix
- tests/test-sources/plugins/utils/wakatime.nix
Add support for [vim-wakatime](https://github.com/wakatime/vim-wakatime).
This module is quite barebone, but at the same time, there is no need to do much.
Fixes #1649
> plugins/wakatime: init

- plugins/lsp/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Following up on #1313, this PR adds a the `plugins.lsp.inlayHints` option, which enables the capability in `plugins.lsp.onAttach`.
Unlike the original PR, no attempt is made to detect the neovim version used by `finalPackage`.
I still haven't considered if/how this should impact any existing server-specific options:
Fixes #1306
> plugins/lsp: add inlay-hint option

- plugins/lsp/default.nix
`mkEnableOption` adds an extra `.`, just use `mkOption` and be explicit.
> plugins/lsp: fix inlayHints description

- lib/options.nix
Introduce a **new** `helpers.pluginDefaultText` and **deprecate** `helpers.defaultNullOpts.mkDesc`.
Displaying the "plugin default" within `defaultText` ensures that both defaults are grouped together in the docs.
This blocks #1665:
- That PR could also do a treewide migration away from `mkDesc`
- Pre-formatted defaults (e.g. `1000 / 30`) could be passed as plugin-`defaultText`
- That PR should also remove the special case `pluginDefaultText` inherited from `mkDesc`
<details><summary>Options <strong>affected</strong> by this PR</summary>
<p>
</p>
</details>
<details><summary>Option manually adding "plugin default" (currently <strong>not</strong> affected)</summary>
<p>
</p>
</details> 
<details><summary>Option using deprecated <code>mkDesc</code> (currently <strong>not</strong> …
> lib/options: move "plugin default" into `defaultText`

- plugins/lsp/language-servers/nixd-settings.nix
`diagnostic.suppress` is a list of diagnostic hints shat should not be shown by the LSP.
> plugins/lsp/nixd: add diagnostic options

- plugins/languages/lint.nix
closes  #1678 
setting `linters.markdownlint-cli.cmd` would genenrate
before:
`linters.markdownlint-cli.cmd` resulting in an error.
after:
`linters["markdownlint-cli"]["cmd"]`
> plugins/languages/lint: allow irregular linters

- docs/mdbook/default.nix
If a maintainer has their github defined, render their name as a link to their github profile:
I snuck in a second commit "capitalize URL" because it is so tiny it'd be a waste of time to review it separately.
> docs: render maintainers with github links

- plugins/none-ls/servers.nix
Nixpkgs renamed to gdtoolkit_3 & _4 without maintaining an alias!
Out of sync lock files could be using either attr name...
I needed this change with my lock file (updated saturday) and the nixvim input overridden to one of my PR feature branches.
Updating my lock file or removing `follows` would fix the issue, of course, but I figured I'd propose a more compatible workaround here.
Ideally, nixpkgs would've kept an alias for the old name (with a trace warning).
> plugins/none-ls: more compatible `gdtoolkit` fix

- plugins/lsp/default.nix
The new lsp inlay hint option in Nixvim (#1655) wasn't enabling inlay hints, and was producing the following error message (apologies for the poor screenshot, the message dissapears quickly with Noice)
The error is caused by an incorrect function call to [`vim.lsp.inlay_hint.enable`](https://github.com/neovim/neovim/blob/72155121006bca884e154e935640054f2e090367/runtime/lua/vim/lsp/inlay_hint.lua#L408). I wasn't sure what to put for the filter parameter (maybe that should be it's own option?), so I just left it as an empty table for the time being.
> plugins/lsp fix: incorrect function call

- plugins/lsp/language-servers/default.nix
- tests/test-sources/plugins/lsp/_lsp.nix
Add `nls`, the official language server for the Nickel language.
https://github.com/tweag/nickel/
> plugins/lsp: add nickel-ls

- plugins/utils/toggleterm.nix
- tests/test-sources/plugins/utils/toggleterm.nix
Updates the option schema for the `toggleterm` plugin to allow lua functions as values for the `float_opts` options `width`, `height`, `row`, and `col`. These properties are described as being either a number or lua function [in the plugin documentation](https://github.com/akinsho/toggleterm.nvim?tab=readme-ov-file#setup).
> plugins/toggleterm: allow lua functions in `float_opts` keys which support them

- lib/options.nix
- plugins/bufferlines/barbar.nix
- plugins/ui/edgy.nix
Following up on #1667, this PR allows the `pluginDefault` argument to be passed to any of nixvim'd option factory helpers.
Taking advantage of this where possible, the 3 internal uses of `mkDesc` have been migrated either to `pluginDefault` or calling `helpers.pluginDefaultText` directly.
It might make sense to have a `helpers.mkOption`, which simply extends `lib.mkOption` with support for custom nixvim args like `pluginDefault`:
```nix
mkOption = args: lib.mkOption (processNixvimArgs args);
```
Let me know if you'd like that included in this PR, and I'll be able to simplify the plugins/barbar implementation.
Maybe we'd also consider no longer exposing `pluginDefaultText` publicly, if all use-cases are accommodated by a `mkOption` wrapper?
- **lib/options: remove …
> Allow `pluginDefault` arg outside of `defaultNullOpts` + remove `mkDesc`

- lib/options.nix
- plugins/lsp/language-servers/nil-ls-settings.nix
- plugins/lsp/language-servers/nixd-settings.nix
I was expecting this PR to be much bigger. Luckily we only use the `defaultNullOpts` prime variants in a few locations and many of those uses don't actually set a plugin default.
The non-prime variants are only affected internally, because renaming arguments does not change the function signature.
See original discussion here: https://github.com/nix-community/nixvim/pull/1667#discussion_r1632607368
> lib/options: migrate to `pluginDefault` arg-name

- .github/workflows/build_documentation.yml
- build-docs.sh
- Inline `build-docs.sh` into the workflow step
- Remove the `checkout` step
- Remove the `configure-pages` step
- Enable `on.push` for either release branch
- [Tested workflow on my fork](https://github.com/MattSturgeon/nixvim/actions/runs/9517774174)
By inlining `build-docs.sh` we no longer need to checkout the repo. The `configure-pages` action was also redundant, since we are not configuring a static site generator.
> ci: simplify docs-build workflow

- lib/helpers.nix
- lib/types.nix
- lib/utils.nix
Motivated by needing to migrate some existing options from maybeRaw types to strLua types, this PR refactors the types and mkRaw to accommodate that use case, plus others.
To be specific:
- strLua types now also accept rawLua
- mkRaw will "pass through" rawLua untouched
- mkRaw now `throw`s when passed a non-null, non-string, non-raw value
- previously _any_ invalid value resulted in `null`
> lib: make lua types + `mkRaw` helper more accommodating

- plugins/completion/cmp/sources/cmp-git.nix
- tests/test-sources/plugins/completion/cmp-git.nix
Prompted by (and extracted from) #1674, this PR is a general cleanup of some options in the cmp-git plugin.
- Move several options to `strLuaFn`
- Replace all pre-formatted plugin defaults
- Fix some incorrect examples/tests
This PR **depends on** #1709, otherwise existing `__raw` values in users' configs will produce an incorrect type error:
```
error: A definition for option `plugins.cmp-git.settings.github.issues.format' is not of type `null or lua function string'. Definition values:
- In `<unknown-file>':
{
__raw = ''
function(_, issue)
local icon = ({
open = '',
...
```
> plugins/cmp-git: general cleanup of options

- plugins/neotest/adapters.nix
The fix has reached `nixos-unstable`.
> Revert "plugins/neotest/adapters/playwright: temporarily enable telescope when this adapter is used"

- modules/highlights.nix
Hi. Thanks for the great project! Just submitting a small typo fix for the docs.
The example of highlightOverride didn't use the correct option name.
> Fix typo in highlights.nix

- modules/default.nix
- modules/diagnostic.nix
[`:h vim.diagnostic.config()`](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.config())
> Configuration can be specified globally, per-namespace, or ephemerally
Maybe we should offer a way to set config per-namespace? Uses the second parameter:
> `{namespace}` `(integer?)` Update the options for the given namespace. When omitted, update the global diagnostic options.
> modules/diagnostic: init

- lib/maintainers.nix
- plugins/utils/auto-save.nix
- tests/test-sources/plugins/utils/auto-save.nix
- typos.toml
This PR switches the plugin to `mkNeovimPlugin` and updates plugin options according to [okuuva/auto-save.nvim](https://github.com/okuuva/auto-save.nvim?tab=readme-ov-file#%EF%B8%8F-configuration) configuration options.
> plugins/auto-save: switch to mkNeovimPlugin + update options

- lib/deprecation.nix
- lib/helpers.nix
- plugins/git/gitsigns/default.nix
- plugins/git/gitsigns/options.nix
- **lib/deprecation: init with mkRemovedSubmoduleOptionModule**
- **plugins/gitsigns: remove deprecated options**
Added a clone of `mkRemovedOptionModule` that supports nested sub-options. This is exactly the same, except is uses our custom `getOptionRecursive` instead of `getAttrFromPath`.
Like `mkRemovedOptionModule`, this is an assertion. Maybe a warning would make sense instead, seeing as `settings` is a freeform type?
I've tested the functions a little in the repl and by checking out the old test file (before the options were removed from the test).
Should we have some lib-tests? If so do you have any suggestions for test-cases?
> plugins/gitsigns: remove deprecated options

- docs/mdbook/default.nix
This prevents non-visible aliases for submodules (e.g. `settings`) from appearing in the docs.
<details><summary>Screenshot comparison</summary>
<p>
| Current | This PR |
|--------|--------|
| ![image](https://github.com/nix-community/nixvim/assets/5046562/8896b724-06e0-4bf4-85a8-34230d187a8b) | ![image](https://github.com/nix-community/nixvim/assets/5046562/a225878c-6248-4e0b-a695-e0a1b8ff5e54) | 
</p>
</details>
I also included an additional commit cleaning up the `isVisible` function a little. This shouldn't change its behaviour at all.
> docs/mdbook: only show sub-options of visible options

- docs/mdbook/default.nix
> [backport] docs/mdbook: only show sub-options of visible options

- plugins/default.nix
- plugins/utils/codesnap.nix
- tests/test-sources/plugins/utils/codesnap.nix
Add support for [codesnap.nvim](https://github.com/mistricky/codesnap.nvim).
Closes #1514
Doc is failing: we have to wait for https://github.com/NixOS/nixpkgs/pull/322120
> plugins/codesnap: init

- lib/helpers.nix
- lib/to-lua.nix
- tests/lib-tests.nix
- **lib/lua: add `isKeyword` and `isIdentifier`**
- **lib/lua: only quote table keys when needed**
- **lib/lua: pad table `,` with a space**
Valid identifiers as [defined in the lua manual](https://www.lua.org/manual/5.1/manual.html#2.1) do not need to be quoted in lua tables, so we can make most tables less verbose and more readable by checking if the key is a valid identifier.
The table separators are more readable when padded with whitespace.
I think toLuaObject could be improved by taking some inspiration from generators.toPretty.
In particular, we could add optional support for multiline output and the empty attr values filter could be more efficient by not calling toLuaObject recursively in its condition.
> lib/lua: more readable tables

- plugins/none-ls/default.nix
- plugins/none-ls/servers.nix
- plugins/none-ls/settings.nix
- tests/test-sources/plugins/none-ls.nix
Part one refactoring none-ls (#1705): switch the top-level plugin options to use mkNeovimPlugin and rfc42-style settings.
This PR maintains the existing option `enableLspFormat`, a legacy option that sets none-ls's `on_attach` to `require('lsp-format').on_attach`. There are some issues with this option, but removing or refactoring it is not a focus for this initial PR.
I did update the option description though: fixes #1690.
The various sources have a `withArgs` option (`plugins.none-ls.sources.*.*.withArgs`), which is a lua-string type. Switching this to rfc42-style settings would be nice, but is not in scope for this PR. ([Upstream docs](https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTIN_CONFIG.md#configuration), [experimental draft …
> plugins/none-ls: switch to mkNeovimPlugin

- plugins/utils/surround.nix
This alias exists already in 23.11, so it should be safe to backport.
https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/editors/vim/plugins/aliases.nix
> plugins/surround: stop using alias

- .github/mergify.yaml
Follow up to the slightly more extensive #1642, this PR keeps things simple and does **not** add any automation rules.
All interactions with mergify will therefore have to be done using [commands], i.e. special comments that tag @mergifyio.
The goal of this PR is to setup an initial mergify config, allowing us to trial using mergify via its [commands].
We can then evaluate if we wish to continue using mergify, and if so whether we want to introduce additional config/rules.
As per their [getting started](https://docs.mergify.com/getting-started/) instructions, we should:
Like us, mergify is subject to GitHub branch protection rules.
If we later decide we want to exclusively use mergify to merge PRs, we should set _GitHub's_ branch protection to [only mergify can …
> github/mergify: init

- plugins/default.nix
- plugins/languages/otter.nix
- tests/test-sources/plugins/languages/otter.nix
https://github.com/jmbuhr/otter.nvim
Unfortunately, cannot run tests for this. After 33 minutes, it exits with SIGSTOP with no error message (both times I tried)
> plugins/otter: init

- lib/helpers.nix
- lib/to-lua.nix
- tests/lib-tests.nix
Refactor toLuaObject, providing a `lua.toLua'` version that takes configuration options.
`lua.toLua` is the same as `lua.toLua' { }` (default options), and is aliased at the top-level as `toLuaObject` to avoid breaking changes.
Heavily based on nixpkgs [`lib.generators.toPretty`](https://github.com/NixOS/nixpkgs/blob/00ba4c2c35f5e450f28e13e931994c730df05563/lib/generators.nix#L326-L398), which has the added benefit of improving the output format (more space padding) and supporting indented multiline output.
Removal of empty/null attrs has been refactored as a recursive first-pass or pre-proccess. Before we called `toLuaObject` an additional time in the filter function, which was inefficient.
All tests pass, but I should probably add new tests for the configuration options.
I deprecated …
> lib/lua: refactor toLuaObject, now configurable

- lib/neovim-plugin.nix
- plugins/completion/cmp/sources/cmp-git.nix
Sometimes we use `mkVimPlugin` for neovim plugins just because we want to avoid creating the `settings` option. This isn't ideal at the best of times, but makes even less sense when we still need to call `setup` anyway.
Allow callers to explicitly set `settingsOptions = null` to disable creating the `settings` option.
It still defaults to `{ }`, so existing plugins are not affected.
`toLuaObject cfg.settings` is now an optional string.
I've incorporated changes from #1676 that felt more suited to this PR than that one.
Namely:
- Allow overriding the settings description
- Allow overriding the `setup` function name (used in config & description)
> lib/neovim-plugin: more configurable settings

- plugins/lsp/lsp-lines.nix
- tests/test-sources/plugins/lsp/lsp-lines.nix
~~It is a neovim plugin, but it has no setup options so use mkVimPlugin.~~
The plugin recommends several defaults and examples for `vim.diagnostic.config`, some of which we've historically set. This PR makes that a little more configurable, closes #1703.
IMO we could probably handle this better by having a `diagnostics` module (similar to `opts`, `keymaps`, etc); a freeform submodule option that gets passed directly to `vim.diagnostic.config()`. Any thoughts on this approach?
If we had a diagnostics module, would we deprecate the `extraOptions` here, or would we just `lib.mkDefault` what we need to and document other examples?
> plugins/lsp-lines: switch to mkNeovimPlugin

- lib/to-lua.nix
A user has reported (https://github.com/nix-community/nixvim/pull/1760#issuecomment-2192066615) that `with lib` isn't bringing `match` into scope on in their flake. Odd, but we can fix by explicitly using `builtins.match`
> lib/lua: workaround `builtins.match` alias issue

- lib/vim-plugin.nix
`foo_bar = true` -> `:setg ${prefix}foo_bar=1` is incorrect and confusing.
See related issue #1741
I think this should be backported to 24.04.
> lib/vim-plugin: fix + improve settings example

- docs/user-guide/install.md
- flake-modules/legacy-packages.nix
- flake-modules/tests.nix
- flake-modules/wrappers.nix
- tests/default.nix
- tests/test-derivation.nix
This ended up being a bigger cleanup/refactor than expected, as I encountered a lot of cruft and redundancy.
The core motivation of these changes is to allow for more complex tests, that need access to module args such as `options` or `config`. In particular #1776.
I've removed a few functions, which may look scary at first, however I've checked for any places where they may have been exposed publicly and they appear to be 100% internal.
While working in this area I was question why `makeNixvim` is deliberately restrictive in only accepting a config attrset.
I guess this made sense when we had a name conflict with `options`, but now that that's resolved I see no reason why _any_ module form shouldn't be accepted and passed directly through to `makeNixvimWithModule`.
Incidentally, this …
> tests/test-derivation: allow tests to be modules

- README.md
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
Otherwise the following error is generated when building my config
```
… while evaluating definitions from `/nix/store/ds9973rzhbwq1mk4lznqwrm9x44qp9qy-source/flake.nix#nixosModules.nixvim':
(stack trace truncated; use '--show-trace' to show the full, detailed trace)
error: attribute 'system' missing
at /nix/store/ds9973rzhbwq1mk4lznqwrm9x44qp9qy-source/wrappers/nixos.nix:58:56:
57|         cfg.printInitPackage
58|       ] ++ (lib.optional cfg.enableMan self.packages.${pkgs.system}.man-docs);
|                                                        ^
59|     }
Did you mean one of mystem, systemc, systemd, syntex or systemfd?
```
> Remove aliases

- plugins/utils/flash.nix
- tests/test-sources/plugins/utils/flash.nix
Prompted by changes in #1674, I've gone ahead and updated https://github.com/folke/flash.nvim to use mkNeovimPlugin and rfc42 settings.
The "modes" use the same options as top-level settings, so I've maintained a similar system to the existing implementation where `mkModeOption` combines all the common settings with any extras.
Rather than documenting mode-specific defaults in the option itself, I pass the defaults through to the sub-options themselves. This makes the docs slightly more accurate.
The `search.automatic` option is removed. If my interpretation of upstream's docs is correct it was never needed?
> plugins/flash: switch to mkNeovimPlugin

- plugins/default.nix
- plugins/utils/neoclip.nix
- tests/test-sources/plugins/utils/neoclip.nix
Add support for [nvim-neoclip.lua](https://github.com/AckslD/nvim-neoclip.lua).
Note: I haven't done anything fancy regarding the pickers (I am not checking if the user has either `telescope` or `fzf-lua` enabled).
Fixes #1543
> plugins/neoclip: init

- docs/modules/standalone.md
- tests/extend.nix
- wrappers/standalone.nix
This is our scope, so there's no need to be explicit.
This also follows the precedent set by `lib.extend`, although that takes an overlay function.
The old name still exists, but it will print the following when used:
> trace: warning: <nixvim>.nixvimExtend has been renamed to <nixvim>.extend
> standalone: rename `nixvimExtend` to `extend`

- plugins/utils/nvim-osc52.nix
As per the notice on the [plugin's readme](https://github.com/ojroques/nvim-osc52/blob/main/README.md)
Tagging @PowerUser64
Closes #1704
> plugins/nvim-osc52: mark as obsolete

- plugins/lsp/language-servers/pylsp.nix
Currently, pkgs.python3Packges is used by default and is unable to be changed. Without this, using features from newer python versions in mypy(and maybe other plugins) is impossible since mypy uses it's own python interpreter that it's installed under for getting typing hints afaik.
Fixes https://github.com/nix-community/nixvim/issues/1456
> plugins/lsp/pylsp: Add python option to generate obtain the pylsp from.

- lib/to-lua.nix
- tests/lib-tests.nix
- Add options for removing empty/null list entries (default false)
- Fix recursion into attrs that are themselves list entries
- Added some tests
- One test for #1804
- Two tests for the new list filters
Fixes #1804
> lib/to-lua: fix removing empties nested in lists

- plugins/ai/chatgpt.nix
- plugins/default.nix
- tests/test-sources/plugins/ai/chatgpt.nix
Add support for [ChatGPT.nvim](https://github.com/jackMort/ChatGPT.nvim), effortless Natural Language Generation with OpenAI's ChatGPT API.
Fixes #1802
> plugins/chatgpt: init

- .github/mergify.yml
Fixes #1793
See [our issue], [upstreams issue], and [this discussion] I had with upstream.
The core problem is also summarised nicely in [this comment] on another affected project:
> Quick summary here:
> * GitHub API doesn't allow a bot to do certain things including rebasing. So, it has to impersonate real people to work because rebasing is pretty usual:
>   * we use rebase to update a PR branch  when `master` went ahead (see Mergify config);
>   * we use Mergify queues, and those require rebases in general: the bot tries to create a "merge train" rebasing several PRs one on top of each other (Ibid.).
> * Before February 2023 Mergify would impersonate random "authorized users" (users with elevated permissions on the repo), which was annoying but working.
> * [Since February 2023 they …
> github/mergify: set an explicit "update" account

- plugins/utils/coverage.nix
- tests/test-sources/plugins/utils/coverage.nix
Adds option for setting a keymap to the [CoverageLoadLcov](https://github.com/andythigpen/nvim-coverage/blob/aa4b4400588e2259e87e372b1e4e90ae13cf5a39/doc/nvim-coverage.txt#L275) command.
> plugins/coverage: Add loadLcov keymap.

- tests/test-sources/plugins/utils/nvim-osc52.nix
#1736 introduced deprecation warnings, which now print when we run the tests. ([Example](https://buildbot.nix-community.org/api/v2/logs/141658/raw_inline)).
We don't care about them in the tests, so just disable all warnings using `mkForce`. This might also hide other warnings we do care about, but I don't see a better approach?
> plugins/nvim-osc52: hide warnings in tests

- modules/top-level/output.nix
- wrappers/hm.nix
- wrappers/nixos.nix
This (internal) option introduces IFD, and can be substituted internally with the `initPath` option easily.
If the content is required somewhere users can use readFile on the initPath, though it will result in an IFD in their project.
> modules/output: Remove the initContent option

- docs/default.nix
- flake-modules/packages.nix
`getHelpers` is defined here: https://github.com/nix-community/nixvim/blob/main/flake-modules/helpers.nix (asside: I'm not a fan of having this defined in a flake module)
I was hoping this would be a fix for #1618, but that doesn't seem to be the case.
> docs: use pkgsDoc to build helpers

- docs/default.nix
- docs/mdbook/default.nix
- modules/misc/context.nix
- modules/misc/default.nix
- modules/top-level/files/default.nix
Added `isTopLevel` and `isDocs` internal options. This replaces `specialArgs.isDocs` that was added in #1807.
We should only use `specialArgs` when absolutely necessary, a module or `_module.args` is preferred, but those aren't available until `config` is evaluated so they can't be used for `imports`.
The main problem with `specialArgs` is it makes our modules less portable, but it also means the arg can't be overridden with `mkForce` (etc).
Luckily that shouldn't be an issue for these context flags.
The `isTopLevel` option is currently unused; I can drop it from this PR if preferred.
It is _intended_ to allow `files` or `extraFiles` to have a different _type_ when at the top-level, since we can't have a submodule option that recursively includes itself in its modules.
> modules/context: init

- lib/neovim-plugin.nix
Some plugins may wish to handle package installation themselves, so make installing `cfg.package` optional.
I used a "real" branch instead of `mkIf` because we don't know _why_ the plugin doesn't want us to install it - it's possible `cfg.package` shouldn't be evaluated.
This is needed for #1801
@GaetanLepage sorry to step on your toes again re: the the mkPlugin refactor!
> lib/neovim-plugin: allow disabling `installPackage`

- modules/top-level/output.nix
- tests/test-sources/modules/output.nix
It seams `extraLuaPackages` doesn't work or am I missing something?
This PR ensures `extraLuaPackages` are made available on the runtimepath.
> modules/output: fix extraLuaPackages

- flake-modules/tests.nix
- lib/deprecation.nix
- modules/default.nix
- modules/files.nix
- modules/output.nix
- modules/top-level/files/default.nix
- modules/top-level/files/submodule.nix
- plugins/languages/treesitter/treesitter.nix
- tests/extra-files.nix
- tests/test-sources/modules/extra-files.nix
- wrappers/_shared.nix
Refactored `extraFiles` to use a file-type submodule.
This submodule has the following options:
- `source`: the file path to use
- `text`: (optional) text to write and (potentially) override `source`
- `target`: (default attr name) where the file should be installed
- `enable` (default true) can be used to disable a file added by another module
Users should now assign text to a `text` attribute, however they could also assign a file path to a `source` attribute instead.
The type conversion is a non-breaking change, as I was able to deprecate the old type using coercion.
I've introduced a tweaked version of `types.coerceTo` (`helpers.transitionType`) that a) only shows the new type's description and b) prints a warning when the old type is used in a definition.
I've added an additional …
> modules: refactor `extraFiles`

- flake-modules/dev/default.nix
- flake-modules/dev/devshell.nix
- flake.lock
- flake.nix
Primarily based off the work done in https://github.com/nix-community/lanzaboote/pull/282
Currently most of the flake's dependencies are solely used for development (with the exception of nixpkgs of course). There isn't much reason to have these inputs pollute the flake.lock of end users, and they should be able to remove them via the `inputs.<input>.follows = ""` interface
Usually this would "just work" with lazy evaluation, but due to flake-parts and it's modules, inputs that we import `flakeModule`s from are evaluated eagerly and become required. To work around this, we can conditionally define and import these options and modules
Assuming the `nixvim` input was originally defined with the following
```nix
{
inputs = {
nixvim = {
url = "github:nix-community/nixvim"; …
```
> flake: make most inputs optional

- plugins/utils/leap.nix
- tests/test-sources/plugins/utils/leap.nix
Fixes #1698.
I have added an item to the notepad to not forget about considering the fundamental problem.
-> Should `mkListOf` options be typed `maybeRaw (listOf ...)` ?
> plugins/leap: allow __empty for safeLabels option

- docs/user-guide/helpers.md
Backport the #1220 fix from #1831
> [nixos-24.05] docs/user-guide: fix blurb on accessing `helpers`

- docs/default.nix
- docs/user-guide/helpers.md
- flake-modules/helpers.nix
- flake-modules/packages.nix
- flake-modules/wrappers.nix
- lib/helpers.nix
- wrappers/_shared.nix
- wrappers/darwin.nix
- wrappers/hm.nix
- wrappers/nixos.nix
- wrappers/standalone.nix
We can consolidate some duplication by propagating config files directly in a shared module, we just need to know the option name and the name of the init file.
**NOTE: this change has been dropped from this PR!**
<details><summary>Details</summary>
<p>
Currently we make helpers available via `config.nixvim.helpers`, however NixOS, nix-darwin and home-manager all provide a `config.lib` option (type `attrsOf attrs`).
This `lib` option is intended to be used by modules to define their custom functions in a global scope. It is **unrelated** to the `lib` available via module args.
I've used `mkRenameOptionModule` to rename `nixvim.helpers` to `lib.nixvim`. This prints a warning when `config.nixvim.helpers` is evaluated:
```
trace: Obsolete option `nixvim.helpers' is used. It was renamed to …
```
> wrappers: make `_shared` return a module

- .github/mergify.yml
- .github/workflows/build_documentation.yml
- .github/workflows/update.yml
- docs/mdbook/highlight.js
- flake-modules/dev/default.nix
- flake-modules/dev/list-plugins.py
- **flake/pre-commit: use treefmt in git hook**
- **flake: format JS & YML with "prettier"**
- **flake: format python with "black"**
- **flake: format lua with "stylua"**
- **flake: ignore unformatted files**
- **treewide: reformat**
Adding formatters and excluding unformatted files suppresses these warnings:
```
WARN format: no formatter for path: .envrc
WARN format: no formatter for path: .git-blame-ignore-revs
WARN format: no formatter for path: .github/ISSUE_TEMPLATE/bug_report.md
WARN format: no formatter for path: .github/ISSUE_TEMPLATE/feature_request.md
WARN format: no formatter for path: .gitignore
WARN format: no formatter for path: CONTRIBUTING.md
WARN format: no formatter for path: README.md
WARN format: no formatter for path: assets/nixvim_logo.svg
WARN format: no formatter …
```
> flake/treefmt: extend config and suppress warnings

- plugins/languages/treesitter/injections.scm
This PR fixes the existing nixvim queries to work with neovim 0.10. It also adds support for `lua` injections in `helpers.mkRaw` or `__raw` strings.
> plugins/treesitter: Update nixvim queries
